### ISSUE TITLE
Search doesn't work when page != 1

### ISSUE THREAD

**Issue by sjardim** [rappasoft/laravel-livewire-tables#10]
Hi, just installed to test and noticed that on the page is not the first one, the search returns no results.

<details>
 <summary>Screenshot: Step 1 - Initial rendering on first page</summary>

![image](https://user-images.githubusercontent.com/125217/81083330-5bb16580-8eec-11ea-9815-1a8bf8ac0f51.png)

</details>

<details>
 <summary>Screenshot: Step 2 - Searching for "goos" on first page</summary>

Returns one row as expected. 

![image](https://user-images.githubusercontent.com/125217/81083675-c95d9180-8eec-11ea-912e-2bb544cd1f2b.png)

</details>

But if we go to **?page=2**, and search again for "goos" nothing is returned

**Comment by sjardim** [comment]
Maybe it can be fixed using the resetPage() method of Livewire's withPagination trait:

```php
/*
     * Reset pagination when doing a search
     */
    public function updatingSearch()
    {
        $this->resetPage();
    }
```

**Comment by rappasoft** [comment]
I'll look into it

**Comment by sjardim** [comment]
Great, thank you!

**Comment by rappasoft** [comment]
@sjardim I'm adding that method to the plugin, it fixes the problem thanks.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-livewire-tables/releases/tag/v0.1.3
