### ISSUE TITLE
toolbar-right-end

### ISSUE THREAD

**Issue by nicolocaruso85** [rappasoft/laravel-livewire-tables#1001]
There is a spelling mistake on line 846 in toolbar.blade.php
'toolbar-righ-end' instead of 'toolbar-right-end'

**Comment by lrljoe** [comment]
I've issued a pull request for this [](https://github.com/rappasoft/laravel-livewire-tables/pull/1015/)

**Comment by lrljoe** [comment]
Expect this pull request to be fixed wtihin the next week or two, sorry for the delay!

**Comment by rappasoft** [comment]
Fixed in next release
