### ISSUE TITLE
Column built from hasOne() relationship results in duplicate rows

### ISSUE THREAD

**Issue by lrljoe** [rappasoft/laravel-livewire-tables#1005]
Originally from dirtbikr

Example `User` model has a relationship with a `Purchase` model:

```
    public function latestPurchase()
    {
        return $this->hasOne(Purchase::class)->latestOfMany();
    }
```

Users may have many purchases, outside of the package, the latestPurchase relationship correctly returns one result.
Within the package, it returns as many purchases as exist.

```
public function columns(): array
    {
        return [
            Column::make("ID", "id")
                ->sortable()->searchable(),
            Column::make("Name", "name")
                ->sortable()->searchable(),
            Column::make("Email", "email")
                ->sortable()->searchable(),
            Column::make("State", "state")
                ->sortable(),
            Column::make("Last Purchase", "latestPurchase.created_at"),
        ];
    }
```

**Query outside of the package is as follows:**
An initial select for the users:
```
select
    `id`,
    `name`,
    `email`,
from
    `users`
```
Then a self-joined query for the latest purchase:
```
select
    `purchases`.*
from
    `purchases`
    inner join (
        select
            MAX(`purchases`.`id`) as `id_aggregate`,
            `purchases`.`user_id`
        from
            `purchases`
        where
            `purchases`.`user_id` in (1, 2, 3, 4, 5)
        group by
            `purchases`.`user_id`
    ) as `latestOfMany` on `latestOfMany`.`id_aggregate` = `purchases`.`id`
    and `latestOfMany`.`user_id` = `purchases`.`user_id`

```

**Query within the package is as follows:**
```
select
    `users`.`id` as `id`,
    `users`.`name` as `name`,
    `users`.`email` as `email`,
    `purchases`.`created_at` as `latestPurchase.created_at`
from
    `users`
    left join `purchases` on `purchases`.`user_id` = `users`.`id`
limit
    10 offset 0
```

**Example repo:**
[https://github.com/lrljoe/livewire-tables-latestofmanyissue/tree/Showing-Issue](https://github.com/lrljoe/livewire-tables-latestofmanyissue/tree/Showing-Issue
)
**Interim Fix**
Interim fix is as follows, with recommendation to use Builder to eager load the relationship.
[https://github.com/lrljoe/livewire-tables-latestofmanyissue/blob/Fixed-Issue/app/Http/Livewire/UserTable.php](https://github.com/lrljoe/livewire-tables-latestofmanyissue/blob/Fixed-Issue/app/Http/Livewire/UserTable.php)
```
Column::make('Last Purchase', 'id')
            ->format(
                fn ($value, $row, Column $column) =>  $row->latestPurchase->created_at
            ),
```

![image](https://user-images.githubusercontent.com/6034702/211115606-9cbc8070-a5ed-4981-8110-c9343101d7c7.png)

_Originally posted by @dirtbikr in https://github.com/rappasoft/laravel-livewire-tables/discussions/1004_

**Comment by apydevs** [comment]
Same issue here

**Comment by lrljoe** [comment]
The fix for this was actually a relationship level one in the model if I remember correctly!  Will take a look in a week or two.

Which Laravel version are you using?

**Comment by apydevs** [comment]
Laravel Framework 9.52.15
Livewire V2.12.6

Just to put abit more context to this 

**Relationships**
`
    public function businessLicence(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Licence::class, 'tenant_id', 'id')->latest('created_at');
    }


    public function deviceLicence(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(DeviceLicence::class,'tenant_id','id')->latest('created_at');
    }
`
**Livewire Table Component**
`
   public function configure(): void
    {
            return [
              Column::make('ID', 'id')->isHidden(),
              Column::make('Tenant Name', 'tenancy_name') ->sortable()->searchable(),
              Column::make('Businesses used','businessLicence.current_used_total')->sortable()->unclickable()
              ->deselected()->searchable()
              ]
    }

   public function columns(): array
    {

        return [
             Column::make('ID', 'id')->isHidden(),
              Column::make('Tenant Name', 'data->tenancy_name') ->sortable()->searchable(),
              Column::make('Business used','businessLicence.current_used_total')->sortable()->unclickable()
              ->deselected()->searchable()]
`
public function builder(): Builder
    {
        return Tenant::query()
            ->with(['businessLicence','deviceLicence']);

I have multiple references to the tenant id , within the business licence table (Licence::).

if i `dd(Tenant::query()
            ->with(['businessLicence','deviceLicence'])->get());`
  I see the last records in the relationships  as expected and no duplication 
  
  Any help would be greatly appreciated

**Comment by mohamad-supangat** [comment]
@rappasoft can you tell me how to fix this

i have same issue there in hasOne relationship only

**Comment by emiliosh** [comment]
Same here, trying with Laravel 10 and Datatables 3 and also same on Datatables 2 with Laravel 9.

**Comment by paianoa** [comment]
Same problem here. Laravel 11 and Datatable 3. Fix needed.

**Comment by AurelienLab** [comment]
Hi here, I struggled with the same issue, and was able to make a Quick'n Dirty fix for that.
If someone's passing by, here's how:

You need to override the `joinRelation()` method to call an alternative `performJoin()` method, and add an array property `$joins`.
Personnally, I did it in an abstract class that extends `Rappasoft\LaravelLivewireTables\DataTableComponent` and that I use in all my data table.

```php
namespace App\Livewire\DataTable;

use Illuminate\Contracts\Database\Eloquent\SupportsPartialRelations;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\Relations\Relation;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;

abstract class CustomDataTableComponent extends DataTableComponent
{

    protected array $joins = [];

    // Override of the base method to handle HasOne of Many relations
    protected function joinRelation(Column $column): Builder
    {
        if ($column->eagerLoadRelationsIsEnabled() || $this->eagerLoadAllRelationsIsEnabled()) {
            $this->setBuilder($this->getBuilder()->with($column->getRelationString()));
        }

        $table = false;
        $tableAlias = false;
        $foreign = false;
        $other = false;
        $lastAlias = false;
        $lastQuery = clone $this->getBuilder();

        foreach ($column->getRelations() as $i => $relationPart) {
            $model = $lastQuery->getRelation($relationPart);
            $tableAlias = $this->getTableAlias($tableAlias, $relationPart);

            switch (true) {
                case $model instanceof MorphOne:
                case $model instanceof HasOne:
                    $table = "{$model->getRelated()->getTable()} AS $tableAlias";
                    $foreign = "$tableAlias.{$model->getForeignKeyName()}";
                    $other = $i === 0
                        ? $model->getQualifiedParentKeyName()
                        : $lastAlias . '.' . $model->getLocalKeyName();

                    break;

                case $model instanceof BelongsTo:
                    $table = "{$model->getRelated()->getTable()} AS $tableAlias";
                    $foreign = $i === 0
                        ? $model->getQualifiedForeignKeyName()
                        : $lastAlias . '.' . $model->getForeignKeyName();

                    $other = "$tableAlias.{$model->getOwnerKeyName()}";

                    break;
            }

            if ($table) {
                // Edit: Here we call a new method with $model and $tableAlias
                $this->setBuilder($this->performJoinAlternative($table, $foreign, $other, $model, $tableAlias));
            }

            $lastAlias = $tableAlias;
            $lastQuery = $model->getQuery();
        }

        return $this->getBuilder();
    }


    protected function performJoinAlternative(string $table, string $foreign, string $other, Relation $model, string $tableAlias, string $type = 'left'): Builder
    {
        if (in_array($table, $this->joins, true)) {
            return $this->getBuilder();
        }

        // We save the current table to not intent join it again (a bit dirty because we don't handle an existing join from the base query)
        $this->joins[] = $table;

        // If the query has bindings (like where clauses) or is a OneOfMany relation we perform a subquery join
        if (!empty($model->getQuery()->getBindings()) || ($model instanceof SupportsPartialRelations && $model->isOneOfMany())) {
            $this->setBuilder($this->getBuilder()->joinSub($model->getQuery(), $tableAlias, $foreign, '=', $other, $type));
        } else {
            $this->setBuilder($this->getBuilder()->join($table, $foreign, '=', $other, $type));
        }

        return $this->getBuilder();
    }


}

```

There is probably a better way to do it, but it works with a relation with a where, having etc... clause and "OneOfMany" relationships.
