### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by keizah7** [rappasoft/laravel-livewire-tables#1006]
![image](https://user-images.githubusercontent.com/49227202/211249022-6b60d843-239d-4ea3-ad0c-6c97c6962e4d.png)

for some reason default setup looks like this.

Previously, it was white and I didn't change anything

**Comment by keizah7** [comment]
tailwind dark mode overrides css

**Comment by maganius** [comment]
> tailwind dark mode overrides css

how did you solve it?

my tables are in dark mode but I want it in light mode

**Comment by lrljoe** [comment]
You need to set your tailwind config to use class for darkmode

In your tailwind.config.js

```
module.exports = { 
darkMode: 'class', 
// ... 
}
```

**Comment by maganius** [comment]
> darkMode: 'class',

thank you a lot
