### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::total does not exist.

### ISSUE THREAD

**Issue by paramwork** [rappasoft/laravel-livewire-tables#1009]
Configure is 

```
 public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setPaginationMethod('simple');
        $this->setPerPageAccepted([20, 50]);
        $this->setPerPage(20);
        $this->setEmptyMessage('No submissions found');
        $this->setDefaultSort('position', 'asc');

        $this->setBulkActions([
            'exportSelected' => 'Export',
        ]);
    }
```

I am on the version - v2.9 

It happens when I select users using the checkbox.

**Comment by lrljoe** [comment]
If this is in relation to when you run a bulk action, can you post the relevant bulk function please.

**Comment by lrljoe** [comment]
> The error only shows when I use `simple` pagination.

Ah that makes sense, total() isn't an available method for simplePagination sadly, that's a Laravel Core thing.

**Comment by lrljoe** [comment]
Found the issue, corrected in a test branch and have issued a pull request for it.

In the meantime, you can use the bulk-actions.blade.php from the pull request if you publish the views and make the changes.

[View Pull Request](https://github.com/rappasoft/laravel-livewire-tables/pull/1015/commits)

**Comment by lrljoe** [comment]
No problem, please mark this as answered if you're all good, and yeah, hopefully so, I've been quite busy opening up pull requests  lately for @rappasoft to take a look at to merge, but I appreciate he's busy!
