### ISSUE TITLE
Sortable on eagerLoad MorphMany

### ISSUE THREAD

**Issue by Geovanek** [rappasoft/laravel-livewire-tables#101]
I have a:
**Users**
`id`
`name`

**Athletes**
`id`
`company_id`

**Userables**
`user_id`
`user_typ`
`userable_type`

In **User.php**

    public function getAthleteAttribute()
    {
        return $this->athletes->first();
    }

    public function athletes()
    {
        return $this->morphedByMany(Athlete::class, 'userable');
    }

In **Athlete.php**

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function coach()
    {
        return $this->belongsTo(Coach::class);
    }

    public function getUserAttribute()
    {
        return $this->users->first();
    }

    public function users()
    {
        return $this->morphToMany(User::class, 'userable');
    }

My **table component**

    class ProfileAthletes extends TableComponent
    {
    use HtmlComponents;
    public $companyId;

    public function mount($id)
    {
        $this->companyId = $id;
    }

    public function query() : Builder
    {
        return Athlete::with(['coach.users', 'users'])->where('company_id', $this->companyId);
    }

    public function columns() : array
    {
        return [
            Column::make('Nome', 'user.name')
                ->searchable()
                ->sortable(function ($builder, $direction) {
                    return $builder->orderBy( ?????????? , $direction);
                })
                ->format(function(Athlete $model) {
                    return $this->html($model->user->name);
                }),

How do I make this work?

**Comment by rappasoft** [comment]
What are you trying to make work?

**Comment by Geovanek** [comment]
What am I trying to make it work?
It's written there.

The Sortable method, but for data coming from a polymorphic relationship. I've tried in many ways and always make the mistake.

**Comment by R00118189** [comment]
I have similar question - we need to create query here so how can we construct it with polymorphic relations? In my case my `Project` is `commentable` and I am trying to get table component of `comments` for this project. Is there a cleaner way than one below.

```php

public function query(): Builder
    {
        return Comment::where([
            ['commentable_type', '=', 'App\Models\Project')],
            ['commentable_id','=',$this->project->id]
            ]);
    }
```
