### ISSUE TITLE
Using LinkColumn does not include the attribute of the model in $row like it does with other Columns

### ISSUE THREAD

**Issue by SimonMacIntyre** [rappasoft/laravel-livewire-tables#1010]
``` 
 LinkColumn::make('ID', 'uuid')
     ->sortable()
    ->searchable()
    ->title(fn($row) => $row->uuid)
    ->location(fn($row) => route('device.edit', [$row->uuid])),
```

`$row->uuid` will not be populated. Note that if you for example just add a duplicate column below with the field, it will work because then `$row->uuid` will be populated.

This is desired so that for example you can use the `ID` column to double as a link, while still displaying the `ID` in the column. 

When I have time I will try to patch it but thought I'd start by reporting it.

**Comment by lrljoe** [comment]
In the interim, add the field to the setAdditionalSelects:

```
public function configure(): void
{
  $this->setAdditionalSelects(['uuid']);
}
```

**Comment by G4Zz0L1** [comment]
It should be documented, in my opinion, the documentation currently says the opposite (screenshot below).
Furthermore it's not specified in the "Other column types" page.
And why does the `LinkColumn` class have the `$from` attribute if it's not used in the select?
Thanks in advance.

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/13220636/50402778-1b08-4a36-9b7a-ec06d6bf7c7d)
