### ISSUE TITLE
Add french language

### ISSUE THREAD

**Issue by invaders-xx** [rappasoft/laravel-livewire-tables#102]
Please find below the french translation:
return [
    'clear' => 'Réinitialiser',
    'export' => 'Exporter',
    'loading' => 'En cours de chargement...',
    'no_results' => 'Il n\'y a pas de résultat à afficher pour cette requête.',
    'offline' => 'Vous n\'êtes pas connecté à l\'internet actuellement.',
    'per_page' => 'Par page',
    'results' => 'Affichage des entrées :first à :last sur un total de :total',
    'search' => 'Chercher...',
];
Hope it helps !

**Comment by invaders-xx** [comment]
This one is better for "Clear" button
return [
    'clear' => 'Effacer',
    'export' => 'Exporter',
    'loading' => 'En cours de chargement...',
    'no_results' => 'Il n\'y a pas de résultat à afficher pour cette requête.',
    'offline' => 'Vous n\'êtes pas connecté à l\'internet actuellement.',
    'per_page' => 'Par page',
    'results' => 'Affichage des entrées :first à :last sur un total de :total',
    'search' => 'Chercher...',
];

**Comment by rappasoft** [comment]
I'll add manually thanks.
