### ISSUE TITLE
setTableWrapperAttributes default is false, not true

### ISSUE THREAD

**Issue by joseph-d** [rappasoft/laravel-livewire-tables#1029]
Referring to the [the docs for setTableWrapperAttributes()](https://rappasoft.com/docs/laravel-livewire-tables/v2/datatable/available-methods#content-settablewrapperattributes) it is stated as follows:

> By default, this replaces the default classes on the table wrapper, if you would like to keep them, set the default flag to true.

However, I have found that this is not the case. For example, if I pass this:

```
        ->setTableWrapperAttributes([
            'class' => 'new-class'
        ])
```

The result of the code in `table.blade.php` which combines the classes is `shadow overflow-y-scroll border-b border-gray-200 dark:border-gray-700 sm:rounded-lg new-class`

To get the described behaviour of replacing the default classes, it is necessary to pass `'default' => false`

I'm happy to submit a PR either for the behaviour or for the docs, but I'm unsure what the desired behaviour is supposed to be. Should `table.blade.php` be updated so that it works in the way that the docs describe it, or should the docs be updated so that they explain how it currently behaves?

**Comment by lrljoe** [comment]
So I did a couple of tests on this one.
->setTableWrapperAttributes([
    'class' => 'new-class',
]);
Adds the "new-class" as expected to the default class list

->setTableWrapperAttributes([
    'class' => 'new-class',
    'default' => false,
]);
Replaces all wrapper classes with "new-class", as (knowing the code) I'd expect.

->setTableWrapperAttributes([
    'class' => 'new-class',
    'default' => true,
]);
Adds the "new-class" as expected to the default class list

So yep, feel free to issue a PR for the docs as they should reflect default behaviour, this mirrors the rest of the package so it's not unexpected.  If you don't get round to it by the end of the weekend then I'll update and issue a PR, just a bit short of time at the mo, good catch tho!

**Comment by lrljoe** [comment]
Bump, still needs docs fixing

**Comment by lrljoe** [comment]
Going to review the docs for this tomorrow as I've had a similar experience with other methods when testing.
