### ISSUE TITLE
Using label() on a column make it unsortable

### ISSUE THREAD

**Issue by wmfairuz** [rappasoft/laravel-livewire-tables#1033]
Hi,

I realized that when I use label() on a column, the column header is not longer sortable.

Example:
`
Column::make("No dobi", "no_dobi")->label(fn($row, Column $column) => $row->no_dobi_str)->sortable()
`

**Comment by lrljoe** [comment]
Use the sortable() function for this:

`Column::make("No dobi", "no_dobi")->label(fn($row, Column $column) => $row->no_dobi_str)->sortable(fn (Builder $query, string $direction) => $query->orderBy('no_dobi', $direction)),`

**Comment by lrljoe** [comment]
@wmfairuz if this is sorted, then please mark it as resolved , otherwise give me an update and I'll try to lend a hand

**Comment by gRoberts84** [comment]
I'm also experiencing this with the following:

```
Column::make('Sites')->label(
    fn($row) => $row->sites_count
)->sortable(
    fn(Builder $query, string $direction) => $query->orderBy('sites_count', $direction)
)
```

Tried it without the sortable callback and that made no difference. 

Columns with an actual column in the table sorts as expected.

**Comment by lrljoe** [comment]
Yeah, any time you have a label only column, you'll need to tell the component how to sort using parameters in the sortable() method
This is because the column isn't linked to a field, so it can't automatically determine how to sort.

**Comment by gRoberts84** [comment]
Hey @lrljoe 

Thanks for getting back to us.

Unfortunately in both of my examples above, even with a sortable callback, the column does not show the icon on hover to indicate that sorting is supported.

I might be doing something wrong though?

**Comment by lrljoe** [comment]
Very strange!  Let me take a quick look in my demo environment and see if I can figure out what's going on!

**Comment by lrljoe** [comment]
How odd!  There's a workaround where you use format() instead of label(), and just specify a column that you're not using as the field.

I'll definitely give this a proper poke and figure out why that's the case though!

**Comment by lrljoe** [comment]
Given it a poke, have somewhat of a solution, but needs a bit more work before I can really do a PR, and @rappasoft may not like the solution

**Comment by lrljoe** [comment]
So solution seems fairly stable, I'll issue a PR next week for it, to join the dozens of others I've inundated Anthony with!

**Comment by lrljoe** [comment]
Update, I'll add the fix for this into the release after the imminent one, as the next release has a lot in already.

**Comment by lrljoe** [comment]
This should make it into 2.13

**Comment by lrljoe** [comment]
Still undecided if I've tested this sufficiently.  I'm planning to get the next version out in the next week, but this will definitely be fixed in the version after if not this next version.

Apologies, I've been caught up with other projects so haven't had much time to write the relevant tests.

**Comment by lrljoe** [comment]
This should make it in for the next release, I've added it in to remind myself.

**Comment by lrljoe** [comment]
Just to update, it is working as expected, but I need to fix it being absent from the Sortable Pills, definitely expect this in the next release.

**Comment by lrljoe** [comment]
Sortable Pills seems to be fixed, it needs further testing.  I'd welcome anyone else using the branch linked with this issue and letting me know if it fixes the issue!

**Comment by bhagat-abhishek** [comment]
can anyone let me know how can i fix it, please.

`Column::make('Views', 'views')
            ->label(fn ($row, Column $column) => $row->visit()->count())
            ->sortable(),`
            
 Above code doesnt work for me, and i am not sure how will it work.

**Comment by lrljoe** [comment]
> @lrljoe @gRoberts84 @wmfairuz can anyone let me know how can i fix it, please.
> 
> `Column::make('Views', 'views') ->label(fn ($row, Column $column) => $row->visit()->count()) ->sortable(),`
> 
> Above code doesnt work for me, and i am not sure how will it work.

Please open a fresh thread, rather than replying to closed threads.
