### ISSUE TITLE
Extra 'space' or padding on the right side

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-livewire-tables#1045]
Hi

Just created a new data table and can see that at the end, or right side of the table, there is some extra space.

![Screenshot 2023-02-09 at 12 02 00](https://user-images.githubusercontent.com/1177191/217795679-facf1b4f-069f-48a0-b70f-85ce6312775e.png)

I'm using the standard views, not published and not modified

**Comment by lrljoe** [comment]
I've been trying to replicate this with no success, can you confirm if this is resolved or outstanding?

**Comment by rabol** [comment]
NOTE: If I turn on the DevTools in Chrome, the extra space disappears

**Comment by lrljoe** [comment]
Can you post the full rendered html for the page, and your full component, or stick them in a repo where I can see them?

**Comment by krishnabinstellar-droid** [comment]
Let me know if this is resolved or not coz i am having the same.
