### ISSUE TITLE
how can I change the search pattern  

### ISSUE THREAD

**Issue by hemant17** [rappasoft/laravel-livewire-tables#105]
how can I change the search pattern  like i sarch 
NIFTY

but it shows in A to Z

It's show 
AXISNIFTY
BANKNIFTY 11 FEB21 27500 CE
NIFTY

but it's show search like 
NIFTY
AXISNIFTY
BANKNIFTY 11 FEB21 27500 CE

**Comment by maximiliandoerner** [comment]
Did you try to sort the table by giving the column `->sortable()` ?

**Comment by rappasoft** [comment]
In this current version you can not, in the next version 1.0 you control the search query.
