### ISSUE TITLE
Error creating join with multiple connection

### ISSUE THREAD

**Issue by fnorataEdra** [rappasoft/laravel-livewire-tables#1072]
Hello, first of all thank you for the excellent work done with this component.

I'd like to report this bug: if you have 2 models that have two different connections (to two different databases), when you create the query, the join doesn't take account of the database name.

I think the problem may be in the getTableForColumn function in WithData.php

Hoping to have been helpful in reporting
Good work

**Comment by lrljoe** [comment]
The join is a standard sql join.  What would you expect to happen?

**Comment by fnorataEdra** [comment]
I would expect to find the database name before the table name

```
class A extends Model
{
    protected $connection = 'mysql_a_connection';
....
}
```

```
class B extends Model
{
    protected $connection = 'mysql_b_connection';
....
}
```

```
Select .... from a.table1
join b.table2 on b.table2.id = a.table1.id_b
...
```

This code maybe can helps you:
$dbB = DB::connection("mysql_b_connection")->getDatabaseName();

**Comment by lrljoe** [comment]
The issue I can see with this is if you're not using federated connections.  

It's not a massive problem if they're both on the same server, but if they're on multiple servers then it will get a little complex and error prone, especially with the dynamic nature.

You can of course use the builder function and it  should work sensibly.

**Comment by fnorataEdra** [comment]
Of course, the user must also have access to both databases, otherwise I don't think it can be done.
Thanks for the tip about the use of [Builder](https://rappasoft.com/docs/laravel-livewire-tables/v2/usage/the-query#content-using-the-builder-method), I'll try :-)

Have a nice day
