### ISSUE TITLE
Unable to set custom view on BooleanColumn

### ISSUE THREAD

**Issue by michele-grifa** [rappasoft/laravel-livewire-tables#1083]
I read in the documentation the piece to customize the view for a BooleanColumn, but when i set my custom view, instead it always shows the default one, and no error is thrown.

Example:
```php
BooleanColumn::make('Att x PV 1', 'att_xPV1')
                ->sortable()
                ->hideIf($this->testata->att_xPV1 == "")
                ->collapseOnMobile()
                ->view('components.datatable.boolean')
```

Laravel Version: 9.52.4
Laravel Livewire Tables: 2.11.0

**Comment by lrljoe** [comment]
Use a standard column, Boolean is set to use a standardised view.

**Comment by michele-grifa** [comment]
Thanks it worked

**Comment by happymacarts** [comment]
+1 on this.  the docs need a pr to account for this one

**Comment by lrljoe** [comment]
Docs still need updating, please feel free to issue a PR if you have time to update them!

**Comment by lrljoe** [comment]
Merged fix for docs into develop, it'll be in the next release.  Thanks

**Comment by lrljoe** [comment]
This has been released, thanks for contributions!
