### ISSUE TITLE
Refresh propery doesn't seem to be used

### ISSUE THREAD

**Issue by pdiveris** [rappasoft/laravel-livewire-tables#109]
Hi,

I am adding 

```php
    public $refresh = 7000;

```

at the top of my "table" class but no matter what I set the number to it seems updating every three or four seconds.

Any ideas very welcome but also, Happy New year!

**Comment by rappasoft** [comment]
You are correct. I have [fixed](https://github.com/rappasoft/laravel-livewire-tables/commit/1b2d3a4e2f3515cdfa13feffd75ce3003151bfcb#diff-7d22ecdce0e565073859c4d7da646e10971953c67a0c96e9e5a512f588dbfe15R3) the issue and it will be available in the next 0.4 release.

You can publish the view and make that change if you don't want to wait.
