### ISSUE TITLE
search data then error method 

### ISSUE THREAD

**Issue by menphurk236** [rappasoft/laravel-livewire-tables#1090]
![2566-03-07 22_38_02-ระบบบริหารจัดการหอพัก บี เอส  ปล์ามวิว _ การจัดการผู้ใช้งาน](https://user-images.githubusercontent.com/16397672/223471452-44f07909-698d-437e-8a65-d9978001ea2a.png)

i want idea fix bug it

Thank you

**Comment by lrljoe** [comment]
Can you post the whole stack trace please

**Comment by jarwonozt** [comment]
> ![2566-03-07 22_38_02-ระบบบริหารจัดการหอพัก บี เอส ปล์ามวิว _ การจัดการผู้ใช้งาน](https://user-images.githubusercontent.com/16397672/223471452-44f07909-698d-437e-8a65-d9978001ea2a.png)
> 
> i want idea fix bug it
> 
> Thank you

Try to check your php extension and see fileinfo has been activated.
