### ISSUE TITLE
Error when try to apply default filter on boot level

### ISSUE THREAD

**Issue by jadersilvabr** [rappasoft/laravel-livewire-tables#1099]
I have a filter by status and it is defined as follows:

```
MultiSelectFilter::make('Status')
                ->options(
                    TextStatus::query()
                        ->orderBy('name')
                        ->get()
                        ->keyBy('id')
                        ->map(fn($status) => $status->name)
                        ->toArray()
                )
                ->filter(function(Builder $builder, array $values) {
                    $builder->whereHas('status', fn($query) => $query->whereIn('text_statuses.id', $values));
                }),

```
I would like to open the table already with the filter equal to 4.

For that I am trying to do the following like [here](https://rappasoft.com/docs/laravel-livewire-tables/v2/filters/applying-filters#content-apply-filters-at-the-component-boot-level)

```
public function mount() {
        $this->setFilter('status', '4');
    }
```

But I get the following error

App\Http\Livewire\Admin\Tables\TextsTables::App\Http\Livewire\Admin\Tables\{closure}(): Argument #2 ($values) must be of type array, string given, called in /var/www/logamers/vendor/rappasoft/laravel-livewire-tables/src/Traits/WithFilters.php on line 37

Could you help me?

**Comment by lrljoe** [comment]
The following should do the trick:
```php
public function mount() {
        $this->setFilter('status', ['4']);
    }
```

**Comment by jadersilvabr** [comment]
Hi, it did not work, nothing happens and list is not filtered!

**Comment by lrljoe** [comment]
What's the resultant query that you get?

Can you paste the relationship from your model for the "status" relationship?

**Comment by lrljoe** [comment]
Ah. Add it into your configure() rather than your mount, and it should do the trick.

Apologies that I overlooked that earlier!
