### ISSUE TITLE
Enhancement: posibility to turn off the 'pr. page' at the top

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-livewire-tables#11]
At the top of the table, there is drop-down to select number pr. table, it would be nice to be able to turn that off

**Comment by rappasoft** [comment]
You can turn pagination off, are you saying turn it off with pagination still on?

**Comment by rappasoft** [comment]
I added a feature to turn it off while keeping pagination on in the next release.

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-livewire-tables/releases/tag/v0.1.3
