### ISSUE TITLE
Add custom class to table header and data

### ISSUE THREAD

**Issue by khairu-aqsara** [rappasoft/laravel-livewire-tables#110]
How to Add custom class to table header and data

**Comment by iosiflivadaru** [comment]
You can view all the available methods [here](https://github.com/rappasoft/laravel-livewire-tables#table-methods). 

If you don't know how to implement it, here is an example for others that might struggle:
```php
  public function setTableRowClass($model) : ?string {
    if ($model->id === 1) {
      return "test";
    }
    return '';
  }
  public function setTableRowAttributes($model) : array {
    if ($model->id === 4) {
      return ['name' => 'my-custom-name', 'data-key' => 'my-custom-key'];
    }
    return [];
  }
```

Make sure you put this code in your **LivewireTable.php**

**Comment by rappasoft** [comment]
It's in the docs: https://github.com/rappasoft/laravel-livewire-tables#table-methods
