### ISSUE TITLE
error creating multi-select filters

### ISSUE THREAD

**Issue by fernandcf** [rappasoft/laravel-livewire-tables#1109]
public function filters(): array
    {

        return [
            MultiSelectFilter::make('countries')
                ->options([
                    'one option',
                    'two option',
                ]),
        ];
    }

when trying to create this filter it gives me the following error

`foreach() argument must be of type array|object, string given`

**Comment by lrljoe** [comment]
You seem to be missing your filter method/callback from the end there, unless you're calling that from a when function?

Are you able to post your whole component?

**Comment by lrljoe** [comment]
Hey @fernandcf are you still having an issue with this?  If so can you post your component code and I'll see if I can help
