### ISSUE TITLE
Export extension stuck at txt

### ISSUE THREAD

**Issue by RJFares** [rappasoft/laravel-livewire-tables#111]
I have followed the doc examples, and when it's time to download the exported table, I'm always receiving it as a .txt extension.
Anyone has the same issue and was able to easily solve it without overriding the Export class?

I did an override of the export method and noticed that the parent::export is returning the file export as "Symfony\Component\HttpFoundation\BinaryFileResponse" which for me makes sense that the livewire is returning a txt, but I don't see how it may work for others with the correct extension.

I am using the defaults configs and maatwebsite/excel

**Comment by ScriptingBeating** [comment]
I am having the same problem. It is exporting a text file instead of the exported type file. @RJFares Did you solve this problem?

**Comment by RJFares** [comment]
> I am having the same problem. It is exporting a text file instead of the exported type file. @RJFares Did you solve this problem?

Not yet as luckily I have not needed this feature yet

**Comment by rappasoft** [comment]
New version lets you control exports fully, but also requires some modifications since it was a ground up rebuild.

**Comment by ScriptingBeating** [comment]
What modifications are you talking about? I have done all the modifications mentioned in docs.

**Comment by damms005** [comment]
I think this has more to do with how Livewire is handling such response. What I do is:

```
            $randomPath = storage_path(Str::of('file-')->append(Str::random(7))->append(now())->append('.xlsx')->lower());

            (FastExcel($this->selectedRowsQuery->get()))->export($randomPath);

            return response()->download($randomPath)->deleteFileAfterSend();
```
