### ISSUE TITLE
Example from doco for Column::make(...)->format() does not work.

### ISSUE THREAD

**Issue by davidbelleoctfolio** [rappasoft/laravel-livewire-tables#1121]
If you copy paste the example given in the doco to a livewire table made for the User model, it does not work.

Steps to reproduce.
1. Run `php artisan make:datatable ContactsTable User`
2. Call @livewire('contacts-table') in a view somewhere. Table works as expected here.
3. Copy paste the code below into your newly created ContactsTable component inside the "columns()" function.
```
Column::make('Name')
    ->format(
        fn($value, $row, Column $column) => $row->first_name . ' ' . $row->last_name
    ),

```
`Column not found: 1054 Unknown column 'users.name' in 'field list'`

There is the work around of Column::make('Name')->label()->html() instead but would be great if this worked as per doco. 

Thanks

**Comment by lrljoe** [comment]
I think this has come about as a result of different versions of the demo code to be honest.

I've got half a dozen PRs to go through, but I'll look at revising the demo code by the end of next week.

**Comment by lrljoe** [comment]
Just been through all the docs, and can't find any reference/example for the above, can you do me a favour and drop me a link please?

**Comment by lrljoe** [comment]
Okay, the docs should be fixed in the next release.

Worth noting that if you are regularly concatenating the first/last name, that most of the DBs have a generated field method that you can use to return it as a field from the DB.  Slightly more performant than using PHP.

**Comment by davidbelleoctfolio** [comment]
Awesome. I'll check it out. Thanks
