### ISSUE TITLE
Search is not working when pasted on the field

### ISSUE THREAD

**Issue by harshuchilzy** [rappasoft/laravel-livewire-tables#1123]
Search is not fired up when copy / paste on the table's search field. Any solution for that?

**Comment by salioudiabate** [comment]
I have the same error

**Comment by harshuchilzy** [comment]
@salioudiabate I managed to do a workaround. 
```
 $('input[placeholder="Search"]').on("paste",function(){
            var _this=$(this);
            setTimeout(function(){
                $(_this).trigger('input');
            },500);
        });
```

**Comment by lrljoe** [comment]
Please can you confirm:
Tailwind or Bootstrap (and version)
The package version you're using
Livewire version
Laravel version
Alpine version
PHP version

And I'll try to replicate and fix properly.

**Comment by harshuchilzy** [comment]
> Please can you confirm: Tailwind or Bootstrap (and version) The package version you're using Livewire version Laravel version Alpine version PHP version
> 
> And I'll try to replicate and fix properly.

Tailwind
Tables Version 2.10
Livewire 2.5
Alpine 3.0.6
PHP 8.2

**Comment by lrljoe** [comment]
Is this still an issue?
