### ISSUE TITLE
setFilterSlideDownDefaultStatusEnabled Not Working !!!

### ISSUE THREAD

**Issue by akiftezcan38** [rappasoft/laravel-livewire-tables#1128]
By default, I want the filter slide to be open. But this feature is not working.
How can I solve this problem?

Current 
![image](https://user-images.githubusercontent.com/77398471/228663445-81481df1-debe-486d-902d-2911f1736ddf.png)

I want this
![image](https://user-images.githubusercontent.com/77398471/228664155-fc9aa1d4-5668-4740-8f16-edc799093c93.png)

**Comment by lrljoe** [comment]
Have you previously published the views?

**Comment by lrljoe** [comment]
I've just tested this in a fresh demo instance, and it is definitely working.

Can you post the contents of your configure() method please.

**Comment by lrljoe** [comment]
The normal cause of this is not having alpine 3.x present!

**Comment by lrljoe** [comment]
Is this still an issue, if so please let me know and re-open the issue!
