### ISSUE TITLE
CSS not loading on live server

### ISSUE THREAD

**Issue by pro-pooja** [rappasoft/laravel-livewire-tables#1140]
Hi, 
 I use this plugin with laravel 9, tailwind, alpine, and vite. CSS for the datatable is loading correctly on my local machine, on our live server CSS for the datatable is not loading. 
 
 Here is a screenshot from my local 
 
![Local-Draft](https://user-images.githubusercontent.com/89035927/229785001-e1db7519-8fa2-492a-b011-bfcd621da1e2.png)
 
Screenshot from live server
![staging-draft](https://user-images.githubusercontent.com/89035927/229785127-a02e60c4-46e8-4741-8d2c-23ca5859e69c.png)

Here is my vite.config.js

```
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    "server": {
        "host": "0.0.0.0",
        "watch": {
            "ignored": [
                "!**/vendor/**"
            ]
        },
        "port": 191
    },
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
});

````

Snippet from my theme layout app.blade.php

```
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="dark h-full">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title> {{ config('app.name', 'Laravel') }}</title>
        <link rel="stylesheet" href="{{ asset('fonts/material-icons.css') }}" />
        <link rel="stylesheet" href="{{ asset('fonts/octicons.css') }}" />
        @vite(['resources/css/app.css', 'resources/js/app.js'])
        @livewireStyles
        <style>
            [x-cloak] { display: none !important; }
        </style>
    </head>
```
    
Here is snippent tailwind.config.js
    
```
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Http/Livewire/*.php',
        './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
    ],
```

A snippet of livewire view
```
<x-app-layout>
 <div class="overflow-hidden sm:rounded-md">
            <livewire:user-datatables/>
        </div>
 </x-app-layout>
```

**Comment by lrljoe** [comment]
Looks like you may be missing some of the tailwind plugins.  
Have you run a production compile?

**Comment by pro-pooja** [comment]
@lrljoe Yes, I've run a production compile, but I am not sure if it is picking the compiled assets or not.
When I try to import CSS from app.js, on page refresh, it looks a little odd cause at that time the CSS is not loaded.

Here is my tailwind.config

```
const defaultTheme = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './app/Http/Livewire/*.php',
        './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                "tdl": {
                    "50": "#FEF4F1",
                    "100": "#FDE9E3",
                    "200": "#FBD2C6",
                    "300": "#F8B5A0",
                    "400": "#F49376",
                    "500": "#EF5D30",
                    "600": "#ED4917",
                    "700": "#E34212",
                    "800": "#D03D10",
                    "900": "#B9360E"
                }
            }
        },
    },

    plugins: [require('@tailwindcss/forms')],
    darkMode: 'class'
};
```

**Comment by lrljoe** [comment]
Please can you try the following for your tailwind.config, I appreciate I've removed your colours, but see what it does, and then tweak as required:

```php
/** @type {import('tailwindcss').Config} */

const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors')

module.exports = {
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('@tailwindcss/aspect-ratio'),
        require('@tailwindcss/line-clamp')
    ],
    purge: {
        content: [
            './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php',
            './app/Http/Livewire/*.php',
        ],
    },
    darkMode: 'class',
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter var', ...defaultTheme.fontFamily.sans],
            },
        },
    },
    variants: {
        extend: {
            backgroundColor: ['responsive', 'dark', 'checked', 'disabled', 'hover', 'focus', 'active', 'even', 'odd'],
            textColor: ['disabled'],
            opacity: ['dark'],
            overflow: ['hover'],
        }
    },
};

```
You'll need to install the additional @tailwindcss

Please can you also drop in your 
resources/js/app.js
and
package.json

As I'm intrigued as to what the issue you're having with it not loading correctly!

**Comment by lrljoe** [comment]
Finally taken a second look, don't include your CSS in this fashion.

Instead include it in your app.js and reference that in your vite config.

See #1165 for an example

**Comment by pro-pooja** [comment]
@lrljoe , I've done the changes you mentioned. But still no luck.

This is my package.json

```
{
    "private": true,
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "heroku-prebuild": "npm install",
        "heroku-postbuild": "npm run build"
    },
    "devDependencies": {
        "@alpinejs/focus": "^3.12.0",
        "@tailwindcss/forms": "^0.5.2",
        "alpinejs": "^3.4.2",
        "autoprefixer": "^10.4.2",
        "axios": "^0.27",
        "laravel-vite-plugin": "^0.6.0",
        "lodash": "^4.17.19",
        "postcss": "^8.4.6",
        "tailwindcss": "^3.1.0",
        "vite": "^3.0.0"
    }
}
```

Here, is app.js

```
import './bootstrap';
import Alpine from 'alpinejs';
import focus from '@alpinejs/focus';
import '../css/app.css';

window.Alpine = Alpine;
window.Alpine.plugin(focus);
window.Alpine.start();
```

**Comment by lrljoe** [comment]
Is this still an issue, if so please let me know!

**Comment by pro-pooja** [comment]
@lrljoe , Yes this is still an issue.

**Comment by lrljoe** [comment]
Okay, and you've run
"npm update"
and
"npm run build" 
In your console?  Did it return any errors?

If you run php artisan view:clear, does that make any difference?

Do you have a CDN between you and your production environment?

**Comment by pro-pooja** [comment]
@lrljoe , I've run `npm update` and `npm run build`, and both executed successfully.

In the browser console, I see these messages

1. Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
2. Content Security Policy of your site blocks the use of 'eval' in JavaScript`

Also, I Tried clearing the cached view.

No, we are not using any CDN. 

Removed ignore section from vite.config, looks like this
`
server: {
        "host": "0.0.0.0",
        "port": 191
    },
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
    ],
`


My app.css
`
@tailwind base;
@tailwind components;
@tailwind utilities;
`
 
I tried all of the things you have suggested, but nothing seems to be working

**Comment by lrljoe** [comment]
Livewire itself isn't properly compatible with CSP

You need to allow unsafe-eval for it to work.

**Comment by lrljoe** [comment]
It depends how you're implementing CSP to be honest!

Take a look at this package for implementing it within Laravel
https://github.com/spatie/laravel-csp

You'll then need to remove CSP from your webserver default headers.

Or take a look at this website which goes into detail on implementation of CSP on a range of webservers
https://content-security-policy.com/examples/
