### ISSUE TITLE
php artisan make:datatable does not work when models are in an atypical location

### ISSUE THREAD

**Issue by nie7321** [rappasoft/laravel-livewire-tables#1153]
The `MakeCommand` assumes models will either be directly under `app/`, or in `app/Models`. In projects that keep models elsewhere (e.g. domain-driven design), the make command does not work.

I tried giving it a fully-qualified class name, but this does not work. It would be good if that were an option?

**Comment by lrljoe** [comment]
This did come up previously, it's certainly something I'll take another look at. you can of course extend the MakeCommand in the interim!

**Comment by lrljoe** [comment]
Can you give me an example of where else you'd anticipate storing them, I'm assuming still somewhere in the App namespace?

**Comment by nie7321** [comment]
Yeah, I'm doing a domain-driven thing, so I've got them split up across several folders in  `app/Domains/**/Models`.

I ended up implementing this to either take something prefixed with `\App` as-is, or discover across all `app/Domains/<something>/Models` folders:

```php
    public function getModelImport(): string
    {
        $this->model = Str::replace('/', '\\', $this->model);
        if (Str::startsWith($this->model, ['\\App\\', 'App\\'])) {
            return $this->model;
        }

        $modelDirs = Finder::create()
            ->directories()
            ->in([
                app_path('Domains').DIRECTORY_SEPARATOR.'**',
                app_path(),
            ])
            ->name('Models');

        $modelName = Str::afterLast($this->model, '\\');
        foreach ($modelDirs as $modelDir) {
            $fullyQualifiedName = Str::of(Arr::join([$modelDir->getPath(), 'Models', $modelName], DIRECTORY_SEPARATOR))
                ->afterLast('app/')
                ->prepend('App/')
                ->replace('/', '\\');

            if (class_exists($fullyQualifiedName)) {
                $this->model = $fullyQualifiedName;

                return $this->model;
            }
        }

        $this->error('Could not find path to model.');

        return $this->model;
    }
```

Something I've seen [another package do](https://github.com/kevincobain2000/laravel-erd) is include this in their config. I can give a path with the glob so it's able to discover all the models -- perhaps something similar might be appropriate here?

```
'models_path' => sprintf('%s/Domains/**/Models', base_path('app/')),
```

**Comment by lrljoe** [comment]
Would it work for you if you were able to pass in the path to the model?
e.g.
php artisan make:datatable UserTable User 'app/Domains/Test/Models'

**Comment by nie7321** [comment]
Yeah, absolutely!

**Comment by lrljoe** [comment]
I'll be able to get that into the next version, and will also look at your other suggestion of the models_path in the config for a future release.

**Comment by nie7321** [comment]
thank you! 🚀

**Comment by lrljoe** [comment]
PR #1163 has this in, I just need to add some relevant tests.

**Comment by lrljoe** [comment]
Migrated to #1168 and merged into Develop - will be in next release.  Feel free to use "dev-develop" temporarily if you want to test this out.

**Comment by lrljoe** [comment]
In 2.13.0, should be resolved now, please re-open if this is not the case!
