### ISSUE TITLE
Export table data bug

### ISSUE THREAD

**Issue by roomdada** [rappasoft/laravel-livewire-tables#1155]
The selection when exporting brings back an empty string. Can you tell me what is the cause of this problem. And the selection of all the elements of the table brin
![Screenshot (184)](https://user-images.githubusercontent.com/61591337/230989403-ef515a34-7138-4453-8a06-833c89f1d19a.png)
![Screenshot (183)](https://user-images.githubusercontent.com/61591337/230989394-2e4311e8-a91b-4aa9-a714-1e13333bf063.png)ack an error. You will find attached the different captures.

**Comment by lrljoe** [comment]
It looks like you're missing the "id" field from your query.  Replace "activities" with the actual SQL name of your table.

```php
    public function configure(): void
    {
        $this->setPrimaryKey('id')
            ->setAdditionalSelects(['activities.id as id']);
    }
```

If that doesn't work, please paste your component code here, then I may be able to offer more help.

**Comment by roomdada** [comment]
thanks a lot, it'is ok now
