### ISSUE TITLE
MorphTo relationship not working !

### ISSUE THREAD

**Issue by MarienMupenda** [rappasoft/laravel-livewire-tables#1164]
I am in the situation as below

Table
![image](https://user-images.githubusercontent.com/57844897/232264695-11427653-2da5-498a-adbd-49e490cd656d.png)

Model
![image](https://user-images.githubusercontent.com/57844897/232264757-c2dd27d6-0e59-4c61-b691-22a7017c0630.png)

Table
![image](https://user-images.githubusercontent.com/57844897/232264796-23ddaf4e-bffe-4384-9076-19691d2fa62a.png)

Result
<img width="912" alt="image" src="https://user-images.githubusercontent.com/57844897/232264906-cd62e148-33c0-44e3-9e37-b8e5b291bf0b.png">

**Comment by lrljoe** [comment]
You should be referencing inventoriable as your morph method.

**Comment by MarienMupenda** [comment]
> inventoriable
```php

    public function inventoriable(): MorphTo
    {
        return $this->morphTo();
    }
```

```php
public function columns(): array
    {
        return [
            Column::make("created_at"),
            Column::make("Quantity", "quantity")
                ->sortable(),
            /*Column::make('Article', 'model.name')
                ->sortable(),*/
            Column::make('Article', 'inventoriable.name')
                ->sortable(),

        ];
    }
```

Result
<img width="903" alt="image" src="https://user-images.githubusercontent.com/57844897/232426772-f8cdf644-3095-4f54-83d9-faba6484f99a.png">

It not working, and then is there any way for the package to simple take loaded fields by Eloquent ORM instead of making SQL queries?

In fact, the dynamic property below won't be recognized because the package will look fot it in the database table.
```php
    public function getProductNamesAttribute()
    {
        return $this->model->pluck('name');
    }
```

```php
 Column::make('Article', 'product_name')
                ->sortable(),
```

Result
<img width="902" alt="image" src="https://user-images.githubusercontent.com/57844897/232428987-a24ea924-4d6e-4a3e-b2ba-faa587237547.png">

**Comment by lrljoe** [comment]
For dynamic properties, use a label() Column, and you can then call any method/attribute you like on the row, keep in mind that it will potentially result in additional DB calls.
```php
Column::make('Product Name')
                ->label(fn ($row) => ($row->productName ?? '')),
```

You can also use setAdditionalSelects in your configure() method to add more fields in for you to use to avoid additional DB queries.

Ability to dynamically load in custom attributes etc are likely to come in v3.0, but that's some way off!

**Comment by MarienMupenda** [comment]
Thank you it's working now!

Of cours the issue was also on my structure, the below code works now.
```php
     public function model(): MorphTo
    {
        return $this->morphTo('model', 'inventoriable_type', 'inventoriable_id');
    }
```
or
```php
    public function inventoriable(): MorphTo
    {
        return $this->morphTo();
    }
```

You also have to eager load the model.
```php

    public function builder(): Builder
    {
        return Inventory::with('inventoriable') // Eager load anythingJoin some tables
        ->select(); // Select some things
    }
```

The you can use it as below.
```php
Column::make('Article')->label(function (Inventory $model) {
                return $model->inventoriable->name;
            }),
```
