### ISSUE TITLE
Need to click twice on a filter option  if one has been set during mount

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#1169]
I noticed a small bug when I'm using a datatable with a mount  function to preset a filter like:

```
    public function mount() {
        $this->setFilter('year', 2);
    }
```
If I'm trying to select an option in another MultiSelectFilter, I need to click twice on the checkbox the first time (it's ok afterwards).

Note : I'm using the slidedown filter version.

Thanks, Denis

**Comment by lrljoe** [comment]
So mount() will only run on the first boot (I'm sure you know that)

I'll have a look and see what it's doing with your use case.

**Comment by lrljoe** [comment]
Is your filter "Year" a MultiSelectFilter? If so, you need to pass it an array, 
```php
    public function mount() {
        $this->setFilter('year', [2]);
    }
```

**Comment by lrljoe** [comment]
If you've got a MultiSelectFilter in use, can you do me a favour and just paste that filter into here please?

**Comment by lrljoe** [comment]
Also, FYI - I've created a setFilterDefaultValue() method for the filters, as I appreciate it can be a tad annoying to not have that capability.  I just need to write the tests (I feel that a day of coding tests is in my imminent future).

**Comment by dgillier** [comment]
Here is one of my MultiSelectFilter

```
            MultiSelectFilter::make(__('cruds.payment.fields.status'), 'status')
                ->options(PaymentStatus::names())
                ->setFilterSlidedownColspan(2)
                ->filter(function (Builder $builder, array $values) {
                    $builder->whereIn('status', $values);
                }),
```

**Comment by lrljoe** [comment]
I'm assuming that your "names" method for the PaymentStatus is cached somewhere speedier than the DB?  If not, let me know and I'll drop a line of code in that'll make subsequent loads a little speedier for you.

There's a few tweaks to make setting options a little easier in the next release and the one that follows, as the continual pulling of options from databases (especially with more complex option sets or multiple filters) does have an impact on larger tables.

**Comment by dgillier** [comment]
Thanks,« names » is an enum class method return enum translated content :)On 21 Apr 2023, at 07:31, Joe ***@***.***> wrote:﻿
I'm assuming that your "names" method for the PaymentStatus is cached somewhere speedier than the DB?  If not, let me know and I'll drop a line of code in that'll make subsequent loads a little speedier for you.
There's a few tweaks to make setting options a little easier in the next release and the one that follows, as the continual pulling of options from databases (especially with more complex option sets or multiple filters) does have an impact on larger tables.

**Comment by lrljoe** [comment]
Definitely cache that, whether in a local public variable, or using the Cache helper, as that'll speed up your table massively.

**Comment by lrljoe** [comment]
In 2.13.0, should be resolved now, please re-open if this is not the case!
