### ISSUE TITLE
Bug with formatting

### ISSUE THREAD

**Issue by alesonyeagwa** [rappasoft/laravel-livewire-tables#1179]
First off, this is a wonderful package. I appreciate the efforts put into building this.
I understand that only created columns (that are not labels) are selected in the select query, however, would that not make the format example here behave incorrectly?  https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-modifying-the-column-value

**Comment by lrljoe** [comment]
Yep, you'd need to use setAdditionalSelects to add the extra fields in.

I'll update the documentation to reflect this in the version after next.
