### ISSUE TITLE
Syntax error in ...\vendor\rappasoft\laravel-livewire-tables\src\Views\Traits\FilterConfiguration.php using php 7.4

### ISSUE THREAD

**Issue by 1andy11** [rappasoft/laravel-livewire-tables#1180]
Hello,

you have an error in the file ...\vendor\rappasoft\laravel-livewire-tables\src\Views\Traits\FilterConfiguration.php using php 7.4

these two functions

public function setFilterSlidedownRow(string|int $filterSlidedownRow): self
public function setFilterSlidedownColspan(string|int $filterSlidedownColspan): self

Regards,
Andrej.

**Comment by lrljoe** [comment]
What error are you receiving?

It may be because PHP7.4 doesn't support typehinting fully.

Do you have a requirement to not upgrade to PHP 8.x?

**Comment by 1andy11** [comment]
Hello,
 
the error is related to string|int in php 7.4.
I cannot upgrade to 8.x for now.
The strange thing is that string|int is used only in this file in whole project. If it is not used anywhere else and it is declared to support php7.4 it should be fixed. For now I replaced your file with mine using autoload.
 
Regards,
Andrej Nagy.
 
______________________________________________________________
> Od: "Joe" ***@***.***>
> Komu: "rappasoft/laravel-livewire-tables" ***@***.***>
> Dátum: 05.05.2023 13:34
> Predmet: Re: [rappasoft/laravel-livewire-tables] Syntax error in ...\vendor\rappasoft\laravel-livewire-tables\src\Views\Traits\FilterConfiguration.php using php 7.4 (Issue #1180)
>
 
What error are you receiving?
It may be because PHP7.4 doesn't support typehinting fully.
Do you have a requirement to not upgrade to PHP 8.x?

**Comment by lrljoe** [comment]
Opened PR #1185 which addresses this.

**Comment by lrljoe** [comment]
In next release (possibly releasing this weekend)

**Comment by lrljoe** [comment]
It's probably worth mentioning that the tests for 7.4 aren't currently enabled as some of the test methods aren't supported in 7.4.

So I'd have to look at either alternative tests or disabling certain ones for 7.4.  I don't plan on doing either immediately but someone else may pick it up.

Of course you're welcome to take a look and produce 7.4 versions of the tests that don't work, I know it'd be appreciated!

**Comment by lrljoe** [comment]
Merged into Develop

**Comment by lrljoe** [comment]
In 2.13.0, should be resolved now, please re-open if this is not the case!
