### ISSUE TITLE
ImageColumn Type doesn't add field to select

### ISSUE THREAD

**Issue by rsee49** [rappasoft/laravel-livewire-tables#1184]
Hi,
as mentioned in title, I have an issue when I try to add to DataTable an image column type.
In this case, the field isn't in the model (laravel) and consequentially, it's not possibile to get value from it during
the closure execution as showed here:

https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/other-column-types#content-image-columns

Thanks in advance, for support.
Have nice and good coding day!

**Comment by lrljoe** [comment]
Use the setAdditionalSelects method to add the field to the query.

**Comment by rsee49** [comment]
@lrljoe thanks!
It runs smoothly..
