### ISSUE TITLE
BulkAction Select All does not select checkboxes for hash ids

### ISSUE THREAD

**Issue by saleemepoch** [rappasoft/laravel-livewire-tables#1192]
In this datatable I am fetching records from MongoDB with hash IDs like so:
`645a5018c981bdaa2108d252`

As you can see, Select All checkbox is checked, it says 661 rows selected, but none of the checkboxes are selected:
<img width="424" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/7266213/f074d74e-e742-409c-ab85-9af1dedbaf89">

In the BulkAction method, the getSelected() method gives me this:
<img width="417" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/7266213/dac1a5ec-ac24-4d8b-8592-30a043b86cd4">

I assume this is because the ids are hashes rather than typical integers.

<img width="555" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/7266213/b15d640c-f53d-4142-af41-4c122cdca4e5">
<img width="416" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/7266213/f79722a5-a97b-4566-b99c-d8bdf57761f4">

Any help will be appreciated.

**Comment by lrljoe** [comment]
I'm working on a migration to using AlpineJS for Bulk Actions which should in theory sort this. it's 95% of the way there.

**Comment by lrljoe** [comment]
So 2.13 may fix this, can you let me know if it does please?

**Comment by saleemepoch** [comment]
I just updated composer and unfortunately the issue is still there :/

**Comment by lrljoe** [comment]
Are you are able to run either the debugbar or the debug console?

If so, try selecting a row, and change the page (i.e. go to page 2 or 3).

When you do this do you see any values in the selected array on the component?

Can you use developer tools in your browser, inspect the checkbox, does it have a value?
