### ISSUE TITLE
Tailwind checkboxes are solid white in dark mode

### ISSUE THREAD

**Issue by bengs** [rappasoft/laravel-livewire-tables#1199]
Checkbox classes in the Tailwind views contain both `text-indigo-500` and `dark:text-white`. 
This causes checkboxes to display like this when checked in dark mode:
<img width="217" alt="Screenshot 2023-05-16 at 13 41 09" src="https://github.com/rappasoft/laravel-livewire-tables/assets/20150565/60285100-d549-48a7-9ee7-300ebf1e572b">. 
Solution: remove all `dark:text-white` classes from checkboxes:
<img width="217" alt="Screenshot 2023-05-16 at 13 42 19" src="https://github.com/rappasoft/laravel-livewire-tables/assets/20150565/3d9052c8-82c6-4462-aa04-304e8f6e29d5">.  
Also the checkboxes are repeated a little in the code, refactoring them to a blade component might be a good thing to do, so they're utilised similarly to this:
```
<x-livewire-tables::inputs.checkbox wire:model="selected" wire:loading.attr.delay="disabled" value="{{ $row->{$this->getPrimaryKey()} }}"  />
```
Then if people want to change look of the checkboxes eg the primary `*-indigo-*` colour classes they only need to publish & modify classes inside `inputs/checkbox.blade.php` rather than components inside multiple folders like`table/td`, `table/th` `tools` etc.

**Comment by lrljoe** [comment]
Good idea with refactoring into a blade, however bulk actions changes slightly in the next version, as it moves to AlpineJS approach.

I'm currently reviewing more of the blades to get more refactored, and removing some of the existing theme behaviour where the code is repeated, and using conditional classes.

Expect this to be in the version after this imminent release.

**Comment by lrljoe** [comment]
I've tested in the current develop stream, and the checkbox works as expected in light/dark modes for Tailwind 2 and 3:

**Dark**
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/104938042/7edf134c-0770-412e-a399-bd65631326c1)

**Light**
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/104938042/e4e86b7c-0eea-4f0a-aa70-ae6791ac9c83)

I suspect either someone else spotted this and did a PR, or I inadvertently fixed it while migrating the code over to Alpine!

**Comment by lrljoe** [comment]
If you can test using the develop branch and let me know if its still an issue or not, then that'd be handy!

**Comment by bengs** [comment]
Aha, it's still happening for me on the `develop` branch but your screenshot was helpful because I'd assumed the checkmarks were supposed to be `indigo` in both light and dark mode, but in your testing they're white. So the problem is actually with the checked colour classes not working as expected in tailwinds default **_system_** dark mode. When I inspect the CSS the `dark:bg-gray-900` it is being overriden by the combination of `dark:text-white` and the following `@tailwindcss/forms` CSS:
```
[type="checkbox"]:checked, [type="radio"]:checked {
  border-color: transparent;
  background-color: currentColor;
  background-size: 100% 100%;
  background-position: center;
  background-repeat: no-repeat;
}
```
Which picks up on the `dark:text-white` and also makes the background colour white.
Screenshot of applied CSS:
<img width="260" alt="Screenshot 2023-05-17 at 14 18 45" src="https://github.com/rappasoft/laravel-livewire-tables/assets/20150565/5133714a-774b-4ff8-889d-c808f3bbe2fa">

However if you use `darkMode: 'class',` in your tailwind config, then it works because this CSS takes precedence:
```
:is(.dark .dark\:bg-gray-900) {
  --tw-bg-opacity: 1;
  background-color: rgb(17 24 39 / var(--tw-bg-opacity));
}
```
[There is an open tailwind forms issue for it here](https://github.com/tailwindlabs/tailwindcss-forms/issues/74).
Personally I think the checkboxes work well as indigo in both light and dark modes, but either way if we follow Adam Wathan's suggested fix changing the active checkbox colours to utilise `checked:bg-*` instead of `text-*` colours that works. Here's a copy of your `bulk-actions.blade.php` checkbox classes using `checked:bg-indigo-600` and `dark:checked-bg-indigo-500` etc instead of text colours and that equalises the behaviour across both dark modes for me:
```
<input class="rounded border-gray-300 checked:bg-indigo-600 shadow-sm transition duration-150 ease-in-out focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 dark:bg-gray-900 dark:checked:bg-indigo-500 dark:checked:focus:bg-indigo-500 dark:checked:hover:bg-indigo-500 dark:border-gray-600 dark:hover:bg-gray-600 dark:focus:bg-gray-600">
```

**Comment by bengs** [comment]
Also nice work with the Alpine checkboxes on the `develop` branch, they're notably more responsive to toggle.

**Comment by lrljoe** [comment]
No problem, more to come imminently in AlpineJS migrations as it really smooths the experience.

**Comment by lrljoe** [comment]
Tweaked the labels so that I've captured the enhancement request with the blade for checkboxes.

**Comment by lrljoe** [comment]
Just to update, and be realistic!  In terms of refactoring checkboxes into a blade.  This is on the roadmap, but not in an immediate release.

In terms of blades at the moment, my priority is rebasing all of the blades to use conditional classes and styles across TW/BS4/BS5.

Once that is done, then I'll be able to more readily implement UX improvements!

At the moment, functional changes and improvements are taking longer than I'd like to implement, and I'm sporadically missing adding attributes to one or more of the themes, which means panic-stations and multiple releases, which I really **need** to avoid.

I'd expect moving steadily to conditional classes in 2.15, completing by 2.20.

2.20+ will have some more refactoring of some of the controls & elements, including checkboxes.

I'm not intending on such a lengthy period between releases going forward, so it shouldn't be too long before this all starts rolling out.

**Comment by iamgoodbytes** [comment]
Hey friends, bumped into this issue as well and saw that it was logged here. I updated to 2.14 but still have the white on white checkboxes. Is that something that will be released later? 

I tried to find it in the CHANGELOG but that mentioned "Bulk Actions (alpine.js)".

Just checking. Thanks to both for picking this up!

**Comment by bengs** [comment]
@iamgoodbytes it might be a while before it's fixed but a quick fix in the meantime is to set dark mode manually by adding `darkMode: 'class'`, to your `tailwind.config.js` file like this:
```js
module.exports = {
  darkMode: 'class',
  // ...
}
```
And adding a `dark` class to your `<html>` element (or whichever element you want to scope dark mode too):
```html
<html lang="en" class="dark">
```
More info here: https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually

**Comment by iamgoodbytes** [comment]
Thanks @bengs - that does the trick!

**Comment by lrljoe** [comment]
I'll make a note to update the docs to reference this, thought it was in there already to be honest.
