### ISSUE TITLE
Getting offline error even if online

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-livewire-tables#12]
I'm getting the " You are not currently connected to the internet." even if I'm online

**Comment by rappasoft** [comment]
Was this a local error or do I need to fix something?

**Comment by rabol** [comment]
One get this error if there is a 'JS conflict' - I cannot reproduce it 100% relaible

**Comment by rabol** [comment]
![Screenshot 2020-05-08 at 09 35 08](https://user-images.githubusercontent.com/1177191/81382821-4700e780-910f-11ea-841c-f347a6da4f73.png)

**Comment by rappasoft** [comment]
Hmm it's really just the livewire feature I didn't implement it any differently.

**Comment by rabol** [comment]
I know, which is why I closed the ticket :)

**Comment by rappasoft** [comment]
Ok just making sure it wasn't something I had to look into :)
