### ISSUE TITLE
Nested Children

### ISSUE THREAD

**Issue by inmanturbo** [rappasoft/laravel-livewire-tables#121]
Is there a way nest children rows, perhaps collapsible?
Or perhaps inject another livewire component at the row level?

i.e.
  - Parent Permission1> <--click me to expand
      - Child Permssion1     -- hidden by default
      - Child Permission2    -- hidden by default
  - Parent Permission2 > <--click me to expand
       - Child Permission1   -- hidden by default
       - Child Permission2   -- hidden by default

**Comment by inmanturbo** [comment]
Never mind. I see this is very easy to if you publish the views.

**Comment by invaders-xx** [comment]
@inmanturbo , how did you handle that please ?
