### ISSUE TITLE
[Bug]:  Bulk action btn and secondary header bar are flashing on refresh

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#1210]
### What happened?

When the table is displayed (or refresh) the Bulk action btn (and a bar behind the table headers) is appearing and disappearing, creating a not very nice flashing effect...

### How to reproduce the bug

Always present

### Package Version

2.13.0

### PHP Version

8.1.x

### Laravel Version

9.xx

### Alpine Version

3.1.2

### Theme

None

**Comment by dgillier** [comment]
Of course only on tables with selectable rows...

**Comment by lrljoe** [comment]
Can you pop an example component in here if possible?
I'll try to replicate.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by dgillier** [comment]
https://github.com/rappasoft/laravel-livewire-tables/assets/37960204/763365f2-55cc-47b8-9267-3fc2e3a185ea
