### ISSUE TITLE
[Bug]: SelectAllOnpage does not work if "select all" has been done

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#1212]
### What happened?

If you had selected all rows, a click on the new "select all on page" is doing nothing.
I'm expecting it to unselected all the other rows and keep select only the page ones.

### How to reproduce the bug

Allways

### Package Version

2.13.1

### PHP Version

8.1.x

### Laravel Version

9.X

### Alpine Version

3.1.12

### Theme

None

**Comment by lrljoe** [comment]
That's a good point/thought, and one I hadn't considered!  I can't promise to fix that bit today, I will try, but if not then it'll be very high on my list for the week.

**Comment by lrljoe** [comment]
Current approach is okay with Anthony, but I'll be looking at some configurable options for this going forward

**Comment by lrljoe** [comment]
So I think my approach is going to be:

If all on page are not selected, displayed option will be:
- select all on page 

If all on page are selected, displayed option will be:
- deselect all on page

I'm also going to add in a configure() toggle to enable/disable the per-page options, and in a later version add toggles for tablet/mobile

Does that work for you?  If you have any UX suggestions then I'd be very receptive as that's not my area of expertise!

**Comment by dgillier** [comment]
Looks good to me!

Thanks :)

**Comment by lrljoe** [comment]
Cool, I'm also planning a toggle for "track selected across pages", where you can enable or disable the default behaviour of persisting the selection across pages.
