### ISSUE TITLE
[Bug]: If you go to another page with selected rows and do a browser back, rows are still selected but the bulk action btn is not visible

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#1213]
### What happened?

 If you go to another page after having selected rows and do a browser back, rows are still selected but the bulk action btn is not visible...

If you then click to another row, the already selected rows are unselected...

### How to reproduce the bug

Always

### Package Version

2.13.1

### PHP Version

8.1.x

### Laravel Version

9.XX

### Alpine Version

3.1.12

### Theme

None

**Comment by dgillier** [comment]
No Js errors and using OSX Chrome

**Comment by lrljoe** [comment]
Hmm, this is definitely a very odd behaviour.  I've got a fix together for the bulk actions button/row remaining visible if any item is selected.

On pressing the back button, any items that were selected on the previous lifecycle will become unselected, maybe I'm sleep deprived, but that seems to be me to be what I'd expect to happen - thoughts from your side?
i.e.
You select three items on Page 1
Click to go to Page 2
You select two items on Page 2
Click to go to Page 3
Change your mind, and click the browser back button, the three items from Page 1 will be selected, but the two items from Page 2 will not.

This is the default Alpine/JS behaviour anyway, particularly when you're deferring updates, as you're effectively "undoing" the last activity (which includes updating the selected array)

If that's what you'd expect then I can get this fix in place very shortly.

**Comment by lrljoe** [comment]
@dgillier  - Do you fancy taking the develop branch for a quick spin on this one too.

It will "forget" the previous page's selections if you use the Browser Back Button, but not if you paginate.  That should at least be a reasonable fix for now, and I'll add in an option to either persist it or forget it for the next proper release.

**Comment by lrljoe** [comment]
I've made some further tweaks to the behaviour, it will still clear whatever you did in the previous page view when you click back, but it won't display any oddities now.

I'm intending to do some Alpine style data store/persistence as an option, so that it can work either way.  That's a June project most likely unless everyone wants it to persist across back button presses.

**Comment by lrljoe** [comment]
Discussed this one with Anthony, current approach is okay. I am going to introduce some options for behaviour in a future release though.


 Unless it's actually not behaving at all, but I threw as much as I could at it and it seems okay now
