### ISSUE TITLE
Export file can't download

### ISSUE THREAD

**Issue by sumon4skf** [rappasoft/laravel-livewire-tables#123]
I using on on table..
**public $exportFileName = 'Customer Wallet';
public $exports = ['xlsx', 'xls', 'pdf', 'csv'];**

After export file save on **storage/framework/laravel-excel** but can't download the file. I read all the docs and instruction but can't solve it.

**Comment by FareedR** [comment]
I also got issue with this , are you able to solve this ? @sumon4skf

**Comment by sumon4skf** [comment]
I can't solve yet!
**But I use this package on laravel 8 and that is work.**
I am also use on laravel 6 and 7 . After export, file store the same directory but can't force to download.
