### ISSUE TITLE
[Bug]: Failed to get all records when using GROUP BY or alike and pagination

### ISSUE THREAD

**Issue by sebacastroh** [rappasoft/laravel-livewire-tables#1235]
### What happened?

I noticed that when a query builder uses ```GROUP BY``` (or some other aggregated functions), pagination fails to get all records when ```perPage``` is set to ```-1``` (all records). This happens because when the pagination is called in ```executeQuery```, the result of ```$this->getBuilder()->count()``` does not return the correct number of rows due to the ```GROUP BY```

https://github.com/rappasoft/laravel-livewire-tables/blob/77408c70837de90839e55dc97f832d2135db07be/src/Traits/WithData.php#L48

Some discussions about this can be found on internet (e.g., https://stackoverflow.com/questions/47608873/laravel-count-vs-get-count). Basically, Laravel does not apply the count function as expected when there is a ```group by``` and the pagination method could receive an incorrect value.

Also, there has been some discussion to get all records when pagination is called (Ref: https://github.com/laravel/framework/issues/16578), but there is no input to get all records automatically. I did the following code to solve the problem based on that discussion, but I didn't create a PR as I haven't tested thoroughly ([here is my fork](https://github.com/sebacastroh/laravel-livewire-tables/tree/fix-get-all-records)) 

```php
protected function executeQuery()
{
    if ($this->paginationIsEnabled()) {
        $perPage = $this->getPerPage();
        if ($perPage === -1) {
            $results = $this->getBuilder()->get();
            $this->paginationTotalItemCount = $results->count();
            return new \Illuminate\Pagination\LengthAwarePaginator($results, $this->paginationTotalItemCount, -1);
        } else if ($this->isPaginationMethod('standard')) {
            $paginatedResults = $this->getBuilder()->paginate($perPage, ['*'], $this->getComputedPageName());

            // Get the total number of items available
            $this->paginationTotalItemCount = $paginatedResults->total() ?? 0;

            return $paginatedResults;
        } else if ($this->isPaginationMethod('simple')) {
            return $this->getBuilder()->simplePaginate($perPage, ['*'], $this->getComputedPageName());
        }
    }

    return $this->getBuilder()->get();
}
```

This will return the current behaviour if ```perPage``` is different to ```-1```, but in case you want to get all results, it will get the data first and then count it. The queries are not affected at all, just the count.

### How to reproduce the bug

Use ```GROUP BY``` or some aggregate selects such as 

```php
public function builder(): Builder
{
    $suffix_roles = '_1';
    $suffix_regions = '_2';
    $query = User::withRoles($suffix_roles)
        ->withRegions($suffix_regions)
        ->groupBy(['users.id'])
        ->select([DB::raw('MIN(CONCAT_WS(";;",`roles' . $suffix_roles . '`.`precedence`, `roles' . $suffix_roles . '`.`readable_name`)) as `precedence`'),
                  'regions' . $suffix_regions . '.label as region_name',]);

    return $query;
}
```

### Package Version

2.14

### PHP Version

None

### Laravel Version

9.52.6

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
To start - thanks for such a detailed report!

I'll give it a review on Monday, but at first glance it looks okay to me.  Feel free to open a PR and I'll mark it as in-progress/draft until its fully tested, mostly so we can keep track of anything pending.

**Comment by sebacastroh** [comment]
Hi 👋 

I researched a little more. Looking the source code of ```paginate``` (ref: https://github.com/laravel/framework/blob/fd4619b56b56308e2c2c1840fedd0b8ebb73dfc5/src/Illuminate/Database/Eloquent/Builder.php#L897) I noticed that ```$perPage``` can be ```int```, ```null``` or a ```Closure``` instance. In the latter case, it receives the ```total``` parameter that is computed using ```$this->toBase()->getCountForPagination();```. With that on mind, I did the following change in my project

```php
protected function executeQuery()
{
    if ($this->paginationIsEnabled()) {
        $perPage = $this->getPerPage();
        if ($this->isPaginationMethod('standard')) {
            $perPage  = $perPage === -1 ? $perPage = function ($total) {return $total;} : $perPage;
            $paginatedResults = $this->getBuilder()->paginate($perPage, ['*'], $this->getComputedPageName());

            // Get the total number of items available
            $this->paginationTotalItemCount = $paginatedResults->total() ?? 0;

            return $paginatedResults;
        }

        if ($this->isPaginationMethod('simple')) {
            $perPage = $perPage === -1 ? $perPage = $this->getBuilder()->toBase()->getCountForPagination() : $perPage;
            return $this->getBuilder()->simplePaginate($perPage, ['*'], $this->getComputedPageName());
        }
    }

    return $this->getBuilder()->get();
}
```
In the case of the standard pagination method, it indicates that ```$perPage``` will be equal to ```$total``` as it is computed in the paginate function. On the other hand, for the simple pagination method, it uses the ```getCountForPagination``` function to determine the total amount of rows. I think this is the proper way to do it.

> To start - thanks for such a detailed report!
> 
> I'll give it a review on Monday, but at first glance it looks okay to me, but will probably need a toggle to enable/disable the behaviour. If you try and do a get() without pagination on a 1.5m row table with 100 concurrent users then something will almost certainly have a moan!

I think that if you have a very large table, you have to be aware of this and decide if you enable or not this option. Remember that the ```-1``` value is optional and not added by default, so the developer should understand the risk of enabling this. We are using this option for small tables (~500 rows) but for large ones we do not give the option to the user.

> Feel free to open a PR and I'll mark it as in-progress/draft until its fully tested, mostly so we can keep track of anything pending.

I will open a PR with this changes, I tested on the project of my company and it's working well.
