### ISSUE TITLE
Always show button (bulkActions)

### ISSUE THREAD

**Issue by lrljoe** [rappasoft/laravel-livewire-tables#1239]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/1238

<div type='discussions-op-text'>

<sup>Originally posted by **LaMance22** June  1, 2023</sup>
Hi.

Is it possible to make the "bulkActions" button always visible? after update, it appears only after selecting a row in the table. I understand that this may be the case, but in my case it will be better if it is always visible.

https://rappasoft.com/docs/laravel-livewire-tables/v2/bulk-actions/available-methods</div>

**Comment by lrljoe** [comment]
Not forgotten just haven't had time.  Expect fix for this within a week

**Comment by lrljoe** [comment]
I'm still doing some final tests, PR is ready, just want to make sure nothing else is broken/impacted

**Comment by manuelsansoresg** [comment]
aun no he podido hacer que se vean las acciones masivas :( tengo la ultima versión

**Comment by manuelsansoresg** [comment]
I have not yet been able to show the massive actions :( I have the latest version

**Comment by lrljoe** [comment]
Hi @manuelsansoresg - the fix to enable "always show bulk actions" will be in the next release.

For now, once you select one of the rows, and have Bulk Actions Enabled, then the dropdown will appear with your configured bulk actions.
See [this guide](https://rappasoft.com/docs/laravel-livewire-tables/v2/bulk-actions/introduction) for details on how to configure Bulk Actions.

**Comment by lrljoe** [comment]
@manuelsansoresg  - This is in 2.15, please let me know if you have any issues!
