### ISSUE TITLE
Add an 'emit' event trigger to a custom column.

### ISSUE THREAD

**Issue by fikoulli** [rappasoft/laravel-livewire-tables#124]
Hi All,

Thx for  this excellent component.
I have a question please,

Is there a way to Add an 'emit' event trigger, Ex :

           <  button wire:click="$emit('postAdded')" >
           
to a custom livewire-tables colum (or in another way) ?, Ex :   

            Column::make(__('Actions'))
                ->format(function(Mymodel $model) {
                    return view('backend........', ['mymodel'=>$model]);
                })

So that, when you click on this button, you trigger an event in another livewire component.

Thx in advance.

**Comment by fikoulli** [comment]
Hi all,

I'll answer my self :)
Maybe it will help someone else,

In the Actions column, I didn't put the variable between {{ }}

Before: didn't work :
    wire:click.prevent="$emit('MyLivewireEvent', $userId )"

After : worked :
    wire:click.prevent="$emit('MyLivewireEvent', {{ $userId }} )"

**Comment by Denysetya1** [comment]
Hi, I'm having trouble creating an action button using emit on a column, can you write down how to add it?

Thank you
