### ISSUE TITLE
[Bug]: Fix ambiguous column id when using JOIN

### ISSUE THREAD

**Issue by demeus** [rappasoft/laravel-livewire-tables#1274]
### What happened?

@rappasoft

```

  public array $selectedColumns = [
        'users.id',
        'users.name',
    ];
    
      
    public array $relations = [
        'roles',
    ];

 public function columns(): array
    {
        return [
                        Column::make("id")
                             ->searchable(),
                             
                         Column::make("name")
                             ->searchable(),      
                   ];
    }
    
    
     public function builder(): Builder
    {
        return User::query()
          ->addSelect($this->selectedColumns)
            ->with($this->relations)
           
           ->join('roles', 'roles.user_id', '=', 'user.id');
    }
```

I've tried setting it via

```
 ->addSelect($this->selectedColumns)
->select($this->selectedColumns)
```

in Builder
and in configure via
->additionalSelects($this->selectedColumns)

but either way I get an error 
Column 'id' in field list is ambiguous
this will only work if you put 
```
Column::make("id")
                ->deselected()
```
            

### Package Version

2.15

### PHP Version

8.0.x

### Laravel Version

9.52.10

### Alpine Version

^3.10.4

### Theme

None

### Notes

I also noticed that the first time I load the query, it runs correctly. 
```
SELECT DISTINCT
    `users`.`id`,
    `users`.`title`
FROM
    `users`
INNER JOIN 
```

but when searching for sql the query changes to the following
```
SELECT DISTINCT
   `id`,
  `title`
FROM
    `users`
INNER JOIN 
```

### Error Message

SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous

**Comment by demeus** [comment]
I still get this error.
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/2157091/24a9e89c-ea3f-4566-8609-9dcbfb6cfae7)

I've put the project on git so you can see all the code
https://github.com/demeus/laravel-livewire-tables/blob/main/app/Http/Livewire/Promotion/DashboardTable.php
https://github.com/demeus/laravel-livewire-tables

**Comment by lrljoe** [comment]
You didn't follow the guidance around the use of setAdditionalSelects(), look at my previous example and it should clear that up.

It's also really not good practice to keep extending classes.  Look at using a trait instead where you need to re-use code repeatedly.

Finally, you're ordering & limiting in your builder() function, which negates the whole purpose of using a package that provides sortable/pagination etc.
