### ISSUE TITLE
[Bug]: "All Columns" checkbox does not match the current selection.

### ISSUE THREAD

**Issue by rpringadi** [rappasoft/laravel-livewire-tables#1276]
### What happened?

"All Columns" checkbox does not match the current selection, if we use [`deselected()` ](https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/column-selection#content-deselected-by-default)

### How to reproduce the bug

* I create seven columns `Column::make`
* Two of them, set it with `->deselected()`
* Example:
```PHP
            Column::make(__('users.First Name'), 'firstname')->sortable()->searchable(),
            Column::make(__('users.Last Name'), 'lastname')->sortable()->searchable(),
            Column::make(__('common.Email Address'), 'email')->sortable()->searchable(),
            Column::make(__('common.Department'), 'teamuser.department.name')->sortable()->searchable(),
            Column::make(__('common.Title'), 'teamuser.position.name')->sortable()->searchable(),
            Column::make(__('users.Last Access Time'), 'last_login_at')->deselected()->sortable(),
            Column::make(__('Role'))->label(function ($user) use ($currentTeam) {
                echo "role";
            })->deselected()->sortable(),
            Column::make(__('common.Actions'))->label(function ($user) {
                echo "[action 1] [action 2]";
            })
        ];
```
* Click the columns drop down. See picture attachment. Notice that "All Columns" is actually not all columns.
* Toggle "All Columns" (Click to uncheck and check again). Notice that "All Columns" is actually not all columns. 
<img width="616" alt="Screenshot 2023-07-25 at 11 26 58 AM" src="https://github.com/rappasoft/laravel-livewire-tables/assets/2053877/3da716cc-2347-4099-8215-ff7129ab0992">

Expectation:

* On page load, "All Columns" is not checked, because we have one or more columns `deselected()` by default.
* Manual toggle of "All Columns", will make the `deselected()` column(s) reselected.

### Package Version

2.14.0

### PHP Version

8.2.x

### Laravel Version

10.3.3

### Alpine Version

3.0.6

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
That's an odd one, thanks for raising it.

We're focusing on v3 at the moment, but I'll be back to clear up any outstanding bugs with v2 once we've released v3.

**Comment by lrljoe** [comment]
I'll review the PR by next weekend, as I currently am trying to get some fixes backported in V2 from V3, but this is very much on my radar!

**Comment by lrljoe** [comment]
Slightly easier way to fix this, which I've done in v3, and I'll backport

**Comment by lrljoe** [comment]
Sadly I'll need to adjust some tests, but this is on my radar!

**Comment by lrljoe** [comment]
Needs a backport, but v3 is significantly different so needs a careful review, thus the delay

**Comment by lrljoe** [comment]
V3 Beta is out.  So I will be reviewing backports this weekend.
