### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of null (reading '__livewire')

### ISSUE THREAD

**Issue by amshehzad** [rappasoft/laravel-livewire-tables#1279]
### What happened?

I just installed the package and created a component. when I render the users component, I can see the page but in the console I see errors:
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/15146578/3ef29ffe-4453-454a-b3f4-344ba20a4b17)
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/15146578/b3373824-3374-48b9-9135-6f1d840327b4)

Now if I do any action ( sort, search etc ) I don't see the component at all and have the above mentioned errors in the console

### Package Version

2.15.0

### PHP Version

8.1.x

### Laravel Version

10.3.1

### Theme
3.7.1
Bootstrap 5.x

### Error Message

Uncaught TypeError: Cannot read properties of null (reading '__livewire')

Uncaught ReferenceError: paginationTotalItemCount is not defined

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/15146578/15136e12-1947-4414-82d6-4cb65ab7c341)

**Comment by lrljoe** [comment]
Do you have livewire installed?  Which version?

**Comment by amshehzad** [comment]
Yes, I'm already using Livewire in all difference places. I'm using v2.12.3

**Comment by lrljoe** [comment]
Okay, that's certainly unusual, please can you confirm that you:
1) Have not published the views for this package
2) That you have not added any render() etc to your table component
3) That you're referencing your table component within a blade in the normal way?

**Comment by amshehzad** [comment]
Certainly.
I just created datatable using the command from documentation:

and here is the component: 

```
class UserTable extends DataTableComponent
{
    protected $model = User::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable(),
            Column::make("Created at", "created_at")
                ->sortable(),
            Column::make("Updated at", "updated_at")
                ->sortable(),
        ];
    }
}
```

and I'm rendering in my blade view:

```
@extends('layouts.app')

@section('content')
    {{--<livewire:datatables.user-datatable />--}}
    <livewire:user-table/>
@endsection
```

currently I'm using my own custom datatable but now I'm trying to replace all of my datatables with this package.

when I load the page I see the table properly:

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/15146578/2197fec4-d24b-4a11-874e-6b5cba3bd45f)

I can see the above mention errors in console though.

but when I click on any action sort, pagination etc 

the component disappears 

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/15146578/13c99a6c-8d16-4713-b573-a9c2fb127e6f)

**Comment by lrljoe** [comment]
If you use discord, it may be easier to bounce back/forth on the Rappasoft discord:
[https://discord.gg/9dR8R3DwB](https://discord.gg/9dR8R3DwB)

**Comment by mrl22** [comment]
I have this same issue in Tailwind view only. When switching the config to Bootstrap4 or 5 I get no errors, but there is no CSS obviously.

**Comment by lrljoe** [comment]
The issue that the other gent had was undiagnosed, and seemed to be related to another package he was using, but it worked perfectly when he tried it in a fresh install.

**Comment by mrl22** [comment]
Thank you.

I have just resolved this in my version. I will explain what I did for anyone else who may see this.

It seems that in my app.js:

```
import Alpine from 'alpinejs'
Alpine.start()
```

This, for some reason was conflicting with laravel-livewire-tables.

I changed it to the following and it is now working:

```
import Alpine from 'alpinejs'
window.Alpine = Alpine
window.Alpine.start()
```

**Comment by lrljoe** [comment]
That's good to hear, with v3 currently in testing (which uses Livewire 3), that oddity goes away as well.
