### ISSUE TITLE
Status of this package

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-livewire-tables#128]
I apologize for being MIA for a _while_. Things got quite hectic with everything going on and maintenance on this project fell behind.

I've been using it on other projects, and I can just never get it to do all the things I want it to do because I think it's too restrictive.

So i've been working on a demo, it's not ready to be turned into a project yet but it's promising. The code is a lot more loose, but there is more of a learning curve because there is less API to consume and more grunt work.

I like to compare it to the javascript [photoswipe](https://photoswipe.com/documentation/getting-started.html) plugin, because there is a lot of up front work, but the result is nice and super configurable.

I am going to keep working on it, hopefully i'll get it to the point where i'm happy and can make it a version 1 of this package.

It also gives you full access to the DOM, because you write it instead of me generating it. So you can use wire:click and whatnot in your row actions, pop up modals, etc.

In the meantime, i'll probably go through all the issues and PR's and tag an 0.4 for all the people currently using this plugin. But when 1.0 comes out it will probably be a little bit of work to replace the current version to get this working.

[Here is a demo](https://streamable.com/h6mzbp) (built on tailwind in this case)

**Comment by ReinisL** [comment]
Thanks, @rappasoft for this great package! Can't wait for the new version

**Comment by pkeogan** [comment]
solid work, I forked off 0.3, but I'll come back and start making PRs to help out. Thanks for crushing that out!
