### ISSUE TITLE
[Feature Request]: Livewire 3 compatibility

### ISSUE THREAD

**Issue by zokistale** [rappasoft/laravel-livewire-tables#1281]
### Overview

I would like to use laravel-livewire-tables with Livewire 3, but it's not compatible yet.

### Detailed explanation

When installing the laravel-livewire-tables with Livewire 3 installed, it throws compatibility errors.

**Comment by zokistale** [comment]
Awesome. Keep up the good work!

**Comment by lrljoe** [comment]
I'm closing this as there's a discussion post for this:
[https://github.com/rappasoft/laravel-livewire-tables/discussions/1278](https://github.com/rappasoft/laravel-livewire-tables/discussions/1278)
