### ISSUE TITLE
[Feature Request] allow adding classes and attributes in input/search/select filters

### ISSUE THREAD

**Issue by fernandcf** [rappasoft/laravel-livewire-tables#1284]
### Overview

allow adding classes and attributes in input/search/select filters

**Comment by lrljoe** [comment]
We are reviewing filters as part of v3, and almost certainly completely overhauling for v4.

My plan (code permitting) is to introduce the capability to actually customer the display per-filter using a custom blade, but I don't know if it'll make it into 3.0 or not.

**Comment by lrljoe** [comment]
I previously customised certain filter classes etc, happy to discuss it on the Discord

**Comment by lrljoe** [comment]
I've added this into our v3 Project board, but it's unlikely to make the initial release.

Attributes for other elements is definitely something that will be looked into though, as the more customisable the better.

**Comment by lrljoe** [comment]
In the meantime, there are ways to add custom classes using some manual CSS, if you need pointers, please jump on the discord where I've previously posted examples

**Comment by lrljoe** [comment]
Just an update to say that this hasn't been forgotten.  It's in the pipeline, but still working out priorities, fixing bugs from V3 beta etc.

There are a few different pieces in flight, and this is definitely of them.

**Comment by lrljoe** [comment]
Just finished adding capability for
- Filter Popover Menu
- Search Box

this will go into v3 develop, probably after the weekend.

Once v3 is released then it may sneak onto the backports list.

**Comment by lrljoe** [comment]
Now added to filter text boxes/select boxes too

More to come once this is tested.

**Comment by lrljoe** [comment]
Completed:
SearchInput
FilterLabel

In Progress:
Filter Popover Menu
Filter Slidedown Menu

To Do:
Column Select
Filter Inputs

**Comment by lrljoe** [comment]
Closed - replaced with
#1472 - Filter Popover Menu
#1471  - Filter Slidedown Menu
#1470  - Filter Inputs
#1469  - Column Select
