### ISSUE TITLE
Can't install in Livewire3

### ISSUE THREAD

**Issue by mai1237** [rappasoft/laravel-livewire-tables#1293]
### What happened?

I hav tried to install having Livewire3 beta
and I got the message below:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rappasoft/laravel-livewire-tables[v0.1.0, ..., v0.2.1] require php ^7.2.5 -> your php version (8.2.4) does not satisfy that requirement.
    - rappasoft/laravel-livewire-tables[v0.3.0, ..., v0.3.2] require php ^7.3 -> your php version (8.2.4) does not satisfy that requirement.
    - rappasoft/laravel-livewire-tables[v0.3.3, ..., v0.4.0] require livewire/livewire ^1.3|^2.0 -> found livewire/livewire[v1.3.0, ..., v1.3.9, v2.0.0, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - rappasoft/laravel-livewire-tables[v1.11.0, ..., v1.14.0] require livewire/livewire ^2.5.3 -> found livewire/livewire[v2.5.3, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - rappasoft/laravel-livewire-tables v1.15.0 requires livewire/livewire ^2.6.2 -> found livewire/livewire[v2.6.2, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - rappasoft/laravel-livewire-tables v1.16.0 requires livewire/livewire ^2.6.5 -> found livewire/livewire[v2.6.5, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - rappasoft/laravel-livewire-tables[v1.0.0, ..., v1.19.1] require livewire/livewire ^2.0 -> found livewire/livewire[v2.0.0, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - rappasoft/laravel-livewire-tables[v1.19.2, ..., v1.25.1, v2.0.0, ..., v2.15.0] require livewire/livewire ^2.6 -> found livewire/livewire[v2.6.0, ..., v2.12.5] but it conflicts with your root composer.json require (^3.0@beta).
    - Root composer.json requires rappasoft/laravel-livewire-tables * -> satisfiable by rappasoft/laravel-livewire-tables[v0.1.0, ..., v0.4.0, v1.0.0, ..., v1.25.1, v2.0.0, ..., v2.15.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require rappasoft/laravel-livewire-tables:*" to figure out if any version is installable, or "composer require rappasoft/laravel-livewire-tables:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### PHP Version

8.2.x

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Please see the discussion, v3 of this package is under development which will support Livewire v3.

Unfortunately there were a few breaking changes, and Anthony and I also took the opportunity to make some other improvements.

**Comment by lrljoe** [comment]
[Please See Discussion](https://github.com/rappasoft/laravel-livewire-tables/discussions/1278)
