### ISSUE TITLE
[Feature Request]: getTableRowWireClick functionality in v2

### ISSUE THREAD

**Issue by trippo** [rappasoft/laravel-livewire-tables#1295]
### Overview

In v1 there was [getTableRowWireClick function](https://rappasoft.com/docs/laravel-livewire-tables/v1/rows/clickable-rows#content-working-with-wireclick-on-rows)

I can't see it on v2...

How can use `wire:click` when a row is clicked?

**Comment by lrljoe** [comment]
You can override the behaviour of a TR using the following:
```
public function configure(): void
{
  // Takes a callback that gives you the current row and its index
  $this->setTrAttributes(function($row, $index) {
      if ($index % 2 === 0) {
        return [
          'class' => 'bg-gray-200',
        ];
      }
 
      return [];
  });
}
```

You could add a wire:click to the return[] array to give this capability.

Adding wire methods/properties is something that'll come in v3.x (not initial 3.0-beta release), it's certainly something I routinely use so I'm keen to provide a smoother approach for everyone else.

**Comment by trippo** [comment]
Thanks a lot
