### ISSUE TITLE
Grand totals of all records

### ISSUE THREAD

**Issue by ntraykov** [rappasoft/laravel-livewire-tables#1296]
### Overview

I need to have a grand total of all records without pagination applied. Currently I cannot do that because the current builder has pagination applied.

**Comment by lrljoe** [comment]
You have opened discussions and issues on this.

You can add additional selects, or add withCount or withSum.

To return the entire unpaginated response in addition to a paginated one would be undesirable for 99.99% of users.

Adding a total for the entire dataset at the bottom of the table also goes against all UX practices.

This is not a bug, and not a feature request that is sensible to take forward in my opinion.

**Comment by ntraykov** [comment]
So, for those 0.01% of all the users on the planet (like me), is there a way to achieve this, despite going against all UX practies? Because you're sharing an opinion but doesn't offer a solution.

**Comment by lrljoe** [comment]
I think you'll find that I did give you a couple of options above!

You'd need to add additional selects (use setAdditionalSelects), or add a withCount or withSum using the builder() method, or add an additional query using the builder method.

OR

On boot run the query again but unpaginated, you'd need to use a trait to do this to avoid impacting the core functionality, and access the boot lifecylce from there.
