### ISSUE TITLE
[Feature Request]: Support protected $queryString

### ISSUE THREAD

**Issue by brianium** [rappasoft/laravel-livewire-tables#1298]
### Overview

It would be awesome if the following could work with regards to the standard livewire `$queryString` property.

```php
class MyTable extends DataTableComponent
{
    protected $model = MyModel::class;

    public string $startDate = "";

    public string $endDate = "";

    // It would be great if this worked
    protected $queryString = [
        'startDate', 
        'endDate' => ['except' => now()->format('Y-m-d')]
    ];
};
```

### Detailed explanation

The query string appears to be handled in the `Rappasoft\LaravelLivewireTables\Traits\ComponentUtilities` trait

```php
    /**
     * Set the custom query string array for this specific table
     *
     * @return array<mixed>
     */
    public function queryString(): array
    {
        if ($this->queryStringIsEnabled()) {
            // can we merge in $this->queryString here if it exists
            return [
                $this->getTableName() => ['except' => null, 'as' => $this->getQueryStringAlias()],
            ];
        }

        return [];
    }
```

This doesn't take into account any `$queryString` properties defined in a class extending `DataTableComponent`. I see that Livewire seems to prefer one over the other, so maybe this isn't the best path forward. Maybe this could be a documentation update?

### Notes

For now I overcome this limitation in my own data tables by defining the `queryString` method in my own components like so:

```php
    public function queryString(): array
    {
        return [
            ...parent::queryString(),
            'startDate' => ['except' => now()->subMonth()->format('Y-m-d')],
            'endDate' => ['except' => now()->format('Y-m-d')]
        ];
    }
```

**Comment by lrljoe** [comment]
I'll take another look at this once V3 is released.  But you can't have both in place I'm afraid, as one will always override the other (can't remember offhand which way V2 overrides!)

**Comment by lrljoe** [comment]
So reviewing this post v3 beta, I think your approach is probably the sensible one for now.

I'm trying to consider existing installations of the package, and anything changed in this regard is likely to break them sadly.

What is most likely is some methods to assist with merging.

What would your ideal solution be?

**Comment by brianium** [comment]
@lrljoe setting via `configure()` and `setAdditionalQueryStringOptions` sounds super intuitive.  Another option might be a template method that a user's DataTableComponent could define. I.e if a class extends `DataTableComponent` and defines `getAdditionalQueryStringOptions()` it's result will be merged for them.

I think given the current API (and my understanding of it), the `setAdditionalQueryStringOptions` seems more natural.

Thanks for looking into this 🙇🏻

**Comment by lrljoe** [comment]
No problem at all.  No promises on timescale this moment, but I'm adding it into the project roadmap this evening for v3 at least!

**Comment by lrljoe** [comment]
**For V3**

I've adjusted how queryString behaves significantly, you should now be able to use queryString() if you so desire without over-riding the core methods.
