### ISSUE TITLE
[Feature Request]: Livewire v3 Support

### ISSUE THREAD

**Issue by alphaolomi** [rappasoft/laravel-livewire-tables#1300]
### Overview

It will be great to have support for Livewire version 3 supported 

### Detailed explanation

When using LV v3, Installations of LLT package fails

**Comment by lrljoe** [comment]
Please see
[https://github.com/rappasoft/laravel-livewire-tables/discussions/1278](https://github.com/rappasoft/laravel-livewire-tables/discussions/1278)

**Comment by alphaolomi** [comment]
Thank you @lrljoe for pointing this out.

**Comment by lrljoe** [comment]
No problem @alphaolomi  - I do give more regular updates in the Discord if you want to join :)
