### ISSUE TITLE
[Bug]: Bulk Actions - Deselect all

### ISSUE THREAD

**Issue by OndrejMiko** [rappasoft/laravel-livewire-tables#1301]
### What happened?

When I click on checkbox in TH to select all it works , but when i clicked on "Deselect All" button it deselect all items but TH main checkbox stay checked 
<img width="401" alt="Screenshot 2023-08-14 at 17 04 36" src="https://github.com/rappasoft/laravel-livewire-tables/assets/9248133/1947bee0-3466-4eb0-addd-6125537a29eb">
<img width="399" alt="Screenshot 2023-08-14 at 17 04 45" src="https://github.com/rappasoft/laravel-livewire-tables/assets/9248133/5414e6ed-3fa9-4f4a-9044-aa00a960fa68">
 

### How to reproduce the bug

It do allways when i try

### Package Version

2.5

### PHP Version

8.2.x

### Laravel Version

10.0.3

### Alpine Version

3.4.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
I notice you're on version 2.5 of the package.  Are you able to update to the latest version?

There were some issues prior to 2.15 with bulk actions.

**Comment by OndrejMiko** [comment]
Sorry my bad I mispelled version , I am on version 2.15 , I send bad request . Its problem on version 2.15 . And found new one. If I have no items in table , main checkbox to select is selected

**Comment by lrljoe** [comment]
Thanks for the update @OndrejMiko  - I've got this on my to-do list to address both issues.

**Comment by lrljoe** [comment]
Are you using simple pagination out of interest?

**Comment by OndrejMiko** [comment]
> Are you using simple pagination out of interest?

What u mean simple pagination , pagination in livewire table ?

**Comment by lrljoe** [comment]
Yes, I'm in the process of reviewing the bug, but if you could share the contents of your configure() method from the component then that'd be great

**Comment by LaMance22** [comment]
I have the same problem. In addition, if I select all the results and export to EXCEL, the checkbox for selecting all is not unchecked.

I check "demo" https://tables.laravel-boilerplate.com/tailwind - it works, but the demo doesn't use AlpineJS.

```
    public function bulkActions(): array
    {
        return [
            'exportToXlsx' => __('Export to Excel),
        ];
    }
    public function exportToXlsx()
    {
        if ($this->getSelected()) {
            $clients= $this->getSelected();
            $this->clearSelected();
            return Excel::download(
                new TableExport($clients),
                __('Clients').'_'.date('d-m-Y_H-m-s').'.xlsx'
            );
        }
    }
```

**Comment by lrljoe** [comment]
Fix for this will be out next week!

**Comment by LaMance22** [comment]
> Fix for this will be out next week!

Hi, did you manage to solve the problem? If so, can you describe what changes should be made to the files? I'm pressed for time so I'll do it manually and then update it when it's available. Best regards.

**Comment by lrljoe** [comment]
If I didn't merge this fix already, then I'll take a look this weekend and figure out why I didn't, and get it merged in.

**Comment by lrljoe** [comment]
V3 Beta is out.  So I will be reviewing backports this weekend, and reviewing any v2 bugs
