### ISSUE TITLE
[Bug]: Column Hiding/Showing Giving Error When Playing Around With Columns

### ISSUE THREAD

**Issue by ethanpatchell** [rappasoft/laravel-livewire-tables#1318]
### What happened?

When I enable column selection on my table, and start playing around with what's hidden and shown / hide/show all it gives the following error:

Cannot assign bool to property Rappasoft\LaravelLivewireTables\DataTableComponent::$selectedColumns of type array

### Package Version

v3-master

### PHP Version

8.3.x

### Laravel Version

10.x

### Alpine Version

3.x

### Theme

Bootstrap 5.x

### Error Message

Cannot assign bool to property Rappasoft\LaravelLivewireTables\DataTableComponent::$selectedColumns of type array

**Comment by lrljoe** [comment]
Thanks for the report, will look at this later this evening.

**Comment by lrljoe** [comment]
Trying to get to the bottom of this one, is there any chance you can share a short video or similar of how you're getting that error to fire please?

Can't seem to replicate in my demo/test environments at the moment

**Comment by ethanpatchell** [comment]
https://github.com/rappasoft/laravel-livewire-tables/assets/139511867/ea5e1bd8-31c4-46af-922c-864b6ee9780e

I've just run composer update - which still hasn't fixed the issue.

The start of the video is fine till it starts bugging.

Also noticed the "all columns" checks and unchecks at the wrong times.

**Comment by lrljoe** [comment]
Thanks. I'll take a look.

Auth::id() is an easier way to get the current authenticated user's ID by the way!

**Comment by ethanpatchell** [comment]
Thanks - and I thought it might do but just stuck with what I knew ahahaha - I appreciate that, and will shorten it now :)

**Comment by lrljoe** [comment]
@ethanpatchell  - What's the blank column at the end of the list out of interest?

**Comment by lrljoe** [comment]
Definitely  seems specific to Bootstrap, I'll pull that apart this weekend to figure it out.

**Comment by lrljoe** [comment]
Still looking at this, think I may need to adjust how the column selection is functioning, not a big one tho!

**Comment by ethanpatchell** [comment]
Hey, it's just a link to another page - code below:

`LinkColumn::make('')
                ->title(fn($row) => 'Pet Dashboard')
                ->location(fn($row) => route('my.pets.dashboard', ['code'=>$row->code]))
                ->attributes(fn($row) => [
                    'class' => 'rounded-full',
                    'alt' => $row->name . ' Avatar',
                ]),`

**Comment by lrljoe** [comment]
Column Select fix should be read by Monday.

For your LinkColumn, as it's not related to a field it's displaying as a blank field in column select.  If you exclude it then that'll hide it from the Column Select:
```
  ->excludeFromColumnSelect(),
```
Alternatively you can use the labels & setCustomSlug to give it a name.

**Comment by lrljoe** [comment]
The bug with the state not being correct of the "Select All" is now fixed in "dev-v3-develop", this will go into dev-v3-master in the week.
