### ISSUE TITLE
[Bug]: Bulk Actions button not showing available options

### ISSUE THREAD

**Issue by kien-ha** [rappasoft/laravel-livewire-tables#1329]
### What happened?

Clicking the bulk actions button should open a dropdown menu of available bulk actions but it does not.

### How to reproduce the bug

With bootstrap-5 theme, click the bulk action button after selecting any number of rows. 

### Package Version

v3-master

### PHP Version

8.2.x

### Laravel Version

10.x

### Alpine Version

3.x

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
Now in v3-develop branch.  Will merge into master in the week.
