### ISSUE TITLE
[Bug]: wire:navigate not working on published view files

### ISSUE THREAD

**Issue by ethanpatchell** [rappasoft/laravel-livewire-tables#1349]
### What happened?

I published the view files, and am inside the `link.blade.php` file. I added `wire:navigate` to the `<a>` tag however it still reloads the page to render the new one.

`<a href="{{ $path }}" {!! count($attributes) ? $column->arrayToAttributes($attributes) : '' !!} wire:navigate>{{ $title }}</a>`

### Package Version

v3-master

### PHP Version

8.3.x

### Laravel Version

10.x

### Alpine Version

3.x

### Theme

Bootstrap 5.x

### Error Message

No error message

**Comment by lrljoe** [comment]
Hey @ethanpatchell - Can you please share:
1) The content of your edited blade file
2) The code for the Column that is using that file.
3) The resultant HTML in the browser

Feel free to just nudge me on Discord if that's easier

**Comment by lrljoe** [comment]
I'm currently testing a fix for lazy loading which may also fix this, will update most likely on Monday

**Comment by lrljoe** [comment]
On v3-develop branch, do you still experience this issue?

**Comment by lrljoe** [comment]
Worth noting you should add a wire:key to those links, just to make sure it's not going to act weirdly

**Comment by lrljoe** [comment]
Worth noting you should add a wire:key to those links, just to make sure it's not going to act weirdly
