### ISSUE TITLE
[Feature Request]: Livewire 3 Support

### ISSUE THREAD

**Issue by kornatzky** [rappasoft/laravel-livewire-tables#1352]
### Overview

Please upgrade the requirements to work with Livewire 3

### Detailed explanation

Currently trying to upgrade a project with Livewire 2 to Livewire 3, yields the error from composer:

  Problem 1
    - Root composer.json requires rappasoft/laravel-livewire-tables ^2.15 -> satisfiable by rappasoft/laravel-livewire-tables[v2.15.0].
    - rappasoft/laravel-livewire-tables v2.15.0 requires livewire/livewire ^2.6 -> found livewire/livewire[v2.6.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).

**Comment by lrljoe** [comment]
Please see the numerous discussions around the v3 beta for this package.
