### ISSUE TITLE
[Bug]: Multiple dispatch when a method is executed via an event

### ISSUE THREAD

**Issue by joserick** [rappasoft/laravel-livewire-tables#1353]
### What happened?

Multiple dispatches are generated when executing a method through an event that in turn triggers another event.

app.js or DeviceTable.php
```js
Livewire.dispatch('load-token', [true]);
```
```php
$this->dispatch('load-token', true)->to(Device::class);
```
Device.php
```php
#[On('load-token')]
public function token(bool $status) : void {
    if ($status) {
        // ...
        $this->dispatch('get-hostname');
    }
}
```

Out:
```json
{
	"components": [
		{
			"snapshot": "...",
			"effects": {
				"returns": [
					null
				],
				"html": "...",
				"dispatches": [
					{
						"name": "get-hostname",
						"params": []
					},
					{
						"name": "get-hostname",
						"params": []
					},
					{
						"name": "get-hostname",
						"params": []
					},
					{
						"name": "get-hostname",
						"params": []
					}
				]
			}
		}
	]
}
```

### How to reproduce the bug

1. Create a component.
2. Add a method that listens to an event.
3. Add a dispatch in the method.
4. Dispatch the event for the second executive event.

### Package Version

dev-v3-develop

### PHP Version

8.2.x

### Laravel Version

10.23.1

### Alpine Version

3.13.0

### Theme

Tailwind 3.x

### Notes

If I delete this part of the code from the LaravelLivewireTablesServiceProvider.php file on line 49 it no longer launches multiple events, unfortunately I don't understand what exactly these lines do.

```php
if (config('livewire-tables.inject_assets', true) === true) {

    (new RappasoftFrontendAssets)->boot();
    app('livewire')->componentHook(AutoInjectRappasoftAssets::class);
    ComponentHookRegistry::boot();
}
```

**Comment by joserick** [comment]
I think that apparently the "boot" method of "ComponentHookRegistry" is re-executed, which was already executed by Livewire, causing the components to be registered in the lifecycle several times.

```php
(new RappasoftFrontendAssets)->boot();
app('livewire')->componentHook(AutoInjectRappasoftAssets::class);
// ComponentHookRegistry::boot(); <- Remove this line.
```

**Comment by lrljoe** [comment]
@joserick - does the removal of that fix your issue?

The FrontendAssets provide various AlpineJS and custom CSS that are used throughout the table by injecting (once) the relevant includes, without the necessity of referencing the various items.

I'm still reviewing various options for toggling the different behaviour options etc tho!

**Comment by joserick** [comment]
Yes, removing the line fixed the problem and the table works fine, of course I am only using the basics of the livewire-table component, so I am not sure if all its features work correctly.

Regarding Discord, don't worry, you better focus on what the next development RP would be.

Thanks.

**Comment by lrljoe** [comment]
Next develop PR will include:
- Ability to add the Rappasoft (and relevant 3rd party) elements via your app.js
- Initial Draft of a Livewire Component Filter

Expect it probably close of play tomorrow.

**Comment by lrljoe** [comment]
@joserick  - Out of interest, did you update your Livewire to 3.0.4?  Josh made some tweaks to the way that the injectors/component hooks works, which I need to port back across.

Will still be merging in the smoother app.js approach tho!

**Comment by joserick** [comment]
Yes, I have updated to version 3.0.4 and run "npm update && npm run build" and "php artisan view:clear" but if not remove "ComponentHookRegistry::boot();" continues launching multiple dispatches.

**Comment by lrljoe** [comment]
Just spoken to LW core devs, couple of tweaks I need to backport.

There's an open PR for this package which will allow you to more smoothly add the specific Rappasoft code into your app.js and then turn off the injection completely.

I expect to finish testing it tomorrow or Saturday, and will merge it into develop then.

**Comment by lrljoe** [comment]
Fixes seem to work, it was just a movement of some of the injection elements.

I'll need to test:
1) app.js import approach
2) Injection approach
3) Multiple table components on a page

Before I can merge it in, but initially, it seems okay.

**Comment by lrljoe** [comment]
Fix should be in develop by mid week

**Comment by lrljoe** [comment]
Believe this should now be in v3-develop

Admittedly keeping track of which fixes I've merged is a struggle this week!

Let me know if not fixed in that branch, as I'll have the fix somewhere :)

**Comment by jacksontong** [comment]
@lrljoe I don't think it's on v3-develop, it's still happening for me.

`Upgrading rappasoft/laravel-livewire-tables (dev-v3-develop e609f13 => dev-v3-develop e7c10c1)`

**Comment by lrljoe** [comment]
Hmm, it's entirely possible I've missed off a merge, give me 20 mins, as that v3-develop branch definitely doesn't have the fix

**Comment by lrljoe** [comment]
Should be in v3-develop now, just ran a quick test and got a single dispatch of an event

**Comment by lrljoe** [comment]
@joserick  - Note that this should be resolved (I believe) in v3-develop, unless someone says otherwise!

I will be merging v3-develop into v3-master, and then onto a proper beta release by the end of the weekend, with a view to having an official v3 not too long after that, thanks to everyone using the develop branches.

**Comment by jacksontong** [comment]
yep, it fixed on my end too.

**Comment by lrljoe** [comment]
Awesome!  Glad to hear it.

Please do raise any other issues on here, and feel free to give me a prod on Discord, or tag me in the issue, there's one or two very minor bugs I'm aware of (which involve all kinds of edge scenarios), and a couple of new features that I'm trying to finalise prior to getting the official beta out.

I really, genuinely appreciate your patience, and the awesome feedback, and detailed info throughout the beta period that helps identify the issues (95% of the battle).

I was oh-so-keen to get it released shortly after LW3 was released, but wanted to instead take the opportunity to adjust the code so that it's easier to deliver new features, performance enhancements etc, as it's rare that there's the opportunity to really drains-up the codebase.

We should be back to normal in the coming days :)

**Comment by lrljoe** [comment]
Please reply if this re-occurs, closing purely so I can tell what's outstanding!
