### ISSUE TITLE
[Bug]: Search input looses focus on initial search reload

### ISSUE THREAD

**Issue by othyn** [rappasoft/laravel-livewire-tables#1359]
### What happened?

When using the search functionality on a table, on submitting the _initial_ search and it has been applied, the table is reloaded and the search box looses focus.

However, once you re-focus onto the search box, for subsequent searches the search box remains focused despite new results being returned - which is how I would expect the table to behave at all times.

### How to reproduce the bug

Reproducing the bug:

1. Navigate to a fresh page with a table on it.
2. Perform a search until the table is refreshed. An easy way to confirm this is once the search query parameters have been added to the URL `?table[search]=xyz`.
3. The search box will loose focus.

Working reproducable example of how I think it should behave:

1. Navigate to a fresh page with a table on it.
2. Perform a search until the table is refreshed. An easy way to confirm this is once the search query parameters have been added to the URL `?table[search]=xyz`.
3. The search box will loose focus.
4. However, this time re-focus into the search box and perform another search until the table is refreshed. Again, confirming this once the search query parameters have been changed in the URL `?table[search]=abc`.
5. This time, you'll note the intended behaviour occurs. Upon each subsequent confirmed search, the search box will remain focused as (I think) should be intended.

So it appears the issue only occurs on the initial search.

### Package Version

2.12.0

### PHP Version

8.2.x

### Laravel Version

10.8.0

### Alpine Version

3.12.1

### Theme

Bootstrap 4.x

**Comment by lrljoe** [comment]
Thanks for raising, once we've ironed out any v3 bugs, I'll be coming back to do fixes on v2.

**Comment by lrljoe** [comment]
@othyn - can you just confirm which search method you're using from your configure() please?

Also - if you've published any views for this package etc?

Will help me figure out what's going on here.

**Comment by othyn** [comment]
@lrljoe yep, with pleasure.

Here is the `configure()` for the table in question:

```php
public function configure(): void
{
    $this->setPrimaryKey(key: 'id')
        ->setDefaultSort(field: 'id', direction: 'desc')
        ->setTableAttributes([
            'default' => true,
            'class' => 'table-bordered',
          ]);
}
```

And there are no views that are published, all running from Livewire Tables default 👍

**Comment by lrljoe** [comment]
Okay, so default search binding.

Are you using "when" in your builder, or just a straight forward searchable() on the relevant columns?
Do you have more than one table component on the page, if so - have you given them a distinct table name?

Are you able to share the full component, feel free to DM it to me on the official Discord if you have privacy concerns.

**Comment by othyn** [comment]
> Are you using "when" in your builder, or just a straight forward searchable() on the relevant columns?

Straight forward `searchable()` on all columns.

> Do you have more than one table component on the page, if so - have you given them a distinct table name?

Nope, just one table on the page. Naming hasn't been specified, just left as default.

> Are you able to share the full component, feel free to DM it to me on the official Discord if you have privacy concerns.

Before I share this, I'll give your suggestion a go to explicitly define a table name. If it doesn't work, I'll report back and share the component.

Thanks for all your help so far!

**Comment by othyn** [comment]
Okay so I've given it a go, still exhibits the same problem.

I can see the query string gets modified, so I know the change has taken in the table component `?testTable1[search]=test`.

The component isn't sensitive, its just surfacing a table:

```php
<?php

declare(strict_types=1);

namespace App\Http\Livewire;

use App\Models\Log;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;

class LogTable extends DataTableComponent
{
    protected $model = Log::class;

    public string $tableName = 'testTable1';
    public array $testTable1 = [];

    public function configure(): void
    {
        $this->setPrimaryKey(key: 'id')
            ->setDefaultSort(field: 'id', direction: 'desc')
            ->setTableAttributes([
                'default' => true,
                'class' => 'table-bordered',
              ]);
    }

    public function columns(): array
    {
        return [
            Column::make(title: 'ID', from: 'id')
                ->sortable()
                ->searchable(),

            Column::make(title: 'Type', from: 'type')
                ->sortable()
                ->searchable(),

            Column::make(title: 'Requested At', from: 'created_at')
                ->sortable(),
        ];
    }
}

```

**Comment by lrljoe** [comment]
Thanks, V3 Beta is out.  So I will be reviewing backports this weekend, along with v2 bugs.

Should have at least a timescale, if not a fix by this time next week

**Comment by othyn** [comment]
Super, thank you! No urgency on this as its a non-blocking UX bug, nothing impacting functionality, its more just a mild annoyance haha
