### ISSUE TITLE
[Bug]: assertViewIs is not working

### ISSUE THREAD

**Issue by jacksontong** [rappasoft/laravel-livewire-tables#1367]
### What happened?

`assertViewIs` always return `The response is not a view.` for normal Laravel route test, however it's working fine for Livewire component. If I set `inject_assets` to false then it's working again.

### How to reproduce the bug

```php
class DocumentController
{
    public function index(): View
    {
        return view('documents.index');
    }
}

it('renders correct view', function () {
    \Pest\Laravel\get(route('documents.index'))
        ->assertOk()
        ->assertViewIs('documents.index');
});
```

### Package Version

v3-develop

### PHP Version

8.2.x

### Theme

None

**Comment by lrljoe** [comment]
This should be resolved in the latest v3-develop.  I adjusted your PR somewhat, and also threw a load of new tests and amendments to behaviour in at the same time.

Please do let me know your findings!

**Comment by jacksontong** [comment]
thanks, it's fixed on my end.
