### ISSUE TITLE
[Bug]: Listener in lazy component throws error

### ISSUE THREAD

**Issue by jacksontong** [rappasoft/laravel-livewire-tables#1370]
### What happened?

I have many tables on my page, so I take the advantage of Livewire lazy loading component to defer loading them, but the table listen for an echo event so it'll refresh the table automatically. If the event was triggered before I see the table then it's gonna throw an error `Typed property Rappasoft\LaravelLivewireTables\DataTableComponent::$columns must not be accessed before initialization`

### Stack trace
https://flareapp.io/share/Rmr36EOP

### How to reproduce the bug

```php
class MembersTable extends DataTableComponent
{
    #[Locked]
    public int $accountId;

    public ?int $searchFilterThrottle = 400;

    public function getListeners()
    {
        return array_merge(parent::getListeners(), [
            "echo-private:App.Account.{$this->accountId},.".MembersImported::class => '$refresh',
            'test' => '$refresh',
        ]);
    }

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function builder(): Builder
    {
        return Member::query();
    }

    public function columns(): array
    {
        return [
            Column::make('id')
                ->searchable()
                ->sortable(),
            Column::make('First Name')
                ->searchable()
                ->sortable(),
            Column::make('Last Name')
                ->searchable()
                ->sortable(),
        ];
    }
}

// failing pest test with same error message
// if I remove lazy then it works same on the web
test('lazy component', function () {
    $account = Account::factory()->create();
    $member = Member::factory()->create();

    livewire(MembersTable::class, [
        'accountId' => $account->id,
        'lazy' => true,
    ])
        ->dispatch('test')
        ->assertOk();
});
```

### Package Version

v3-develop

### PHP Version

8.2.x

### Laravel Version

10.24

### Theme

None

**Comment by lrljoe** [comment]
Cheers, will take a look, may not be fixed in the first official beta tho!

**Comment by lrljoe** [comment]
Looks like this may be an issue with lazy components, listeners and undefined (at initialisation) variables.

Reviewing livewire core code to see if an existing issue has been raised

**Comment by lrljoe** [comment]
For now, you could check

isset($this->columns) 

and only call $refresh if that is true

**Comment by jacksontong** [comment]
is this correct? it does seem to work for me
```php
class MembersTable extends DataTableComponent
{
    public function getListeners()
    {
        return array_merge(parent::getListeners(), [
            'test' => 'refresh',
        ]);
    }

    public function refresh(): void
    {
        if (isset($this->columns)) {
            $this->dispatch('refreshDatatable')->self();
        } else {
            $this->booted();
        }
    }   
}
```

**Comment by lrljoe** [comment]
Would need to do some testing.  If it works, then I'll look at adding in some core functionality for it, possibly in Livewire core, but certainly here to start.

**Comment by paianoa** [comment]
same problem here! :(
