### ISSUE TITLE
I cant install in laravel 10 with livewire V3[Bug]: 

### ISSUE THREAD

**Issue by mesayuda** [rappasoft/laravel-livewire-tables#1372]
### What happened?

I cant install this package in a fresh laravel project with livewire v3, laravel jetstream

### How to reproduce the bug

When i import this package (composer require rappasoft/laravel-livewire-tables)

### PHP Version

None

### Theme

None

### Error Message

Using version ^2.15 for rappasoft/laravel-livewire-tables
./composer.json has been updated
Running composer update rappasoft/laravel-livewire-tables
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires rappasoft/laravel-livewire-tables ^2.15 -> satisfiable by rappasoft/laravel-livewire-tables[v2.15.0].
    - rappasoft/laravel-livewire-tables v2.15.0 requires livewire/livewire ^2.6 -> found livewire/livewire[v2.6.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require rappasoft/laravel-livewire-tables:*" to figure out if any version is installable, or "composer require rappasoft/laravel-livewire-tables:^2.1" if you know which you need.

**Comment by lrljoe** [comment]
Please see the discussion on v3.

You will need to use the dev-v3-develop branch for now, proper beta imminent.

```
composer require rappasoft/laravel-livewire-tables:dev-v3-develop
```
