### ISSUE TITLE
[Bug]: Frontend assets load time problem

### ISSUE THREAD

**Issue by danie-ramdhani** [rappasoft/laravel-livewire-tables#1375]
### What happened?

Here's screenshot of my network request when i do hard reload browser or when the `cache_assets` is `false`:

![Capture](https://github.com/rappasoft/laravel-livewire-tables/assets/58886605/7fb5e4fd-feb8-4b9a-9680-d8591c5f72d7)

I believe it doesn't make sense to load `core.min.js` for one second (and 4s to load whole laravel-livewire-tables frontend assets) meanwhile `livewire.js` only takes 800ms (fo thousands loc)

Even the assets is injected when the component doesn't using laravel-livewire-tables

Thanks for your time.

### Package Version

dev-v3-develop

### PHP Version

8.2.x

### Laravel Version

10

### Alpine Version

3.13

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Leave it with me, its still alpha/beta, so the code is constantly being amended.
Do you see any difference on a subsequent refresh with browser caching?

**Comment by lrljoe** [comment]
Also have a test running at the mo where it wont inject the assets without a table component being present, just tinkering at the mo, so no real timeline other than soon.

Bundler is definitely an easier way

**Comment by lrljoe** [comment]
With cache_ assets set to false, it will always tell the browser that the file has expired.
It is more of a dev toggle than anything else

With it enabled, it'll cache the rappasoft assets for one hour (will be adjusted to match browser in next revisions)

**Comment by lrljoe** [comment]
@danie-ramdhani  -  In theory - yes, an approach like that will work.  In practice, sometimes what happens is the table loads before the assets make available their methods to Alpine, and then things go... missing?

If you have 15 minutes, I'm on the [Official Discord](https://discord.gg/txaRx6EydH) at the moment, and there's a couple of alternatives that you can use (e.g. bundled elements) that will probably be much quicker for you.

**Comment by lrljoe** [comment]
This should be fixed in the [v3.0.0-beta.1](https://github.com/rappasoft/laravel-livewire-tables/releases/tag/v3.0.0-beta.1) Pre-release.

Please re-open if not!
