### ISSUE TITLE
[Bug]: Checking on the header bulk select checkbox seems to crash the table

### ISSUE THREAD

**Issue by rpringadi** [rappasoft/laravel-livewire-tables#1379]
### What happened?

When I select the header bulk select it immediately crash.

<img width="1322" alt="Screenshot 2023-10-03 at 3 13 30 PM" src="https://github.com/rappasoft/laravel-livewire-tables/assets/2053877/2592b129-84d6-4e44-80e4-1bb030ff3827">

<img width="1321" alt="Screenshot 2023-10-03 at 3 14 03 PM" src="https://github.com/rappasoft/laravel-livewire-tables/assets/2053877/52b91a4f-698d-4dbe-a1f8-d1c5678ed877">

### How to reproduce the bug

Click on the top bulk select, the table immediately crashed.

### Package Version

dev-v3-develop

### PHP Version

8.2.x

### Laravel Version

10.26.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Just checking - if upgrading from v2 to v3, that you have deleted any published views for laravel-livewire-tables?

**Comment by rpringadi** [comment]
It was a clean V3.

As requested the configure looks like this:

```php
   public function configure(): void
    {
        $this->setPrimaryKey('id')
            ->setAdditionalSelects(['users.id as id']);
        $this->setEmptyMessage(__('users.No results found'));

        $this->setComponentWrapperAttributes([
            'class' => 'users-table-component',
        ]);

        $this->setTableWrapperAttributes([
            'class' => 'users-table',
        ]);
        $this->setSearchLive();
    }

    public function builder(): Builder
    {

        return User::query()->with($this->getRelationships())
            ->leftJoin('departments', 'departments.id', '=', 'users.department_id')
            ->leftJoin('positions', 'positions.id', '=', 'users.position_id')
            ->select(
                'users.firstname as firstname',
                'users.lastname as lastname',
                'users.email as email',
                'departments.name',
                'positions.name',
                'users.last_login_at as last_login_at'
            );
    }
    
    
```

**Comment by lrljoe** [comment]
Confirmed that removing select() from builder works.  This is not required with this package :)
