### ISSUE TITLE
[Bug]: Search doesn't auto reload

### ISSUE THREAD

**Issue by rpringadi** [rappasoft/laravel-livewire-tables#1380]
### What happened?

The search doesn't seem to self / auto reload. 
I do noticed that the page url is immediately changed to include my search keyword.
But no page / data refresh.

I can go to the browser address bar, at the very end of the line hit Enter/Return, to force the page reload.
Only then the data seems to be refreshed. The search seems to work fine but no auto reload after the last letter that I typed.

<img width="1328" alt="Screenshot 2023-10-03 at 3 20 58 PM" src="https://github.com/rappasoft/laravel-livewire-tables/assets/2053877/786dac45-35f3-4570-b30f-f720bd9b6239">

### How to reproduce the bug

In the table listing page put a search keyword.
The page url is immediately changed to include my search keyword.
But no page / data refresh.

I can go to the browser address bar, at the very end of the line hit Enter/Return, to force the page reload.
Only then the data seems to be refreshed. The search seems to work fine but no reload.

### Package Version

dev-v3-develop

### PHP Version

8.2.x

### Laravel Version

10.26.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Confirmed that using setSearchLive() fixes this.
