### ISSUE TITLE
[Bug]: Extra @endphp in DateRangeFilter blade

### ISSUE THREAD

**Issue by Traqza** [rappasoft/laravel-livewire-tables#1392]
### What happened?

When using this filter I get a @endphp tag, and out of scope view for the filter menu.

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/17535556/29d07634-c0ec-4c4f-8144-cf745cd00c40)

I can tab through and locate them, but the icon overtakes.

### How to reproduce the bug

 DateRangeFilter::make('Date Range')
                ->config([
                    'allowInput' => true,   // Allow manual input of dates
                    'altFormat' => 'Y/m/d', // Date format that will be displayed once selected
                    'ariaDateFormat' => 'Y/m/d', // An aria-friendly date format
                    'dateFormat' => 'Y/m/d', // Date format that will be received by the filter
                    'earliestDate' => '2020/01/01', // The earliest acceptable date
                    'latestDate' => Carbon::now()->format('Y/m/d'), // The latest acceptable date
                ])
                ->setFilterPillValues([0 => 'minDate', 1 => 'maxDate']) // The values that will be displayed for the Min/Max Date Values
                ->filter(function (Builder $builder, array $dateRange) { // Expects an array.
                    $builder
                        ->whereDate('start_timestamp', '>=', $dateRange['minDate']) // minDate is the start date selected
                        ->whereDate('end_timestamp', '<=', $dateRange['maxDate']); // maxDate is the end date selected
                }),

### Package Version

v3.0.0-beta.1

### PHP Version

None

### Laravel Version

10.12.0

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
Thanks. Not sure how this one worked its way back in as did address it before.

If you have previously published the views, then suggest that you delete the published views.

If it is still persisting, then will fix this evening.

**Comment by lrljoe** [comment]
#1394 should fix this, will be in v3-develop shortly, tested briefly, then moved across and hopefully into a v3.0.0-beta.2 tomorrow.

**Comment by bahriid** [comment]
[#1394](https://github.com/rappasoft/laravel-livewire-tables/pull/1394) I tried the solution in this pull request on my published view, the @endphp is missing, but it still has bugs:

1. The hero icon is still large.
2. When clicking the date range input, the filter list is closed

here is the screenshot : 
![CleanShot 2023-10-07 at 04 05 38@2x](https://github.com/rappasoft/laravel-livewire-tables/assets/33280718/1b39563e-560a-4069-91a1-a6eb0c4af4fb)

![CleanShot 2023-10-07 at 04 09 02@2x](https://github.com/rappasoft/laravel-livewire-tables/assets/33280718/04c01c27-ce40-42cf-b3c5-b9ee5e0666d9)

**Comment by lrljoe** [comment]
Will give it another test in bootstrap 5, can you confirm the exact bootstrap 5 version you are using please so that I can match precisely

**Comment by lrljoe** [comment]
This is in beta 3 I believe!
