### ISSUE TITLE
[Feature Request]: show loader when some action has been done

### ISSUE THREAD

**Issue by amshehzad** [rappasoft/laravel-livewire-tables#1417]
### Overview

we should be able to configure a "loader" and then we can enable it, then on every request we can show the loader. that is something I must use in my projects
otherwise for any action, the user doesn't know that something is happening

**Comment by lrljoe** [comment]
Been looking at this, should have this into core in next day or so

**Comment by lrljoe** [comment]
This is in v3-develop, needs a final once over before it can go into master then release.

**Comment by lrljoe** [comment]
Now in beta4
