### ISSUE TITLE
[Feature Request]: Add checkbox fitler

### ISSUE THREAD

**Issue by amshehzad** [rappasoft/laravel-livewire-tables#1419]
### Overview

It would be nice to have a checkbox filter

**Comment by lrljoe** [comment]
So this exists as MultiSelectFilter

There's a work in progress for a Boolean/Toggle Filter

**Comment by lrljoe** [comment]
So a single CheckBox is available via MultiSelectFilter

A Toggle icon, e.g:
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/104938042/15e09698-50eb-4bd1-9ac3-e8abc8e9cf23)

Is a different request, but is in progress
