### ISSUE TITLE
[Bug]: Composer installation fails on package requirements/Livewire3

### ISSUE THREAD

**Issue by realmarkcross** [rappasoft/laravel-livewire-tables#1422]
### What happened?

When attempting to install the package into a fresh installation of Laravel with Livewire 3 (TALL stack) via:
`composer require rappasoft/laravel-livewire-tables` I receive an error that the package isn't installable due to requirements for Livewire 2.

### How to reproduce the bug

Run the composer require command on a new Laravel 10/Livewire3/TALL stack installation.

### Package Version

2.15

### PHP Version

8.2.x

### Laravel Version

10.10

### Alpine Version

3.13.1

### Theme

Tailwind 3.x

### Error Message

Your root composer.json require (^3.0).
    - rappasoft/laravel-livewire-tables[v1.19.2, ..., v1.25.1, v2.0.0, ..., v2.15.0] require livewire/livewire ^2.6 -> found livewire/livewire[v2.6.0, ..., v2.12.6] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires rappasoft/laravel-livewire-tables * -> satisfiable by rappasoft/laravel-livewire-tables[v0.1.0, ..., v0.4.0, v1.0.0, ..., v1.25.1, v
2.0.0, ..., v2.15.0].

**Comment by lrljoe** [comment]
You need to use v3 of the rappasoft package too.
