### ISSUE TITLE
[Bug]: Footer Oddities

### ISSUE THREAD

**Issue by lrljoe** [rappasoft/laravel-livewire-tables#1427]
### What happened?

Under certain conditions, the footer loses a column.

### Package Version

3.0.0-beta4

### PHP Version

8.2.x

### Laravel Version

10.0.0

### Alpine Version

3.1.12

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Testing of fix underway logged for tracking purposes only

**Comment by bonge-ian** [comment]
Hello @lrljoe.


It seems that this issue is still persistent on version 3.1

![Web capture_25-11-2023_82529_lv3 test](https://github.com/rappasoft/laravel-livewire-tables/assets/35810849/be10dce1-31fe-4619-ad7c-7a01b47ffbb9)


The column configuration for the above datatable.

```php
public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable()
                ->footer(fn () => "Total"),
            Column::make("Name", "name")
                ->sortable(),
            Column::make("Email", "email")
                ->sortable(),
            Column::make("Created at", "created_at")
                ->sortable(),
            Column::make("Updated at", "updated_at")
                ->sortable()
                ->footer(fn ($rows) => $rows->count()),
        ];
    }
```

Using `secondaryHeader` and `$this->setUseHeaderAsFooterEnabled()` configuration, seems to align the columns as compared with the earlier configuration.

![Web capture_25-11-2023_83945_lv3 test](https://github.com/rappasoft/laravel-livewire-tables/assets/35810849/804121ee-7b61-446c-808b-fe29d24ebda8)

**Comment by lrljoe** [comment]
I'll take a look this weekend, can you share your configure() too so that I can replicate fully please

**Comment by bonge-ian** [comment]
I used the default example from the docs, using the Laravel's user model.

```php
<?php

namespace App\Livewire;

use App\Models\User;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\DataTableComponent;

class UserTable extends DataTableComponent
{
    protected $model = User::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable()
                ->footer(fn () => "Total"),
            Column::make("Name", "name")
                ->sortable(),
            Column::make("Email", "email")
                ->sortable(),
            Column::make("Created at", "created_at")
                ->sortable(),
            Column::make("Updated at", "updated_at")
                ->sortable()
                ->footer(fn ($rows) => $rows->count()),
        ];
    }
}
```

The above configuration is the one that causes the column mismatch.

If you define a `secondaryHeader`, in the columns(id and updated_at), with the same callback as the footer and then enable `$this->setUseHeaderAsFooterEnabled();` configuration in the `configure` method, the columns align perfect.

For now I have ended up enabling `$this->setUseHeaderAsFooterEnabled();`  and `$this->setSecondaryHeaderDisabled();` in the configure method and added `secondaryHeader` configuration in the columns as a stop gap.

**Comment by lrljoe** [comment]
Thanks for the detailed example, I'll fix this weekend

**Comment by lrljoe** [comment]
Self-note, relates to bulk actions column, need to double check what's going on there.

**Comment by lrljoe** [comment]
Just doing some testing, but should make it into the next release @bonge-ian

**Comment by lrljoe** [comment]
In most recent release I believe!

**Comment by bonge-ian** [comment]
The bug has been fixed in the latest release.
I've just tested it.

Thank you @lrljoe for the fix.
