### ISSUE TITLE
[Bug]: setQueryStringDisabled is not working

### ISSUE THREAD

**Issue by jacksontong** [rappasoft/laravel-livewire-tables#1428]
### What happened?

I have called `setQueryStringDisabled` on the `configure` method but it has no effect.
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/7871218/c7f533fa-e31f-489c-adeb-f70ac3b328ea)

If I set `$queryStringStatus = false;` then it works.

### How to reproduce the bug

```php
public function configure(): void
{
    $this->setPrimaryKey('id');
    $this->setQueryStringDisabled();
}
```

### Package Version

dev-v3-develop

### PHP Version

None

### Laravel Version

10

### Theme

None

**Comment by lrljoe** [comment]
Thanks for raising, I'll look into this shortly :)

**Comment by lrljoe** [comment]
Plan for this is to:

1. Migrate current queryString into the appropriate traits
2. Fix the global disable/enable
3. Enable simple enable/disable on a per-trait basis (i.e. enable/disable queryString for search/filter/columnselect/sort)

Expect this fix by early November

**Comment by lrljoe** [comment]
Tasks 1 & 2 for this are done, and I'm just doing some final tests on it, expect it this weekend, ahead of an initial stable release.

Task 3 - I've raised a Feature Request for rather than a bug, as it's "new functionality" to enable/disable them individually

**Comment by lrljoe** [comment]
Task 1 &2 are in beta 10.

Task 3 is captured separately.

Please advise if anything is **not** working relation to this
