### ISSUE TITLE
[Bug]: Can't add new columns after using filters

### ISSUE THREAD

**Issue by jclee100** [rappasoft/laravel-livewire-tables#1433]
### What happened?

Tried adding new columns but columns refuse to appear.

### How to reproduce the bug

Apply filters then add new column in  relevant table class. Columns will not appear.

### Package Version

v3.0.0-beta.4

### PHP Version

8.2.x

### Laravel Version

10.27.0

### Alpine Version

(Whatever is bundled with  livewire v3.0.1)

### Theme

Tailwind 3.x

### Notes

Columns appears after deleting cookies. So I am guessing that using filters caches the columns into the cookies. Any addition to columns does not appear unless cookies are cleared.

### Error Message

N/A

**Comment by lrljoe** [comment]
Please update to the latest Livewire version, as there are bugs in Livewire 3.0.1 that may be impacting this!

**Comment by lrljoe** [comment]
Please update to both beta 10 and latest livewire, this issue is fixed.
