### ISSUE TITLE
[Bug]: setFilter() has no effect

### ISSUE THREAD

**Issue by nathan-io** [rappasoft/laravel-livewire-tables#1440]
### What happened?

We're passing an array `$filters` to the component from our view, then setting those filters like so:

```
    public function mount($filters = [])
    {
        foreach ($filters as $key => $value) {
            $this->setFilter($key, $value);
        }
    }
```

This works in v2, but in v3-beta4 the filters aren't applied when the table is loaded.

We can apply them manually via the filter UI, that works fine.

### Package Version

3.0.0-beta4

### PHP Version

8.1.x

### Laravel Version

10.x

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Thanks for raising the bug.

Just as a test, could you please try the following:

```
    public function mount($filters = [])
    {
        foreach ($filters as $key => $value) {
          $this->appliedFilters[$key ] = $this->filterComponents[$key ] = $value;
        }
    }
```

**Comment by nathan-io** [comment]
Thanks for the fast response! That fixes it.

**Comment by lrljoe** [comment]
Great, I'll update the setFilter() method to update both to save you having to update a ton of tables.

Expect that to be in beta.8 (tomorrow)

**Comment by lrljoe** [comment]
#1449 1449 <- for reference

**Comment by lrljoe** [comment]
Fix should be in v3.0.0-beta.8, please re-open and let me know if something is broken!

**Comment by nathan-io** [comment]
Getting the same result with beta8.

**Comment by nathan-io** [comment]
I got beta9 installed and that fixes it, sorry for any confusion. Everything is working perfectly using

```
$this->setFilter($key, $value);
```
