### ISSUE TITLE
[Bug]:  Not working with Livewire v3

### ISSUE THREAD

**Issue by Ola-Yusuf** [rappasoft/laravel-livewire-tables#1460]
### What happened?

the package installation failed on livewire 3

### How to reproduce the bug

when I do composer require ...package name...,

I see an error message requires livewire 2.x.x

### PHP Version

8.1.x

### Laravel Version

10

### Alpine Version

3

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
Version 3 of this package is in beta, which supports Livewire v3.

https://github.com/rappasoft/laravel-livewire-tables/discussions/1305

A 3.1.0 stable release is anticipated this weekend.
