### ISSUE TITLE
[Bug]:Search field no work 

### ISSUE THREAD

**Issue by mesayuda** [rappasoft/laravel-livewire-tables#1468]
### What happened?

I cant search in search field when i press enter, the table freeze and no load any data, the data only loads when i click in paginate links

### How to reproduce the bug

In search field, i write any content that exist in table, the table freeze and no load data, only load data when i press in paginate links.

### Package Version

3.0.0 beta 9

### PHP Version

8.2.x

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
What have you set for your search method in configure()

**Comment by lrljoe** [comment]
Please respond to re-open this issue if the problem persists after reviewing the above.
