### ISSUE TITLE
[Bug]: Using when() in builder() for getAppliedFilterWithValue() can be a lifecycle behind

### ISSUE THREAD

**Issue by lrljoe** [rappasoft/laravel-livewire-tables#1491]
### What happened?

Using a getAppliedFilterWithValue can be a lifecycle behind, and thus you don't see the filter applied until the following lifecycle:
```
public function builder(): Builder
{
    return User::query()
         ->when($this->getAppliedFilterWithValue('active'), fn($query, $active) => $query->where('active', $active === 'yes'));
}
```

This is likely due to the sequence that everything is being applied.

### Package Version

3.0.0

### PHP Version

8.2.x

### Laravel Version

10.x

### Alpine Version

3.13.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Just testing the fix

**Comment by lrljoe** [comment]
This will be in the release **after** the next one, as I've already shoved a ton into the next release.

**Comment by RenoLooijmans** [comment]
> I have fixed this by overriding the render method in the child class of the livewire component.
> 
> ```
> /**
>  *
>  * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Contracts\Foundation\Application
>  */
> public function render(): \Illuminate\Contracts\View\Factory | \Illuminate\Contracts\View\View | \Illuminate\Contracts\Foundation\Application
> {
>     //Sets up the Builder Instance
>     $this->setBuilder($this->builder());
>     return parent::render();
> }
> ```

Interesting! I might apply that as well in the meanwhile. Thanks for sharing.

**Comment by siebsie23** [comment]
@lrljoe I'm still having this issue in v3 when using `when(! $this->getSort('created_at')` and `when(empty($this->getSearch())`

The manual fix in this issue https://github.com/rappasoft/laravel-livewire-tables/issues/1491#issuecomment-1831332636 fixes the problem for me. Was the fix you made already implemented in the code, or is it broken again by later updates?
