### ISSUE TITLE
[Bug]:  Search param is broken after V3 upgrade

### ISSUE THREAD

**Issue by xrezut** [rappasoft/laravel-livewire-tables#1516]
### What happened?

So after upgrading to V3 of this package, the search no longer works.

One thing I noticed which broke my tests also is the search param for the query is now renamed to `table-search`. Previously it was `search`.

Before: http://localhost/admin/accounts?search=test
Now: http://localhost/admin/accounts?table-search=test

However, even when updating the query param to the old one from v2 the table data still does not show the correct results. Has something changed in this version ?

The theme i am using is bootstrap-4, and I have not published any views so it should be using those from the package.

My code is as follows:

```
class AdminTable extends DataTableComponent
{
    protected $model = User::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setAdditionalSelects('id');
    }

    public function builder(): Builder
    {
        return User::query()->admins();
    }

    public function columns(): array
    {
        return [
            Column::make('Name')
                ->searchable()
                ->sortable(),
            Column::make('Email')
                ->searchable()
                ->sortable(),
        ];
    }
}

```

### How to reproduce the bug

Search the table using the search input field. See the search query param is now "table-search", and the records are not filtered.

### Package Version

3.1.0

### PHP Version

8.1.x

### Laravel Version

10.30.0

### Theme

Bootstrap 4.x

**Comment by lrljoe** [comment]
In your configure() add
```
$this->setSearchLive();
```

Does this fix the issue?

**Comment by xrezut** [comment]
@lrljoe Thanks a lot for the quick reply, yes that fixes the issue i was facing. I didn't see this mentioned anywhere or in the examples on V3. 

For now i could add this to all my tables, however is there another approach for this or is this a known issue that will be fixed in a later version?

**Comment by lrljoe** [comment]
Having reviewed the v2 behaviour (defaults to live), I'll update v3 to use Live as default.

It's in the development branch now, so should go into master and then into the next release (sometime this week)

**Comment by xrezut** [comment]
Awesome work. Thanks! 💙

**Comment by dmyers** [comment]
@lrljoe Could it be possible to make more of the entangled values `live`? Like `selectedItems` for example which can be useful for disabling/enabling the select all checkbox if `selectedItems.length > 0`, but without live I can't seem to get it to work until after the next render or something.

**Comment by lrljoe** [comment]
Hmmm, yep, that's certainly possible, can you open up a separate discussion thread for it, or a feature request issue.

More of them were live originally, but it causes an extra update call on first load which was painful for more complex tables, and that was the easiest fix.

**Comment by tjhunkin-inhance** [comment]
This still doesn't seem to work on the latest version v3.1.5
