### ISSUE TITLE
[Bug]: Sorting deep relations

### ISSUE THREAD

**Issue by levizoesch** [rappasoft/laravel-livewire-tables#1546]
### What happened?

If you sort a column that is a deep relation, the url param will be [filter][value] where as it should be [filter.value].

### How to reproduce the bug
Column::make('Bank','bank.alias')
    ->searchable()
    ->sortable()
    ->collapseOnMobile(),

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/18410490/cdb0a4ab-3359-4927-976c-d454fec396b1)
vs
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/18410490/9c979e0b-3faf-45ac-b89f-48d7e3a41c6c)

### Package Version

3.x

### PHP Version

8.1.x

### Laravel Version

10.x

### Error Message
Rappasoft\LaravelLivewireTables\Views\Column::getSortingPillDirection(): Argument https://github.com/rappasoft/laravel-livewire-tables/issues/2 ($direction) must be of type string, array given, called in /home/.../storage/framework/views/b496047e5597363e8385316850f702ff.php on line 134 (View: /home/.../vendor/rappasoft/laravel-livewire-tables/resources/views/components/tools/sorting-pills.blade.php)

**Comment by lrljoe** [comment]
Possible fix, needs further testing

**Comment by yogiri** [comment]
We're facing the same issue. Was there a fix to it?

**Comment by levizoesch** [comment]
> We're facing the same issue. Was there a fix to it?
> 
> EDIT: This happens only when using a filter AFTER applying a sort. If the filter is applied before the sorting, then it doesn't break.

Yes this bug has been resolved in later versions of both Livewire, and Livewire Tables.

This bug was a issue particularly with Livewire changes early on in 3.0, and how Livewire Tables was handling things.
