### ISSUE TITLE
[Bug]: Could not check compatibility between App\Livewire\ClientTable::builder(): App\Livewire\Builder and Rappasoft\LaravelLivewireTables\DataTableComponent::builder(): Illuminate\Database\Eloquent\Builder, because class App\Livewire\Builder is not available

### ISSUE THREAD

**Issue by Abdox3** [rappasoft/laravel-livewire-tables#1551]
### What happened?

Can't use builder function

### Package Version

"rappasoft/laravel-livewire-tables": "^3.1",

### PHP Version

8.2.x

### Laravel Version

10.x

### Alpine Version

3.13.2

### Theme

Tailwind 3.x

### Error Message

[Bug]: Could not check compatibility between App\Livewire\ClientTable::builder(): App\Livewire\Builder and Rappasoft\LaravelLivewireTables\DataTableComponent::builder(): Illuminate\Database\Eloquent\Builder, because class App\Livewire\Builder is not available

**Comment by lrljoe** [comment]
Not a bug.  Please ensure to include the builder reference in the head of your component
