### ISSUE TITLE
[Bug]: Variables $filterLayout $tableName $isTailwind $isBootstrap4 $isBootstrap5 $isBootstrap are undefined

### ISSUE THREAD

**Issue by GithubEficienciaTributaria** [rappasoft/laravel-livewire-tables#1552]
### What happened?

When you use a SelectFilter in a table, the variables $filterLayout $tableName $isTailwind $isBootstrap4 $isBootstrap5 $isBootstrap are undefined inside the view, triggering an error.

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/133399447/93c025c3-2fe0-4d7a-ba06-52abe222c809)

### How to reproduce the bug

Create a table
Create a filters method
Create a SelectFilter object inside the returning array.

### Package Version

3.1.12

### PHP Version

8.2.x

### Laravel Version

10.31.0

### Alpine Version

3.13

### Theme

Bootstrap 5.x

### Notes

I tried checking each variable with a dd inside the blade and only the filter variable is not undefined.

**Comment by lrljoe** [comment]
If you have previously published the views, then remove your published copies.
