### ISSUE TITLE
[Feature Request]: Visual customizations of the Bulk Actions Dropdown

### ISSUE THREAD

**Issue by zokistale** [rappasoft/laravel-livewire-tables#1566]
### Overview

Add ability to the Bulk Actions Dropdown to:
1. Set the label as HTML instead of just plain text (e.g. it will allow us to add icons).
2. Define a horizontal divider between actions.

### Detailed explanation

We have large bulk actions drop-downs with e.g. 9 actions. We'd like to visually enhance them by grouping them using a divider and by adding SVG icons. For example, in the screenshot below, we'd like to be able to put dividers between each 3 actions.

Thank you for your great work, by the way.

### Notes

![bulk-actions-dropdown](https://github.com/rappasoft/laravel-livewire-tables/assets/1614867/b6adb634-ea65-4d93-a00e-d2fba08c1f98)

**Comment by lrljoe** [comment]
Replacing the current dropdowns with more modern editions is currently on the roadmap happily.
The recent version added in an ability for a confirmation modal, and the plan will be to add in more customisations, allowing for use of HTML strings in the display name for the bulk action.

Just having to be conscious of adding new capabilities without impacting existing, so it'll involve some new methods to achieve this.

Then v4 will be when the approach gets overhauled completely

**Comment by zokistale** [comment]
Icons and horizontal dividers is still something we'd like to be able to use. Thank you.

**Comment by lrljoe** [comment]
This will be coming, most likely in February, as I'm planning to replace the current classic select drop downs with smarter AlpineJS/Tailwind popovers instead.
