### ISSUE TITLE
[Feature Request]: Any plans to upgrade to Livewire 3?

### ISSUE THREAD

**Issue by javis** [rappasoft/laravel-livewire-tables#1581]
### Overview

I would like to upgrade to Livewire 3, but this package is holding me back. 

Are you planning to upgrade it to Livewire 3? Or should I think on replacing it with a custom component?

Thanks!

**Comment by lrljoe** [comment]
Version 3 of this package supports Livewire 3.

**Comment by isaackearl** [comment]
> Version 3 of this package supports Livewire 3. You will need to remove previously published views for this page (as they've all changed)

I noticed there isn't an upgrade guide of any kind.  Is there a plan for that? (even if it just says to delete previously published views?). I've been waiting to upgrade because I tried once and couldn't get things working.
