### ISSUE TITLE
[Bug]: Auto injection is triggered on non-Livewire pages

### ISSUE THREAD

**Issue by dmyers** [rappasoft/laravel-livewire-tables#1587]
### What happened?

I noticed that the core and 3rd party assets are loaded on every page, regardless if there is a table on the page or not.

Is it possible that I could either manually load these in a parent view I have or, make it so that they only are loaded on pages that have the Livewire table loaded somehow?

Or maybe with a directive? Like `@livewireTables`.
Or could this be in the Livewire views with a `@once` or something?

### Package Version

3.1.4

### PHP Version

8.2.x

### Laravel Version

10

### Alpine Version

3

### Theme

Tailwind 3.x

**Comment by dmyers** [comment]
I just discovered that there are directives already. Very awesome. They just don't seem to be listed anywhere in the docs that I could find here: https://rappasoft.com/docs/laravel-livewire-tables/v3/start/including-assets

Here they are if anyone else needs them. @lrljoe I will close this, but let me know if you want help with the docs.

```blade
    @rappasoftTableStyles
    @rappasoftTableThirdPartyStyles
    @rappasoftTableScripts
    @rappasoftTableThirdPartyScripts
```

**Comment by lrljoe** [comment]
Will make sure to update the docs for next release!
