### ISSUE TITLE
[Bug]: DateRangeFilter does not permit a single date

### ISSUE THREAD

**Issue by lrljoe** [rappasoft/laravel-livewire-tables#1595]
### What happened?

Cannot select a **single** date when using DateRangeFilter

### Package Version

3.x

### PHP Version

8.3.x

### Laravel Version

10.x

### Theme

None

**Comment by lrljoe** [comment]
Fix in progress, almost ready to deploy, it's an issue with how we're parsing the returned values

**Comment by ahmetsabri** [comment]
is there any progress ?

**Comment by NikolaiL** [comment]
Any progress?

**Comment by lrljoe** [comment]
Happily - yes!

I'm doing some more testing on the solution prior to releasing it, expect it by the end of the week.

**Comment by lrljoe** [comment]
This should be in the next release - currently undergoing testing.

**Comment by lrljoe** [comment]
This should be in v3.4.10 :)  Please reply if it's not working!
