### ISSUE TITLE
[Bug]: setSearchDebounce(1000) has no effect

### ISSUE THREAD

**Issue by saleemepoch** [rappasoft/laravel-livewire-tables#1605]
### What happened?

I have the table configured as follows:
`public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setPerPage(25);
        $this->setSearchDisabled();
        $this->setSearchDebounce(1000);
        $this->setDebugEnabled();
    }`
I have the columns configured as follows:
`
Column::make("Firstnames")
                ->secondaryHeader($this->getFilterByKey('firstnames'))
                ->sortable()
                ->searchable(),
`
However, the search is not triggered until my mouse goes out of focus.

### How to reproduce the bug

The search is not triggered upon very keystroke, only when I click outside the search box.

### Package Version

3.1.5

### PHP Version

8.2.x

### Laravel Version

10.38

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Are you referring to the secondary header, or the independent search box?

**Comment by saleemepoch** [comment]
The secondary header

**Comment by lrljoe** [comment]
Thanks for the information, can you share the code relating to the Column in question please

**Comment by saleemepoch** [comment]
The issue affects all columns, and what I have is pretty standard:

`
public function columns(): array
    {
        return [
            Column::make("ID", "id")
                ->sortable()
                ->deselected(),
            Column::make("Firstnames")
                ->secondaryHeader($this->getFilterByKey('firstnames'))
                ->sortable()
                ->searchable(),
            Column::make("Lastname")
                ->secondaryHeader($this->getFilterByKey('lastname'))
                ->sortable()
                ->searchable(),
            Column::make("Email")
                ->secondaryHeader($this->getFilterByKey('email'))
                ->sortable(),
....
`

This is my configuration:

`
    public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setPerPage(25);
        $this->setSearchDisabled();
        $this->setSearchDebounce(1000);
    }
`

**Comment by lrljoe** [comment]
If you remove setSearchDisabled()

Type something into the search box, and wait 1 second before doing anything else

Does it then update?
