### ISSUE TITLE
[Bug]: can not  use cutom  toolbar.blade.php

### ISSUE THREAD

**Issue by mrqaidi** [rappasoft/laravel-livewire-tables#1607]
### What happened?

custom toolbar.blade.php not applied  all i am trying to do is change this line
https://github.com/rappasoft/laravel-livewire-tables/blob/2bfe6df78d0e9d286b31176131a95b2041ba36cb/resources/views/components/tools/toolbar.blade.php#L46

![screenshot](https://github.com/rappasoft/laravel-livewire-tables/assets/9336767/0faa1898-12d1-4572-a0ff-756d9c090f2f)

### How to reproduce the bug

use custom toolbar.blade.php in resources/views/vendor/rappasoft/livewire-tables/components/tools/toolbar.blade.php

### Package Version

3.1.5

### PHP Version

8.2.x

### Laravel Version

10

### Alpine Version

3.4.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
When you say it's not applied, once you update that file, did you clear out your view cache?

What did you try editing it from/to?
Did you run your bundler/build to ensure any new classes are picked by up Tailwind?

**Comment by CThomas87** [comment]
I'm having the same issue; the package doesn't seem to respect published views.

I published the views and edited line 9 in toolbar.blade.php (resources\views\vendor\rappasoft\livewire-tables\components\tools\toolbar.blade.php):
` 'd-md-flex justify-content-between mx-3 my-3' => $component->isBootstrap(),`

**Ran**
php artisan view:clear
php artisan cache:clear

The views aren't updated and the div still has the class list:
`'d-md-flex justify-content-between mb-3'`

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/801969/8033d5cf-88f9-42e6-aa21-f31e75cfa941)

**Comment by lrljoe** [comment]
Right, issue with the publish path, if you symlink/copy the folder from "views/vendor/rappasoft/livewire-tables" to "views/vendor/livewire-tables" then this will fix the issue for now!

**Comment by lrljoe** [comment]
The fix that corrects the path that is published to is now in 3.1.7  - just released.

I do recommend that you avoid publishing the views wherever possible, as this can often lead to breaking changes.

If you **do** need to publish the views, then remove any non-modified views from your published copy.

If you find yourself needing to modify just some classes on a view, then please do raise a feature request, as we are trying to cover more of the areas that may need customising as we go.  There are also some upcoming changes allowing you to more smoothly swap out specific blades.
