### ISSUE TITLE
[Bug]: Cannot load css/js assets under a non-root URI

### ISSUE THREAD

**Issue by warkingous** [rappasoft/laravel-livewire-tables#1608]
### What happened?

       Hello, 
       
       locally everything works fine - Windows 11, xampp, app url: http://127.0.0.1:9000
       
       but in production - ubuntu 23.10, apache2, app url: https://domain.com/test
       
       Im having errors about loading these assets:
        
       GET https://domain.com/rappasoft/laravel-livewire-tables/core.min.css net::ERR_ABORTED 404 (Not Found)       
       GET https://domain.com/rappasoft/laravel-livewire-tables/thirdparty.css net::ERR_ABORTED 404 (Not Found)        
       GET https://domain.com/rappasoft/laravel-livewire-tables/core.min.js net::ERR_ABORTED 404 (Not Found)        
       GET https://domain.com/rappasoft/laravel-livewire-tables/thirdparty.min.js net::ERR_ABORTED 404 (Not Found)
       
       Everything else works fine - Livewire works fine, no errors, it just completely ignores the fact that the app_url is 
       https://domain.com/test, it tries to load these assets from https://domain.com/ instead https://domain.com/test

### Package Version

3.1

### PHP Version

8.2.x

### Laravel Version

10

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Easiest and best way is to bundle the code rather than rely on the injection approach
