### ISSUE TITLE
[Bug]: Loading placeholder not working

### ISSUE THREAD

**Issue by StuBlackett2022** [rappasoft/laravel-livewire-tables#1625]
### What happened?

Hello,

I've added 

`$this->setLoadingPlaceholderBlade('livewire/loaders/table-loader');` 

To my table, which loads the following HTML

```
<div class="bg-white text-center p-5">
    <i class="fa fa-tire fa-2xl fa-spin"></i>
</div>
```

The loader shows in the table (In the wrong place) and also doesn't dissapear once the table has been rendered.

![Screenshot 2024-01-02 at 14 58 45](https://github.com/rappasoft/laravel-livewire-tables/assets/108682692/f1ba90ce-6842-4c71-bfdb-eff282341889)

I've followed the docs and tried various things, but no luck

### How to reproduce the bug

Add a loader as per the docs : https://rappasoft.com/docs/laravel-livewire-tables/v3/datatable/loaders#content-loading-placeholder

`$this->setLoadingPlaceholderBlade('livewire/loaders/table-loader');`

### Package Version

3.1.8

### PHP Version

8.3.x

### Laravel Version

10.38.1

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
Thanks for the bug report, I've managed to replicate the issue, and fix it in my local environment.

I'm trying to make a habit of not posting interim fixes on here, but if you reach out on the official Discord then I'm happy to give you an interim solution if you've got a production issue.

However, the fix will be in the next release!
