### ISSUE TITLE
[Bug]: publishing assets not working

### ISSUE THREAD

**Issue by tjhunkin-inhance** [rappasoft/laravel-livewire-tables#1638]
### What happened?

published resources\views\vendor\rappasoft\livewire-tables\components\tools\toolbar\items\pagination-dropdown.blade.php and changed 

```
'select select-bordered w-full max-w-xs' => $component->isTailwind(),
```

It does not take effect, even if clearing cache etc. 

Editing the file in the package works.

What am I doing wrong?

### Package Version

3.1.5

### PHP Version

8.2.x

### Laravel Version

10.37.2

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
There was a bug with the publish paths, on the latest version (3.2.x) the path is corrected.

Path should be:
resources\views\vendor\livewire-tables
