### ISSUE TITLE
[Bug]: Uncaught ReferenceError: currentlyReorderingStatus is not defined

### ISSUE THREAD

**Issue by winkcler** [rappasoft/laravel-livewire-tables#1640]
### What happened?

I don't know why this problem happens every now and then.

When this happens, the table is completely disconfigured.

<img width="1265" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/4259380/95701d93-0890-4881-b2eb-c714b4c270f8">

The search input disappears.

When I change the page, the button appears again, but the table is unconfigured.

<img width="562" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/4259380/d3a0f665-48a0-4afb-979d-ac11b4d7c6ac">

<img width="592" alt="image" src="https://github.com/rappasoft/laravel-livewire-tables/assets/4259380/a00b201f-8e88-4cc2-afb6-007128e47c75">

### Package Version

3.2.0

### PHP Version

8.2.x

### Laravel Version

10.8.0

### Alpine Version

3.10.5

### Theme

Bootstrap 5.x

### Error Message

livewire.js?id=e2b302e9:1202 Uncaught ReferenceError: currentlyReorderingStatus is not defined
    at [Alpine] !currentlyReorderingStatus (eval at safeAsyncFunction (livewire.js?id=e2b302e9:1249:21), <anonymous>:3:33)
    at livewire.js?id=e2b302e9:1271:23
    at tryCatch (livewire.js?id=e2b302e9:1191:14)
    at livewire.js?id=e2b302e9:3534:19
    at reactiveEffect (livewire.js?id=e2b302e9:2365:18)
    at Object.effect2 [as effect] (livewire.js?id=e2b302e9:2340:7)
    at effect (livewire.js?id=e2b302e9:734:35)
    at wrappedEffect (livewire.js?id=e2b302e9:750:29)
    at Function.<anonymous> (livewire.js?id=e2b302e9:3534:5)
    at flushHandlers (livewire.js?id=e2b302e9:1353:48)

**Comment by CLCWebsiteServices** [comment]
https://laraveldaily.com/post/livewire-3-laravel-breeze-error-alpine-js-conflict

**Comment by jaroslavstefanec** [comment]
Review your app.js file to ensure that Alpine.js is not initialized twice.

**Comment by desinabl** [comment]
> https://laraveldaily.com/post/livewire-3-laravel-breeze-error-alpine-js-conflict

in addition to the solution given by CLCWebsiteServices, after you make sure that alpinejs is not being loaded twice and if you are using a bundler, such as vite for example I suggest you add the following to app.js:

`import '../../vendor/rappasoft/laravel-livewire-tables/resources/imports/laravel-livewire-tables-all.js';
`
Reference: https://rappasoft.com/docs/laravel-livewire-tables/v3/start/including-assets.
