### ISSUE TITLE
[Bug]: sortable() doesn't work when i use label

### ISSUE THREAD

**Issue by bhagat-abhishek** [rappasoft/laravel-livewire-tables#1641]
### What happened?

I am trying to make use of the label method for showing the views from a relation, but eventually it doesn't work. I tried to look for a solutions but even after months i am unable to fix, can anyone help me reslove this issue.

Here is the code from the component table

```
Column::make('Views')->label(fn ($row, Column $column) => $row->visit()->count())->sortable(),
Column::make('Whatsapp')->label(fn ($row, Column $column) => Click::where('listing_id', $row->id)->where('is_whatsapp', true)->count())->sortable(),
Column::make('Call')->label(fn ($row, Column $column) => Click::where('listing_id', $row->id)->where('is_call', true)->count())->sortable(),
```

### How to reproduce the bug

When using the label(), with sortable() itsnt working;
also when I tried one solution from the closed issue #1033 but it didn't work when i tried.

### Package Version

2.11

### PHP Version

8.1.x

### Laravel Version

10.0

### Theme

None

**Comment by bhagat-abhishek** [comment]
@rappasoft @WhereIsLucas @dmyers @kijtra can anyone please help me

**Comment by lrljoe** [comment]
@bhagat-abhishek  - so sortable() when using a label requires a callback to be used, as it's not a "real field", so the package won't try to do anything with it in terms of the database query.

e.g.
```
Column::make('Address')
  ->label(fn ($row, Column $column) => $row->addr_line1)->sortable(
        fn(Builder $query, string $direction) => $query->orderBy('addr_line_2', $direction)
    ),
```

Worth noting, looking at your code, that you should really be using relationships to pull that data into the main builder(), so that you aren't executing multiple queries per row.

**Comment by bhagat-abhishek** [comment]
@lrljoe thank you, let me try that.

**Comment by lrljoe** [comment]
Definitely look at relationships for those models instead of running separate queries though!  It'll run much better
