### ISSUE TITLE
[Bug]: Artisan About: wrong version number

### ISSUE THREAD

**Issue by mLicorn** [rappasoft/laravel-livewire-tables#1645]
### What happened?

The version displayed in the '_**php artisan about**_' command is not the correct one.

### How to reproduce the bug

1. Install last version
2. Check installed version
```shell
composer show rappasoft/laravel-livewire-tables
``` 
![local-version-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/6aaa6c81-56a6-4018-892b-ead4ffaa0505)

3. Check Artisan version
```shell
php artisan about
``` 
![artisan-version-min](https://github.com/rappasoft/laravel-livewire-tables/assets/10559840/3685e595-151b-4e14-a4cb-bbd0a36125cd)

### Package Version

3.2.0

### PHP Version

8.1.x

### Laravel Version

10.40.0

### Theme

None

### Notes

Rappasoft\LaravelLivewireTables\LaravelLivewireTablesServiceProvider::boot() line 17

```php
AboutCommand::add('Rappasoft Laravel Livewire Tables', fn () => ['Version' => '3.0.0']);
```

**Comment by lrljoe** [comment]
Can't believe I missed that all this time!  Thanks for pointing it out, I'll get it updated for the next release

**Comment by lrljoe** [comment]
This will be addressed in the next version!
