### ISSUE TITLE
[Bug]: collapsing seems to be broken on table row because of the breakpoints that doesnt match with the one on table head

### ISSUE THREAD

**Issue by mrevanzak** [rappasoft/laravel-livewire-tables#1646]
### What happened?

so this happens to me

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/73029778/da3ef494-2aab-4434-9e9d-71fff2f33981)

the last 2 columns should be on collapse but the table row doesn't disappear, only the table head disappears.
the culprit is `lg:table-cell` on the table head but `md:table-cell` on the table row

### How to reproduce the bug

just use collapseOnTablet() or collapseOnMobile

### Package Version

3.2.0

### PHP Version

8.1.x

### Laravel Version

10

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Apologies for the delay, will try to get this one resolved this weekend!  It didn't come up during testing oddly, so need to check if I've got something custom on my end.

**Comment by lrljoe** [comment]
Okay, identified the issue, will have a fix in this weekend's release!

**Comment by Astalyos** [comment]
![image_2024-02-22_154034442](https://github.com/rappasoft/laravel-livewire-tables/assets/57922504/9de2adf3-5078-48dc-9c8e-d3660847c68d)
Hi Joe ! 
I just installed the package today and might have something that seems connected to that too
Let me know if you need more details

I don't have anything special in the code tho, i've joined the discord so i'll be checking the releases patches from there ! 

Package Version 3.2
Php : 8.2
Laravel 10 

Have a good one !

```php
class LocationCountry extends DataTableComponent
{
    protected $model = Country::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
        $this->setAdditionalSelects(['call_prefix']);
        $this->setComponentWrapperAttributes([
            'class' => '',
        ]);
        $this->setDebugEnabled();
        $this->setSearchEnabled();
        $this->setSortingEnabled();
    }

    public function columns(): array
    {
        return [
            Column::make('Id', 'id')
                ->sortable(),
            Column::make('Name')->label(fn ($row) => $row->name)
                ->sortable(fn (Builder $query, $direction) => $query->orderBy('name', $direction))
                ->searchable(fn (Builder $query, $term) => $query->where('name', 'like', '%'.$term.'%')),
            Column::make('Iso code', 'iso_code')
                ->sortable(),
            Column::make('Prefix')->label(fn ($row) => '+'.$row->call_prefix)
                ->sortable(),
            Column::make('Zone', 'zone.name')
                ->eagerLoadRelations()
                ->sortable(),
            BooleanColumn::make('Enabled', 'active')
                ->sortable(),
        ];
    }
}
```

**Comment by lrljoe** [comment]
Currently testing the fix
[https://github.com/rappasoft/laravel-livewire-tables/pull/1665](https://github.com/rappasoft/laravel-livewire-tables/pull/1665)
