### ISSUE TITLE
[Bug]: Search box and Column Per Page Dropdown can't read css style from tailwind

### ISSUE THREAD

**Issue by narahunter13** [rappasoft/laravel-livewire-tables#1649]
### What happened?

Search box and Column Per Page Dropdown can't read css style from tailwind

Laravel 10.x
Tailwind 3.x
Livewire 3.x
Table 3.x

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/44825321/231fc752-972d-492d-ab1f-a5bd972a7867)

### PHP Version

None

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Please read the installation instructions here for configuring Tailwind to include the relevant CSS Classes
[https://rappasoft.com/docs/laravel-livewire-tables/v3/start/configuration](https://rappasoft.com/docs/laravel-livewire-tables/v3/start/configuration)
