### ISSUE TITLE
[Bug]: Per Page doesn't apply when returning to the table

### ISSUE THREAD

**Issue by tjhunkin-inhance** [rappasoft/laravel-livewire-tables#1654]
### What happened?

select show 100 records for example, which it does, navigate away from the table, then return and the per-page remains at 100, however, the table shows the default limit. So either the per page needs to be reset when returning or it needs to display the selected amount of 100.

### Package Version

latest

### PHP Version

8.2.x

### Laravel Version

latest

### Alpine Version

latest

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Just to confirm that you're on v3.x?

**Comment by CovertError** [comment]
I'm having the same issue on v3

**Comment by CovertError** [comment]
> Just to confirm that you're on v3.x?
> 
> Can you try adding to a table:
> 
> ```
>     public string $tableName = 'my-random-table';
> 
>     public $my-random-table;
> ```
> 
> Just want to see if that's the issue or not!

adding this doesn't fix it

**Comment by lrljoe** [comment]
@CovertError - can you share the content of your table component please :) as this will help me figure out what isn't correct!

**Comment by nicomitov** [comment]
I can confirm the bug. 
It occurs when setPerPageAccepted() and setPerPage() are set in the table component.

e.g.:
```
public function configure()
{
    $this->setPerPageAccepted([12, 30, 50, 100]);
    $this->setPerPage(12);
    ...
}
```

**Comment by lrljoe** [comment]
So setting this in configure():
```
    $this->setPerPage(12);
```
Will over-ride whatever it receives in the querystring.

Effectively what is happening is:
- The mount method is setting the historic "per-page" from the session (if it exists)
- The QueryString is then updating the "per-page" (which by default with Laravel/Livewire happens in the boot step)
- Your configure() method is then changing  "per-page" to be whatever you define there.

I think the smoothest approach would be adding in a setDefaultPerPage() method, so that you can set a default, that'll apply only if it's not in the session/querystring.

**Comment by nicomitov** [comment]
setDefaultPerPage() works for me. Thanks!

**Comment by tjhunkin-inhance** [comment]
So I changed the setPerPage to setDefaultPerPage and if I select say to show 10 records it shows 10, if I navigate away and come back, it shows 10 in the paginate drop down but the grid itself only shows 5 records. Not sure what I'm doing wrong?

```php
    public function configure(): void
    {
        $this->setPrimaryKey('id')
            ->setTableRowUrl(function ($row) {
                return route('product.edit', $row);
            })
            ->setTableRowUrlTarget(function ($row) {
                return 'navigate';
            });

        $this->setSearchEnabled();
        $this->setSearchLive();
        $this->setPerPageAccepted(config('truthy.tables.rows.setPerPageAccepted'));
        $this->setDefaultPerPage(config('truthy.tables.rows.setPerPage'));
        $this->setDefaultSort('products.created_at', 'desc');
    }
```

```php
return [
    'rows' => [
        'setPerPageAccepted' => [5, 10, 25, 50, 100], // config('truthy.tables.rows.setPerPageAccepted')
        'setPerPage' => 5, // config('truthy.tables.rows.setPerPage')
    ]
];
```

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/86232273/82067271-feff-41ea-bbb7-c8c2fb22b2e7)

**Comment by tjhunkin-inhance** [comment]
seems to be working fine, thanks
