### ISSUE TITLE
[Bug]: Multiple tables collapsible on mobile

### ISSUE THREAD

**Issue by manuelpmgt** [rappasoft/laravel-livewire-tables#1668]
### What happened?

When i have multiple tables on the same page with columns()->collapseOnMobile, when i click to view the collapsed columns, it shows the columns of the same row on all tables on the same page.

### How to reproduce the bug

Create multiple tables on the same page with various collapsible columns.

### Package Version

3

### PHP Version

8.3.x

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
Thanks for the report.  I've spotted the issue, but it may be a week before I can get it fixed.

**Comment by manuelpmgt** [comment]
Thank you! No worries im working around it for the moment.

**Comment by lrljoe** [comment]
Just responding to note that I've not forgotten about this, and am still looking into options to get this working smoothly and consistently.

**Comment by lrljoe** [comment]
Managed to find a straight-forward fix, so this will be in v3.2.4, which should be out shortly.

**Comment by lrljoe** [comment]
This is in 3.2.4, just tested and it appears to have resolved the issue, please re-open if the issue persists.
