### ISSUE TITLE
[Bug]: Column sorting is not working

### ISSUE THREAD

**Issue by joukhar** [rappasoft/laravel-livewire-tables#1689]
### What happened?

Hi Mr rappasoft!
I'm trying to sort integer columns with no hope 

https://github.com/rappasoft/laravel-livewire-tables/assets/94228259/d0007c1b-3b0e-40b5-b567-7e5f50013284

### Package Version

latest

### PHP Version

8.2.x

### Laravel Version

v10.48.2

### Alpine Version

latest

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Apologies, been on holiday.

Please can you share:
1) The code for your Table Component.
2) The column definition for your database table for the "rank" column
3) Any "casts" defined in the Model.

**Comment by joukhar** [comment]
so it works based on casts, thanks for info.
