### ISSUE TITLE
[Bug]: hideBulkActionsWhenEmpty is not working

### ISSUE THREAD

**Issue by rpringadi** [rappasoft/laravel-livewire-tables#1703]
### What happened?

My understanding is if we want to keep showing the bulk action button, we can do the following:

```php
        $this->hideBulkActionsWhenEmpty = false;
        $this->setHideBulkActionsWhenEmptyStatus(false);
```
I tried that, but that doesn't work. Looking into the code closely, we have  this file:

```php
// resources/js/laravel-livewire-tables.js  - line 11

alwaysShowBulkActions: !wire.entangle('hideBulkActionsWhenEmpty'),
```

The `wire.entangle('hideBulkActionsWhenEmpty'),` actually returns an object instead of a simple true/false.
```javascript
{
  "initialValue": false,
  "_x_interceptor": true
}
```
I guess the proper code should be the following?  -- just guessing.

```php
alwaysShowBulkActions: !wire.entangle("hideBulkActionsWhenEmpty").initialValue,
```

### How to reproduce the bug

```php
  public function configure(): void
    {
        ...
        $this->hideBulkActionsWhenEmpty = false;
        $this->setHideBulkActionsWhenEmptyStatus(false);
    }
```

### Package Version

3.2.4

### PHP Version

8.2.x

### Laravel Version

10.48.4

### Alpine Version

3.13.8

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Won't be initial value, as the entangle keeps it synchronised with the backend.  Certainly not working though, will have to see where it became broken, give me til the end of the week.

**Comment by lrljoe** [comment]
Will be fixed very soon!

**Comment by shawe** [comment]
Interested in the same issue, I see now that alwaysShowBulkActions never changes to true.

**Comment by lrljoe** [comment]
Yeah, it's on the to-do list for the next week, apologies for the delay.

**Comment by lrljoe** [comment]
Now released as v3.2.8, please advise if anything not as expected!

**Comment by shawe** [comment]
Still happening to me @lrljoe 

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/145989/2de8f6b6-d96c-45b1-a71f-69ac12980af6)

![image](https://github.com/rappasoft/laravel-livewire-tables/assets/145989/e6817e86-8bd5-4421-96c9-fda4e26f4274)

**Comment by shawe** [comment]
For me the problem seems to be related with the command for publish the views to resources/views/vendor/livewire-tables

I removed the folder and launch the command again and this issue disappear.

**Comment by lrljoe** [comment]
You do not need to publish the views, unless you are making changes to them.

It is recommended not to do so!

**Comment by shawe** [comment]
> You do not need to publish the views, unless you are making changes to them.
> 
> It is recommended not to do so!

I need to do it, to replace some theme diffs.
