### ISSUE TITLE
[Bug]: Incorrect work filters and blade view Laravel 11, Livewire 3

### ISSUE THREAD

**Issue by rah-emil** [rappasoft/laravel-livewire-tables#1704]
### What happened?

Just see video, please: https://drive.google.com/file/d/1_st0p4Y9mrqneEfHWiOk3KN3GK7-MZqB/view?usp=drive_link

Alpine:
```html
       <!-- ... other code -->

        <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
    </body>
</html>
```

My table component:
```php
<?php

namespace App\Livewire\Components\Incidents;

use App\Models\Incident;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;


class IncidentsTable extends DataTableComponent
{
    protected $model = Incident::class;
    public string $tableName = 'incidents';

    public function configure(): void
    {
        $this->setPrimaryKey('id')
            ->setDefaultSort('id', 'desc')
            ->setReorderStatus(false)
            ->setColumnSelectStatus(true);
    }

    public function columns(): array
    {
        return [
            Column::make('ID', 'id'),
            Column::make('Status', 'status'),
            Column::make('Topic', 'topic'),
            Column::make('Type', 'type'),
            Column::make('Level Priority', 'priority'),
        ];
    }
}
```

My livewire blade:
```html
<div>
    <livewire:components.incidents.incidents-table />
</div>
```

### How to reproduce the bug

Please, see the video 

### Package Version

3.2.4

### PHP Version

8.3.x

### Laravel Version

11.4.0

### Alpine Version

3.X.X

### Theme

Tailwind 3.x

### Notes

I checked all your documentation

### Error Message

All errors inside the video

**Comment by JustGregGithub** [comment]
Please note that the video needs to be public. No one is currently able to see the video.

**Comment by rah-emil** [comment]
> Please note that the video needs to be public. No one is currently able to see the video.

My bad) I did it, you can see: https://drive.google.com/file/d/1_st0p4Y9mrqneEfHWiOk3KN3GK7-MZqB/view?usp=sharing

**Comment by apydevs** [comment]
@rah-emil  I had the same experience, This be worth a try. lucky i realised quite quickly and didn't spend to much time chasing my tail! 
Stop vite services and re-run `npm run build`, once complete restart `npm run dev`.

**Comment by lrljoe** [comment]
Worth noting, Livewire v3 bundles in AlpineJS, so you shouldn't be using a cdn for Alpine, as it'll cause Livewire itself to throw a tantrum.
