### ISSUE TITLE
[Feature Request]: Make data tables for Models not within app folder

### ISSUE THREAD

**Issue by marvoh** [rappasoft/laravel-livewire-tables#1713]
### Overview

We are grateful for the efforts you have put into this package, it has saved us tons of hours of effort.

As we work on newer projects, we find that the scope of functionality begins to become repetitive and therefore you or someone else may have already done some piece of work that you already need. These would typically be installed in the vendors folder through composer. 

Some of these packages have models which the user of the end product would need to interact with therefore will require presentation in tables. However, this package at the moment does not accept packages outside app path. 

If time permits and resources permits, please consider looking into supporting both scenarios.

Thank you and God bless you and your family.

**Comment by DishaRupareliya** [comment]
+1 from my side.

**Comment by DishaRupareliya** [comment]
i am facing same issue. i am working with livewire and i wanted to create datatable `PurchaseCodeVerifierTable` and model location is `modules/Items/Models/PurchaseCodeVerifier`

here is command i am using `php artisan make:datatable PurchaseCodeVerifierTable modules/Items/Models/PurchaseCodeVerifier`

but it give me an error. 
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/111873195/e1fbbabe-b148-41a1-8185-5c1a830a9f27)

Note : i am using nwidart module package

**Comment by lrljoe** [comment]
Should be in the next release thanks to @marvoh

**Comment by lrljoe** [comment]
Is now in develop should you wish to test it, should be a new release this weekend.

**Comment by lrljoe** [comment]
This is in the latest release, please reach out if you still have issues, either by re-opening, giving me a mention, or reaching out on Discord!
