### ISSUE TITLE
[Feature Request]: Support for laravel nWidart module package

### ISSUE THREAD

**Issue by DishaRupareliya** [rappasoft/laravel-livewire-tables#1717]
### Overview

i am facing same issue. i am working with livewire and i wanted to create datatable `PurchaseCodeVerifierTable` and model location is `modules/Items/Models/PurchaseCodeVerifier`

### Detailed explanation

here is command i am using `php artisan make:datatable PurchaseCodeVerifierTable modules/Items/Models/PurchaseCodeVerifier`

but it give me an error. 
![image](https://github.com/rappasoft/laravel-livewire-tables/assets/111873195/e1fbbabe-b148-41a1-8185-5c1a830a9f27)

### Notes

i am using nwidart module package

**Comment by lrljoe** [comment]
Does it work with backslashes rather than forward slashes?

**Comment by lrljoe** [comment]
Should be in the next release thanks to @marvoh

**Comment by lrljoe** [comment]
Is now in develop should you wish to test it, should be a new release this weekend.

**Comment by lrljoe** [comment]
This is in the latest release, please reach out if you still have issues, either by re-opening, giving me a mention, or reaching out on Discord!
