### ISSUE TITLE
[Bug]: URL param converts to scientific notation on reload

### ISSUE THREAD

**Issue by pwveupry** [rappasoft/laravel-livewire-tables#1769]
### What happened?

When using the search functionality `?table-search` query param will convert certain values to scientific notation on reload.

### How to reproduce the bug

Examples:

Search for "13E7"
Reload page
URL param and search input will now have the value "130000000"

Search for "12E33"
Reload page
URL param and search input will now have the value "1.2E+34"

### Package Version

3.2.8

### PHP Version

8.1.x

### Laravel Version

10

### Theme

Bootstrap 5.x

**Comment by lrljoe** [comment]
So we utilise the standard Livewire code for URL Query parameters.  Which version of Livewire are you currently using?

**Comment by lrljoe** [comment]
Just validated, it happens in Core Livewire as well (without the package), so I'm speaking to the Livewire Core team about the issue.

**Comment by lrljoe** [comment]
Seems to be from Livewire Core
Livewire\Features\SupportQueryString\BaseUrl

Line 63-65 where it does
```
        $decoded = is_array($initialValue)
            ? json_decode(json_encode($initialValue), true)
            : json_decode($initialValue, true);
```

Have raised it, will update on the outcome

**Comment by lrljoe** [comment]
You can see the status of the core fix here:
[https://github.com/livewire/livewire/pull/8647](https://github.com/livewire/livewire/pull/8647)

**Comment by pwveupry** [comment]
Thanks a lot! I was unsure of where exactly it occurred so thank you for the clarification. Let's hope they look in to it.

**Comment by lrljoe** [comment]
Going to close this, I've spoken to the core team and it's being investigated, but it doesn't relate to this package.

If they choose not to fix it, then it's a bit more widespread, but we'll look to implement some interim fix
