### ISSUE TITLE
[Feature Request]: conditional deselected()

### ISSUE THREAD

**Issue by markebjones** [rappasoft/laravel-livewire-tables#1842]
### Overview

I would like to be able to conditionally determine if the column should be deselected, or not, similarly to how I can conditionally determine if the column should be hidden, or not.

_Great repo, obviously, thanks so much!_

### Detailed explanation

My suggestion is to either:

1) adapt `deselected()` to support an optional boolean argument that would deselect if true, with a default of true
2) introduce `deselectIf()` with a mandatory boolean argument that would deselect if true

**Comment by lrljoe** [comment]
Good suggestion.

I'm in the process of actually updating the Column behaviours, so will see if this can be added in at the same time.

**Comment by lrljoe** [comment]
So, introducing
deselectedIf()
Where you use non-table properties to determine whether or not to show it, is straight forward.

Obviously you can't use the Row, as that'll change with each row.
There's no point in passing the Column.

So are you happy with just a straight forward callback, e.g.

```php
            Column::make('Something', 'id')
              ->deselectedIf(fn() => Auth::user()->can('Do-Something'))
              ->sortable(),
```

**Comment by markebjones** [comment]
It looks great. This is exactly what I'm looking for. Thanks so much!

**Comment by lrljoe** [comment]
No problem, I'll need to write docs and tests, but should be done by the end of the week

**Comment by lrljoe** [comment]
Just linking in the PR, I'll need to double check it all before I can do a release, but it's all on-track as you can see!

**Comment by lrljoe** [comment]
@markebjones  - should be present now as of v3.4.6

**Comment by markebjones** [comment]
Great. Thank you. I will test it over the weekend!

**Comment by markebjones** [comment]
Seems to work perfectly. Thank you. :)
