### ISSUE TITLE
[Bug]: After Update the livewire tables

### ISSUE THREAD

**Issue by NoxzMSTR** [rappasoft/laravel-livewire-tables#1845]
### What happened?

I updated the livewire tables now it is not working as it should and give lots of error in the console

### How to reproduce the bug

I updated the package this list also has filter but not shown
![Screenshot 2024-08-14 153059](https://github.com/user-attachments/assets/81e4f090-a58c-4118-bb37-58b8fc9f1b99)
![Screenshot 2024-08-14 153112](https://github.com/user-attachments/assets/bc94e33b-d4b8-4150-b2e3-3b174950ddc0)

### Package Version

3.4.5

### PHP Version

8.3.x

### Laravel Version

11

### Alpine Version

3.4.2

### Theme

Bootstrap 5.x

**Comment by dieselmatic** [comment]
Same here after upgrading from 3.4.3 -> 3.4.4 or 3.4.5
Alpine Expression Error: tableWrapper is not defined

<img width="1502" alt="image" src="https://github.com/user-attachments/assets/97d9e2fc-d128-4318-9982-7e2de1f082a9">

**Comment by dieselmatic** [comment]
> ### What happened?
> I updated the livewire tables now it is not working as it should and give lots of error in the console
> 
> ### How to reproduce the bug
> I updated the package this list also has filter but not shown ![Screenshot 2024-08-14 153059](https://private-user-images.githubusercontent.com/42188571/357778847-81e4f090-a58c-4118-bb37-58b8fc9f1b99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODQ5NjMsIm5iZiI6MTcyMzY4NDY2MywicGF0aCI6Ii80MjE4ODU3MS8zNTc3Nzg4NDctODFlNGYwOTAtYTU4Yy00MTE4LWJiMzctNThiOGZjOWYxYjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZTg3OTJkYTIwMWRjMjI0ZGVhZmNiN2U1OGJjNDEyYzdiODM2Nzc0Mjk2Yzc3ZThiMjNhOTVlYmM5ZDU3NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pfNZZP-ncSY0nSOO1bKIp_fhnedbqKOkoXOiU15NlyE) ![Screenshot 2024-08-14 153112](https://private-user-images.githubusercontent.com/42188571/357778855-bc94e33b-d4b8-4150-b2e3-3b174950ddc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODQ5NjMsIm5iZiI6MTcyMzY4NDY2MywicGF0aCI6Ii80MjE4ODU3MS8zNTc3Nzg4NTUtYmM5NGUzM2ItZDRiOC00MTUwLWIyZTMtM2IxNzQ5NTBkZGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxMTc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZDRhMmZlYTNiODkyYzllMzMzNzdiMThhMzE1ODgyYzE1YWJkODYyOGJmYmYxNzc2NDQxZDJiN2YyYTRmYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FtlFJPYNYiaziWOCSSYdTfZ9J9j8ElbDhHmPaQ2JhM)
> 
> ### Package Version
> 3.4.5
> 
> ### PHP Version
> 8.3.x
> 
> ### Laravel Version
> 11
> 
> ### Alpine Version
> 3.4.2
> 
> ### Theme
> Bootstrap 5.x
> 
> ### Notes
> _No response_
> 
> ### Error Message
> _No response_

It seems that you copied the vendor files into your project, and the changes made from version 3.4.4 are not backward compatible. Remove your changes and republish the vendor files using the following command:

`php artisan vendor:publish --provider="Rappasoft\LaravelLivewireTables\LaravelLivewireTablesServiceProvider"`

After that you can merge your old changes with new files

File list I need to change:
- resources/views/vendor/livewire-tables/datatable.blade.php
- public/vendor/rappasoft/livewire-tables/...

**Comment by lrljoe** [comment]
What @dieselmatic said

This change was fairly large!  And was to try and tidy up a large swathe of backend code.

We **strongly** recommend **not publishing** the views.  The vast majority of elements are fully customisable in the tables.

If you need to customise something, and it isn't currently possible, then please do open up a Feature Request, and it'll get added in as a customisation option.

**Comment by lrljoe** [comment]
There is another major change coming in the next day or two, which will also be impactful / not backwards compatible.

These changes are to improve performance, and stability.

If you are publishing the views - please do let us know why you need to, as the package does make the majority of elements customisable.

**Comment by lrljoe** [comment]
@NoxzMSTR - please see my above comments, hope this helps!

**Comment by lrljoe** [comment]
I've restored the original Alpine data methods.  However - you should definitely update to the latest views, as there are numerous performance improvements present

**Comment by NoxzMSTR** [comment]
Ok thanks @lrljoe i will try it and let you know about it

**Comment by NoxzMSTR** [comment]
I removed the vendor in the public files and updated the package now it is working but i having issue with filter

Livewire
 \ 
Features
 \ 
SupportLockedProperties
 \ 
CannotUpdateLockedPropertyException
PHP 8.3.6
11.20.0
Cannot update locked property: [filterSlideDownDefaultVisible]

**Comment by NoxzMSTR** [comment]
![Screenshot 2024-08-16 123628](https://github.com/user-attachments/assets/f952ed36-c2cd-44ec-9ea6-b723019df6e1)
I think this is the issue

**Comment by lrljoe** [comment]
> ![Screenshot 2024-08-16 123628](https://private-user-images.githubusercontent.com/42188571/358507010-f952ed36-c2cd-44ec-9ea6-b723019df6e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MzMxMzgsIm5iZiI6MTcyMzkzMjgzOCwicGF0aCI6Ii80MjE4ODU3MS8zNTg1MDcwMTAtZjk1MmVkMzYtYzJjZC00NGVjLTllYTYtYjcyMzAxOWRmNmUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE3VDIyMTM1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3MDEzN2Q5YzgzZWQ5MDdiNDViMDBkNDYyM2RlMmZlNmVhYmFlODhiOWJhOWY2OWE3Zjk5ZmEwNTM0ZTUwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-1uHuSUr7MIY_NYA9ZdgINz1pVTB2953hx-JTs4iUc) I think this is the issue

Please do give me a tag, or prod me on the official Discord [https://discord.com/invite/pQgzQuRZuS](https://discord.com/invite/pQgzQuRZuS) if you get an issue like this so that I'm aware more readily.

This should be fixed imminently.

**Comment by lrljoe** [comment]
Should be fixed as of v3.4.7
