### ISSUE TITLE
[Bug]: SelectAll not working if pagination disabled

### ISSUE THREAD

**Issue by markusnissl** [rappasoft/laravel-livewire-tables#1865]
### What happened?

If you set `$this->setPaginationDisabled();` the value of the selectAll checkbox is not updated correctly and always shows an empty result.

### Package Version

3.4.8

### PHP Version

8.2.x

### Laravel Version

11.20.0

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
How big is the table you are using?  In terms of number of records.

**Comment by lrljoe** [comment]
@markusnissl  - If I don't hear back from you this week, I'll have to close the issue.

**Comment by markusnissl** [comment]
I had 2 records in the table

**Comment by lrljoe** [comment]
Can you share the full table component please

**Comment by markusnissl** [comment]
I think it is better if I show you the exact error what is missing:

In view `resources/views/components/table/th/bulk-actions.blade.php` you access `paginationTotalItemCount` without checking if it is null.

By `src/Traits/WithPagination.php` this value is optional any by default `null`.

By `src/Traits/WithData.php` this value is only set to not null in case pagination is enabled.

So what has to be fixed is to check if pagination is enabled in the view and use in case it is not enabled the number of rows.
