### ISSUE TITLE
[Bug]: Undefined variables $columns - V3.3.3 => V3.4.8

### ISSUE THREAD

**Issue by ZitelliDZ** [rappasoft/laravel-livewire-tables#1866]
### What happened?

![Imagen de WhatsApp 2024-08-20 a las 12 11 17_0e7c31cd](https://github.com/user-attachments/assets/51759ea1-301e-4c0b-a37e-c466695af7ca)

### How to reproduce the bug

The error occurs when the package is updated to the latest version.  V3.3.3 => V3.4.8

### Package Version

3.4.8

### PHP Version

8.2.x

### Laravel Version

11.17

### Alpine Version

3.14.0

### Theme

Bootstrap 5.x

**Comment by S-Marouene** [comment]
i have the same problem when updating from V3.3.4 to V3.3.8 !

**Comment by lrljoe** [comment]
If you published the views, then this now uses computed properties to get rows/columns

**Comment by lrljoe** [comment]
I will issue an update for now to default to the original behaviour.

**Comment by lrljoe** [comment]
This should be fixed in the latest version.  The new behaviour was set to enabled by default, this is no longer the case.  Let me know if after updating this still presents an issue.

**Comment by thomasgalue** [comment]
> This should be fixed in the latest version. The new behaviour was set to enabled by default, this is no longer the case. Let me know if after updating this still presents an issue.

In my case, only fails (for now) if there is a `boolean` column in the table.

`Undefined variable $component` 
![Captura de pantalla_21-8-2024_205457_dot test](https://github.com/user-attachments/assets/0c85d36d-9f69-49ee-82d4-217958865335)
I think you can see that pic.
Some tables work, the ones that have `boolean `don't.

**Comment by lrljoe** [comment]
Replace with

```
@if ($isTailwind)
    @if ($status)
        @if ($type === 'icons')
            @if ($successValue === true)
                <x-heroicon-o-check-circle class="inline-block h-5 w-5 text-green-500" />
            @else
                <x-heroicon-o-check-circle class="inline-block h-5 w-5 text-red-500" />
            @endif
        @elseif ($type === 'yes-no')
            @if ($successValue === true)
                <span>Yes</span>
            @else
                <span>No</span>
            @endif
        @endif
    @else
        @if ($type === 'icons')
            @if ($successValue === false)
                <x-heroicon-o-x-circle class="inline-block h-5 w-5 text-green-500" />
            @else
                <x-heroicon-o-x-circle class="inline-block h-5 w-5 text-red-500" />
            @endif
        @elseif ($type === 'yes-no')
            @if ($successValue === false)
                <span>Yes</span>
            @else
                <span>No</span>
            @endif
        @endif
    @endif
@elseif ($isBootstrap)
    @if ($status)
        @if ($type === 'icons')
            @if ($successValue === true)
                <x-heroicon-o-check-circle  class="d-inline-block text-success laravel-livewire-tables-btn-small" />
            @else
                <x-heroicon-o-check-circle class="d-inline-block text-danger laravel-livewire-tables-btn-small" />
            @endif
        @elseif ($type === 'yes-no')
            @if ($successValue === true)
                <span>Yes</span>
            @else
                <span>No</span>
            @endif
        @endif
    @else
        @if ($type === 'icons')
            @if ($successValue === false)
                <x-heroicon-o-x-circle class="d-inline-block text-success laravel-livewire-tables-btn-small" />
            @else
                <x-heroicon-o-x-circle class="d-inline-block text-danger laravel-livewire-tables-btn-small" />
            @endif
        @elseif ($type === 'yes-no')
            @if ($successValue === false)
                <span>Yes</span>
            @else
                <span>No</span>
            @endif
        @endif
    @endif
@endif
```

There have been numerous changes to the blades/views, so would recommend that you look at migrating to the new ones.

**Comment by thomasgalue** [comment]
My bad I think, should a clean install works or how can I migrate to the new blade/views?

**Comment by lrljoe** [comment]
If you've not changed anything in the views manually, then you can just delete the resources/views/vendor/livewire-tables directory.
You don't need to publish the views for anything to work.

**Comment by lrljoe** [comment]
If you have previously published the views, you will need to set the following in your configure method:

```
    public function configure(): void
    {
        $this->useComputedPropertiesDisabled();
    }
```

This ensures that the original methodology is used.
