### ISSUE TITLE
font awesome icon

### ISSUE THREAD

**Issue by kickdev** [rappasoft/laravel-livewire-tables#19]
Unfortunately, the icons are strongly defined in the template. But I love the icons fal and not fas, it would not be bad if it would be made in the settings

**Comment by rappasoft** [comment]
Which ones?

**Comment by KenLewis** [comment]
I believe the recent update that allows publishing the views would allow @kickdev to override this.

**Comment by niels-hubs** [comment]
Hi Kickdev,

I'm also looking for such way to change the icon. We use the most recent version of FontAwesome and we only see blocky icons, because the new version doesn't use FAS prefix for the sortable icons.

Is there anyway to fix this issue?

**Comment by KenLewis** [comment]
With the most recent release, you can publish the views and modify them however you want.
```
php artisan vendor:publish
```

**Comment by rappasoft** [comment]
The next version I removed the hard coded FA icon, and added configs for the other ones.
