### ISSUE TITLE
[Bug]: Livewire property `tableName` cannot be found

### ISSUE THREAD

**Issue by danie-ramdhani** [rappasoft/laravel-livewire-tables#1920]
### What happened?

When upgrading to latest version (3.4.17) there's console bug `Livewire property [tableName] cannot be found` from [this PR](https://github.com/rappasoft/laravel-livewire-tables/pull/1914) and i think from [this line](https://github.com/rappasoft/laravel-livewire-tables/blob/3ca9979a5b304f9d2eadf49eeb7ad6f32969839e/resources/js/laravel-livewire-tables.js#L7).

defining property to table component like `public string $tableName = 'some-table';` fix the bug. but is it really required to define `$tableName` from version `3.4.17`?

Here's the console error looks like:
<img width="260" alt="image" src="https://github.com/user-attachments/assets/1dd7b5bd-3e7f-4ffb-9f80-f50eafb2a261">

### Package Version

3.4.17

### PHP Version

None

### Theme

None

**Comment by qwasyx0** [comment]
yes it is required

**Comment by lrljoe** [comment]
I shall look at tweaking this email

**Comment by lrljoe** [comment]
This is in development branch, and will be in the next release.

**Comment by lrljoe** [comment]
Should be fixed now

## [v3.4.20] - 2024-09-10
### Bug Fixes
- Revert tableName to be public by @lrljoe in https://github.com/rappasoft/laravel-livewire-tables/pull/1937
