### ISSUE TITLE
[Bug]: Undefined variable $columns

### ISSUE THREAD

**Issue by rajbalar004** [rappasoft/laravel-livewire-tables#1924]
### What happened?

After trying `composer update`, all I can see in pages with tables is `Undefined variable $columns` or `Undefined array key "filterLayout"` if filters are enabled.

### Package Version

3.4.17

### PHP Version

8.2.x

### Laravel Version

10.48.20

### Theme

Bootstrap 5.x

**Comment by mohamadarifin97** [comment]
im having same issue

**Comment by rajbalar004** [comment]
> ```
> php artisan clear-compiled &&
> php artisan cache:clear &&
> php artisan route:clear &&
> php artisan view:clear &&
> php artisan config:clear &&
> composer dumpautoload -o
> ```
> 
> run this

I have run this command already..

**Comment by shawe** [comment]
Also appears to me on production, working without problems on local.

**Comment by lrljoe** [comment]
Are you running injection or bundled assets?
Did you previously publish the views? (this is very much not recommended)

**Comment by shawe** [comment]
> Are you running injection or bundled assets? Did you previously publish the views? (this is very much not recommended)

Yes previously I published, in other issue that was closed some days ago I tell the other problem.

**Comment by adilaslam1807** [comment]
how you fix this

**Comment by shawe** [comment]
> how you fix this

With the previous shared commands.

**Comment by adilaslam1807** [comment]
yes it fixed thanks
