### ISSUE TITLE
[Bug]: When Install  package, the project becomes very heavy

### ISSUE THREAD

**Issue by asmaa143** [rappasoft/laravel-livewire-tables#1929]
### What happened?

When Install  package, the project becomes very heavy

### PHP Version

None

### Theme

None

**Comment by danie-ramdhani** [comment]
how about try clear the cache?

```
php artisan optimize:clear
```

**Comment by asmaa143** [comment]
> how about try clear the cache?
> 
> ```
> php artisan optimize:clear
> ```

all  method and php artisan config:cache , when remove package project become light

**Comment by ahmadrivaldi-arv** [comment]
I had this issue last week. running fine in local but when i push to production my app is very slow (before i install this package it runs fine)

[laravel-livewire-tables](https://github.com/rappasoft/laravel-livewire-tables) using [blade-icons](https://github.com/blade-ui-kit/blade-icons.git)

in blade-icons documentation it says you should cache icons or your app will slow down. read this for more details [doc: caching](https://github.com/blade-ui-kit/blade-icons?tab=readme-ov-file#caching)

**Comment by asmaa143** [comment]
> I had this issue last week. running fine in local but when i push to production my app is very slow (before i install this package it runs fine)
> 
> [laravel-livewire-tables](https://github.com/rappasoft/laravel-livewire-tables) using [blade-icons](https://github.com/blade-ui-kit/blade-icons.git)
> 
> in blade-icons documentation it says you should cache icons or your app will slow down. read this for more details [doc: caching](https://github.com/blade-ui-kit/blade-icons?tab=readme-ov-file#caching)

still same issue in local and production

**Comment by ahmadrivaldi-arv** [comment]
> > I had this issue last week. running fine in local but when i push to production my app is very slow (before i install this package it runs fine)
> > [laravel-livewire-tables](https://github.com/rappasoft/laravel-livewire-tables) using [blade-icons](https://github.com/blade-ui-kit/blade-icons.git)
> > in blade-icons documentation it says you should cache icons or your app will slow down. read this for more details [doc: caching](https://github.com/blade-ui-kit/blade-icons?tab=readme-ov-file#caching)
> 
> still same issue in local and production

have you try this?

check your ```livewire-tables.php``` configuration make sure the ``cache_assets``` set to true

    /**
     * Cache Rappasoft Frontend Assets
     */
    'cache_assets' => true,

**Comment by ahmadrivaldi-arv** [comment]
same with im struggle with this issue for 1 week, already trying optimize:clear and optimize the issue still same

when i open dev tools -> network tab -> it show the asset of laravel-livewire-tables like core.min.js etc took 2 second to load
so my production total time to load the page almost 20second, that sound crazy

i'm trying to remove this package and boom my app run fine after that. So I thought this library had a problem until I found the problem, which was in the dependency library blade-icons and trying caching the assets and now it works fine

**Comment by danie-ramdhani** [comment]
> same with me, struggling with this issue for 1 week, already trying optimize:clear and optimize the issue still same
> 
> when i open dev tools -> network tab -> it show the asset of laravel-livewire-tables like core.min.js etc took 2 second to load so my production total time to load the page almost 20second, that sound crazy
> 
> i'm trying to remove this package and boom my app run fine after that. So I thought this library had a problem until I found the problem, which was in the dependency library blade-icons and trying caching the assets and now it works fine

Ah yeah, that is known issue https://github.com/rappasoft/laravel-livewire-tables/issues/1375

Alternatively you can just manually import datatable assets using vite besides automatically injected assets

**Comment by lrljoe** [comment]
What @danie-ramdhani  said, bundle the assets via Vite, and it'll be speedy!

Caching the blade icons is also sensible!

**Comment by alvitres01** [comment]
> Tuve este problema la semana pasada. funcionando bien en local, pero cuando empujo a producción, mi aplicación es muy lenta (antes de instalar este paquete, funciona bien)
> 
> [laravel-livewire-tables](https://github.com/rappasoft/laravel-livewire-tables) usando [blade-icons](https://github.com/blade-ui-kit/blade-icons.git)
> 
> probar:
> 
> ```shell
> php artisan icons:cache
> ```
> 
> En la documentación de blade-icons, dice que debe almacenar los íconos en caché o su aplicación se ralentizará. Lea esto para obtener más detalles [Doc: Almacenamiento en caché](https://github.com/blade-ui-kit/blade-icons?tab=readme-ov-file#caching)

I was having the same problem, I tried the icons solution and it worked perfectly, very grateful.
