### ISSUE TITLE
[Bug]: shouldBeDisplayed is not defined

### ISSUE THREAD

**Issue by web-developer4-luc** [rappasoft/laravel-livewire-tables#1941]
### What happened?

![image](https://github.com/user-attachments/assets/0546ae2e-8616-4209-8534-23c13ece3b7b)

### Package Version

3.4.20

### PHP Version

8.3.x

### Laravel Version

10.48.20

### Alpine Version

3.14.1

### Theme

None

**Comment by web-developer4-luc** [comment]
Hello, I am using injection for the assets. I downgraded to version 3.4.16 and from alpineJs to 3.13.3 and it does not generate the error.

**Comment by lrljoe** [comment]
Okay, and have you published the views previously?

**Comment by web-developer4-luc** [comment]
The views are not published, and I followed the instructions to clean everything: https://rappasoft.com/docs/laravel-livewire-tables/v1/usage/troubleshooting

**Comment by lrljoe** [comment]
You referenced the v1 docs there, which version are you using?

**Comment by web-developer4-luc** [comment]
I am using version 3.4.16 I only referenced that documentation in the troubleshooting

**Comment by lrljoe** [comment]
Have you run:
```
npm run build
```
and
```
php artisan view:clear
```
?

**Comment by lrljoe** [comment]
This should be resolved, so closing, please re-open if not!
