### ISSUE TITLE
[Bug]: getSearchPlaceholder() Wrong Return

### ISSUE THREAD

**Issue by NastyOOF** [rappasoft/laravel-livewire-tables#1951]
### What happened?

Hey, i am new to this Package. I get the following error when i want to load the page:

`Rappasoft\LaravelLivewireTables\DataTableComponent::getSearchPlaceholder(): Return value must be of type string, array returned`

So i used the Example Component for my first Component:

```php
<?php

namespace App\Livewire\Administration;

use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Models\Languages;

class LanguagesTable extends DataTableComponent
{
    protected $model = Languages::class;

    public function configure(): void
    {
        $this->setPrimaryKey('id');
    }

    public function columns(): array
    {
        return [
            Column::make("Id", "id")
                ->sortable(),
            Column::make("Created at", "created_at")
                ->sortable(),
            Column::make("Updated at", "updated_at")
                ->sortable(),
        ];
    }
}
```

In my Blade File i run simple this:

```php
@extends('dashboard.overlay')
@section('title', 'Manage Languages')

@section('custom_css')
    <link href="{{ asset('assets/css/custom/dashboard/admin/manageLanguages.css') }}" rel="stylesheet">
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
@endsection

@section('content')

    <livewire:administration.languages-table>

@endsection
```

### How to reproduce the bug

call up the page :c

### Package Version

3.4.20

### PHP Version

8.3.x

### Laravel Version

11

### Theme

Bootstrap 5.x

### Error Message

Rappasoft\LaravelLivewireTables\DataTableComponent::getSearchPlaceholder(): Return value must be of type string, array returned

**Comment by lrljoe** [comment]
For Livewire v3 - take careful note of how the core Livewire behaves.

Notably, Alpine v3 is bundled in with Livewire v3, so you almost certainly do not need
```
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
```
In your layout, and this may be causing an issue!

**Comment by NastyOOF** [comment]
> For Livewire v3 - take careful note of how the core Livewire behaves.
> 
> Notably, Alpine v3 is bundled in with Livewire v3, so you almost certainly do not need
> 
> ```
>     <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
> ```
> 
> In your layout, and this may be causing an issue!
> 
> As to why you'd be seeing "Rappasoft\LaravelLivewireTables\DataTableComponent::getSearchPlaceholder(): Return value must be of type string, array returned"
> 
> I can't see you defining setSearchPlaceholder() in your configure() method there. Is that the entirety of your Table where you're experiencing the issue?
> 
> Just to rule out anything local, do you have a definition for "Search" locally in your lang files that would return an array?
> 
> If you update your configure to match the below, what do you end up with:
> 
> ```
>     public function configure(): void
>     {
>         $this->setPrimaryKey('id');
>         $this->setSearchPlaceholder('search');
>     }
> ```

Hey,
First: Thanks for your try to help me!

After I removed Alpine in the code as you described, nothing changed.
I added the "search" Placeholder, but then this Error is coming:

![grafik](https://github.com/user-attachments/assets/2b079a7e-5c8b-432c-96a7-73aed84e760e)

**Comment by lrljoe** [comment]
Okay, it looks like you're getting conflicts with what your existing localisations.

You must have "Columns" defined in your resources/lang directory

**Comment by NastyOOF** [comment]
I use the language variables via the database. I don't actually have any that have anything to do with ‘columns’.

But you can publish a fix for it or how do I understand that?

**Comment by lrljoe** [comment]
The next release will have a new set of views that refer directly to livewire-tables for localisation.

I anticipate releasing it tomorrow

However - you will need to remove your published views before it takes effect.

There is generally no need to publish the views!

**Comment by NastyOOF** [comment]
Is the Update out? And if yes, how can i get that?
And the published Views can i delete easily right?

**Comment by lrljoe** [comment]
> Is the Update out? And if yes, how can i get that? And the published Views can i delete easily right?

Yep, update is out, and you can delete any published views by removing/renaming the directory:
resources/views/vendor/livewire-tables
