### ISSUE TITLE
[Bug]: Filter refresh

### ISSUE THREAD

**Issue by OndrejMiko** [rappasoft/laravel-livewire-tables#1958]
### What happened?

Hello , i got problem with filter if I dynamicaly change values for filter field in livewire code . In version 2 its working but in version 3 filter not refresh values from livewire in function filters()
Any suggestion please , thank you 

### Package Version

3.4

### PHP Version

8.3.x

### Laravel Version

10.10

### Alpine Version

3.13

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Please share an example of exactly what you're doing

**Comment by OndrejMiko** [comment]
Hello 
In function     

```
public function filters(): array{
       $payment_types=$this->filterPaymentTypes;

        $filters=array();

        $filters["payment_state"]=SelectFilter::make(__("payment_state"),"payment_state")
            ->options($payment_states)
            ->filter(function(Builder $query, $value) {
                $query->where('payment_state', '=', $value);
            });
}
```
If I change in livewire $filterPaymentTypes by changing other filter values , filter dont change select , in v2 it works use like this . I need to change second select filter depends on first select filter value , like u pick car brand in first and second filter change models .

Thank you

**Comment by lrljoe** [comment]
```
public function filters()
```

Needs to RETURN an array.

**Comment by lrljoe** [comment]
In your example - 
Do you want "car brand" to apply any logic to the query?
Or only "car models" to apply logic to the query?

**Comment by OndrejMiko** [comment]
> In your example - Do you want "car brand" to apply any logic to the query? Or only "car models" to apply logic to the query?

I know it must have return array, i dont write it there it was just example.
 
I just need conditional logic in filter . If I set in first filter field "car brand" it must change second filter field "car models" to this brand only models .  The second filter field "car models" should only show models to selected first filter field "car brand"

Its it clear or should I create image example ?

Thank you
