### ISSUE TITLE
[Bug]: Inconsistently UI input on Boolean filter

### ISSUE THREAD

**Issue by danie-ramdhani** [rappasoft/laravel-livewire-tables#1991]
### What happened?

Enable then disable the boolean filter will not update the switch value

[Inconsistently switch ui on Boolean filter.webm](https://github.com/user-attachments/assets/4bea1380-17a6-4c38-9981-3b9f3a4fa4eb)

### Package Version

3.4.22

### PHP Version

None

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
This will be in the next release

**Comment by lrljoe** [comment]
This should be in 3.5.0 please let me know if the issue persists
