### ISSUE TITLE
[Bug]: setThAttributes default Flag not working

### ISSUE THREAD

**Issue by Kell** [rappasoft/laravel-livewire-tables#1997]
### What happened?

It seems the " 'default' => true" ist not working when applied in setThAttributes();

Expected behaviour: 
 use default = true gives the same result when using 
default-colors = true and default-styling = true;

### How to reproduce the bug

For this case we just take a look at the column "Action".  Adding custom class 

```php
$this->setThAttributes(function(Column $column) {
	$title = $column->getTitle();

	switch ($title) {
		case 'Actions':
			return [
				'class' => 'colum-action',
				];
			break;
		}

		return [];
});
```

results in different style on the Action colum
![Bildschirmfoto 2024-10-14 um 11 53 28](https://github.com/user-attachments/assets/3f432ed9-ab79-4626-ada7-40c01a37c836)

added default flag as described in https://rappasoft.com/docs/laravel-livewire-tables/v3/columns/styling#content-keeping-default-colors-and-default-styling

```php
$this->setThAttributes(function(Column $column) {
	$title = $column->getTitle();
	switch ($title) {
		case 'Actions':
			return [
                                 'default' => true,
				'class' => 'colum-action',
			];
			break;
		}

		return ['default' => true];
});
```

this change do nothing, column header looks same way as before:
![Bildschirmfoto 2024-10-14 um 11 55 57](https://github.com/user-attachments/assets/f3fb863f-0000-498d-ae28-3ac1ef657351)
![Bildschirmfoto 2024-10-14 um 11 57 30](https://github.com/user-attachments/assets/7d44bd31-e410-400b-97fb-b4eb34e717c6)
default classes are still overridden

Now if i add only default-styling:
```php
$this->setThAttributes(function(Column $column) {
	$title = $column->getTitle();

	switch ($title) {
		case 'Actions':
			return [
                                  'default-styling' => true,
				'class' => 'colum-action',
			];
			break;
	}

	return ['default-styling' => true];
});
```
this shows effect:
![Bildschirmfoto 2024-10-14 um 12 00 58](https://github.com/user-attachments/assets/0e08b380-e927-4126-9eee-a667b01ed980)
![Bildschirmfoto 2024-10-14 um 12 01 28](https://github.com/user-attachments/assets/07cd00d0-0820-4088-9b70-5f56a9be888f)

if i add default-colors:
```php
$this->setThAttributes(function(Column $column) {
	$title = $column->getTitle();

	switch ($title) {
		case 'Actions':
			return [
                                  'default-styling' => true,
                                   'default-colors' => true,
				  'class' => 'colum-action',
		];
		break;
	}

	return ['default-styling' => true, 'default-colors' => true];
});

```
it also works:
![Bildschirmfoto 2024-10-14 um 12 03 29](https://github.com/user-attachments/assets/a2a34e70-7d01-432b-bf47-83082adbc770)
![Bildschirmfoto 2024-10-14 um 12 03 54](https://github.com/user-attachments/assets/b947d65a-3295-4d3c-a337-7b00edf37d02)

The docs says
[#](https://rappasoft.com/docs/laravel-livewire-tables/v3/columns/styling#content-keep-default-colors-and-default-styles)Keep Default Colors And Default Styles
set default flag to true or
set default-colors flag to true
set default-styling flag to true

i can use default OR the other two, but as shown above the default flag does nothing.

Using 3.4.22 version, but it seems it is in since 3.4.21.

### Package Version

3.4.22

### PHP Version

8.2.x

### Laravel Version

11.27.2

### Theme

Tailwind 3.x

**Comment by mrl22** [comment]
I am having the same issue and diggiting into it, it seems to be an issue with null coalescing.

Looking at this condition in components/table/td.blade.php:

```PHP
($customThAttributes['default-colors'] ?? true || $customThAttributes['default'] ?? true)
```

We would assume that if either 'default-colors' or 'default' equals true, it will return true, but with the null coalescing (??) and the lack of an additional set of brackets, it will always return false unless both values are true.

It should be changed to:

```PHP
(($customThAttributes['default-colors'] ?? true) || ($customThAttributes['default'] ?? true))
```

The same for 'default-styling'.

I am not the best with pull-requests, but I will test this change and try to push it.

If I am unable to fix, atleast it points @Kell in the right direction.

**Comment by lrljoe** [comment]
Closing as recent PRs suggest this should be fixed, please let me know/reply if this is not the case.
