### ISSUE TITLE
[Bug]: Problem to Export PDF

### ISSUE THREAD

**Issue by lucassmacedo** [rappasoft/laravel-livewire-tables#2003]
### What happened?

Hi! I'm trying to export a PDF but the downloads doest start, neither stream. 

### How to reproduce the bug

![image](https://github.com/user-attachments/assets/f2f3c49b-069b-4594-872b-dd0190c84735)
![image](https://github.com/user-attachments/assets/2b06ec07-cd28-4c33-a6a1-285b0935ee6c)
![image](https://github.com/user-attachments/assets/8a8e771f-cde9-42fc-b685-d71dd64ee0c1)

### PHP Version

None

### Theme

None

**Comment by mrl22** [comment]
This is not a bug. You are expecting Livewire to stream the PDF data. 

You should create your PDF and a Laravel route and then redirect to it.

**Comment by lucassmacedo** [comment]
even if a change stream to download, it's doest start the download.

**Comment by mrl22** [comment]
Livewire is not designed to return anything other than HTML and redirects. As explained above, create a route and redirect to it.

**Comment by ahmadrivaldi-arv** [comment]
> even if a change stream to download, it's doest start the download.

this is not a bug as mentioned @mrl22 livewire is not designed to return anyting other than HTML

just create your own route inside web.php for example

```php

//web.php

Route::get('export-pdf',[ExportController::class,'export'])->name('export-pdf')
```

```php

class YourController extend Controller{

public function export()
{
       $pdf = Pdf::loadView('your-pdf-view',[]);

        return $pdf->stream(); //stream or use $pdf->download()
}

}
```
and inside your bulk actions should be like this

```php

//YourTableComponent.php
public function pdf()
{
     $this->redirect(route('export-pdf'))
}

```
