### ISSUE TITLE
[Bug]: Translations don't apply

### ISSUE THREAD

**Issue by G4Zz0L1** [rappasoft/laravel-livewire-tables#2029]
### What happened?

I think the current format of the translations has some issues, judging by the screenshots provided below.

I've noticed this problem in the last two versions (starting from v3.4.21 onward). I managed to make them work by removing all instances of `livewire-tables::` from the views and only keeping the strings themselves. (I’d also add that the search string is missing from the views and is hardcoded in a file within the vendor folder, but it can be modified using the `setSearchPlaceholder` method.)

However, with this approach, the translations only work in English, and they don’t translate to other languages, and I have no idea why.

Would it be possible to manage the translations in .php files, like other packages already do? This way, we could avoid conflicts (since each lang folder would use the vendor’s name) and possibly face fewer issues than with the JSON format.

Thanks in advance!

![image](https://github.com/user-attachments/assets/16abb0df-253e-4b06-b00c-69020f21ef30)
![image](https://github.com/user-attachments/assets/5663f6df-afa9-400e-92bc-76e0428be4fc)
![image](https://github.com/user-attachments/assets/77bc5d38-0289-4724-8dca-a0e0871507f3)

### Package Version

3.4.22

### PHP Version

8.3.x

### Laravel Version

11.30.0

### Alpine Version

3.14.3

### Theme

Tailwind 3.x

**Comment by lrljoe** [comment]
Yeah, I've been back and forth on localisation approach a number of times.

Think you may be right and migrating back from json to php files may ultimately be the smoothest transition.


I'll look into it after the next release

**Comment by lrljoe** [comment]
So I've released 3.5.0

I've started migrating everything back to the older PHP file approach.

What I'll do before I continue however - is reach out to anyone who's localised, and ensure any/all strings are still current/correct.

Will reach out to everyone I have contact info for over next few days, and will then see where we are in terms of coverage. While it's not necessarily related, it's a good opportunity to ensure as many localisation strings are covered off, and I can then list what's actually natively 100% covered.

**Comment by lrljoe** [comment]
Presently working on migrating BACK to PHP files

**Comment by tahirrasheed208** [comment]
<img width="649" alt="Screenshot 2024-11-09 at 1 58 53 PM" src="https://github.com/user-attachments/assets/31ecda69-3d5f-4e79-a28a-ca42e10c6e48">

Translations are also not working when reorder records

**Comment by lrljoe** [comment]
@tahirrasheed208  - let me know when you're available (ideally on the official Discord), I have a fix that I'm going to merge into development shortly, but would appreciate feedback.

**Comment by lrljoe** [comment]
This is in the development branch now, but I need to do some further testing, and validation of any missing translation keys.

**Comment by tahirrasheed208** [comment]
Yes, now I see the development branch. Thanks! Waiting for the official version release

**Comment by lrljoe** [comment]
Should be released now!

**Comment by lrljoe** [comment]
I have noticed quite a few gaps, which I'll need to get the localisation contributors to update.  Hoping to have a workflow for that in the next few days.
