### ISSUE TITLE
Conflict between bulk actions and clickable rows

### ISSUE THREAD

**Issue by nguillaumin** [rappasoft/laravel-livewire-tables#204]
When a row is made clickable by providing a URL (`getTableRowUrl()`), it also includes the first dummy column that contains the checkbox used for bulk actions. As a result, clicking on the checkbox just navigates away from the page, rather than just ticking the box.

Possible fix ideas:
- Make each cell (except the first one) clickable rather than the whole row
- Alternatively convert the column texts to links (`<a>`) rather than use Javascript events

**Comment by rappasoft** [comment]
Oof. Alright thanks I'll try to fix it tonight.

**Comment by nguillaumin** [comment]
No worries, no rush from me since I'm not using the provided Tailwind / Bootstrap 4 views anyway.

**Comment by rappasoft** [comment]
Pretty sure a `stopPropagation()` on the left side checkbox will work. Going to try now.

**Comment by rappasoft** [comment]
Yeah that works, i'll send a patch. The only issue is, if you miss the checkbox and hit the cell, it will still follow the URL. But this patch works while I think of another solution.

Thanks for finding all these new release bugs.

**Comment by rappasoft** [comment]
Fixed! Thanks.

**Comment by nguillaumin** [comment]
Thanks. I wonder if the approach needs reviewing, as it would also cause problems if you put buttons inside the table (like a "delete" button for each row).

**Comment by rappasoft** [comment]
Yeah, it might be a trade-off right now, I can't think of a better way to do it without having the user implement it for each cell.
