### ISSUE TITLE
[Bug]: setDefaultPerPage don't work, fallback always to the first in setPerPageAccepted

### ISSUE THREAD

**Issue by nickurt** [rappasoft/laravel-livewire-tables#2050]
### What happened?

I can't set the defaultPerPage anymore for my DataTables (nothing in my session), it always fallbacks to the first option of the setPerPageAccepted (for me, 10 instead of 25).

Looks like this part of code is affected - https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Traits/WithPagination.php#L58-L65

### How to reproduce the bug

```php
public function configure(): void
{
    $this->setPerPageAccepted([10, 25, 50, 100])->setDefaultPerPage(25);
}
```

When I'm using this, the page always shows me 10 results instead of the default 25, while I have nothing in my session for per/page value.

### Package Version

3.5.0

### PHP Version

8.3.x

### Laravel Version

11.30.0

### Alpine Version

3.14.3

### Theme

Tailwind 3.x

**Comment by ahmadrivaldi-arv** [comment]
Have you tried clearing the cache?

```bash
php artisan optimize:clear
```

**Comment by lrljoe** [comment]
Have found the issue, just need to fix, and add a couple of tests to ensure that it doesn't come up again in the future.

Should be released this weekend

**Comment by lrljoe** [comment]
Linking PR for the relevant branch (fix in progress)

**Comment by nickurt** [comment]
Thank you, it worked.
