### ISSUE TITLE
Searching should reset pagination?

### ISSUE THREAD

**Issue by nguillaumin** [rappasoft/laravel-livewire-tables#207]
Currently the pagination is not reset when a search is made, meaning that if there are less results than the current page you are seeing, the "no results" message is shown. Manually resetting the pagination (by removing the `page` URL parameter for example) fixes it.

Is that expected? Should searching always reset the current page? I suspect that would be the behavior expected by most users.

**Comment by rappasoft** [comment]
Yes you're right I forgot to port that over from the last version. Will add.

**Comment by rappasoft** [comment]
Fixed: https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Traits/WithFilters.php#L23
