### ISSUE TITLE
[Bug]: Restore Support for Custom Translations via Override if Published

### ISSUE THREAD

**Issue by Mariosueiro** [rappasoft/laravel-livewire-tables#2070]
### What happened?

In version v3.5.2 of the project, the change "Migrate Localisations back to PHP Files from JSON" (#2040) removed the functionality to **override custom translations** by deleting the following code snippet:

_

> // Override if Published
> $this->loadJsonTranslationsFrom(
>     $this->app->langPath('vendor/livewire-tables')
> );

_

Previously, this code allowed developers to load their own custom translations by overriding the default published JSON translations. Removing this functionality has made it impossible to easily use custom translations, negatively affecting projects relying on this behavior.

### How to reproduce the bug

**

> // Override if Published
> $this->loadJsonTranslationsFrom(
>     $this->app->langPath('vendor/livewire-tables')
> );

**

### Package Version

3.5.2

### PHP Version

None

### Theme

None

### Notes

- Developers who customize translations can no longer use their own JSON files to override the defaults.

- This breaks established workflows where published translations are modified to meet project-specific requirements.

**Comment by lrljoe** [comment]
Hi @Mariosueiro 
- you can still publish them, but they're back in the traditional PHP/Array format now (which was used up until a few months ago).

The reason behind this reversion back to, is that there were conflicts being reported (for example - "Columns", "Cancel", "Clear".

I did consider supporting both approaches, but that seemed like a chunk of overkill/overhead.

**Comment by lrljoe** [comment]
Hi @Mariosueiro - this should now be available in the "development" branch.

It adds in a new option into the "config/livewire-tables.php" file
```
    /**
     * Use JSON Translations instead of PHP Array
     */
    'use_json_translations' => false,

```

If you set

```
    /**
     * Use JSON Translations instead of PHP Array
     */
    'use_json_translations' => true,

```

Then it will use the JSON files instead of the PHP files.

Please let me know if this remediates your issue, before I merge it and release.

**Comment by Mariosueiro** [comment]
Hi @lrljoe ,

I just tried it out, and it works perfectly! This is super helpful, especially since I’ve customized my views, and using JSON translations fits really well with my setup.

Thanks so much for adding this and for the quick turnaround! 🙌

**Comment by lrljoe** [comment]
> Hi @lrljoe ,
> 
> I just tried it out, and it works perfectly! This is super helpful, especially since I’ve customized my views, and using JSON translations fits really well with my setup.
> 
> Thanks so much for adding this and for the quick turnaround! 🙌

v3.5.4 released with this fix in it :)

**Comment by lrljoe** [comment]
Let me know if issue still persists
