### ISSUE TITLE
[Bug]: setDisplayPaginationDetailsDisabled is not respected when table is not paginated

### ISSUE THREAD

**Issue by leesherwood** [rappasoft/laravel-livewire-tables#2118]
### What happened?

Hiding the `Showing 1 to 10 of 25 results` text via `setDisplayPaginationDetailsDisabled()` works fine, however when the table content isn't enough to need multiple pages the text `Showing 8 results` appears. 

I would expect `setDisplayPaginationDetailsDisabled` to cover both instances, hence the bug report

### How to reproduce the bug

- Create a demo table with `setDisplayPaginationDetailsDisabled()` 
- Decrease (if needed) the `perPage` to have at least 2 pages, notice that the `Showing...` text does not show as expected
- Increase the `perPage` so it's a single page table, notice now the `Showing` text does show.

_You can also just apply a search to bring the page count down to 1._

### Package Version

3.5.7

### PHP Version

8.2.x

### Laravel Version

11

With pagination - No "details" displayed
<img width="1105" alt="image" src="https://github.com/user-attachments/assets/e6419ea5-2a55-4a2b-9b2f-10d57a3d5940">

Without pagination - Details displayed
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/78e0f94f-3ebd-4c9f-837b-a3fd49b95946">

**Comment by lrljoe** [comment]
Should be a relatively simple fix, will sort it this weekend

**Comment by lrljoe** [comment]
Have created a PR that fixes this, just need to validate tests etc

**Comment by lrljoe** [comment]
@leesherwood - If you have a development environment, please test the "development" branch, as the fix is in there.

**Comment by leesherwood** [comment]
@lrljoe Tested and it now works as expected.

When `setDisplayPaginationDetailsEnabled()`

- [x] Text displayed on single-page tables
- [x] Text displayed on multi-page tables
- [x] Text displayed when searching
- [x] Text displayed when filtering

When `setDisplayPaginationDetailsDisabled()`

- [x] Text **not** displayed on single-page tables
- [x] Text **not** displayed on multi-page tables
- [x] Text **not** displayed when searching
- [x] Text **not** displayed when filtering
