### ISSUE TITLE
Custimize table header

### ISSUE THREAD

**Issue by nguyendungpc191** [rappasoft/laravel-livewire-tables#226]
I trying to make a checkbox in header table for check all checkbox function. But I have no idea to add a input type checkbox to header. 
![image](https://user-images.githubusercontent.com/37953399/115811573-28782700-a41a-11eb-9a25-58599deebe19.png)
![image](https://user-images.githubusercontent.com/37953399/115811644-480f4f80-a41a-11eb-9b6c-11e4e91d7ae9.png)
![image](https://user-images.githubusercontent.com/37953399/115811692-5fe6d380-a41a-11eb-99e1-a9d0c371194f.png)

**Comment by rappasoft** [comment]
Check all checkbox is built in if you create a bulk action. It will show up as the first column. There is no other solution currently to add additional checkboxes to headers.

**Comment by nguyendungpc191** [comment]
Thank you @rappasoft
