### ISSUE TITLE
Undefined index: showSearch AND primaryKey

### ISSUE THREAD

**Issue by hemant17** [rappasoft/laravel-livewire-tables#227]
![image](https://user-images.githubusercontent.com/10548023/115821737-f5856180-a420-11eb-9a0a-440fb93ec22f.png)
No error in frontend on search but in Laravelog  it's getting this error lot's of time where ever you search

` public function query(): Builder
    {
        return Order_table::where('user_id', auth()->user()->id)->when(
            $this->getFilter('search'),
            fn ($query, $term) =>
            $query->where('custom_tags', 'like', $term . '%')
                ->orWhere('app_type', 'like', $term . '%')
        );
    }
`
after update to latest its also showing now The primary key error 
![image](https://user-images.githubusercontent.com/10548023/115871080-b6c1cc80-a45d-11eb-9735-bf2824c71f5c.png)
getting a lot of them

**Comment by rappasoft** [comment]
If you published the views, try re-publishing. Also make sure you cleared all the caches.

**Comment by hemant17** [comment]
i did but still the same - lot's of primary key error

**Comment by hemant17** [comment]
I think it coming when the table load by Event or refresh by the livewire event function 
you old  table was working fine in my project since its launches but not it's giving 100+ error in logs

**Comment by rappasoft** [comment]
Can not re-create this issue.

**Comment by hemant17** [comment]
so what bro? i have got 5000 errors so far  -  what the use of this - primaryKey? 
i need the solution because it's really slowing down my project- 
it was fine before but when I upgraded to latest it getting lots of error

**Comment by bdelamatre** [comment]
The screenshots you provided are not enough information to troubleshoot and aren't of this codebase. 

Provide more information included code that can be used to reproduce the error and/or stack traces pointing to this code base.

**Comment by rappasoft** [comment]
Yeah, there is literally no way to help you with the information you provided.
