### ISSUE TITLE
Translations removed?

### ISSUE THREAD

**Issue by simonbuehler** [rappasoft/laravel-livewire-tables#228]
hi.

somehow the lang files are missing, or am i missing something?

**Comment by rappasoft** [comment]
Hi, there are no lang files in this one yet but all of the text is wrapped in lang helpers so you could make .json lang files from those keys. I don't have them listed out yet.

**Comment by rappasoft** [comment]
@bdelamatre do you see any problem doing translations [with a json file](https://github.com/rappasoft/laravel-livewire-tables/commit/eae413c942a10ea1b55aa63cc29aed75d5d41a6b) over the traditional `@lang('livewire-tables::lang.key')` method that is still in the package dev docs. I like json files better, but I've never used them in a package.

**Comment by rappasoft** [comment]
Added a json file.

**Comment by bdelamatre** [comment]
I don't have a strong opinion.Thanks for checking though!
