### ISSUE TITLE
cool-gray is not available in tailwind 2

### ISSUE THREAD

**Issue by simonbuehler** [rappasoft/laravel-livewire-tables#229]
hi,

i guess eg `text-cool-gray-500` and others are failing but should be coolGray or gray ( defaults to cool gray) instead so the styles are applied

**Comment by rappasoft** [comment]
You're right I have a tailwind file with them configured. I'll swap them out for base colors soon but until then you can alias coolGray to cool-gray like I have.

**Comment by rappasoft** [comment]
Fixed
