### ISSUE TITLE
datatable labels translation

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-livewire-tables#24]
Hi,

how to make translation for statistics under the datatable ?

1- Showing 1 to 12 out of 12 results
2- Per Page
3- Search

thank you

**Comment by rappasoft** [comment]
You can change the  `$searchLabel` `$perPageLabel` and write a lang file for the last one: https://github.com/rappasoft/laravel-livewire-tables/blob/master/resources/views/includes/_pagination.blade.php#L8
