### ISSUE TITLE
Column Relationship

### ISSUE THREAD

**Issue by mentiantonio** [rappasoft/laravel-livewire-tables#258]
I have this on users model

public function addresses()
{
return $this->hasMany(Address::class);
}

Inside my table component i have

public function query(): Builder
{
return User::with('addresses');
}

but i don't see the related column on the view

Column::make('Phone', 'addresses.phone')

What i am doing wrong?

**Comment by bdelamatre** [comment]
I am not sure someone has tested this scenario.

What behavior would you expect to see with a HasMany relationship mapped to a column?

**Comment by mentiantonio** [comment]
you are right! With HasOne relation, the column appear!
