### ISSUE TITLE
Filter with value "0" clears out the filter.

### ISSUE THREAD

**Issue by shawnholman** [rappasoft/laravel-livewire-tables#265]
Hey! There is a bug when selecting filters. Whenever creating a filter with options where one option's value is "0" selecting that filter will cause the "All" selection to be used.

```
public function filters(): array
    {
        return [
            'deaf_blind_project_exiting_status' =>
                Filter::make('Status')
                    ->select([
                        '' => 'Any',
                        0 => 'Option 1',
                        1 => 'Option 2',
                        2 => 'Option 3',
                    ]),
        ];
    }
```
    
The following code will create a filter with four options: Any, Option 1, Option 2, and Option 3. Selecting 'Option 1', gives the same filtering results as just selecting "Any".

**Comment by rappasoft** [comment]
Can recreate. Will try to fix.

**Comment by shawnholman** [comment]
Thank you! This has been a really useful project for me. I really appreciate the recent updates that you have done. Keep up the great work!

**Comment by rappasoft** [comment]
This is apparently more complicated than anticipated since zero in PHP pretty much becomes false in any check. I have to modify the way filters work in general to support numeric keys or string keys that are numbers. @bdelamatre worked on a lot of filters maybe he has a better way.

**Comment by rappasoft** [comment]
Fixed in latest release.
