### ISSUE TITLE
Fast bulk selecting leads to problems

### ISSUE THREAD

**Issue by spekulatius** [rappasoft/laravel-livewire-tables#266]
Hello @rappasoft 

I've noticed there is an issue when bulk selecting items too fast:

https://user-images.githubusercontent.com/8433587/116844880-6b45b600-abf5-11eb-9eff-e06422af6485.mp4

It looks like the call the backend is too slow. Maybe it needs to be decoupled to work more reliable?

Cheers,
Peter

**Comment by rappasoft** [comment]
Not sure if there's too much I can do, if I add a defer then the row showing how many are selected never shows up.

I added a disabled delay on develop, see if that makes a difference for you: https://github.com/rappasoft/laravel-livewire-tables/commit/ab927ca6431ebf6df5b30efac64294408ba06909

**Comment by spekulatius** [comment]
I've tried the current develop branch and it made the selecting more reliable. I'll keep the branch to see how it's going. Thank you.
