### ISSUE TITLE
Pagination questions

### ISSUE THREAD

**Issue by molnarjg** [rappasoft/laravel-livewire-tables#268]
Using 1.5.1 with Tailwind seems like these properties have no effect:

```
public bool $showPagination = false;
public int $perPage = 6;
```

Overwriting `$perPage` in the **_WithPerPagePagination_** trait works, should work via overwriting the property too:

    public function mountWithPerPagePagination(): void
    {
        ...
        } else {
            $this->perPage = 6;
        }
    }

$showPagination is an unused property. What would be the purpose of it?

With TW it shows duplicated pagination, would be good to be able to switch off each of them, maybe via **$showPagination** ?
![image](https://user-images.githubusercontent.com/48017129/116877255-cfa65b00-ac71-11eb-8c27-02e6cbf23a2d.png)

Thank you.

**Comment by rappasoft** [comment]
showPagination is definitely unused, I don't remember if we took it out of the templates for some reason. But perPage seems to be working fine for me:

```php
public array $perPageAccepted = [1,2,4];
public int $perPage = 2;
```

<img width="1792" alt="Screen Shot 2021-05-03 at 09 00 25" src="https://user-images.githubusercontent.com/6026504/116878945-05a1fb80-abee-11eb-8db4-3cca75f7b90d.png">

**Comment by rappasoft** [comment]
Added missing showPagination conditional to views: https://github.com/rappasoft/laravel-livewire-tables/commit/c99e8351d4f69fcaa566e7d39734a85bc52c2cfb

**Comment by molnarjg** [comment]
No, I haven't published the default pagination views, also the mount method is not overridden. My Componenet looks like this:

```
<?php

namespace App\Http\Livewire\Frontend\Inquiries;

use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\Views\Filter;
use App\Models\User;

class Index extends DataTableComponent
{
    public bool $paginationEnabled = true;
    public bool $showPerPage = false;
    public bool $showPagination = false;
    public int $perPage = 6;
    
    protected string $pageName = 'users';
    protected string $tableName = 'users';

    public function filters(): array
    {
        return [
            'verified' => Filter::make('E-mail Verified')
                ->select([
                    '' => 'Any',
                    'yes' => 'Igen',
                    'no' => 'Nem',
                ]),
        ];
    }

    public function columns(): array
    {
        return [
            Column::make('Nev', 'name')
                ->sortable()
                ->searchable(),
            Column::make('E-mail', 'email')
                ->sortable()
                ->searchable(),
            Column::make('Validalt?', 'email_verified_at')
                ->sortable(),
        ];
    }

    public function query(): Builder
    {
        return User::query()
            ->when($this->getFilter('search'), fn ($query, $search) => $query->search($search))
            ->when($this->getFilter('name'), fn ($query, $name) => $query->where('name', $name))
            ->when($this->getFilter('verified'), fn ($query, $verified) => $verified === 'yes' ? $query->whereNotNull('email_verified_at') : $query->whereNull('email_verified_at'));
    }

    public function rowView(): string
    {
        return 'frontend.inquiries.index-row';
    }
}


```


I cannot find any reason why can I see the duplicated paginations.
Also the perPage works still only in case I overwrite the WithPerPagePagination trait. :(

**Comment by molnarjg** [comment]
Update: Now as I published the livewire paginations, the duplication is gone.

The $perPage issue has something to do with the trait's  session if clause:
![image](https://user-images.githubusercontent.com/48017129/116968295-53ab2200-ad08-11eb-8b28-653d415df0fd.png)

**Comment by molnarjg** [comment]
Update: 

With the livewire paginations published having these two properties overwritten, the custom $perPage works:

```
    public int $perPage = 6;
    public array $perPageAccepted = [6];
```
