### ISSUE TITLE
Losing CSS

### ISSUE THREAD

**Issue by stonkeep** [rappasoft/laravel-livewire-tables#269]
The component is losing css when 
![image](https://user-images.githubusercontent.com/3990028/116922231-71ef2000-ac2b-11eb-9bad-a2ad07b70e84.png)

**Comment by rappasoft** [comment]
What?

**Comment by stonkeep** [comment]
Forget, my mistake

**Comment by oldprettyclementine** [comment]
> Forget, my mistake

What was your mistake? I think I have the same problem with my ButtonGroupColumns in Laravel 9 Jetstream. Everything works and shows as it should, except the button style, no coloring is working. 

Yesterday I set it up in Laravel 9 Breeze without problems. Last week on Laravel 8, no problem. All with the same tailwind CSS and classes as before.

**Comment by TheFredRoger** [comment]
@oldprettyclementine did you find a solution? I've the exact same problem with Laravel 9 Jetstream and will be very interested in any clues for a solution. :)
