### ISSUE TITLE
searching in rendered view column

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-livewire-tables#27]
i think that search operation done in model retrived data from database, but when using view in column mean that additional data added inside the column that not retrived from database, is there a way to make search operation affect in rendered view column?

**Comment by rappasoft** [comment]
Pass a closure:

```
->searchable(function($builder, $term) {
                return $builder->orWhereHas('permissions', function($query) use($term) {
                   return $query->where('name', 'like', '%'.$term.'%');
                });
            }),
```

**Comment by abdosaeedelhassan** [comment]
thank you for response, i mean that view like next

@if($row->enabled==1)
    Yes
@else
    No
@endif

then search with Yes or No

also if view that contain data given from relation like next

{{ $row->serviceproviders->users->full_name }}

**Comment by abdosaeedelhassan** [comment]
in first case i did as next

->searchable(function ($builder,$term){
                    if (strpos(__('labels.general.yes'), $term) !== false) {
                        return $builder->where('published',1);
                    }else if (strpos(__('labels.general.no'), $term) !== false){
                        return $builder->where('published',0);
                    }
                    return $builder->OrWhere('published',$term);
                })

it worked, in second case i did as next


->searchable(function ($builder,$term){
                    return $builder->OrWhereHas('serviceproviders',function ($query)use($term){
                        return $query->OrwhereHas('users',function ($q)use($term){
                            return $q->where('first_name', 'like', '%'.$term.'%');
                        });
                    });
               })

but not worked and return all data at all
