### ISSUE TITLE
tap into the sort query bug

### ISSUE THREAD

**Issue by molnarjg** [rappasoft/laravel-livewire-tables#278]
According to the original post:

![image](https://user-images.githubusercontent.com/48017129/117577709-fe737400-b13e-11eb-89e9-744cd5e48971.png)

The current applySorting() needs to be changed from `query `to `builder`

![image](https://user-images.githubusercontent.com/48017129/117577691-eac80d80-b13e-11eb-9162-ae7c1a001f51.png)

It currently ignores the callback with `query`.

_Originally posted by @rappasoft in https://github.com/rappasoft/laravel-livewire-tables/issues/216#issuecomment-823391324_

**Comment by rappasoft** [comment]
The original post was a discussion, the end result ended up being query, which is what's in the documentation. Where's the bug?

**Comment by molnarjg** [comment]
Yes, right, it works according to the docs. Cheers! :)
