### ISSUE TITLE
opening table page after time

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-livewire-tables#28]
next error happen when device screen lock and open again after time, or browser tab swaped to other and come back after medium time
![error](https://user-images.githubusercontent.com/15355610/87851922-af352c00-c8fd-11ea-954f-fdbad2975275.png)

**Comment by KenLewis** [comment]
I think this is an issue with Livewire's handling of session timeout. It was fixed by this PR: https://github.com/livewire/livewire/pull/1146
