### ISSUE TITLE
Add ability to hide a column

### ISSUE THREAD

**Issue by detygon** [rappasoft/laravel-livewire-tables#29]
For now, we must create a new class that extends `Column` and use `CanBeHidden` trait but it would be great if this package  has built-in support.

**Comment by rappasoft** [comment]
When would you need to hide a column?

**Comment by detygon** [comment]
Well, I have a use case where I need to show/hide some columns based on the
user's role or based on the parameters provided in the request.

**Comment by rappasoft** [comment]
Added in the next release
