### ISSUE TITLE
Wrong item count with bootstrap 4 template

### ISSUE THREAD

**Issue by Restingo** [rappasoft/laravel-livewire-tables#319]
When using pagination sometimes when changing pages the "showing x to y" reports the wrong numbers. For example

![image](https://user-images.githubusercontent.com/84022569/120898642-0504e680-c62c-11eb-94e7-9f904d6d5265.png)

![image](https://user-images.githubusercontent.com/84022569/120898645-0a623100-c62c-11eb-86d8-cad524629d8b.png)

but there are only 27 entries in the database.

**Comment by rappasoft** [comment]
Those numbers come right from the Laravel paginator, you're going to need to provide more details because you're the first with this issue so it's likely something in your application.

**Comment by Restingo** [comment]
I'm using latest version of laravel-livewire-tables, laravel/framework v8.37.0, bootstrap 4 theme and table with three columns and default settings. Server is artisan on local development machine. What else do you need?

**Comment by rappasoft** [comment]
You didn't publish and modify [this](https://github.com/rappasoft/laravel-livewire-tables/blob/master/resources/views/bootstrap-4/includes/pagination.blade.php#L9) template? If there was something wrong there would be more words stuck in your numbers since there is "Showing" "to" "of" "results", with no conditionals so they show all the time.

**Comment by mrl22** [comment]
@Restingo is correct, I have tested this and have the same issue. It seems to be when navigating to the last page and back to page 1. No custom templates, standard model with no modifications.

See here: [Screencast](https://www.dropbox.com/s/3azk5v13qgbetgg/screen-recorder-wed-jun-09-2021-11-17-24.webm?dl=0)

My query:

public function query(): Builder
    {
        return User::query();
    }

**Comment by Restingo** [comment]
@rappasoft nope, as @mrl22 said, default templates.

**Comment by rappasoft** [comment]
Interesting I see, I was able to reproduce. I'll have to dig into it.

**Comment by SPQRBrutus** [comment]
I don't know why but its deleting whole row from code in pagination.blade.php
Between <strong>{{ $rows->count() ? $rows->lastItem() : 0 }}</strong> and <strong>{{ $rows->total() }}</strong>
When you use <span>@lang('of')</span> insted of @lang('of') it's start working.

**Comment by rappasoft** [comment]
[Fixed](https://github.com/rappasoft/laravel-livewire-tables/commit/f76838203976f75a23ed84825ee1f095550a9c02)
