### ISSUE TITLE
Component view($view) doesn't work as expected

### ISSUE THREAD

**Issue by Kehet** [rappasoft/laravel-livewire-tables#33]
I'm not entirely sure if this is documentation issue or I'm doing something wrong but when I try something like this

```php
    public function columns(): array
    {
        return [
            Column::make('Actions')
                ->components([
                    Link::make('Delete')
                        ->view('livewire.includes.delete-button'),
                ]),
        ];
    }
```

It throws exception

```
 Call to a member function isHidden() on string
(View: /project/vendor/rappasoft/laravel-livewire-tables/resources/views/includes/_body.blade.php)
(View: /project/vendor/rappasoft/laravel-livewire-tables/resources/views/includes/_body.blade.php)
(View: /project/vendor/rappasoft/laravel-livewire-tables/resources/views/includes/_body.blade.php)
(View: /project/vendor/rappasoft/laravel-livewire-tables/resources/views/includes/_body.blade.php)
```

This seems to be because view() method in [src/Views/Link.php](https://github.com/rappasoft/laravel-livewire-tables/blob/6d3c5d7551adb6452df806a442e43e2b5f8530c3/src/Views/Link.php#L85) actually returns string. However readme is referring this method as it would work like Column's view() and thus would return $this

**Comment by rappasoft** [comment]
The view only works with the column right now.
