### ISSUE TITLE
setting checkboxes to display not working

### ISSUE THREAD

**Issue by rogerad** [rappasoft/laravel-livewire-tables#334]
hi 
i am trying to display checkboxes 
 i have entered this in productsTable.php in livewire directory under http drectory

```
public bool $showPerPage=true;
public bool $checkboxAll= true;
public $checkboxAttribute  = 'id';
    public bool $checkbox = true;
    public $checkboxLocation = 'left';
```
``
NO CHECKBOXES appear

**Comment by rappasoft** [comment]
To get the checkboxes you need to [add a bulk action](https://github.com/rappasoft/laravel-livewire-tables/wiki/Bulk-Actions). Most of those properties are for < 1.0

**Comment by rogerad** [comment]
Hi 
Checkboxes work now
 I think you should update documentation so people know how to create checkboxes

 **Which checkbox properties work ?**

You have selected 50 rows, do you want to select all 4,694? Select All Unselect All


Also can you please set an option that the user can say eg  I do not want to select all rows eg 4694

 I just want to use the selected 50 rows

**Comment by rappasoft** [comment]
Well if they don't click the "Select All" button then you are only selecting those 50 rows, that's what it says. It says clearly in the docs that I linked that the checkboxes show when you create a bulk action. There are no other checkbox properties.

**Comment by rogerad** [comment]
Thank you for the answer

 

Please see my other question thati raised in discussions

Re

 

 

Hi
i am trying to access the selected rowsquery to export to excel - selectedRowsQuery

the docs says
access to $this->selectedRowsQuery which is a Builder instance of the selected rows.

The rows are selected but i cannot get the data from each row


how do i do this ?
