### ISSUE TITLE
Eager loading - $row in Column format method

### ISSUE THREAD

**Issue by Wit3** [rappasoft/laravel-livewire-tables#338]
$row variable passed in callback parameter of method "format" in Column class doesn't load with eager loaded in query builder.

I've fixed with the $with property in Model, but it's a not nice fix.

```
    /**
     * The relationships that should always be loaded.
     *
     * @var array
     */
    protected $with = ['nameOfRelation'];
```

Why $row lost his 'with' eager laoded relation?

**Comment by bomshteyn** [comment]
@Wit3 can you post your Livewire Component (DataTableComponent)?
