### ISSUE TITLE
Sort fields bug when reloading a page with multiple tables

### ISSUE THREAD

**Issue by PaoloCentomani** [rappasoft/laravel-livewire-tables#343]
A page has:

- Table 1 "Users"
- Table 2 "Activities", with a field named `start_time`

Table 2 is manually sorted by its `start_time` field.
The query gets appended to the URL: `?sorts%5Bstarts_at%5D=asc`

If the page is reloaded, a QueryException gets thrown: `Column not found: 1054 Unknown column 'starts_at' in 'order clause'`. The query is from the "Users" table (`select users.*, ...`).

**Comment by rappasoft** [comment]
There are unfortunately many issues with multiple tables per page that I have not got around to figuring out yet. The only thing that works is pagination, everything else will have conflicts with the query string.

**Comment by PaoloCentomani** [comment]
That's a good workaround for my use case. Thank you!

**Comment by rappasoft** [comment]
Good! That's actually an easy solution for now, I may try to figure out a way to handle it with state eventually but I have to work out these other bugs first.
