### ISSUE TITLE
route is run when button is included in product row

### ISSUE THREAD

**Issue by rogerad** [rappasoft/laravel-livewire-tables#371]
i created a button in a row and the link that that was in the button was run when the datatable was created.

 This  is a bug  because i tested the **same button** with **same route link** in a datatable that is **manually created with livewire**- NOT with this package

```here is the button and the link
  <button type="button"
                class='inline-flex items-center h-8 px-4 m-2 text-sm text-green-100 transition-colors duration-150 bg-green-700 rounded-lg focus:shadow-outline hover:bg-green-800'

                onclick='location.href="{{ url('products/edit/'. $row->store_number .'/'. $row->id ) }}";'>Edit
        </button>
```
 i have attached the button with your package and another image of the button on a manually created datatable NOT with the package

**also the image is messed up as well**

the first picture is the package
 the second picture is manually created datatable
<img width="638" alt="rappabutton3" src="https://user-images.githubusercontent.com/18638656/123047961-3d386180-d441-11eb-8e4e-27644f43921f.png">
<img width="647" alt="manual button2" src="https://user-images.githubusercontent.com/18638656/123047973-3e698e80-d441-11eb-8cb6-1fb9d7531e2c.png">

**Comment by rappasoft** [comment]
Why are you using an onclick on a button instead of just a link with a href that looks like a button? What are the benefits? Also, there's definitely just something wrong going on in the first picture.

**Comment by rogerad** [comment]
hi 
 i removed the modal and set the style to tailwind and it worked properly
