### ISSUE TITLE
Problem with filter results - Need to refresh

### ISSUE THREAD

**Issue by lilouch** [rappasoft/laravel-livewire-tables#375]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **lilouch** June 23, 2021</sup>
Hi,

I have implemented a filter that match a specific label.

`->when($this->getFilter('color'), fn ($query, $color) => $query->where('color', $color))`

It works the first time. Then, if I select another color, the results are messed up i.e I have not only this color but others colors labels that are shown. But If I refresh the page, the filter works again.

Also, when there are no results, I have actually the message "No items found. Try narrowing your search.", but I still have some results displayed.

Any ideas why it happens ?

Thank you</div>

**Comment by lilouch** [comment]
I think, I solved the issue. As I was doing a join on my query, I needed to select only specific attributes that would match my table. Now it seems to work.

**Comment by qwasyx0** [comment]
I have the same issue in two use cases:
1. When repopulating table with different query - First query I have 3 results then i run external command on query which returns 0 results. I expect the table to show 0 results, but the table shows 2 results and the last one is switched to no items found message. Pagination still says 0. Every other refresh of the table switches last row to no items found message. For first result of 5 rows, i need to refresh the table 4 times to get only the items not found message.
2. When using the new function user columns added in v1.10 - in combination with sort/filter it completely messes up the table, shown on pictures below, where I tried hiding the first column. 

<img width="1017" alt="table_error" src="https://user-images.githubusercontent.com/43924784/123068115-e36c7300-d411-11eb-949f-b1be935f7095.PNG">
<img width="958" alt="table_error2" src="https://user-images.githubusercontent.com/43924784/123068117-e4050980-d411-11eb-8771-ab8f1854415b.PNG">

**Comment by rappasoft** [comment]
I'm interested in seeing your query methods because I've only tested queries with a single model as that's what it was built around. So there might be issues with something + dom diffing in Livewire.

**Comment by qwasyx0** [comment]
This is my query that displays data in above picture. 

```
return IRSVOZIKY::query()
                ->when($this->getFilter('TYPSTROJE'), fn ($query, $filter) => $query->where('TYPSTROJE', $filter))
                ->when($this->getFilter('ODPOVEDNAOSOBA'), fn ($query, $filter) => $query->where('ODPOVEDNAOSOBA', $filter))
                ->when($this->getFilter('ZNACKA'), fn ($query, $filter) => $query->where('ZNACKA', $filter))
                ->when($this->getFilter('ROKVYROBY'), fn ($query, $filter) => $query->where('ROKVYROBY', $filter))
                ->when($this->getFilter('UMISTENI'), fn ($query, $filter) => $query->where('UMISTENI', $filter))
                ->when($this->getFilter('VOLNYPARAMETR'), fn ($query, $filter) => $query->where('VOLNYPARAMETR', $filter))
                ->where('IDCISELPOD', Auth::user()->IDCISELPOD);
```

Creating columns:
```
 public function columns(): array
    {
        return [
            Column::make('Název stroje', 'TYPVOZIKU')
                ->sortable()
                ->searchable(),
            Column::make('Typ', 'TYPSTROJE')
                ->sortable()
                ->searchable(),
              ...
                ];
    }
```

For filters I use this query:

```
    public function mount()
    {
        $query = IRSVOZIKY::where('IDCISELPOD', Auth::user()->IDCISELPOD)->get();
        $typProSelect = $query->pluck('TYPSTROJE', 'IDA_TYPSTROJE')->unique()->toArray();
        foreach ($typProSelect as $index => $typ) {
            if ($typ)
                $this->typArrayProSelect[$index] = $typ;
        }
        ...
       }
```

And apply them in filters function like this:
```
 public function filters(): array
    {
        return [
           'TYPSTROJE' => Filter::make('Typ')
                ->select($this->typArray),
            ...
               ];
    }
```

The row view code:

```
@if (!$columnSelect || ($columnSelect && $this->isColumnSelectEnabled('TYPVOZIKU')))
<x-livewire-tables::table.cell>
    <div class="tooltip">{{ substr($row->TYPVOZIKU,0,20) }}
        <span class="tooltiptext">{{$row->TYPVOZIKU}}</span>
    </div>
</x-livewire-tables::table.cell>
@endif


<x-livewire-tables::table.cell>
    <select name="typy" class="w-32" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'IDA_TYPSTROJE')">
        <option value="{{ $row->IDA_TYPSTROJE }}">{{ $row->TYPSTROJE }}</option>
        @foreach($typArrayProSelect as $index => $typ)
        <option value="{{ $index }}">{{ $typ }}</option>
        @endforeach
    </select>

</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div> {{ $row->VYROBNICISLO }}
    </div>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <input class="w-24" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'EVCISLO')" type="text" value="{{ $row->EVCISLO }}" maxlength="20">
    </input>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <input class="w-32" type="text" list="odpovedne-osoby" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'ODPOVEDNAOSOBA')" name="osoba" value="{{ $row->ODPOVEDNAOSOBA }}" maxlength="40">
    <datalist id="odpovedne-osoby">
        @foreach($osobyArray as $osoba)
        <option value="{{ $osoba }}">
            @endforeach
    </datalist>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <input class="w-32" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'UMISTENI')" type="text" value="{{ $row->UMISTENI }}" maxlength="50">
    </input>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <input class="w-20" type="number" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'STAVMTH')" value="{{ $row->STAVMTH }}" maxlength="9">
    </input>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <div class="w-12">
        {{ $row->STAVMTHDNES }}
    </div>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <select name="znacky" class="w-32" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'IDA_ZNACKA')">
        <option value="{{ $row->IDA_ZNACKA }}">{{ $row->ZNACKA }}</option>
        @foreach($znackyArrayProSelect as $index => $typ)
        <option value="{{ $index }}">{{ $typ }}</option>
        @endforeach
    </select>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <input class="w-32" wire:change="clickAway($event.target.value ,{{$row->IDSVOZIKY}}, 'VOLNYPARAMETR')" type="text" value="{{ $row->VOLNYPARAMETR }}" maxlength="50">
    </input>
</x-livewire-tables::table.cell>

<x-livewire-tables::table.cell>
    <div class="w-10">
        {{ $row->ROKVYROBY }}
    </div>
</x-livewire-tables::table.cell>

```

And finally the clickAway function that saves new values to database

```
public function clickAway($value, $id, $column)
    {
        try {
            $vozik = IRSVOZIKY::where('IDSVOZIKY', $id)->first();
            $vozik->$column = $value;
            $vozik->save();
        } catch (\Illuminate\Database\QueryException $exception) {
            $errorInfo = $exception->errorInfo;
            session()->flash('error', 'Error: ' . implode("|", $errorInfo));
            return;
        }
        session()->flash('message', 'OK.');
    }
```

Lmk if you need anything else.

**Comment by rappasoft** [comment]
Hmm yeah it's most likely a dom-diff issue with the custom column select in the custom row. Because generally the @if needs to be wrapped in div for livewire to know what to do with it when it changes, but you can't because it's a TD.

There is an event to trigger a refresh, though I don't know if it will work:

https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/DataTableComponent.php#L93

**Comment by qwasyx0** [comment]
The first case I was talking about - think of the left table as invoice and right table as invoice items


<img width="876" alt="zakazky1" src="https://user-images.githubusercontent.com/43924784/123145881-931b0280-d45d-11eb-8e8b-b0cbefdd8ba5.PNG">
<img width="877" alt="zakazky2" src="https://user-images.githubusercontent.com/43924784/123145882-931b0280-d45d-11eb-8b46-c95ec848b482.PNG">
<img width="876" alt="zakazky3" src="https://user-images.githubusercontent.com/43924784/123145878-91e9d580-d45d-11eb-9555-757bfbc15083.PNG">

Invoice (left) table query, parameters in whereBetween come from date picker at the top left in the image

```
return IROZAKAZKAHLA::query()
               ->where('IDCISELPOD', Auth::user()->IDCISELPOD)
               ->where('IDSVOZIKY', $this->idsvoziky)
               ->whereBetween('VYKRYTI', [$this->datumOd, $this->datumDo]);
```

The custom row View:

```
<x-livewire-tables::table.cell>
    <button class="text-blue-500" type="button" wire:click="clickDetailZakazky({{$row->IDOZAKAZKAHLA}}, {{ $row->ZAKAZKAS }})"> {{ $row->ZAKAZKAS }}
    </button>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div>
        {{ Carbon\Carbon::parse($row->DATUMVYST)->format('d. m. Y')  }}
    </div>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div> {{ Carbon\Carbon::parse($row->VYKRYTI)->format('d. m. Y')  }}
    </div>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div> {{ number_format(ceil(floatval($row->NAKLAD)), 0, ',', ' ') }} Kč
    </div>
</x-livewire-tables::table.cell>
```

The function that emits which data to display in right table (parameter is PK of chosen invoice to display invoice items):

```
    public function clickDetailZakazky($idozakazkahla)
    {
        $this->idozakazkahla = $idozakazkahla;
        $this->emit('detailZakazky', $idozakazkahla);
    }
```

The right (invoice items) table query, parameter is from the invoice table, refresh is made after changing $this->idozakazkahla:

```
return IROZAKPOLSKUT::query()
                ->where('IDOZAKAZKAHLA', $this->idozakazkahla);

```

Refresh triggered when listening to emitted event from right table:
```
protected $listeners = [
        'detailZakazky'
    ];
    public function detailZakazky($idzak)
    {
        $this->idozakazkahla = $idzak;
        $this->render();
    }
```

The custom row view of right table:

```
<x-livewire-tables::table.cell>
   <div>{{ $row->TEXT }}</div>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div>
        {{ $row->CELKKS }}
    </div>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div> {{ $row->MJ }}
    </div>
</x-livewire-tables::table.cell>
<x-livewire-tables::table.cell>
    <div> {{ number_format(ceil(floatval($row->CELKKCPROD)), 0, ',', ' ') }} Kč
    </div>
</x-livewire-tables::table.cell>

```

Lmk if you need anything else.

**Comment by rappasoft** [comment]
If you turn off column select do you have the same issues?

**Comment by qwasyx0** [comment]
Actually no, I just found out that after i composer updated to new version, my filters stopped working (filtering returns 5 rows, table still shows whole 9 unfiltered, some twice.
<img width="866" alt="zakazky1" src="https://user-images.githubusercontent.com/43924784/123149610-ba73ce80-d461-11eb-826a-ec504937174c.PNG">
<img width="876" alt="zakazky2" src="https://user-images.githubusercontent.com/43924784/123149608-b9db3800-d461-11eb-9969-32bef566e7dd.PNG">

**Comment by rappasoft** [comment]
That may be due to a change in the view files of the package, you might have to delete and re-publish. I don't even recommend changing them locally with how often they change.

**Comment by qwasyx0** [comment]
Nope just deleted the views and published them again, same behavior.

**Comment by rappasoft** [comment]
Hmm, I had no issues with filters across my versions. It's hard to say since your table is so complex and I didn't really test with anything that complex. As complicated as I got was the advanced example in the wiki. Minus the filters, all the UI issues look like they are dom-diffing issues, but I can't be sure. I'm curious to know exactly what it is and if it's something I have to fix though.

**Comment by rappasoft** [comment]
This is 1.10.x with filters working as they should: https://tables.laravel-boilerplate.com/tailwind?filters%5Bactive%5D=yes

**Comment by qwasyx0** [comment]
I gutted the table as much as I could and the issue is still there, I'm not even using custom row view.
<img width="876" alt="zakazky1" src="https://user-images.githubusercontent.com/43924784/123152796-41767600-d465-11eb-9853-b29d81234da2.PNG">

The component:
```
<?php

namespace App\Http\Livewire\Stroje;

use App\Models\Remote\IRSVOZIKY;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\Views\Filter;
use Rappasoft\LaravelLivewireTables\DataTableComponent;

class PrehledStrojuTable extends DataTableComponent
{
    public $volnyParametrArray;
    public array $perPageAccepted = [5, 10, 20, 50, 100, 200, 500];
    public bool $perPageAll = true;
    public String $emptyMessage = "Načítám data...";


    public function mount()
    {
        $query = IRSVOZIKY::where('IDCISELPOD', Auth::user()->IDCISELPOD)->get();
        $volnyParametrArray = IRSVOZIKY::where('IDCISELPOD', Auth::user()->IDCISELPOD)->get()->pluck('VOLNYPARAMETR')->unique()->toArray();
        $this->volnyParametrArray[''] = "Vše";
        foreach ($volnyParametrArray as $index => $param) {
            if ($param) {
                $this->volnyParametrArray[$param] = $param;
            }
        }
    }

    public function filters(): array
    {
        return [
            'VOLNYPARAMETR' => Filter::make('Volný parametr')
                ->select($this->volnyParametrArray),
        ];
    }

    public function columns(): array
    {
        return [
            Column::make('Volný parametr třídění', 'VOLNYPARAMETR')
                ->sortable()
                ->searchable(),
        ];
    }

    public function query(): Builder
    {
        return IRSVOZIKY::query()
            ->when($this->getFilter('VOLNYPARAMETR'), fn ($query, $filter) => $query->where('VOLNYPARAMETR', $filter))
            ->where('IDCISELPOD', Auth::user()->IDCISELPOD);
    }
}
```
dd($this->volnyParametrArray); is:

```
array:4 [▼
  "" => "Vše"
  "elektro" => "elektro"
  "diesel" => "diesel"
  "ruční" => "ruční"
]
```

**Comment by rappasoft** [comment]
Looks fine to me. What do you get if you dump the filter value in the query?

**Comment by qwasyx0** [comment]
dd($this->getFilter('VOLNYPARAMETR'));
"diesel"

**Comment by rappasoft** [comment]
What if you tried this:

```php
public function query(): Builder
    {
        return IRSVOZIKY::query()
            ->where('VOLNYPARAMETR', 'diesel')
            ->where('IDCISELPOD', Auth::user()->IDCISELPOD);
    }
```

Does it give you the correct results?

**Comment by qwasyx0** [comment]
Yes it does.

So I created a new project and made this minimal table and I found out that when using mysql everything works fine, but I'm working with Firebird database using harrygulliford/laravel-firebird package.

v1.8.0
On mysql everything works fine just like in your demo
On firebird everything works fine just like in your demo

v1.10.4
On mysql everything works fine just like in your demo
On firebird sorting is broken, showing all previous rows instead actual row count. Combining with user columns breaks it even more as seen in pictures.

Switching database connection is the only thing I'm doing. Query get() method returns the same result for both drivers in both database drivers queries. Downgrading back to v1.8 fixes the problem. 

Since I started with livewire like a month ago I don't really know what happens under the hood but my bet is the dom-diff thing you talked about since on server side everything look fine, but client is broken.

I have no choice but to work with firebird driver which maybe adds something to the query thats different from mysql that results in bad client side rendering.

**Comment by rappasoft** [comment]
I've never used firebird so I can't be much help, but looking at the diff I don't see anything that would cause this, though it has to be in there: https://github.com/rappasoft/laravel-livewire-tables/compare/v1.8.0...v1.10.4

**Comment by pieterschreuder** [comment]
I had the same problem, because the wire:key of the table row was not available/not unique (because of a primary key other than the default 'id').

After I set the $primaryKey attribute in the DataTableComponent, the problem was solved (in my case). Maybe this is helpful for you as well?

**Comment by qwasyx0** [comment]
Could you please give me example? I don't know how to use $primaryKey with custom row view.

**Comment by pieterschreuder** [comment]
See this page: https://github.com/rappasoft/laravel-livewire-tables/wiki/The-primary-key

You have to make sure to have:
1. $primaryKey set in your DataTableComponent (if it isn't default 'id')
2. the primary key available in your query

I think your problem is the second, you only load the 'user'-column in your query.

**Comment by betterrx-developers** [comment]
I had a similar issue and adding a unique wire:key to the tbody tag fixed it.
`<tbody wire:key="{{ uniqid() }}">`

**Comment by cby016** [comment]
I had a similar issue and adding a unique wire key to the table body fixed it.
`<tbody wire:key="{{ uniqid() }}">`

**Comment by salmanjaveed** [comment]
> I had a similar issue and adding a unique wire key to the table body fixed it. `<tbody wire:key="{{ uniqid() }}">`

I had the same issue with livewire and a simple table render on the blade file, and adding wire:key uniquid() worked for me.
