### ISSUE TITLE
Not able to install package into laravel 8

### ISSUE THREAD

**Issue by sunilit42** [rappasoft/laravel-livewire-tables#376]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rappasoft/laravel-livewire-tables[v1.10.0, ..., v1.10.4] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires rappasoft/laravel-livewire-tables ^1.10 -> satisfiable by rappasoft/laravel-livewire-tables[v1.10.0, ..., v1.10.4].

**Comment by qwasyx0** [comment]
If you have this in composer.json, you should be able to install it.
"require": {
        "php": "^7.3|^8.0",
        "laravel/framework": "^8.40",
        "livewire/livewire": "^2.4",
        "rappasoft/laravel-livewire-tables": "^1.7"
         ...
    },

**Comment by rappasoft** [comment]
I have this package installed on a few Laravel 8 projects running PHP 8.

**Comment by sunilit42** [comment]
Sorry my laravel version is 7.14.1

**Comment by rappasoft** [comment]
If you are using <8 it will not work. I can look to see if we can support 7 in the near future.

**Comment by sunilit42** [comment]
thanks but getting 
- rappasoft/laravel-livewire-tables[v1.10.0, ..., v1.10.4] require illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by rappasoft** [comment]
That means you're not running Laravel 8
