### ISSUE TITLE
Allow column filter callbacks to rename their parameter

### ISSUE THREAD

**Issue by natepisarski** [rappasoft/laravel-livewire-tables#381]
(**Originally posted as a discussion accidentally - feel free to delete.** It got posted there because I marked it 'Feature' instead of bug since this is technically working as expected.

<div type='discussions-op-text'>

<sup>Originally posted by **natepisarski** June 29, 2021</sup>
This request is for letting users of this package rename the parameter in the Filter callback for columns.

The root cause of the issue appears to be [this line](https://github.com/rappasoft/laravel-livewire-tables/blob/1c83a63e0670ea0705021a73f07af5d84d0d8f0c/src/Views/Column.php#L238) in the Column class.

# Example of column that works

```php
 Column::make('Thing', 'thing')
            ->format(fn ($value) => view('components.show-thing', ['thing' => $value]))
            ->asHtml()
```

# Example of column that doesn't work
```php
 Column::make('Thing', 'thing')
            ->format(fn ($thing) => view('components.show-thing', ['thing' => $thing]))
            ->asHtml()
```

This would fail with an error such as:

```
Unable to resolve dependency [Parameter #0 [ <required> $thing ]] in class  ...
```

# Rationale
This is overall a very minor issue. But it prevents the use of `compact`. So in the above non-working example, the formatting line could be shortened to:

```php
->format(fn ($thing) => view('components.show-thing', compact('thing'))
```
if it didn't need to be named `value`.</div>

**Comment by rappasoft** [comment]
What's your recommendation for a fix?

**Comment by natepisarski** [comment]
Sorry for the world's latest response. I don't have a 100% great idea for a fix. But I've been thinking about this more recently, and was wondering what something like (pseudocode) would be like:

```php
if ($this->formatCallback) {
  $callbackParameters =  (new \ReflectionFunction($callback))->getParameters();
  if ( /* callback parameters has 'value', 'column', or 'row' */) {
      return app()->call($this->formatCallback, ['value' => $value, 'column' => $column, 'row' => $row]);
  } else {
    // The filter callback doesn't specify a name we're familiar with; we should call it using positional arguments
    $this->formatCallback($value, $column, $row);
  }
}
```
In theory this keeps backwards compatibility, and lets people decide whether or not they want to use their format callbacks positionally or not. The isuse is that for every `formatCallback` that is processed, we need to use reflection to read the arguments. It's not a big performance hit but it goes without saying that it's less performant than what's there now.

**Comment by rappasoft** [comment]
Fixed in next release.
