### ISSUE TITLE
Upgrading from livewire 2.5.1 to 2.5.2 breaks response serialisation

### ISSUE THREAD

**Issue by slakbal** [rappasoft/laravel-livewire-tables#387]
Hi,

I'm using your table component to display data. For actions on a table, I have the following blade code on a custom row view, which opens a modal from the livewire-table component:

```blade
<a wire:click="$emit('openModal', 'tenant.deactivate-modal', {{ json_encode(['tenant' => $tenant->id]) }})" wire:loading.attr="disabled" role="button" href="#" title="{{ __('Deactivate') }}">
    Deactivate
</a>
```

The above generates the following:

```html
<a wire:click="$emit('openModal', 'tenant.deactivate-modal', {"tenant":1})" wire:loading.attr="disabled" role="button" href="#" title="Deactivate">
    Deactivate
</a>
```

For the modals I'm using: https://github.com/livewire-ui/modal

Everything works with Livewire v2.5.1, the modal is called up and the action performed and livewire responds with the updated part. But once I upgrade to v2.5.2 the initial reder is correct, the modal is called up but after the component's action is finished livewire responds with the following, which is clearly a broken response and it feels like an escaping/serialisation issue:

```html
<a wire:click="$emit('openModal', 'tenant.deactivate-modal', {" wire:loading.attr="disabled" role="button" href="#" title="Deactivate">
    Deactivate
</a>
```
Not 100% sure why this is happening, any ideas? This only happens when I move from v2.5.1 to v2.5.2. 

Any assistance would be appreciated!

Thanks!

**Comment by lloricode** [comment]
this should fixed by this released tag https://github.com/livewire/livewire/releases/tag/v2.5.3

in your composer.json, you can bump the minimum version

```json
"livewire/livewire": "^2.5.3",
```

**Comment by rappasoft** [comment]
Thanks i'll bump the min version in the package composer.

**Comment by slakbal** [comment]
Much appreciated!
