### ISSUE TITLE
label's can't be overwritten directly

### ISSUE THREAD

**Issue by MartinP7r** [rappasoft/laravel-livewire-tables#39]
In your readme it says `You can override any of these in your table component:`

however, 
https://github.com/rappasoft/laravel-livewire-tables/blob/6d3c5d7551adb6452df806a442e43e2b5f8530c3/src/TableComponent.php#L62

overwrites the properties in constructor. So normal overwrites don't work and you have to do something like:

```php
    public function __construct($id)
    {
        parent::__construct($id);
        $this->noResultsMessage = '一致するレコードがありません';
        $this->perPageLabel = '件表示';
    }
```

I can see why you need to do it like that, but it might be worth mentioning in the readme.

**Comment by rappasoft** [comment]
Yeah I have them extracted out to language files in the next release. Thanks.
