### ISSUE TITLE
filter refresh problem

### ISSUE THREAD

**Issue by jijiezheng** [rappasoft/laravel-livewire-tables#401]
1.Table Model
![image](https://user-images.githubusercontent.com/56814901/125747446-af109f24-2716-4b14-b3b8-229236db41f4.png)

2、LiveWire Table (MonthTable.php)
```
class MonthTable extends DataTableComponent
{
    public $queryString = [];
    public function query(): Builder
    {
        return Month::query()
            ->selectRaw('user')
            ->when($this->getFilter('user'), fn($query, $type) => $query->where('user', $type));
    }
    public function columns(): array
    {
        return [
            Column::make('User', 'user'),
        ];
    }
    public function filters(): array
    {
        return [
            'user' => Filter::make('user')
                ->select([
                    '' => 'Any',
                    'foo' => 'foo',
                    'bar' => 'bar',
                ])
        ];
    }

}
```

3.Livewire Comment 
```
<div>
    <livewire:tables.month-table />
</div>
```

4. First time with no filter
![image](https://user-images.githubusercontent.com/56814901/125748527-989bde3f-2822-43c1-8caf-9905f603114b.png)

5. Choose filter
![image](https://user-images.githubusercontent.com/56814901/125748893-aca01488-6aaf-419f-a18a-53c20881a465.png)

6. Choose another filter
![image](https://user-images.githubusercontent.com/56814901/125749079-aac13fa0-c0ed-42c0-b397-2fd5f094baf2.png)

**Comment by qwasyx0** [comment]
Same issue as I'm having https://github.com/rappasoft/laravel-livewire-tables/issues/375

What database do you use?

**Comment by jijiezheng** [comment]
> Same issue as I'm having #375
> 
> What database do you use?

I use Mysql,But I dont think it's a database issue
I found out a solution:
```
    public function query(): Builder
    {
        return Month::query()
            ->selectRaw('user,id')
            ->when($this->getFilter('user'), fn($query, $type) => $query->where('user', $type));
    }
```
add a `id` into selectRaw,so it can work well, but I dont know why

**Comment by Majkie** [comment]
> @jijiezheng had the same problem and is definitely because of not having `id` on the rows. This should be documented that an `id` is required to avoid unexpected results.

I agree with @juliancc this should be in docs. Although there might be problem if someone is not using `id` as primary key. He would have to change `$primaryKey` property in table component as well.

My suggestion would be adding this line to construct of DataTableComponent to resolve primary key issue without having user to change property values in table component.

```php
public function __construct()
{
    $this->primaryKey = $this->query()->getModel()->getKeyName();
}
```
But back to the topic. I tried to look further into possible solution to make this foolproof and there is a solution but I'm not really sure if it's safe to use.

There is a way to check selected columns and if id is missing just add it. This would be in `rowsQuery()` function. Although I'm not really sure about this. If someone has time to test it further I'd appreciate it. Here is branch with changes. [Majkie/laravel-livewire-tables](https://github.com/Majkie/laravel-livewire-tables/tree/bugfix/add-id-when-using-select)
```php
if (!empty($query->getQuery()->columns) && !preg_match('~\bid\b~', $query->getQuery()->columns[0]->getValue())) {
    $query->addSelect('id');
}
```

**Comment by nazirulfitrifauzi** [comment]
I'm having the same problem. The table content not refresh after filtering. I don't have any ID or primary key in the query since I'm getting a count from a group by. 

`return xxxOwnership::query()->select('xxx_id', 'xxx_weight', DB::raw('count(*) as total'))->groupBy('xxx_id','xxx_weight')->orderBy('xxx_id', 'asc')`

How can I solve this?

**Comment by rappasoft** [comment]
You should have a primary key set on the rows so I know in Livewire how to check if they are unique by adding the primary key  as Livewires :key. Otherwise Livewire won't know how to correctly dom-diff, for example:

```
wire:key="table-row-{{ $row->{$primaryKey} }}"
```

**Comment by rappasoft** [comment]
https://github.com/rappasoft/laravel-livewire-tables/wiki/Troubleshooting#4-if-you-are-getting-unexpected-row-results-after-filteringsearch-etc

**Comment by rappasoft** [comment]
I don't know how to get around not having a primary key right now. You might have to use one of these hacky solutions or loop your results and append a unique one on if you can. I'll try to generate random ones if one isn't supplied in a future release.
