### ISSUE TITLE
Default 'Empty Message' does not make sense.

### ISSUE THREAD

**Issue by natepisarski** [rappasoft/laravel-livewire-tables#425]
This is a relatively small verbiage / copy thing. If you go to a table, and there's no data, you are presented with this message:

> No items found. Try narrowing your search

But this is the inverse of what it should be. If you "narrow" your search you are going from **many** results to **fewer** results. In this case, saying something like `Try widening your search` would reflect the spirit of the message more accurately.

Obviously using the phrase "widening" isn't perfect copy so feel free to use whatever phrase comes across the best.

**Comment by kehwar** [comment]
I agree that `narrowing` is not the right word. I suggest: `Try to broaden your search`

**Comment by Majkie** [comment]
You can change this message in your table component using `public string $emptyMessage = 'Message';` to anything you want. Also there is a possibility to publish translations where text can be edited.

Although, I agree with changing this message to something more sophisticated like Laravel Nova has in data tables `No {model} matched the given criteria.`. But imho this would be great with complete refactor of translatable texts. (Might as well work on this myself).

**Comment by rappasoft** [comment]
Will update with next release.
