### ISSUE TITLE
Minor localization bug on bulk actions

### ISSUE THREAD

**Issue by kehwar** [rappasoft/laravel-livewire-tables#431]
On the file: `resources/views/tailwind/includes/bulk-select-row.blade.php`
On lines 9 and 44 we have this code:
````
@lang(':rows', ['rows' => count($selected) === 1 ? 'row' : 'rows']).
````
Which I believe should be replaced with:
````
@lang(count($selected) === 1 ? 'row' : 'rows').
````

And add a `row` entry to the localization file

---

I just started learning laravel a few weeks ago so I may be wrong. However I'm using this component with a different locale and this particular translation wasn't working until I made that change.

**Comment by rappasoft** [comment]
Fixed in next release.
