### ISSUE TITLE
Row content visualization problem

### ISSUE THREAD

**Issue by salvomil** [rappasoft/laravel-livewire-tables#437]
Hi, I used the package in others projects and I didn't have any problem. 
Now I'm creating a new project and I tried to create a component from a table. 
The result is a component where I can see blank rows but the query is ok and the field name in return column is also ok.

I get simple blank cell content. What can be the problem?

Thank you

**Comment by Majkie** [comment]
Maybe you could show us your code?

**Comment by salvomil** [comment]
Yes of course,
it's quite simple:

Livewire component 

<?php

namespace App\Http\Livewire;

use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Models\RiscontriItinerariDettagli;
use App\Models\RiscontriItinerariLuoghi;

class RiscontriItinerariDettagliTable extends DataTableComponent
{
    public $itinerarioId = 14; // example
    public $riscontroItinerarioId = 0;

    protected $listeners = ['itinerarioChange' => 'itinerarioChange'];

    public function itinerarioChange($value)
    {
        $this->itinerarioId = $value;
    }

    public function columns(): array
    {
        return [
            Column::make('Luogo', 'luogo'),
            Column::make('Itinerario', 'itinerario_id')
        ];
    }

    public function query(): Builder
    {
        return RiscontriItinerariLuoghi::query();
    }

    public function rowView(): string
    {
        return 'livewire-tables.rows.riscontri_itinerari_dettagli_table';
    }
}


blade file: 

<x-livewire-tables::bs4.table.cell>
{{-- Note: This is a tailwind cell --}}
{{-- For bootstrap 4, use <x-livewire-tables::bs4.table.cell> --}}
{{-- For bootstrap 5, use <x-livewire-tables::bs5.table.cell> --}}
</x-livewire-tables::bs4.table.cell>


And I get:

![table_result](https://user-images.githubusercontent.com/16554089/129898523-f82384d7-2d04-4ee1-ae40-a0cc6a7e4799.png)

**Comment by Majkie** [comment]
Check docs: [https://github.com/rappasoft/laravel-livewire-tables/wiki/Custom-Row-View](https://github.com/rappasoft/laravel-livewire-tables/wiki/Custom-Row-View)

When you are using Custom Row View, you have to define data by hand in your blade file.

Basically your blade file has to look something like this. Only if you are using Bootstrap 4, more theme related info you can see in the bottom of docs I sent to you earlier in the comment.

```blade
<x-livewire-tables::bs4.table.cell>
    {{ $row->luogo }}
</x-livewire-tables::bs4.table.cell>

<x-livewire-tables::bs4.table.cell>
    {{ $row-> itinerario_id }}
</x-livewire-tables::bs4.table.cell>
```

**Comment by salvomil** [comment]
Oh Oh I feel so fool.

Thank you, your answer is the solution to my problem. Sorry if I read the documentation I could get all the answer.
Again thank you!!!
