### ISSUE TITLE
Current state of docs

### ISSUE THREAD

**Issue by Majkie** [rappasoft/laravel-livewire-tables#440]
I wonder if it's possible for you @rappasoft to create a new repository called for example livewire-tables-docs which would contain all markdown files currently presented in Wiki? Or maybe even put them into new docs folder, of this repository?

I don't think you alone can handle managing docs. And Wiki cannot be changed by anyone else this way. For example if docs were open to edit for everyone there is some code with bad practice that might be updated to look better and less confusing for new users, some typos etc.

Also this change might give some space to publish docs on some website with better UI and more complex search (good example is Laravel, Jetstream and other docs).

Thanks for thinking this through.

**Comment by rappasoft** [comment]
I'm open to other forms of documentation if I can just use the same markdown files. But I usually just use the wiki so I don't have any experience on what the current best free to use solution is.

**Comment by bomshteyn** [comment]
I created one few month ago: https://bomshteyn.github.io/laravel-livewire-tables-docs/ 
https://github.com/bomshteyn/laravel-livewire-tables-docs

**Comment by rappasoft** [comment]
> I created one few month ago: https://bomshteyn.github.io/laravel-livewire-tables-docs/
> https://github.com/bomshteyn/laravel-livewire-tables-docs

Damn I didn't even know you made this.

**Comment by bomshteyn** [comment]
> Damn I didn't even know you made this.

LOL, I thought you just didn't like it :-)

**Comment by rappasoft** [comment]
> > Damn I didn't even know you made this.
> 
> LOL, I thought you just didn't like it :-)

Did you show me? I don't remember it. Is it up to date? I usually add to the wiki whenever I merge a feature.

**Comment by bomshteyn** [comment]
@rappasoft I have sent it to you back in June in the middle of the conversation about other issues / PR discussion. 
So i don't blame you for missing it.

I haven't updated it since since end of June so it will need to be brought up to date.

**Comment by rappasoft** [comment]
Is it just the markdown files or you copy/pasted all of that?

**Comment by bomshteyn** [comment]
copy/pasted

**Comment by rappasoft** [comment]
Would it work off markdown files if I made a repo for them?

**Comment by bomshteyn** [comment]
The content is in md files.  But i had to massage it a bit to have the structure / nav etc... you can see it in this folder: https://github.com/bomshteyn/laravel-livewire-tables-docs/tree/main/content/en

**Comment by rappasoft** [comment]
I see. I definitely like the approach. It looks good and it's searchable, and users can contribute.

**Comment by bomshteyn** [comment]
Want to move it to rappasoft on github?

**Comment by rappasoft** [comment]
Yeah I mean you did the work it's up to you.

**Comment by bomshteyn** [comment]
Transfer request sent :-)

**Comment by rappasoft** [comment]
I'll try to get it running and up today after I get some work done.

**Comment by rappasoft** [comment]
Ok it's up here: https://rappasoft.github.io/laravel-livewire-tables-docs/

I'm currently having issues deploying though, so I'm not going to remove the wiki yet.

**Comment by bomshteyn** [comment]
Are you getting an error?

**Comment by rappasoft** [comment]
Yes, I found a few SO articles on it but no resolutions. Basically I can generate but when I go to deploy it has an issue:

```
$ push-dir --dir=dist --branch=gh-pages --cleanup
aborted: problem pushing local branch to remote
```

**Comment by bomshteyn** [comment]
are you running it locally or on gh actions?

**Comment by rappasoft** [comment]
There's no action set up? Did you have one? I've never used this framework before.

**Comment by bomshteyn** [comment]
I have deployed from my local machine without problems. 
Have not setup actions, am trying to get one working on a forked copy now.

**Comment by rappasoft** [comment]
@bomshteyn this is what happens when I try to deploy:

<img width="1792" alt="Screen Shot 2021-09-19 at 21 34 40" src="https://user-images.githubusercontent.com/6026504/133950110-274e7b08-b235-4e70-8817-8dcdf8e65e93.png">

**Comment by rappasoft** [comment]
I set it up with an action and it works. https://rappasoft.github.io/laravel-livewire-tables-docs/

**Comment by rappasoft** [comment]
Thank you again @bomshteyn!

**Comment by bomshteyn** [comment]
Amazing! I was traveling today, so didn't have a chance. Thank you for the package!

**Comment by keenminded** [comment]
@rappasoft @bomshteyn Thanks for all your hard work!
I do seem to have an issue with the docs. Not seeing any content aside from the Home page. On initial load, it works fine, but then even clicking on the Home link doesn't work. Any suggestions?

**Comment by rappasoft** [comment]
> @rappasoft @bomshteyn Thanks for all your hard work!
> I do seem to have an issue with the docs. Not seeing any content aside from the Home page. On initial load, it works fine, but then even clicking on the Home link doesn't work. Any suggestions?

Working fine for me in Chrome
