### ISSUE TITLE
Problem by using the built in cell formatting with view

### ISSUE THREAD

**Issue by logoszGrafikus** [rappasoft/laravel-livewire-tables#456]
By using the built in cell formatting with view it creates a new td tag, and doesn't replace it. So there is an empty cell, and the cells won't be in synchron with its th tag.

My column:
```
Column::make('Van kézbesítési megbízása?', 'has_delivery_agent')
                ->format(function($value, $column, $row) {
                    return view('livewire.ro-client.datalist.boolean-to-cell')
                        ->withBoolean($row->contractingDetail->has_delivery_agent)
                        ->withValue($value);
                }),
```

The view:

```
{{-- boolean-to-cell.blade.php --}}
<x-livewire-tables::bs4.table.cell>
	<span class="{{ $boolean ? 'badge badge-success' : ''}}">{{ $value }}</span>
</x-livewire-tables::bs4.table.cell>
```

![image](https://user-images.githubusercontent.com/48473195/133241824-7d1d45d9-d1d7-459c-a222-606de8e6b279.png)

I could change with the solution below without included view, but this isn't so dynamic:

```
Column::make('Van kézbesítési megbízása?', 'has_delivery_agent')
                ->format(function($value, $column, $row) {
                    if($row->contractingDetail->has_delivery_agent)
                    {
                        return '<span class="badge badge-success">'.$value.'</span>';
                    } else
                        return '<span>'.$value.'</span>';
                })
                ->asHtml(),
```

![image](https://user-images.githubusercontent.com/48473195/133242719-ad796b79-35e1-4474-bf3e-d5a324f02bfe.png)

**Comment by fabio-ivona** [comment]
I think `->format()` is for formatting data **inside** the view, not for replacing the `<td>` element

**Comment by rappasoft** [comment]
The view shouldn't contain the actual cell, that's only if you're using a whole custom row. If you're formatting from the column itself, only return what goes in the cell, i.e.:

```
{{-- boolean-to-cell.blade.php --}}
<span class="{{ $boolean ? 'badge badge-success' : ''}}">{{ $value }}</span>
```
