### ISSUE TITLE
loading events

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-livewire-tables#47]
is there a way to emit loading events on start loading and finishing something like (isLoading), to be able to use custom loading method, thank you

**Comment by rappasoft** [comment]
Can you give an example of a use case? I don't know exactly what you need. Livewire has wire.loading and wire.loading.remove, is that what you're talking about?

**Comment by abdosaeedelhassan** [comment]
i mean that rappasoft/laravel-livewire-tables it's livewire component that has it own wire.loading and wire.loading.remove worked inside, i am asking when this events fired inside is there a way to emit it outside with event name that can be listening to it in outside the   rappasoft/laravel-livewire-tables, the benefit of this ability to disable loading message form   rappasoft/laravel-livewire-tables and doing it outside with custom way, thank you for your response.

**Comment by rappasoft** [comment]
If the component is inside another component, you can publish the views and emit events if you need.
