### ISSUE TITLE
Checkbox behavior

### ISSUE THREAD

**Issue by noxify** [rappasoft/laravel-livewire-tables#48]
Hi,

While testing the "Check All" functionality, I have found a strange behavior.

I have the following table:
![image](https://user-images.githubusercontent.com/521777/90114557-2cb05880-dd53-11ea-93aa-7754d6c72d97.png)

Now i activate the first three checkboxes.

What would I expect:
![image](https://user-images.githubusercontent.com/521777/90114858-9af51b00-dd53-11ea-8975-604b94aa78cf.png)

What I currently get:
![image](https://user-images.githubusercontent.com/521777/90115015-ced04080-dd53-11ea-9ff6-5a6e594e1dac.png)

In the dev console I can see three `POST` requests, which is ok - but the size and the needed time seems to be a problem:
![image](https://user-images.githubusercontent.com/521777/90115363-456d3e00-dd54-11ea-8a6c-84c767dd9790.png)

Any thoughts how to solve/fix this?

Thanks!

Regards,
Marcus

**Comment by rappasoft** [comment]
I apologize but the checkbox functionality is being removed from the next release, if you really need it you can continue using 0.2 or move the functionality over to your components by publishing the views.

**Comment by noxify** [comment]
@rappasoft that's fine for me :) Thanks for the feedback :)
