### ISSUE TITLE
descending defaultSortDirection with sortable behave weirdly

### ISSUE THREAD

**Issue by KevinYobeth** [rappasoft/laravel-livewire-tables#484]
When I sort using `defaultSortDirection` set as descending, it behave very weirdly. It works fine when using ascending as the `defaultSortDirection`

**Steps to Reproduce**
1. Set up the data with the `name` 1 to 8 and `sort_key` 1 to 8 as well
2. Enable reorder and set `$defaultSortDirection` to 'desc'
3. Drag 1 (currently in the bottom) to the top

Initial Data Order: `8, 7, 6, 5, 4, 3, 2, 1`
Result Data Order: `2, 3, 4, 5, 6, 7, 8, 1`
Expected Data Order: `1, 8, 7, 6, 5, 4, 3, 2`

https://user-images.githubusercontent.com/10485985/136682642-3f7c067e-4a5b-4139-9760-567415755919.mov

**Comment by afiqiqmal** [comment]
Sorry. wanna ask, how you enable sortable plugin? i already install livewire-sortablejs, and follow exactly from the livewire-table documentation, But drag wont work..
