### ISSUE TITLE
How to mutate an attribute?

### ISSUE THREAD

**Issue by marbuser** [rappasoft/laravel-livewire-tables#50]
I store money as cents in my database. When I show it on the screen, I pass it through a `money()` helper that converts it to the right currency/format.

Based on the limited docs and other issues I saw that the way to accomplish this was using `view()` or `components()`. However, despite that being said, there is not an explanation of how either of these works really anywhere, and the examples given are basically duplicates of eachother so I'm not really sure what that's about?

Either way, this seems incredibly heavy handed and a lot of work for the developer to do something as basic as modifying the output.

May I give an alternative solution?
```php
Column::make('price', function ($model) {
    return money($model->price);
}),
```

This is incredibly flexible and way more lightweight than this "component" system, and also way easier for developers to integrate.

Hopefully you can look into it.

**Comment by marbuser** [comment]
Should mention this could be used in conjunction with the component system as well since the callback could just as easily return a view of some kind.

**Comment by detygon** [comment]
Sorry for the late reply. I would suggest to use [laravel accessors](https://laravel.com/docs/7.x/eloquent-mutators), then use the custom attribute method.

```php
Column::make('price')->customAttribute(),
```

**Comment by rappasoft** [comment]
Next version has a format method that you can return whatever from.
