### ISSUE TITLE
Property [$numberOfPaginatorsRendered] not found on component

### ISSUE THREAD

**Issue by bdelamatre** [rappasoft/laravel-livewire-tables#503]
Hi @rappasoft , been awhile since I have looked at this project :). 

I upgraded from 1.5 to the latest version and immediately ran into this issue. It looks like the tailwind paginator has references to a property that isn't defined. I don't see this property reference anywhere else in the source and removing references to it seems to work fine.

Should I submit a PR to remove references to this property, or is there some functionality here that needs to be patched?

**Comment by rappasoft** [comment]
Yeah I had it and people said they had issues so I put it back, but it would probably make sense.

**Comment by rappasoft** [comment]
Just added it for next release.
