### ISSUE TITLE
Wrong Search Behavior

### ISSUE THREAD

**Issue by solusoftek** [rappasoft/laravel-livewire-tables#509]
Hi, your component realy like me, so after a few hours implementing am having this strange behavior whit the built-in search, follwing the documentation make a two columns with searchable attrinute, but on every letter that i type the builder drops me a row resulting in 3 rows repited, 
![image](https://user-images.githubusercontent.com/11346975/137614718-76e52f25-66c4-40d4-85f4-27d9897ca8e2.png)

because of this  error, am trying to implement a search scope function instead, so i remove in columns the searchable attribute, put the scope in the model,  and i have the same result,  repetied rows,
beside of this if  put a inexistent term on search the repetied rows still appears but with the emptymessage
![image](https://user-images.githubusercontent.com/11346975/137615113-10fbc49a-39b9-407e-817e-1f884da54d8e.png)

curious stuff if i refresh the page whit the term in search field,  the render view drops me 1 row as it should
in advance thanks for the help

**Comment by rappasoft** [comment]
You probably have issues with your [primary key](https://rappasoft.github.io/laravel-livewire-tables-docs/usage/The-primary-key) make sure each row has a unique attribute or livewire can't tell which ones to remove when it updates.

**Comment by solusoftek** [comment]
yes, you totally right, was the primaryKey, thanks for you answer, awsome component
