### ISSUE TITLE
Sort By Relationship not working

### ISSUE THREAD

**Issue by avinash403** [rappasoft/laravel-livewire-tables#518]
I have column like this:
```
    public function columns(): array
    {
        return [
            Column::make('Project', 'project.name')
                ->sortable()
                ->searchable(),
        ];
    }
```

Query like this:
```
    public function query(): Builder
    {
        return Request::with('project');
    }
```

Now, while sorting the project (project.name) column, I get an error saying "Column project.name not found". It works fine for searching

**Comment by CristhoferMF** [comment]
I think that functionality doesn't exists.

**Comment by avinash403** [comment]
> I think that functionality doesn't exists.

It says it exists here:
<img width="487" alt="Screenshot 2021-10-19 at 9 38 03 PM" src="https://user-images.githubusercontent.com/31030044/137949726-22876b9b-34e1-487b-af5e-a32bf53b214d.png">

and here: 
<img width="1025" alt="Screenshot 2021-10-19 at 9 38 54 PM" src="https://user-images.githubusercontent.com/31030044/137949843-a148768b-0b2e-48a0-aba8-c938f1712e99.png">
