### ISSUE TITLE
duplicate wire:key when using multiple tables and bulkSelect

### ISSUE THREAD

**Issue by bdelamatre** [rappasoft/laravel-livewire-tables#524]
_tailwind/includes/table.blade.php line 99:_

wire:key="table-row-{{ $row->{$primaryKey} }}"

This will cause undesirable behavior when multiple tables are used with a bulk select and overlapping ids. The behavior I experienced was that selecting and deselecting a row would duplicate the first row of a table. 

A simple patch would be to add a random string to make the row unique. For example:

wire:key="table-row-{{ md5(rand()) }}-{{ $row->{\Rappasoft\LaravelLivewireTables\Utilities\ColumnUtilities::parseField($primaryKey)} }}"

A better patch might be to add a property to the component that allows a unique (and expected) prefix to be set. However, that would require more code modification.

Would you like a PR for one of these approaches?

**Comment by bdelamatre** [comment]
Sorry for the delay. Okay, I went ahead and submitted PR https://github.com/rappasoft/laravel-livewire-tables/pull/557 with the random string patch that I have been using.

As discussed, there is probably a better way to handle this, but this has been working fine for me.

**Comment by rappasoft** [comment]
Merged for next release thanks.
