### ISSUE TITLE
How to show relationship attribute in column

### ISSUE THREAD

**Issue by perffy** [rappasoft/laravel-livewire-tables#53]
Hi,

I don't know how to show an attribute of a relationship in a column.
For example, I have a table users and each user has attribute country_id, which is a belongsTo relationship to the countries table. So if I want to show the name of the country and make that column sortable() and searchable(), what do I need to do?

Thanks

**Comment by rappasoft** [comment]
I'm aware there may be an issue with this feature right now.

**Comment by rappasoft** [comment]
There was not an issue with this that I could find.
