### ISSUE TITLE
"Undefined index: id" after updating

### ISSUE THREAD

**Issue by JacAppDev** [rappasoft/laravel-livewire-tables#539]
Hey,

after updating to recent release
![image](https://user-images.githubusercontent.com/84027764/140023481-329947d3-735e-4885-a599-ce3fca20d15d.png)
![image](https://user-images.githubusercontent.com/84027764/140023522-1dc92a42-30cd-48ed-9c50-25c1329c2a19.png)
when clicking on column header to sort i get the following error:

local.ERROR: Undefined index: id {"userId":2,"exception":"[object] (ErrorException(code: 0): Undefined index: id at xxxxxx\\vendor\\livewire\\livewire\\src\\HydrationMiddleware\\PerformActionCalls.php:27)

![image](https://user-images.githubusercontent.com/84027764/140023293-5f0651ee-b3ce-4239-8de0-24487ba1cf95.png)

I've tried to rollback either package step by step and the only combination that works is
![image](https://user-images.githubusercontent.com/84027764/140024659-670b542e-1ae5-4961-8ed3-047fc72359fc.png)

**Comment by silent198214** [comment]
@JacAppDev Do you try to republish livewire assets?

```sh
php artisan livewire:publish --assets
```

**Comment by JacAppDev** [comment]
Sometimes it is that easy. Thanks!
