### ISSUE TITLE
Searching stopped working since v1.13.0 - reason why

### ISSUE THREAD

**Issue by qwasyx0** [rappasoft/laravel-livewire-tables#546]
I'm opening new issue because this was closed: https://github.com/rappasoft/laravel-livewire-tables/issues/480 and is continuation of https://github.com/rappasoft/laravel-livewire-tables/issues/534 sorry if I'm making a mess with opening issues.

I found out where this issue is coming from.

rappasoft/laravel-livewire-tables/src/Traits/WithFilters.php in function     public function applySearchFilter($query)

There is since v.1.14 this change

```
// TODO: Skip Aggregates
 if (! $hasRelation) {
              $whereColumn = Schema::hasColumn($query->getModel()->getTable(), $whereColumn) ? $query->getModel()->getTable() . '.' . $whereColumn : $whereColumn;
 }
```

The version before had this code:
```
// TODO: Skip Aggregates
 if (! $hasRelation) {
              $whereColumn = $query->getModel()->getTable() . '.' . $whereColumn;
 }
```

Schema::hasColumn is using function of same name in 
vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php 
```
   public function hasColumn($table, $column)
    {
        return in_array(
            strtolower($column), array_map('strtolower', $this->getColumnListing($table))
        );
    }
```

So reverting the change, the issue is there no more and on newest version, searching works. What is the reason for this change? Could it be reverted in next update?

**Comment by NBNGaming** [comment]
This change was made in fdb18fa0691dad24924a5bb48e7b1c82717c0392

**Comment by qwasyx0** [comment]
This bug is replicable in my project with mixed type keys in arrays applying filters to columns. I think this should be reverted or use different approach to filters, which could be breaking, so not likely.
```
 public function filters(): array
    {
        return [
            'VEHICLELICENSENUMBER' => Filter::make('Vehicle licence number')
                ->select([ 
                         1 => 1, 
                         2 => 2,
                         '03' => '03',
                         4 => "04",
                         'FSW-34' => 'FSW-34', 
                         'EWG 87' => 'EWG 87'
               ])
        ];
    }
```

Any attempt to apply this filter end in this error:
```
strtolower(): Argument #1 ($string) must be of type string, stdClass given
```
