### ISSUE TITLE
Command "make:datatable" is not defined.

### ISSUE THREAD

**Issue by amirtheshprasad** [rappasoft/laravel-livewire-tables#549]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/548

<div type='discussions-op-text'>

<sup>Originally posted by **amirtheshprasad** November  6, 2021</sup>
Hello,

I have installed the package via composer and when I try to use the make:datatable command to create a data table, I get the error Command "make:datatable" is not defined.  ' It would be of great help if someone could help me out. Thank you.
![Screenshot (1407)](https://user-images.githubusercontent.com/57315922/140608315-638b41d1-a775-4b2a-a6c5-38638511f20e.png)
</div>

**Comment by rappasoft** [comment]
<img width="904" alt="Screen Shot 2021-11-20 at 22 29 13" src="https://user-images.githubusercontent.com/6026504/142748353-521e1363-b0b7-4640-8aff-7de01b47a20a.png">

Can not recreate. Make sure to dump composers autoload.
