### ISSUE TITLE
Cannot search using searchable when use format

### ISSUE THREAD

**Issue by SupunSpera** [rappasoft/laravel-livewire-tables#553]
Column::make('Referrer')->searchable()
->format(function ($created_at, $column, $customer) {
return $customer->referrer_name ;
}),

cannot search using this searchable function when use format dunction. How can i do with rappasoft datatable?

**Comment by rizkhal** [comment]
The `searchable()` method is have nullable callback params, i think you need to use that to custom your search on this issue..
that's looks like:

```php
Column::make('Referrer')
   ->searchable(function(Builder $query, $term) {
     return $query->orWhere('column', 'like', '%' . trim($term) . '%');
   })
   ->format(function ($created_at, $column, $customer) {
  return $customer->referrer_name ;
}),
```

**Comment by SupunSpera** [comment]
@rizkhal  Can we implement this for another table. such as the customer has referrer , then the customer table show referrer name . then We want to search customer by Referrer name. How can we do it?

**Comment by rizkhal** [comment]
@SupunSpera  yes you can, you just need to join query on builder method or using `whereHas` if you have relations on your model

for example
```php
return $query->leftJoin(...)
// or
return $query->whereHas('relations here', ...)
```
