### ISSUE TITLE
Can't use dropdown in table, because of overflow.

### ISSUE THREAD

**Issue by natecorkish** [rappasoft/laravel-livewire-tables#562]
<img src="https://i.imgur.com/KtohyA4.png">

This is due to https://github.com/rappasoft/laravel-livewire-tables/blob/a52839d27d6f31a8b5c5fa77ead3baedcdaad752/resources/views/tailwind/components/table/table.blade.php#L3

**Comment by rizkhal** [comment]
i just need to publish the view and custom your view like remove the `overflow-hidden`

**Comment by rappasoft** [comment]
Feel free to make a PR to fix.
