### ISSUE TITLE
Passing $row in a request doesn't pass the object but the model class

### ISSUE THREAD

**Issue by Mozzarella-dev** [rappasoft/laravel-livewire-tables#563]
I've got a simple datatable with a delete button in each row, the cell of the button looks like this:

```html
<x-livewire-tables::bs4.table.cell>
        <div>
        <form action="{{route('posts', $row)}}" method="POST">
            @csrf
            @method('DELETE')
        <button type="submit" class="badge badge-danger btn-xs">Delete</button>
        </form>
        </div>
</x-livewire-tables::bs4.table.cell>
```

This is my route:
```php
Route::delete('/posts', [App\Http\Controllers\PostController::class, 'destroy'])->name('posts');
```

Finally the `destroy` method inside the controller looks like this:
```php
public function destroy(Post $post)
    {
        dd($post);
    }
```

After clicking the button i get dumped the class of the Post model and not the post itself. (Looking into the attributes of the dump nothing shows up)

There's a way i can hotfix that?

**Comment by rappasoft** [comment]
Why are you not passing the post to the route by either ID or route model binding? It doesn't know how to find it in the route.

Like so:

```php
Route::delete('/posts/{post}', [App\Http\Controllers\PostController::class, 'destroy'])->name('posts');
```

**Comment by Mozzarella-dev** [comment]
Following a tutorial i wasn't binding the model to the route, now it works properly, thanks for the head up!
