### ISSUE TITLE
Doesn't like camelCased relation names

### ISSUE THREAD

**Issue by zack6849** [rappasoft/laravel-livewire-tables#57]
Hi There!

If i have a relation, say, physicalAddress, laravel encodes that as physical_address in the data if you do toArray, for example.

However, your library doesn't pick that up, so if I change the column to physical_address.city, it works for display, but then sorting is broken because it looks for a relation called physical_address

Not sure if that's expected functionality or not, but wanted to make you aware of the bug.

**Comment by detygon** [comment]
Hi ! To enable search for a relation, you have to pass a callback function that return a Builder.

```php
     Column::make('Address', 'physical_address.city')
           ->searchable(function ($builder, $term) {
                 return $builder->orWhereHas('physicalAddress', function ($query) use ($term) {
                        return $query->where('city', 'like', '%'.$term.'%');
           });
    }),
```

Hope it helps.

**Comment by detygon** [comment]
You can check the [boilerplate](https://github.com/rappasoft/laravel-boilerplate/blob/master/app/Http/Livewire/UsersTable.php) for usage examples.

**Comment by zack6849** [comment]
If that's the way it's meant to be used, seems this "bug" is something the author is well aware of, so i'll close this, I guess.
