### ISSUE TITLE
Table with relation column not working currently in v2 branch

### ISSUE THREAD

**Issue by christian-forgacs** [rappasoft/laravel-livewire-tables#598]
In branch v2 you can't use relations for a column. For example:

```
...
Column::make(__('Number of Assigned Districts'), 'districts.name')
...
```

Throw following error:

```
Rappasoft\LaravelLivewireTables\Views\Column::setTable(): Argument #1 ($table) must be of type string, null given, called in /var/www/html/vendor/rappasoft/laravel-livewire-tables/src/Traits/Helpers/ColumnHelpers.php on line 24
```

In v1 it works great and in the row template I can use the row relation and as well for search.

**Comment by rappasoft** [comment]
I'm not ready to start receiving issues for v2 as it is no where near done. However right now the relationships are limited to hasOne and belongsTo.
