### ISSUE TITLE
filters stop working after sorting the table

### ISSUE THREAD

**Issue by aldozumaran** [rappasoft/laravel-livewire-tables#606]
https://user-images.githubusercontent.com/3183704/147890720-8c295635-776c-432e-8ff8-d5cc4c526657.mp4

i added a toggle button to change the row status
![image](https://user-images.githubusercontent.com/3183704/147890798-833e5d93-7637-4e16-a52f-e8595df6491f.png)
![image](https://user-images.githubusercontent.com/3183704/147890810-f9af6488-caaa-4db4-a542-169d871e2ef3.png)

**Comment by aldozumaran** [comment]
at some point the html is regenerated and the javascript (alpinejs ) part no longer works


https://user-images.githubusercontent.com/3183704/147978556-ae1616eb-65f8-4bf7-8a52-cff3568cb187.mp4

**Comment by aldozumaran** [comment]
in the example page the filters continue to work after the component refresh, in my project they don't

Tailwind example: https://tables.laravel-boilerplate.com/tailwind

My project 
"rappasoft/laravel-livewire-tables": "^1.21",
"livewire/livewire": "^2.5",
"laravel/framework": "^8.75",
"laravel/jetstream": "^2.5",

[UsersTable.zip](https://github.com/rappasoft/laravel-livewire-tables/files/7808382/UsersTable.zip)

@rappasoft what's the problem?
ps. sorry for my english

**Comment by aldozumaran** [comment]
basic example, after several sorts, livewire refresh component and bulks/filters not open, click event still works, console.log(open) show open value "true/false" 
![image](https://user-images.githubusercontent.com/3183704/148182173-2f227f57-d359-449e-b352-e907d8118049.png)

**Comment by romeogregory** [comment]
I got the same problem.

**Comment by bureauvk** [comment]
Same here!

**Comment by vildanbina** [comment]
i fix that and I requested a pull request: https://github.com/rappasoft/laravel-livewire-tables/pull/643
