### ISSUE TITLE
How can we show id column as increment Number

### ISSUE THREAD

**Issue by SupunSpera** [rappasoft/laravel-livewire-tables#607]
Can we show id column as increment number instead of real id.  

as an example i want to show records as 1,2,3,4 ... instead if real ID

**Comment by aldozumaran** [comment]
```
 public function columns(): array
    {
        return [
            Column::make('Id')
                ->sortable()
                ->searchable(),
           ...
        ];
    }

<x-livewire-tables::table.cell>
    {{ $row->id }}
</x-livewire-tables::table.cell>

```

**Comment by aldozumaran** [comment]
```
<x-livewire-tables::table.cell>
    {{ $loop->index }}
</x-livewire-tables::table.cell>
```

**Comment by rappasoft** [comment]
This is not an issue, but the above solution should work.

**Comment by mysalf4498** [comment]
Column::make("Id", "id")->format(fn () => ++$this->index +  ($this->page - 1) * $this->perPage),
kindly use this where you need to show increment or indexing no

**Comment by albertdimasa** [comment]
> add this in starting of class protected $index = 0;
> 
> ```
> Column::make("Id", "id")->format(fn () => ++$this->index +  ($this->page - 1) * $this->perPage),
> ```
> 
> kindly use this where you need to show increment or indexing no

i have problem with version 5.x 

$page an $perPage not found

**Comment by lrljoe** [comment]
> > add this in starting of class protected $index = 0;
> > 
> > ```
> > Column::make("Id", "id")->format(fn () => ++$this->index +  ($this->page - 1) * $this->perPage),
> > ```
> > 
> > kindly use this where you need to show increment or indexing no
> 
> i have problem with version 5.x 
> 
> $page an $perPage not found

Please open a new discussion, this is 2 years old.
