### ISSUE TITLE
hasOne Relationship is mirrored in column::make

### ISSUE THREAD

**Issue by Katalam** [rappasoft/laravel-livewire-tables#609]
Hello,

I've got the problem that my model has a `N to 1`  relationship. My model `File` has a `FileStatus` with a column `file_status_id` and my `FileStatus` belongsToMany `Files` without a column `file_id`.

I've created a file table with this package, and I'm creating a column with
```php
Column::make('Status', 'status.name');
```
The app returns a 500 with
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'file_statuses.file_id' in 'where clause' (SQL: select * from
`file_statuses` where `file_statuses`.`file_id` = 6 and `file_statuses`.`file_id` is not null limit 1)
```
Here are my files

```php
class File extends Model
{
	...
	public function status()
	{
		return $this->hasOne(FileStatus::class);
	}
	...

}
```

```php
class FileStatus extends Model
{
	...
	public function file()
	{
		return $this->belongsToMany(File::class);
	}
	...
}

```
And the column as shown above.
I do think that this is mirrored/wrong in hasOne relationship. A belongsTo relationship works fine, and I already used a couple of them, but a hasOne relatonship searches (should at least) for a key in the own class not in the given one.

**Comment by CovertError** [comment]
are you doing a one to one kind of relation or one to many if it's one to one then you have to change the belongsToMany to belongsTo the belongsToMany only works with many to many relationships as far as I know

**Comment by Katalam** [comment]
It is a one-to-many relationship. In the tinker session, it works fine with the relationship itself, but the column is not able to do that.

**Comment by CovertError** [comment]
check this https://laravel.com/docs/8.x/eloquent-relationships#one-to-one
