### ISSUE TITLE
Parameter added via mount() doesn't work?

### ISSUE THREAD

**Issue by zack6849** [rappasoft/laravel-livewire-tables#61]
Hi There!

I have the following component

https://gist.github.com/zack6849/5a025eaa21454c6abecaf5cfbc479ce1

Which I render like this:

<livewire:unit.table :community="$community"></livewire:unit.table>

On page load, the table populates, but if i  search it throws an exception

![inital page load](https://www.zcraig.me/files/Gt3pQKUUUINjrpxtVbOXvioGh.png)
![error screenshot](https://www.zcraig.me/files/659YbkZO38nqWTbTQtw7pe02M.png)

**Comment by zack6849** [comment]
This probably doesn't matter, but it's worth noting the same issue exists on the latest release (0.2.1)

**Comment by detygon** [comment]
Please reproduce the bug [here](https://laravelplayground.com/), so that we can debug it easily.

**Comment by zack6849** [comment]
I'm not too sure how to reproduce that there, since my use case is passing a model and i'm not familiar with this playground thing

I'm fighting a deadline so I can't use this project for now, i'll try and make a repo to reproduce the bug for you guys to test on sometime soon, but in theory having say, an author that hasmany post, and a table that shows all posts for an author, sent via a livewire should be able to reproduce this bug, I think.

**Comment by zack6849** [comment]
It turns out making the property you want bound private breaks things, in fact this breaks in normal livewire too, I haven't tested again, but i'm going to close this for now.

**Comment by rappasoft** [comment]
That's not a bug, they say only public properties are tracked: https://laravel-livewire.com/docs/2.x/properties#introduction

**Comment by zack6849** [comment]
I know, well, at least I do now, that's why I closed it.
