### ISSUE TITLE
text-center/-right doesn't work for tableHead's via addClasses

### ISSUE THREAD

**Issue by REJack** [rappasoft/laravel-livewire-tables#613]
If I set `text-center` or `text-right` via addClasses,

it stay the same text-alignment and will not get overwritten, except I use classes with `!important` but thats not the right way IMHO.
that bug is caused by `text-left` in the table head span/button.

https://github.com/rappasoft/laravel-livewire-tables/blob/eaad8c7c72c1c5edee2d3eb56c5ae8b7c8f28cfe/resources/views/tailwind/components/table/heading.blade.php#L14

https://github.com/rappasoft/laravel-livewire-tables/blob/eaad8c7c72c1c5edee2d3eb56c5ae8b7c8f28cfe/resources/views/tailwind/components/table/heading.blade.php#L21

I would remove the text-left since it's the default, if you are agree this change I would create a PR 😄

**Comment by rappasoft** [comment]
Feel free to make a PR.
