### ISSUE TITLE
White border in dark-mode

### ISSUE THREAD

**Issue by REJack** [rappasoft/laravel-livewire-tables#614]
I found an other bug, related to the dark mode. 

![img](https://i.imgur.com/z4QhH8C.png)
![img](https://i.imgur.com/LIArAUU.png)

https://github.com/rappasoft/laravel-livewire-tables/blob/a52839d27d6f31a8b5c5fa77ead3baedcdaad752/resources/views/tailwind/components/table/table.blade.php#L11

I would remove bg-dark or add dark:bg-gray-800

**Comment by rappasoft** [comment]
Feel free to make a PR.
