### ISSUE TITLE
Add Tailwind CSS for default Laravel with Jetstream scaffold

### ISSUE THREAD

**Issue by christian-forgacs** [rappasoft/laravel-livewire-tables#62]
Currently the complete package is setup for bootstrap. With Laravel 8 the default scaffold for Jetstream is Tailwind CSS.

**Comment by NettSite** [comment]
Just been looking at the code, it doesn't seem to dictate any CSS framework, so it should work with Tailwind CSS as it is. I haven't tried it yet, but I will soon.

**Comment by rappasoft** [comment]
Right now it's pretty heavily tied to bootstrap. But the goal is to be able to change eventually.

**Comment by rappasoft** [comment]
Next version has the ability for different frontend scaffolds, but i've only built in bootstrap. Will need someone with tailwind knowledge to PR that.

**Comment by NettSite** [comment]
I have just started playing with Tailwind, so won't be able to do anything robust as of now. 

Quick question - in the "Table" trait, there are a number of functions which return null - I have overwritten them in my table component to return Tailwind classes as I require. Did you intend for them to be overwritten?

**Comment by rappasoft** [comment]
Yes all those are meant for you to have more control by overriding.
