### ISSUE TITLE
bulk action selection does not preserve search filter

### ISSUE THREAD

**Issue by Lupennat** [rappasoft/laravel-livewire-tables#625]
how to replicate the bug:

- no filter applied total records = 100
- filter results through search query, total records = 50
- select checkbox in the table head
- click select all (the number of selected elements respects the maximum number of filtered records 50)
- execute a bulk action
- the action is executed on all 100 records instead of 50 selected

possible solution:

```php
    /**
     * @return Builder|Relation
     */
    public function selectedRowsQuery()
    {
        $query = $this->query();

        return $query->when($this->selectAll,
            fn ($query) => $this->applySearchFilter($query),
            fn ($query) => $query->whereIn($query->qualifyColumn($this->primaryKey), $this->selected)
        );
    }
 ```

**Comment by bureauvk** [comment]
Can you show us your bulk method? Are you only applying changes to the selectedkeys?
I cant replicate this issue.

**Comment by Lupennat** [comment]
you can check it directly on the demo page https://tables.laravel-boilerplate.com/tailwind.
Type something in the search that reduces the number of users but has more than one page (like "er"), then click the checkbox next to "sort" and then "select all" on the bar. 
You will see X items selected, apply the "deactivate" bulk action, remove the search filter and you will see that all users are disabled instead of X.
