### ISSUE TITLE
Filter problem

### ISSUE THREAD

**Issue by Roomdada** [rappasoft/laravel-livewire-tables#629]
I use joins to perform filters with the reporting and I see that the table is not automatically updated. You have to refresh the page each time to see the result.

**Comment by Roomdada** [comment]
![Capture d’écran de 2022-01-28 21-34-36](https://user-images.githubusercontent.com/61591337/151624653-adb5929b-691d-4d76-8623-499c0b71e167.png)

Here is a capture of the query I made. When I perform the filter the results are not displayed immediately. And when there is nothing as a result, the message that says is displayed with results.

**Comment by Lupennat** [comment]
@Roomdada are you sure you are using the right syntax for the where of eloquent?
if you use `->whereState` you should not pass the column name, alternatively use `->where('state', $this->getFilter('state'))`

**Comment by Roomdada** [comment]
I'm using the package to manage spacy states and the documentation says to use whereState and additionally pass the column

**Comment by Lupennat** [comment]
Sorry @Roomdada, I didn't realise you were using an external package.
Have you tryied to debug queries when filter is applied, probably is a long time query.
Maybe this can help you to understand what happens
https://laravel.com/docs/8.x/database#listening-for-query-events

**Comment by Roomdada** [comment]
I tried queries with eloquent everything works perfectly I think the problem is hard with pure sql queries
