### ISSUE TITLE
Problem hiding a column based on a closure

### ISSUE THREAD

**Issue by woodspire** [rappasoft/laravel-livewire-tables#63]
This commit https://github.com/rappasoft/laravel-livewire-tables/commit/9808eaa7ac5c5972845535414e5d3db6454f43d7#diff-2ef2020b3a79c6d6648f9af7d16b32b0

cause problems when we add a component and use a closure to determine if we should hide or not a component.
Calling isHidden() on the column will try to return the closure, which is not a boolean.

Maybe pass the $models to isHidden and loop through them to test the closure ?

**Comment by rappasoft** [comment]
Right now it only supports a boolean.

**Comment by woodspire** [comment]
Might be a good idea to update the readme.

```
If you would like to hide all the components for a given row, you may pass a callback as the second parameter of the components() method:

Column::make('Actions')
    ->components([
        Link::make('Edit'),
        Link::make('Delete'),
    ], function($model) {
        // Hide the actions for model id 1
        return $model->id === 1;
    })
```

**Comment by rappasoft** [comment]
Thats specific to a component. I don't have the second param of the column a callback, it just has the trait to hide them now. I'll try to go through all of this and make it streamlined but it's still in development.
