### ISSUE TITLE
Feature Request: Add Support for Full-Page Components

### ISSUE THREAD

**Issue by KenLewis** [rappasoft/laravel-livewire-tables#64]
I'd like to be able to be able to do this: "If the main content of a page is a Livewire component, you can pass the component directly into a Laravel route as if it were a controller."

I've worked on this myself and was able to easily add `->layout()` both with and without parameters to the package. However, I got stuck when trying to implement `->slot()`. I'm sure it's a simple thing that I am overlooking. I've just currently run out of time to work on it for now. I'll come back to it when I have more time if no one else figures it out first.

Maybe I'm the only one who wants this. I just thought it'd be a good feature.

**Comment by KenLewis** [comment]
I think that issue I had with getting the `->slot()` to work was fixed the same day I created this feature request. [Livewire pull request 1588](https://github.com/livewire/livewire/pull/1588)

I'll test my code again this weekend and submit a pull request if it works.

**Comment by rappasoft** [comment]
Ok sounds good!

**Comment by KenLewis** [comment]
After some testing, I came to the conclusion that the best way to support the 4 livewire macros is to just override the `render` method of the `TableComponent` and then the 4 macros are automatically available.

However, it did occur to me that the "solution" would be to have an artisan make command that stubs out an example `TableComponent`. Of course it would have to "register" itself as a Livewire component too. Just an idea. 

Either way, I'm just going to close out the issue since technically speaking the requested functionality already exists.
