### ISSUE TITLE
Install on Laravel 9 Issue

### ISSUE THREAD

**Issue by Markwow** [rappasoft/laravel-livewire-tables#647]
Hi I am working on upgrading to Laravel 9 and I am currently running into an issue installing the package through composer:
 Problem 1
    - Root composer.json requires rappasoft/laravel-livewire-tables ^1.22 -> satisfiable by rappasoft/laravel-livewire-tables[v1.22.0].
    - rappasoft/laravel-livewire-tables v1.22.0 requires illuminate/contracts ^8.0 -> found illuminate/contracts[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    
I didnt have this issue on Laravel 8 so I figured it has to be related to Laravel 9

**Comment by rappasoft** [comment]
Laravel 9 is not supported yet. It's literally been out for a few hours.

**Comment by Markwow** [comment]
Can't blame a man for getting excited :)

**Comment by rappasoft** [comment]
I'll have it in this week!

**Comment by Markwow** [comment]
Thank you!
