### ISSUE TITLE
Upcoming 0.3 Rebuild

### ISSUE THREAD

**Issue by rappasoft** [rappasoft/laravel-livewire-tables#66]
I spent the last few days doing a semi-rebuild and removing some features I don't think I need right now. I need some people to test with the current development branch using the new README on that branch for guidance and report back on if you like this format better.

These are the current release points:

### Added

- Config file to choose frontend framework - currently limited to bootstrap
- Render method to columns which returns whatever you put into it, you can return a view, html, an attribute, etc.
- Pulled in and modified the HTML component library from laravelcollective so you an return html components from the render method. i.e.: $this->image(...);
- Added new loading config on whether to keep displaying the current data while loading or collapse it
- Added ability to set frontend framework specific options via a property on a per component basis.

### Changed

- Extracted the sorting icons out to their actual HTML, so you can use whatever you want, not limited to the 'i' tag.

### Removed

- Checkbox functionality for now
- Component functionality pending debate
- All class and styling based properties. It's better to publish the views to change something.

**I will probably merge this to master tomorrow, do not update if you are using components or checkboxes.**

**Comment by KenLewis** [comment]
I didn't have time to test it out today but I "should" tomorrow. I did look through the diff and I like the extra flexibility you allow. If this conversation is still open tomorrow, I'll provide some feedback from firsthand use.

Thanks for all your hard work on this!

**Comment by rappasoft** [comment]
Yes please do, I might end up doing a release tonight if I have time. I look forward to your feedback to make this as good as it can be!

**Comment by KenLewis** [comment]
After a couple of hours of working with it, here's my feedback.

Functionally, it works great and meets most of my needs. I really like the improved flexibility in the `Column` class.

However, here's a couple notes regarding the documentation for [Defining Columns](https://github.com/rappasoft/laravel-livewire-tables#defining-columns):

- The `make` method documentation is missing. It was in previous versions.
- The `format` method is expecting a `callable` but the docs show that it's expecting `Model` and `Column`.

That's all I've got for now. I do think it's a big improvement. I have other ideas for additional functionality that I haven't had much time to work on yet (e.g. #64). As soon as I'm able, I will add an issue with each idea to see if it's something you'd be interested in adding to the package before I start working on it.

Thank you for all your hard work building this!

**Comment by rappasoft** [comment]
Thanks I will fix the docs today! I'll try to look into your full page components issue.

**Comment by KenLewis** [comment]
I just noticed that the `Table` trait methods don't do anything. They all return `null` or `[]`. It was like that in the last version too, but we were able to access the properties. Now there are only 2 properties. I only noticed this now because I was working to "entangle" the table with my alpine code.

**Comment by rappasoft** [comment]
Are you overriding them on your table?

```
public function setTableHeadClass($attribute): ?string
    {
      if ($attribute === 'name') {
             return 'table-success';
     }

        return null;
    }
```

**Comment by KenLewis** [comment]
LOL ... It's been a long day. Didn't even occur to me. I guess it's time for a break.
