### ISSUE TITLE
Undefined variable $wireclick

### ISSUE THREAD

**Issue by Josefikos** [rappasoft/laravel-livewire-tables#680]
After last update package broke because of missing var called $wireclick

![image](https://user-images.githubusercontent.com/27228406/160665700-743b8ecd-8733-439a-b566-391904dcba46.png)

```blade
@props(['url' => null, 'target' => '_self', 'reordering' => false, 'customAttributes' => []])

@if (!$reordering && (method_exists($attributes, 'has') ? $attributes->has('wire:sortable.item') : array_key_exists('wire:sortable.item', $attributes->getAttributes())))
    @php
        $attributes = $attributes->filter(fn ($value, $key) => $key !== 'wire:sortable.item');
    @endphp
@endif

<tr
    {{ $attributes->merge($customAttributes)->merge(['style' => ($url || $wireclick) ? 'cursor: pointer;' : '']) }}

    @if ($url)
        onclick="window.open('{{ $url }}', '{{ $target }}')"
    @elseif ($wireclick)
        wire:click="{{ $wireclick }}"
    @endif
>
    {{ $slot }}
</tr>
```

Need to add wireclick to props?

**Comment by cytech** [comment]
same here
`@props(['url' => null, 'target' => '_self', 'reordering' => false, 'customAttributes' => [], 'wireclick' => null])
`
in row.blade.php gets past the error

**Comment by dinweb3** [comment]
same on my end.
![image](https://user-images.githubusercontent.com/46061736/160700340-3641d2a1-8809-4f03-9e8a-cf4e291e2823.png)

![image](https://user-images.githubusercontent.com/46061736/160700848-ea48c630-4a93-42fc-82e6-e37e1b152723.png)

**Comment by rappasoft** [comment]
Should be fixed, sorry.
