### ISSUE TITLE
Error: Cannot make static method Livewire\Component::getName() non static in class Rappasoft\LaravelLivewireTables\Views\Traits\Helpers\FilterHelpers

### ISSUE THREAD

**Issue by saagoor** [rappasoft/laravel-livewire-tables#684]
FilterHelpers trait's getName() method is conflicting with livewire component's getName() method.
I guess there's been a mix up between `Rappasoft\LaravelLivewireTables\Views\Traits\Helpers\FilterHelpers` & `Rappasoft\LaravelLivewireTables\Traits\Helpers\FilterHelpers` traits.

Please take a look at this.

_Getting this error on:_
Livewire v2.10.4
Laravel Framework v9.6.0
rappasoft/laravel-livewire-tables v2.0.0

**Comment by rappasoft** [comment]
I can not replicate.
