### ISSUE TITLE
[2.0] Method getAppliedFilter('column_name')` does not exist

### ISSUE THREAD

**Issue by mikemand** [rappasoft/laravel-livewire-tables#687]
I am in the process of upgrading a site from v1 to v2, and cannot continue. The upgrade guide says there is a new method for getting the applied filter, and links here: https://rappasoft.com/docs/laravel-livewire-tables/v2/filters/applying-filters#content-apply-filters-at-the-component-level

However, there is no method called `getAppliedFilter`. There is a [`getAppliedFilters`](https://github.com/rappasoft/laravel-livewire-tables/blob/139daaccddecf543e0a293115050d50660ca3505/src/Traits/Helpers/FilterHelpers.php#L187-L195) method with a docblock that suggests it would accept a parameter, but it doesn't actually use any parameters. It also returns applied filters for ALL columns.

**Comment by jijiezheng** [comment]
you can use `$this->getAppliedFilterWithValue('sth')` instend

**Comment by rappasoft** [comment]
> you can use `$this->getAppliedFilterWithValue('sth')` instend

This works, i'll update the documentation.
