### ISSUE TITLE
Custom classes & attributes do not apply to header unless 'sortable' is set

### ISSUE THREAD

**Issue by ConnorHowell1** [rappasoft/laravel-livewire-tables#69]
Classes & attributes do not apply to headers unless they are marked as sortable.
https://github.com/rappasoft/laravel-livewire-tables/blob/0f1d11cd99623196f8ae736300a32fd9f77f4415/resources/views/bootstrap-4/includes/columns.blade.php#L4-L26

Not sure of the best way to resolve other than duplicating the following:
https://github.com/rappasoft/laravel-livewire-tables/blob/0f1d11cd99623196f8ae736300a32fd9f77f4415/resources/views/bootstrap-4/includes/columns.blade.php#L6-L10

**Comment by rappasoft** [comment]
Ah that's a good catch, i'll make a patch in a bit.

Thanks

**Comment by rappasoft** [comment]
Tagged 0.3.1
