### ISSUE TITLE
Error: Undefined variable $dumpFilters

### ISSUE THREAD

**Issue by davidabadi** [rappasoft/laravel-livewire-tables#697]
I am getting an error Undefined variable $dumpFilters after upgrading to version 2.

**Comment by maurocordioli** [comment]
@davidabadi some internal view are changed , clear the view cache 
or if in case you  have published the vendor assets in the past for  the v1 version  now you have some obsolete views
so republish it... as  stated here
(https://rappasoft.com/docs/laravel-livewire-tables/v2/start/configuration#content-publishing-assets) 
or if you have not customized the vendor assets may be removing resources/views/vendor/laravel-livewire-tables tables could be a better solution as they are need only if you want to customize them... if that assets are not present in the vendor dir the package will use the private/default ones ...
