### ISSUE TITLE
date casts

### ISSUE THREAD

**Issue by rabol** [rappasoft/laravel-livewire-tables#7]
Not sure if it's a bug

I have a activity Model, and in the model I have this:

 ```
protected $casts = [
        'updated_at' => 'datetime',
        'created_at' => 'datetime',
        'activity_date' => 'date',
    ];

```

in the column is still rendered as date time and not as date only

**Comment by tanthammar** [comment]
This is a Laravel thing. I had the same issue, it is not due to this package.
