### ISSUE TITLE
how to create the serial number colum

### ISSUE THREAD

**Issue by hemant17** [rappasoft/laravel-livewire-tables#70]
how to create the serial number colum
like 
1
2
3
4
5
.
.
.

**Comment by rappasoft** [comment]
```
Column::make('ID')
    ->searchable()
    ->sortable(),
```

**Comment by hemant17** [comment]
> ```
> Column::make('ID')
>     ->searchable()
>     ->sortable(),
> ```

thanks for the reply sir but I were asking for like seiral number not the database id 
i mean that we normal use like count++

**Comment by rappasoft** [comment]
I don't know why you would need this.

**Comment by hemant17** [comment]
> I don't know why you would need this. What's the point of an incrementing number if you can't use it to identify a row?

yes sir some time you need that table data is for multiple users and multiple users are interesting the data in the database but when you show it to the user to look like 5,56,64 more like that which is not good 
so I want to show them like the 1,2,3

**Comment by hemant17** [comment]
> > I don't know why you would need this. What's the point of an incrementing number if you can't use it to identify a row?
> 
> yes sir some time you need that table data is for multiple users and multiple users are interesting the data in the database but when you show it to the user to look like 5,56,64 more like that which is not good
> so I want to show them like the 1,2,3

why closed  ?

**Comment by jazz7381** [comment]
why this issue is closed?

**Comment by ikramsyakir** [comment]
> ```
> Column::make("Id", "id")->format(fn () => ++$this->index +  ($this->page - 1) * $this->perPage),
> ```
> 
> use this where you need index no or numbering

using label instead of formatting because its not associated with a database column.
