### ISSUE TITLE
Loading only one instance of relationship

### ISSUE THREAD

**Issue by davidabadi** [rappasoft/laravel-livewire-tables#701]
I have a model called order which belongs to user and approvedBy (both instances of the same model). When displaying the name for both it only displays the name for the column that is placed above. 

ie.

```
Column::make('Created By', 'user.name')
    ->searchable()
    ->sortable(),

Column::make('Approved By', 'approvedBy.name')
    ->searchable()
    ->sortable(),
```
in this example both columns will show the name of the user.name. If I invert the order (put approvedBy.name) on top it will show approvedBy.name for both columns.

**Comment by pablomadariaga** [comment]
Rappa I think that to solve this problem, you should allow aliases to be configured for each table that is presented within the query, be it the main table or the relationship tables.

I have a relationship of a column in the same users table to know who invited them to join my platform, and this generates the error:

`SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'users'`

When trying to perform this query:

`select count(*) as aggregate from `users` left join `users` on `users`.`referrer_id` = `users`.`id``

That is why I think that if the aliases of each table could be configured, the problem would be solved, if there is already a solution at the code level, I would like to receive a bit of your experience.

You did an excellent job, thank you for this wonderful tool.
@rappasoft

**Comment by rappasoft** [comment]
Is this a duplicate of: https://github.com/rappasoft/laravel-livewire-tables/issues/688?

**Comment by davidabadi** [comment]
Yes. I'll close it
