### ISSUE TITLE
HtmlComponents seems to be missing

### ISSUE THREAD

**Issue by jeff-crosby** [rappasoft/laravel-livewire-tables#71]
Love this package. I have been using it without issue for a couple of months, but now I am trying to use `format` to render `linkRoute` output in a cell by following the instructions at https://github.com/rappasoft/laravel-livewire-tables#html-components

I get an error that HtmlComponents cannot be found. When I grep the package under vendor/rappasoft, I don't see it anywhere. Removing its inclusion then throws an error that the format function is undefined. I ran composer update to ensure I was testing against the latest version.

When I comment out `format` and `HtmlComponents`, the below code works just fine. Any help would be greatly appreciated.

```
	public function columns() : array
	{
		return [
			Column::make('User', 'user.full_name')->customAttribute()
				->searchable()
				->sortable(),
				/*->format(function ($model) {
					return $this->linkRoute('admin.users.edit', $model->user->full_name, $model->user_id);
				}),*/
			Column::make('Status', 'status')
				->searchable()
				->sortable()
				->view('admin.subscriptions.includes.status'),
			Column::make('Product', 'product.name_short')
				->searchable()
				->sortable(),
			Column::make('Pricing Tier', 'price.label')
				->searchable()
				->sortable()
				->view('admin.subscriptions.includes.price'),
			Column::make('Start Date', 'created_at')
				->searchable()
				->sortable()
				->view('admin.subscriptions.includes.created_at'),
			Column::make('Actions')
				->view('admin.subscriptions.includes.actions'),
		];
	}
```

**Comment by rappasoft** [comment]
That feature is only available in 0.3, which was re-written. You'll have to rewrite your table as such (it probably needs tweaks):

`public function columns() : array
{
	return [
		Column::make('User', 'full_name')
			->searchable()
			->sortable(),
			->format(function ($model) {
				return $this->linkRoute('admin.users.edit', $model->user->full_name, $model->user_id);
			}),
		Column::make('Status')
			->searchable()
			->sortable()
      ->format(function ($model) {
				return view('admin.subscriptions.includes.status');
			}),
		Column::make('Product', 'product.name_short')
			->searchable()
			->sortable(),
		Column::make('Pricing Tier', 'price.label')
			->searchable()
			->sortable()
      ->format(function ($model) {
				return view('admin.subscriptions.includes.price');
			}),
		Column::make('Start Date', 'created_at')
			->searchable()
			->sortable()
      ->format(function ($model) {
				return view('admin.subscriptions.includes.created_at');
			}),
		Column::make('Actions')
      ->format(function ($model) {
				return view('admin.subscriptions.includes.actions');
			}),
	];
}`

**Comment by jeff-crosby** [comment]
Initially, your recommended code change threw me because `format` was the call giving me errors, but when I looked again at the output from `composer update` I had seen this package update from 0.2.0 to 0.2.1 and I see the rule on composer.json is using ^0.2.0 so it wasn't willing to grab the 0.3 versions.

I changed that to ^0.3.0 to grab the latest version right now and I see it no longer supports the `view` function within the package. I see the `customAttribute()` call is no longer needed/supported as well.

The only thing I had to change from your snippet was to explicitly pass `$model` to each `view` call now, but I'll probably refactor these to get rid of all/most of these sub-views now. Thanks!

```
	public function columns() : array
	{
		return [
			Column::make('User', 'full_name')
				->searchable()
				->sortable()
				->format(function ($model) {
					return $this->linkRoute('admin.users.edit', $model->user->full_name, $model->user_id);
				}),
			Column::make('Status', 'status')
				->searchable()
				->sortable()
				->format(function ($model) {
					return view('admin.subscriptions.includes.status', ['model' => $model]);
				}),
			Column::make('Product', 'product.name_short')
				->searchable()
				->sortable(),
			Column::make('Pricing Tier', 'price.label')
				->searchable()
				->sortable()
				->format(function ($model) {
					return view('admin.subscriptions.includes.price', ['model' => $model]);
				}),
			Column::make('Start Date', 'created_at')
				->searchable()
				->sortable()
				->format(function ($model) {
					return view('admin.subscriptions.includes.created_at', ['model' => $model]);
				}),
			Column::make('Actions')
				->format(function ($model) {
					return view('admin.subscriptions.includes.actions', ['model' => $model]);
				}),
		];
	}
```

**Comment by rappasoft** [comment]
Glad it worked out!
