### ISSUE TITLE
Sortable enforces Uppercase styling for headings

### ISSUE THREAD

**Issue by Ceepster14** [rappasoft/laravel-livewire-tables#719]
When typing a column as sortable, the heading automatically gets the 'uppercase' style which can't be overridden using the config attributes. This is not always appropriate as sometimes the casing on the column header can convery important information to the user, so I think it would be better if the uppercase was not imposed automatically, but could be managed through the config attributes if required?

**Comment by rappasoft** [comment]
Configurable in v2.4
