### ISSUE TITLE
how to create the serial number colum

### ISSUE THREAD

**Issue by hemant17** [rappasoft/laravel-livewire-tables#72]
able data is for multiple users and multiple users are interesting the data in the database but when you show it to the user to look like 5,56,64 more like that which is not good
so I want to show them like the 1,2,3

**Comment by ConnorHowell1** [comment]
Looking at the source it wouldn't currently be possible to show the index of the current item as a column in the table.

A PR could be made for this however I'm not sure how useful it would be as the whole point of this package is to filter, search & paginate data and the index would change when these functions are performed. 
Pagination could be overcome by using the pagination 'from' field and adding the current item index. But as soon as you sort/search the data the items would not retain their serial number.

@rappasoft Not sure what the best way to implement this would be; maybe this could be added as a property on the table component?

**Comment by rappasoft** [comment]
These requests literally make no sense to me. There is no use for this feature.

**Comment by hariadi** [comment]
I think you can do like this. Feel free to modify:

```php
public function mount()
{
    $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;
}


public function columns(): array
{
    return [
        Column::make(__('No.'))
            ->format(fn () => ++$this->index),
        //...
    ];
}
```

**Comment by hemant17** [comment]
> I think you can do like this. Feel free to modify:
> 
> ```
> public function mount()
> {
>     $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;
> }
> 
> 
> public function columns(): array
> {
>     return [
>         Column::make(__('No.'))->format(fn () => ++$this->index),
>         //...
>     ];
> }
> ```

![image](https://user-images.githubusercontent.com/10548023/94299821-09192a00-ff1d-11ea-8f61-fc59b4088e4e.png)
it's showing but when I delete the row with the action button it shows me this error

**Comment by hariadi** [comment]
> > I think you can do like this. Feel free to modify:
> > ```
> > public function mount()
> > {
> >     $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;
> > }
> > 
> > 
> > public function columns(): array
> > {
> >     return [
> >         Column::make(__('No.'))->format(fn () => ++$this->index),
> >         //...
> >     ];
> > }
> > ```
> 
> ![image](https://user-images.githubusercontent.com/10548023/94299821-09192a00-ff1d-11ea-8f61-fc59b4088e4e.png)
> it's showing but when I delete the row with the action button it shows me this error

Since pagination changes, just declare your index/serial and move implementation to ```columns``` directly:

```php

protected $index = 0;


public function columns(): array
{
    $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;

    return [
        Column::make(__('No.'))->format(fn () => ++$this->index),
        //...
    ];
}
```

**Comment by hariadi** [comment]
The easy way, just add to your view (e.g. `row.blade.php`):
```blade
<x-livewire-tables::bs5.table.cell>
    {{ ($this->page > 1 ? ($this->page - 1) * $this->perPage : 0) + $loop->iteration }}
</x-livewire-tables::bs5.table.cell>
```

**Comment by PamungkasRizall** [comment]
> > > I think you can do like this. Feel free to modify:
> > > ```
> > > public function mount()
> > > {
> > >     $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;
> > > }
> > > 
> > > 
> > > public function columns(): array
> > > {
> > >     return [
> > >         Column::make(__('No.'))->format(fn () => ++$this->index),
> > >         //...
> > >     ];
> > > }
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/10548023/94299821-09192a00-ff1d-11ea-8f61-fc59b4088e4e.png)
> > it's showing but when I delete the row with the action button it shows me this error
> 
> Since pagination changes, just declare your index/serial and move implementation to `columns` directly:
> 
> ```
> protected $index = 0;
> 
> 
> public function columns(): array
> {
>     $this->index = $this->page > 1 ? ($this->page - 1) * $this->perPage : 0;
> 
>     return [
>         Column::make(__('No.'))->format(fn () => ++$this->index),
>         //...
>     ];
> }
> ```

why in version 3 **$this->page** not found?

**Comment by Hans-Star18** [comment]
in version 3 user $this->getPage()

**Comment by Hans-Star18** [comment]
i make traits for numbering

`
namespace App\Traits\Livewire;

use Rappasoft\LaravelLivewireTables\Views\Column;

trait WithTableNumbering
{
    protected int $index = 0;

    public function numberingColumn(): Column
    {
        return Column::make(__('No.'))
            ->label(function () {
                $this->initializeIndex();
                return ++$this->index;
            });
    }

    protected function initializeIndex(): void
    {
        if ($this->index === 0) {
            $this->index = $this->getPage() > 1 ? ($this->getPage() - 1) * $this->perPage : 0;
        }
    }
}
`

dan in livewire datatables 

`
use App\Traits\Livewire\WithTableNumbering;

class UsersTable extends DataTableComponent
{
    use WithTableNumbering;

    protected $model = User::class;

    public function columns(): array
    {
        return [
            $this->numberingColumn()
                ->sortable(),
            .....
        ];
    }
}

`
