### ISSUE TITLE
Filter Drop Down open after sorting

### ISSUE THREAD

**Issue by AdamKyle** [rappasoft/laravel-livewire-tables#721]
I am not sure if this is a me issue or a library issue but heres how to replicate:

I created a component: `admin.items.item-table` which looks like:

```
<?php

namespace App\Flare\View\Livewire\Admin\Items;

use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use App\Flare\Models\Item;
use Rappasoft\LaravelLivewireTables\Views\Filters\SelectFilter;

class ItemsTable extends DataTableComponent {

    public function configure(): void {
        $this->setPrimaryKey('id');
    }

    public function builder(): Builder {
        return Item::whereNotIn('type', ['quest', 'alchemy'])
            ->whereNull('item_prefix_id')
            ->whereNull('item_suffix_id')
            ->when($this->getAppliedFilterWithValue('types'), fn ($query, $type) => $query->where('type', $type));
    }

    public function filters(): array {
        return [
            SelectFilter::make('Types')
                ->options([
                    'weapon'        => 'Weapons',
                    'bow'           => 'Bows',
                    'body'          => 'Body',
                    'helmet'        => 'Helmets',
                    'shield'        => 'Shields',
                    'sleeves'       => 'Sleeves',
                    'gloves'        => 'Gloves',
                    'leggings'      => 'Leggings',
                    'feet'          => 'Feet',
                    'ring'          => 'Rings',
                    'artifact'      => 'Artifacts',
                    'spell-healing' => 'Healing Spells',
                    'spell-damage'  => 'Damage Spells',
                ]),
        ];
    }

    public function columns(): array {
        return[
            Column::make('Name')->searchable(),
            Column::make('Type')->searchable()->format(function ($value) {
                return ucfirst(str_replace('-', ' ', $value));
            }),
            Column::make('Min Crafting Lv.', 'skill_level_required')->sortable(),
            Column::make('Trivial Crafting Lv.', 'skill_level_trivial')->sortable(),
            Column::make('Cost')->sortable()->format(function ($value) {
                return number_format($value);
            }),
        ];
    }
}
```

This table loads fine, and I can filter fine. But if I then attempt to sort the filter drop down will open. Clicking away, will not close the filter drop down.

I have not made any changes to the view files other then adding some slight padding to the search element.

If I filter, with out sorting it works fine.

Nothing else causes this issue other then sorting any column, the minute you sort the minute the filter box opens up.

## Steps To Replicate

- Create a table with sorting and filtering
- Sort the table

I cannot see any other javascript library messing with this, and I have the latest alpine library as well.

Thoughts?

**Comment by arwanfiles** [comment]
I have same issue.

**Comment by rappasoft** [comment]
These are hard to figure out because I can never understand what in Livewire causes these issues as they don't happen for me.

**Comment by AdamKyle** [comment]
@rappasoft  My exploration of the view files, points to the way you check for filters in the tool bar blade. You have a method, Cannot remember off the top of my head, that checks if we have filters and if we should show them. I think, and you know the code better then I, that the issue might lay with in that check or set of code.

Is it possible that the filter code and the sorting code, for the UI, are conflicting? Because this only happens when you sort. Now it could be live wire, it could be alpine, but you have this check to see if we should open the filter where you set the filter attributes to say open, if you inspect the page after sorting, you see two things:

`{open: false}` on the filter element it's self.

But the filter has been opened, so something is triggering it around the sorting aspect. I, my self for my own sanity, am looking into this and if I find the answer I will post it here, but it seems to be connected to sorting some how.

**Comment by ansien** [comment]
Same here :(

**Comment by lvismer** [comment]
@rappasoft It is the same behaviour on your [Tailwind demo](https://tables.laravel-boilerplate.com/tailwind). Just click the *name* field for ordering and the **filter** opens up and one cannot close it or get around it.

**Comment by marcheffels** [comment]
Hi. I found out by accident that if I disable sorting pills, the error no longer occurs. Maybe that helps to better understand the issue.

`$this->setSortingPillsDisabled();`

**Comment by pnm1231** [comment]
I've just upgraded the package to v2.7.0, but the issue still exists.
