### ISSUE TITLE
Column search does not reset pagination.

### ISSUE THREAD

**Issue by ansien** [rappasoft/laravel-livewire-tables#733]
How to reproduce:

1. Go to page 10 of your table.
2. Do a column search for something that has less than 10 pages of results.
3. Table will still be on page 10 while results are on the pages 1-5 for example.

Global searching does not have this behaviour and does what is expected (resets pagination).

**Comment by rappasoft** [comment]
Column search is not part of the package, you will have to clear pagination yourself. I'd suggest calling `$this->resetPage()` when filtering the column.
