### ISSUE TITLE
setThAttributes() Has no effect on the text in header when the column has filtering enabled

### ISSUE THREAD

**Issue by inmanturbo** [rappasoft/laravel-livewire-tables#742]
This is cause by the same underlying issue as https://github.com/rappasoft/laravel-livewire-tables/issues/719

`th` classes on `sortable` columns have no effect. 

The following line is hard coding the classes on the sort button:

https://github.com/rappasoft/laravel-livewire-tables/blob/6e30f7c510bc5f08eb53cf776de57634e29b554e/resources/views/components/table/th.blade.php#L24

Options to fix: 
1. Add another method to call from `configure`  like `setSortButtonAttributes` 
2. Merge or override classes from the `$customAttributes` set in `setThAttributes`. 
3. Leave out the duplicated classes that are targeting the `text` and inherit them, or I should say let them cascade from the `th` parent.

Options 3 may be the simplest. However I am not 100% on the predictability as to which classes would or should actually affect the text inside the button, and this may not always achieve the desired outcome. 

Option 2 may not be the cleanest. The class lists aren't identical so the `happy medium` might need to be found somehow between text targeting and block targeting classes.

Perhaps the most elegant solution would be to use option one, and also explode the button into another blade view, or `component` as it were, rather than adding another `$customAttributes` variable to the `th` `component`. `$customSortButtonAttributes` ? :shrug: 

@rappasoft  Will you be accepting PR's for this issue? 

P.S (Added)
I would like to mention: aside from his little quirk the new configure api in `v2` is just very very nice. Thank you for that!

**Comment by rappasoft** [comment]
Did you try removing the default though? It's a conditional, unless I'm misunderstanding the issue:

`->class(['px-6 py-3 text-left text-xs font-medium whitespace-nowrap text-gray-500 uppercase tracking-wider dark:bg-gray-800 dark:text-gray-400' => $customAttributes['default'] ?? true])`

```
$this->setThAttributes(function(Column $column) {
     return [
        'class' => 'bg-green-500',
        'default' => false,
      ];
  });
```

**Comment by inmanturbo** [comment]
@rappasoft yes you are misunderstanding the issue, which is understandable :sweat_smile:  The classes for the `th` element itself are indeed conditional. However the classes on the `button` that is used for sorting are not
```blade
        @unless ($component->sortingIsEnabled() && $column->isSortable())
            {{ $column->getTitle() }}
        @else
            <button
                wire:click="sortBy('{{ $column->getColumnSelectName() }}')"
                class="flex items-center space-x-1 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider group focus:outline-none dark:text-gray-400"
            >
```
This button wraps the text in the header if sorting is enabled for the column, and overrides the custom classes set in the parent `th` with hard coded defaults (many of which are the same as the defaults in the `th`). Calling your snippet above will set a green background on all columns headers, yes. But you can't change the font on any of the `sortable` columns. 

Consider the following:
```php
$this->setThAttributes(function(Column $column) {
     return [
        'class' => 'bg-green-500 text-blue-500',
        'default' => false,
      ];
  });
```
![Filters](https://user-images.githubusercontent.com/47095624/165961358-2e384b19-359d-4885-899c-7a1b0e6b7614.png)

This makes it difficult to customize the styles in the header if you are using sorting, As you are stuck with the default colors in the text on sortable columns, which can be difficult to see with other backgrounds, etc. It also affects alignment, which can be clearly observed by adding a `text-right` class:

```php
            $this->setThAttributes(function(Column $column) {
                return [
                   'class' => 'bg-green-500 text-blue-800 text-right',
                   'default' => false,
                 ];
             });
```

![filter-align](https://user-images.githubusercontent.com/47095624/165962416-83f36162-d0e7-4afe-890f-507d1f6e8d67.png)

```diff
            Column::make('E-mail', 'email')
-                ->sortable()
+              // ->sortable()
```
Note: in the above screenshot I remove the sortable option from the `email` `column` in the demo

**Comment by rappasoft** [comment]
Oh ok, so the easy fix then is just to add `setSortButtonAttributes` with the same defaulting conditional?

**Comment by rappasoft** [comment]
Sorry I didn't get to this yet, but can you do me a favor since you I'm assuming you have a few tables built with this thing. Can you pull `v2-query-rework` and see if it breaks any of your stuff? No rush, I just reworked a few things to get the mount methods to work because I had the lifecycle hooks out of order. Here's the commit: https://github.com/rappasoft/laravel-livewire-tables/commit/bce28db3c710c172b4e0e17c0e4102c241512e0d

I'm trying to make extra sure I can actually make it a minor release and not a major, I think it's backwards compatible.

**Comment by inmanturbo** [comment]
Yes I actually was browsing through the branches the other day and noticed you to were working on the query stuff. Lol. I'll have a look when I get a chance. I was actually going to try it out yesterday because I think it's going to help me with some things as well, but I got busy.

**Comment by rappasoft** [comment]
Yeah, no rush at all, all the tests are still passing but I don't remember if I got in-depth at all with testing the query stuff. This version has 339 tests so far but it's still far away from being fully tested.

**Comment by rappasoft** [comment]
Soso for this issue: https://github.com/rappasoft/laravel-livewire-tables/commit/b39afed2cc71c4e4d67c6c127dbb5d26ab9202ff

**Comment by inmanturbo** [comment]
I've just clicked through and did some searches on my most complex and largest table. No issues. All I did on the others was run the ci's with tests. No errors.

I should note though that don't have any tables with relationships. These are huge tables and I mostly just aggregate the data flatten the views into an `eventually consistent` read model by running and caching complex queries (and some external api calls) inside Sushi models that get updated at the end of each day.

Oh! I'll pull again. lol

**Comment by rappasoft** [comment]
FYI this issue is on `develop` in case you didn't see.

**Comment by inmanturbo** [comment]
Yeah. I just ran develop too. everything looks good on my end. And the sort buttons are configurable!

**Comment by rappasoft** [comment]
Cool just need to fix the tests and then I'll merge in the query stuff.

**Comment by inmanturbo** [comment]
only tried one repo with deveop. But they are mostly using similar features. Like I said though: no relationships, I didn't look to see if you are testing for those in any of your tests

**Comment by rappasoft** [comment]
Yeah, I'm working with the demo table which has a 4x nested relationship and it's working. Given they are the simplest type of relationship but that's the only one I currently have out-of-the-box support for anyway. Better query support soon hopefully I just have to learn or find a good example of someone else who's done it.

**Comment by inmanturbo** [comment]
I might tinker with some query stuff at some point soon. If I make any headway I'll share my findings in a discussion. I was thinking of taking a look at that some point because I thought it might be nice to be able to tap the query, to write in support for things like writing `filtername:searchterm` in the search box, or even `columnname:searchterm%` on a given table.

**Comment by inmanturbo** [comment]
just fyi when you release it should also close #719

**Comment by rappasoft** [comment]
> I might tinker with some query stuff at some point soon. If I make any headway I'll share my findings in a discussion. I was thinking of taking a look at that some point because I thought it might be nice to be able to tap the query, to write in support for things like typing `filtername:searchterm` in the search box, or even `columnname:searchterm%` on a given table. 

When I get home I'll make you a collaborator and a branch and we can both play. You've been with this since the beginning anyway.

**Comment by rappasoft** [comment]
v2.4 merged.
