### ISSUE TITLE
Can't run `php artisan view:cache` with version 2 of the package.

### ISSUE THREAD

**Issue by sbrow** [rappasoft/laravel-livewire-tables#746]
Worked fine with v1, but now I get this:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6729162/165586738-1fb53e9d-eb5a-47da-bf81-5de9783bff7f.png">

**Comment by rappasoft** [comment]
I can successfully run the command on all my projects using v2. Sounds like you have something else getting in the way.

**Comment by sbrow** [comment]
For others experiencing this issue, I still had a view that referenced the v1 component names. Deleting the view solved it for me.

```blade
    <x-livewire-tables::bs4.table.cell>
        {{ $row->ip_address }}
    </x-livewire-tables::bs4.table.cell>
```

Sorry for the trouble.
