### ISSUE TITLE
export button as a new feature?

### ISSUE THREAD

**Issue by Fredericld** [rappasoft/laravel-livewire-tables#75]
HI,

I would be great if we could add a feature to export records as CSV or XLS,...

**Comment by rappasoft** [comment]
That would definitely be a good feature. I'll add it to my list.

**Comment by rappasoft** [comment]
So I decided to take a crack at it (Don't mind the test data and formatting): https://a.uguu.se/tyoorj.mov

It has features like excluding columns from the export, formatting the column specifically for the export, and maybe a few other things.

Still a WIP.

**Comment by Fredericld** [comment]
That looks pretty good.
I think if anyone wants to carry this to a real life application, we would need to be able to indicate in the code what field we need from the model(s).

**Comment by rappasoft** [comment]
Right now it just takes whatever's defined as the columns, but I think i'll add support to add columns only to be included in the export.

**Comment by rappasoft** [comment]
I advise you to pull in develop and look at the readme. You should be able to do what you need if you don't want to wait until it's tagged.

**Comment by rappasoft** [comment]
Tagged
