### ISSUE TITLE
setTdAttributes row has null id

### ISSUE THREAD

**Issue by michele-grifa** [rappasoft/laravel-livewire-tables#752]
I'm using setTdAttributes method to add some classes to the cells and i also need to access the row to take the id, but for some reason the id is always null.

The Model Class
```php
class Anagrafica extends Model
{
    use HasFactory;

    protected $table = "anagrafiche";

    public $timestamps = true;
    protected $primaryKey = 'id';

    protected $visible = [];

    protected $hidden = [];
    ...
}
```

The DataTable Class
```php
$this->setTdAttributes(function(Column $column, $row, $columnIndex, $rowIndex) {
            if($column->isField('codice')) {
                return [
                    'default' => true,
                    'class' => 'some-class',
                    'wire:click' => "\$emit('showModal', 'test-modal', " . $row->id . ")"
                ];
            }
            else {
                return [
                    'default' => true,
                    'class' => 'some-class'
                ];
            }
        });
```

Laravel Version: 8.83.10
Laravel Livewire Tables Version: 2.4.0

**Comment by rappasoft** [comment]
Is the column selected? By default you only have properties available to the columns you have specified. If you want more you have to add them with [setAdditionalSelects](https://rappasoft.com/docs/laravel-livewire-tables/v2/datatable/available-methods#content-setadditionalselects)

**Comment by michele-grifa** [comment]
Thanks, i used that method and it worked.
