### ISSUE TITLE
When using Turbolinks the component elements don't work again

### ISSUE THREAD

**Issue by nakigami** [rappasoft/laravel-livewire-tables#76]
I used Turbolinks to build an SPA using Livewire, and for each tab i include a livewire component one of them is a Table of this package, but when i click on a tab and return to the tab where the table exists, it's elements don't work like the search, the number of items in the page ...etc i have to refresh the page to get it working again

**Comment by rappasoft** [comment]
I don't use turbolinks i'm going to need someone else to attempt to diagnose this one.

**Comment by ConnorHowell1** [comment]
Not 100% sure why this happens but as a workaround you can add the following to any page that uses this package:
```javascript
document.addEventListener('turbolinks:load', () => {
    window.livewire.rescan()
})
```
In my testing this fixed this issue?

**Comment by nakigami** [comment]
> Not 100% sure why this happens but as a workaround you can add the following to any page that uses this package:
> 
> ```js
> document.addEventListener('turbolinks:load', () => {
>     window.livewire.rescan()
> })
> ```
> 
> In my testing this fixed this issue?

I WOULD LIKE TO SAY ONE WORD TO YOU : THANK YOU SO MUCH !!! This is working 100%
