### ISSUE TITLE
Unable to pass parameters to configurable areas

### ISSUE THREAD

**Issue by michele-grifa** [rappasoft/laravel-livewire-tables#762]
I'm using the code from the documentation to pass a parameter to a configurable area, but when i load the page i get the following error
```php
Rappasoft\LaravelLivewireTables\DataTableComponent::getConfigurableAreaFor(): Return value must be of type ?string, array returned (View: /var/www/resources/views/vendor/livewire-tables/components/tools/toolbar.blade.php)
```

The code i'm using:
```php
$this->setConfigurableAreas([
  'toolbar-left-end' => [
      'anagrafiche.anagrafiche-toolbar-left', [
          'testata' => 'test',
      ],
  ],
])
```

**Comment by rappasoft** [comment]
The location is the key, not the first parameter:

```php
'anagrafiche.anagrafiche-toolbar-left' => [
      'testata' => 'test',
],
```

**Comment by michele-grifa** [comment]
I was using 2.4.0, and now i updated to 2.6.0. That problem is gone, but i get `Undefined variable $testata` in the blade file

**Comment by rappasoft** [comment]
Hmm I have no issues, do you have the views published?

**Comment by michele-grifa** [comment]
Yes i have

**Comment by rappasoft** [comment]
You shouldn't, delete them and it will work. Publishing the views should only be used if you really need to edit a file, and even in that case, only publish the files you need because Laravel uses them over mine so If I update them you don't get the changes.

**Comment by michele-grifa** [comment]
Ok, now it works.

How i can publish only one file if i need?

**Comment by rappasoft** [comment]
Just delete the published files you don't need.

**Comment by michele-grifa** [comment]
Thanks
