### ISSUE TITLE
Weird search bug that happens only in > v2.5

### ISSUE THREAD

**Issue by ansien** [rappasoft/laravel-livewire-tables#773]
Hey,

I've been running into a really weird bug with column searching. I know this officially isn't part of the bundle, but it's definitely related to something that changed between v2.4 and v2.5.

When I'm using column searching with the following tailwind component `input-search.blade.php` from the demo project:

```
<div class="flex rounded-md shadow-sm">
    <input
        wire:model="columnSearch.{{ $field }}"
        placeholder="Search {{ ucfirst($field) }}"
        type="text"
        class="block w-full border-gray-300 rounded-md shadow-sm transition duration-150 ease-in-out sm:text-sm sm:leading-5 dark:bg-gray-800 dark:text-white dark:border-gray-600 @if (isset($columnSearch[$field]) && strlen($columnSearch[$field])) rounded-none rounded-l-md focus:ring-0 focus:border-gray-300 @else focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 rounded-md @endif"
    />

    @if (isset($columnSearch[$field]) && strlen($columnSearch[$field]))
        <span wire:click="$set('columnSearch.{{ $field }}', null)" class="inline-flex items-center px-3 text-gray-500 border border-l-0 border-gray-300 cursor-pointer bg-gray-50 rounded-r-md sm:text-sm dark:bg-gray-700 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
            </svg>
        </span>
    @endif
</div>
```

What happens after entering something into the search field is that the data in the table is always one state behind compared to what it should be.

Search in 2.4 (correct - #D-00000000 is not showing):
![image](https://user-images.githubusercontent.com/1700132/168053964-d3f0360c-2c32-4a82-a147-75a188e58bfa.png)

Search in 2.5 (incorrect - #D-00000000 should not be shown):
![image](https://user-images.githubusercontent.com/1700132/168053759-d1f26180-fed8-4e61-b2a6-199e4a241bbb.png)

In 2.4 the problem does not happen. In both instances the Livewire debug extension shows the correct value. But something seems to go wrong when applying the search.

Thanks!

**Comment by rappasoft** [comment]
Since column search was never really a supported feature and more of a hack, you should update to the latest version and use the new header and footer filters which are the native support.

**Comment by inmanturbo** [comment]
@ansien can you please confirm whether updating and using the new builtin header column with search fixes this for you?

**Comment by ansien** [comment]
> @ansien can you please confirm whether updating and using the new builtin header filter with search fixes this for you?

Have about 200 tables using the old way. So kinda hard to upgrade right now haha. But I'll run some tests in the coming week.
