### ISSUE TITLE
Wierd Behaviour in Sorting Column

### ISSUE THREAD

**Issue by pirex360** [rappasoft/laravel-livewire-tables#778]
Hi, 

I cannot sort by a date column, it adds another column with the same name, triggering [SQL Server]Ambiguous column name error.

Example of my builder:

```
    public function builder(): Builder
    {
        return Order::query()
            ->select('stamp','st_tabct','st_tabof','st_tabofop', 'st_tabpr', 'data_inicio', 'u_tabmo')
            ->withNoLock()
            ->with('workcenter:stamp,codct,descricao')
            ->with('operation:st_tabof,numof,prioridade,numop,descricao,cod_art,desc_art')
            ->with('stop')
            ->with('user_stop:nomeutil')
            ->OpenStop();
    }
```

Now my column ('data_inicio' column comes from the Order model with no relationship ):
```

    public function columns(): array
    {

        return [
            Column::make('Data Início', "data_inicio")
                ->sortable()
                ->searchable()
                ->format(function($value) {
                    return Carbon::parse($value)->format('d/m/Y H:i:s');
                }),


        ];
```

Initial renders well
![image](https://user-images.githubusercontent.com/17271768/168442578-05222188-1bbe-42ec-8d92-c05d04bdb80c.png)

Now when I click on the column sorting:

![image](https://user-images.githubusercontent.com/17271768/168442684-cec4af56-081f-40b6-b32b-d258048fabc1.png)

It adds another `data_inicio` alias on the query at the end, I don't get it.

What is my mistake, I'm lacking anything?

**Comment by rappasoft** [comment]
You are selecting it and then using it as a column, which selects it twice. Remove it from your select statement and the column will do it automatically.

**Comment by pirex360** [comment]
Thanks for your reply...

So in the builder, I don't need to select the fields needed for the table creation?

If so, how can I efficient work with the model? because the model could have 40 fields, and the table only needed 5 fields... is the Builder loading all the fields ? Same with the relationships `->with(table:fields,...) ? 

Or the builder only gets the fields that I put into the `columns() `function?

```
        return Order::query()
            ->select('stamp','st_tabct','st_tabof','st_tabofop', 'st_tabpr', 'data_inicio', 'u_tabmo')
            ->withNoLock()
            ->with('workcenter:stamp,codct,descricao')
            ->with('operation:st_tabof,numof,prioridade,numop,descricao,cod_art,desc_art')
            ->with('stop')
            ->with('user_stop:nomeutil')
            ->OpenStop();
```

**Comment by rappasoft** [comment]
The table will automatically only select the fields that are related to columns, do if you need more selects you can do as you are or use the `[setAdditionalSelects()](https://rappasoft.com/docs/laravel-livewire-tables/v2/datatable/available-methods#content-setadditionalselects)` configuration method. Any relational columns (only hasOne or belongsTo) will automatically join the necessary tables, and you can eagar load them by using `[eagerLoadRelations()](https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-eager-loading-relationships)` on the column, or by [eager loading them all](https://rappasoft.com/docs/laravel-livewire-tables/v2/datatable/available-methods#content-seteagerloadallrelationsenabled) on the component.

**Comment by pirex360** [comment]
Thank you ;)
