### ISSUE TITLE
How to refresh the page after delete a row?

### ISSUE THREAD

**Issue by Fredericld** [rappasoft/laravel-livewire-tables#78]
Hi,

Could you explain how I can refresh the datagrid when I delete an item from my datagrid (which I currently do using jquery ajax)? 
If using jquery/ajax is not good, please suggest an alternative

**Comment by rappasoft** [comment]
Hmm maybe you can use [alpine](https://laravel-livewire.com/docs/2.x/alpine-js) along with the [$refresh](https://ryangjchandler.co.uk/articles/manually-refreshing-a-livewire-component) variable somehow?

**Comment by ConnorHowell1** [comment]
You can access components with Javascript via the 'Livewire' object; then you can trigger the refresh.

`Livewire.components.getComponentsByName('component-name')[0].$wire.$refresh()`
(getComponentsByName returns an array of components)

**Comment by pkeogan** [comment]
@ConnorHowell1 , if i use
`Livewire.components.getComponentsByName('component-name')[0].$wire.$refresh()`

I get a a undefined error. How can I call the Livewire object/class within my javascript?
