### ISSUE TITLE
Default sorting is not displayed in table header

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#809]
Hello,

I'm using ->setDefaultSort('date', 'desc') but  it's not shown in the table header.
And if I'm using ->setSortingPillsStatus(true), not shown in the status area either.

Thanks, Denis

**Comment by rappasoft** [comment]
Default sort does not know as a pill, it just modifies the base query.

**Comment by dgillier** [comment]
Tks, got it, anyway to have at least ,the thead reflecting this default sort ?
It's a bit confusing for the user.

**Comment by rappasoft** [comment]
Instead of setting a default sort you can try to trigger an event to sort by whatever column when the component loads or from a parent component: https://rappasoft.com/docs/laravel-livewire-tables/v2/datatable/events#content-setsort

**Comment by dgillier** [comment]
Thanks, but I assume the table update will be visible then ?
