### ISSUE TITLE
Downloading Exported file

### ISSUE THREAD

**Issue by abdosaeedelhassan** [rappasoft/laravel-livewire-tables#82]
hi, i did all required steps, but when try to download not worked for me just refreshed the datatable, is there need to do the export customizing?, next is explain record
https://www.loom.com/share/2c9cf6c7e6c949b4920e9b85da9dccdf

**Comment by rappasoft** [comment]
Do you have any errors in your log?

**Comment by abdosaeedelhassan** [comment]
no error in log file or browser console, next is data from export trait and also the same from export class if it help
![Screenshot from 2020-10-02 15-10-13](https://user-images.githubusercontent.com/15355610/94927407-7fd89900-04c2-11eb-849e-dc14393641bd.png)

**Comment by rappasoft** [comment]
You have Laravel Excel installed? DOMPDF if using PDF export? I'm going to assume it's something specific with your project giving it an issue.

**Comment by abdosaeedelhassan** [comment]
i will try the customization for export class, because i am not found any errors, thank you

**Comment by abdosaeedelhassan** [comment]
Hi,
i was tried to store exported file to storage instead of downloaded and it is worked for me, all type of export work successful, also i checked fileinfo php extension  are installed, also i tried response->download but not worked for me, i am using chrome browser on ubuntu os is this problem belong to used os or browser, i can customizing export function by emitting path to stored file and downloaded using javascript but this not compatible with package updates , I need your help or your suggestions please thank you

**Comment by abdosaeedelhassan** [comment]
i don't know what the problem ,but it worked for me when upgrade to laravel 8, thank you

**Comment by surajjdhv** [comment]
For people who are facing this issue. upgrade live-wire version to 2.x
