### ISSUE TITLE
Issue with boostrap 4 default styling

### ISSUE THREAD

**Issue by JohnWeidmann** [rappasoft/laravel-livewire-tables#824]
![boostrap4](https://user-images.githubusercontent.com/14594258/175185480-1fe8f839-da2d-4444-95bf-94d739162323.PNG)

not sure whats going on here, but theres no way other stylings are interfering with this.

**Comment by rappasoft** [comment]
It looks like something isn't being loaded on your end, here's the working example: https://tables.laravel-boilerplate.com/bootstrap-4
