### ISSUE TITLE
setSelectAllEnabled is not selecting all rows

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#826]
Hello,

I understand setSelectAllEnabled would select all rows, but It just select the checkbox in the table header without effect on the rows themselves...
User has to check the already selected header checkbox to to a select all.

Is there a way a way to programmatically select all rows ?

Tks, Denis

**Comment by rappasoft** [comment]
This does not select all rows, it enables the selecting of all rows.
