### ISSUE TITLE
This line breaks queries that lean on GROUP BY

### ISSUE THREAD

**Issue by Rietveld** [rappasoft/laravel-livewire-tables#85]
https://github.com/rappasoft/laravel-livewire-tables/blob/3a4604ceaf8df22c55891441dc0c64ac2838cec9/src/TableComponent.php#L134

Its better to remove this line bc you cant ever use a GROUP BY query with this, you dont ever want to GROUP BY id.

**Comment by rappasoft** [comment]
How would you suggest doing this without breaking the current functionality?

**Comment by Rietveld** [comment]
Its not an easy solution. Itll require some extra logic to see if group by has been used in the builder and when you have, only allow to sort on the grouped fields. Ill see if i have some time next week to hammer this out and suggest a PR.
For the rest the lib works great btw.

**Comment by rappasoft** [comment]
Thanks. Yeah feel free, I haven't had the need for a group by yet so I guess I haven't run into the issue.
