### ISSUE TITLE
Can not use sort when using label on column

### ISSUE THREAD

**Issue by lloricode** [rappasoft/laravel-livewire-tables#850]
Im using sorttable along with label, 

in version 1 it was working while using `->format()`, but since upgrade to v2, its need to chance to `->label`, but this not gonna work with sortable

```php
          Column::make('Name', 'name')
              ->sortable()
              ->searchable()
              ->label(function ($row, Column $column) {
                  return $row->custome_value + $row->custome_value2;
              }),
```

**Comment by lloricode** [comment]
also the `->searchable()` not working with `->label()`

**Comment by rappasoft** [comment]
This is the intended functionality.

**Comment by lloricode** [comment]
hmm, so hows possible to upgrade in version 2

I have costume column not not related in local model table columns, and need a sortable function?

I have a column has count on its relation and can be sorter via `orders_count`,

```php
    public function query(): Builder
    {
       return User::withCount('orders');
    }
```


```php
            Column::make('Returnee', 'orders_count')
                ->sortable(function (Builder $query, $direction) {
                    return $query
                        ->orderBy(
                            'orders_count',
                            $direction
                        );
                })
                ->format(
                    function ($value, $column, User $row) {
                       // some costume output
                )->asHtml(),
```

hope it has possible way this in version 2

thank you

**Comment by satoved** [comment]
Also couldn't achieve sorting by count field.

Column class has:
```
    public function isSortable(): bool
    {
        return $this->hasField() && $this->sortable === true;
    }
```

But label sets field to null, and makes a column never sortable.

What is the point of having $this->hasField() check? It only limits my options. I guess, if the user deliberately sets the column to be sortable, then it can be sortable and through a Mysql exception if he messed it up.
