### ISSUE TITLE
Error in Traits/Export.php

### ISSUE THREAD

**Issue by tuluong** [rappasoft/laravel-livewire-tables#86]
I've faced an issue "syntax error, unexpected ')' " with livewire table. How can i fix this? Thanks.
![Screenshot_20201008-103340~2](https://user-images.githubusercontent.com/15993038/95412077-4edce600-0952-11eb-9215-342a6d25b180.png)

**Comment by rappasoft** [comment]
What version of PHP?

**Comment by tuluong** [comment]
> What version of PHP?

I've used Php 7.3

**Comment by rappasoft** [comment]
I have no idea what's causing this you're going to need to post more information.

**Comment by tuluong** [comment]
I think maybe it related to some php extensions. Let me try by myself, thanks a lot

**Comment by thibeDev** [comment]
Hello,
How did you fix this? I have exactly same error... Thanks
