### ISSUE TITLE
Search with scout driver

### ISSUE THREAD

**Issue by chapdel** [rappasoft/laravel-livewire-tables#860]
Hello, I'm experiencing this issue. 
When I make a search with Laravel Scout I have no results and yet everything seems to be going well.

**Comment by macbookandrew** [comment]
Here’s how I set up a table to use Scout for searching:

```php
Column::make('name')
    ->searchable(fn (Builder $query, string $searchTerm) => $query->orWhereIn('product_groups.id', ProductGroup::search($searchTerm)->keys())),
```

In other words, use `ProductGroup::search($searchTerm)->keys()` to retrieve just the model IDs, and then search for models where the ID was in that set, along with (`or`) other search conditions

**Comment by booni3** [comment]
A better way to do this is to overwrite the  `executeQuery` method. 

The above idea has issues as soon as you want to do sorting with the search driver. i.e. relevancy + sorting with Meilisearch or Agolia. Pagination also works fully in this way and is not just limited to 20 hits.

```php
public function executeQuery()
{
    if($searchTerm = $this->getSearch()){
        $model = $this->builder()->getModel();
        return $model::search($searchTerm, function(Indexes $index, $query, $options){
//                $options['sort'] = ["received_at:desc"];
            return $index->search($query, $options);
        })->simplePaginate($this->getPerPage() === -1 ? $this->getBuilder()->count() : $this->getPerPage(), $this->getComputedPageName());
    }

    parent::executeQuery();
}
```
