### ISSUE TITLE
getHash issue 

### ISSUE THREAD

**Issue by CovertError** [rappasoft/laravel-livewire-tables#861]
Call to undefined method Rappasoft\LaravelLivewireTables\Views\Column::getHash()

resources/ views/vendor/ livewire-tables/ components / tools / toolbar.blade.php : 200

`                      @foreach($component->getColumns() as $column)

                            @if ($column->isVisible() && $column->isSelectable())

                                <div wire:key="columnSelect-{{ $loop->index }}-{{ $component->getTableName() }}">

                                    <label

                                        wire:loading.attr="disabled"

                                        wire:target="selectedColumns"

                                        class="px-2 {{ $loop->last ? 'mb-0' : 'mb-1' }}"

                                    >

                                        <input

                                            wire:model="selectedColumns"

                                            wire:target="selectedColumns"

                                            wire:loading.attr="disabled"

                                            type="checkbox"

                                            value="{{ $column->getHash() }}"

                                        />

                                        <span class="ml-2">{{ $column->getTitle() }}</span>

                                    </label>

                                </div>

                            @endif

                        @endforeach

                    </div>

                </div>

            </div>`

**Comment by CovertError** [comment]
it got updated and I was on an older version of this file thanks guys

**Comment by jude-san** [comment]
Hello @CovertError ,
I am facing the same issue here on my project, @CovertError can give me in detail how you solved your error.
