### ISSUE TITLE
Use Bootstrap 5 themed checkboxes and selects

### ISSUE THREAD

**Issue by gjm** [rappasoft/laravel-livewire-tables#868]
In the column visibility and results per page selector, the controls are not using the themed inputs in bootstrap-5 theme. 

For checkboxes `form-check` class must be added to the wrapper div and `form-check-input` class to the `input` tag and for selects `form-select` class must be added to the `select` tag.

**Comment by WhereIsLucas** [comment]
My PR #864 fixes the select input problem, and I will add the checkbox styling too.

**Comment by WhereIsLucas** [comment]
This is fixed in the PR, we should wait for someone to merge it, thanks for pointing it out !

**Comment by WhereIsLucas** [comment]
Hi @rappasoft,

Would it be possible to merge the linked PR https://github.com/rappasoft/laravel-livewire-tables/pull/864 ?

Does it need more work ?

Thanks !

**Comment by rappasoft** [comment]
Included in the next release. Thanks.
