### ISSUE TITLE
Dragabble rows

### ISSUE THREAD

**Issue by zaidonch** [rappasoft/laravel-livewire-tables#87]
will it be possible to define a draggable rows option for ordering rows?

**Comment by rappasoft** [comment]
The order comes from the query.

**Comment by zaidonch** [comment]
> The order comes from the query.

Of course, but I want to change the order in a row, how can i do it?

**Comment by rappasoft** [comment]
You can't because the order would just get un-done the next time the table loaded, why would you need this?

**Comment by zaidonch** [comment]
I want to do this: https://datatables.net/extensions/rowreorder/examples/initialisation/simple.html

Drag a row to change the order

**Comment by rappasoft** [comment]
I understand what you want, I just don't see how it's a useful feature. You can definitely publish all the views and inject your own javascript.
