### ISSUE TITLE
Relation not loaded

### ISSUE THREAD

**Issue by gjm** [rappasoft/laravel-livewire-tables#872]
Let's say I have two models, `Employee` and `Company` and `Employee` belongsTo `Company`.

I want to have a simple datatable listing employees and respective companies. The column definition would be something like:

```php
public function columns(): array
{
    return [
        Column::make('Number')->searchable()->sortable(),
        Column::make('Name')->searchable()->sortable(),
        Column::make('Company', 'company.name')->searchable()->sortable(),
    ]
}
```

Relations are being eager loaded and everything works fine like this.

But, say I want to display the company's description, through the `getDescription()` method. If I chain a call to `format` to the column's definition to do so I get an error saying I'm calling `getDescription()` on `null`.

```php
Column::make('Company', 'company.name')
    ->searchable()
    ->sortable()
    ->format(fn ($value, $row) => $row->company->getDescription())
```

I would expect, since the company name is being shown correctly and search and sorting also work fine, that the `company` relation of  each employee would be correctly loaded and set but it is not.

**Comment by gjm** [comment]
As I said in my report, relations are being eager loaded by default. I also tried adding `->eagerLoadRelations()` to the column definition but the result is the same.

**Comment by the-turk** [comment]
Maybe we've the same mistake in our code, I don't know. 

The only workaround I can think of is using additional selects, but things get messy when you have so much to show:

```php
public function builder(): Builder
{
	return Employee::query()
		->join('company', 'employee.company_id', '=', 'company.id');
}

public function configure(): void
{
	$this->setAdditionalSelects([
		'company.description as companyDescription'
	]);
}

public function columns(): array
{
	return [
		Column::make('Company', 'company.name')->format(fn ($value, $row) => $row->companyDescription);
	]
}
```

I'll be waiting other answers on the issue.

**Comment by the-turk** [comment]
I figured it out after two hours later...

You must have a column definiton for `foreign_key` column to get that relationship working.

```php
class Company extends Model
{
  public function employee()
  {
    return $this->hasMany(Employee::class, 'employee_id');
  }
}

class Employee extends Model
{
  public function company()
  {
    return $this->belongsTo(Company::class, 'company_id');
  }
}
```

```php
public function columns(): array
{
    return [
        Column::make('Employee Id', 'employee_id'), // <---- here it is
        Column::make('Company', 'company.name')
            ->searchable()
            ->sortable()
            ->format(fn ($value, $row) => $row->company->getDescription()),
    ]
}
```

**Comment by gjm** [comment]
Yes your workaround seems to work. But shouldn't this be done automatically @rappasoft ?

**Comment by rappasoft** [comment]
Yes, I'm aware of this limitation. It's on my list to auto select foreign keys of eager loaded relationships but for now the setAdditionalSelects method fixes the issue.
