### ISSUE TITLE
Why rowView is not working?

### ISSUE THREAD

**Issue by paramwork** [rappasoft/laravel-livewire-tables#885]
I just upgraded to V2 and my `rowView()` is not working at all.

```
public function rowView(): string
{
       return 'livewire-tables.rows.submissions_row';
}
```

It is loading the default view from columns. How do I use rowView in V2? 

If it is removed from V2 what is the alternative to use? All of my tables (over 50) work in a custom row without `rowView` all of my tables have become unusable. Please help

**Comment by YnievesDotNet** [comment]
Im have same problem, and I get this error
```
Unable to locate a class or view for component [livewire-tables::table.cell].
```
how fix that?

**Comment by DanielGSoftware** [comment]
> I just upgraded to V2 and my `rowView()` is not working at all.
> 
> ```
> public function rowView(): string
> {
>        return 'livewire-tables.rows.submissions_row';
> }
> ```
> 
> It is loading the default view from columns. How do I use rowView in V2?
> 
> If it is removed from V2 what is the alternative to use? All of my tables (over 50) work in a custom row without `rowView` all of my tables have become unusable. Please help

Afaik there's not alternative, perhaps we can build back this feature?

**Comment by imabug** [comment]
For most of my custom row views, I was able to replace them with format().  They were all relatively simple though, so YMMV

https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-formatting

**Comment by DanielGSoftware** [comment]
You're right, I knew `format()`, `label()` or `view()` were the alternatives, but it's not quite the same since you can end up with a lot of partials for one datatable vs using 1 row view.

**Comment by YnievesDotNet** [comment]
> You're right, I knew `format()`, `label()` or `view()` were the alternatives, but it's not quite the same since you can end up with a lot of partials for one datatable vs using 1 row view.

I are using the `label()` but has better continue using el rowView

Thanks.

**Comment by booni3** [comment]
Agree with this. RowView was one of my most favourite features. Just upgraded to V2 and was suprised I could not find it.
