### ISSUE TITLE
Adding to query string

### ISSUE THREAD

**Issue by pkeogan** [rappasoft/laravel-livewire-tables#89]
Is there anyway to add to the query string via javascript/alpinejs?

For example, if button A is toggled, a `->where('foo', '=', 'bar')` would be added to the query.

**Comment by detygon** [comment]
Hi ! We are working on a filtering feature (#49) that will allow you to add query constraint from the frontend.

**Comment by pkeogan** [comment]
Saw your response on #49, I'll continue the conversation there.  Thanks!
