### ISSUE TITLE
Filter issue

### ISSUE THREAD

**Issue by drSun** [rappasoft/laravel-livewire-tables#890]
Hi guys,
Great extension, thanks a lot for it!

Unfortunately, found a bug. Env: php 7.4, laravel 8, bootstrap4

1) "Filters" label is not clickable (just nothing happens on click). I added this to config:
`
$this->setFiltersEnabled();
$this->setFilterLayoutSlideDown();
`
So now filter box is open and visible by default, but the label is still not clickable.
![image](https://user-images.githubusercontent.com/9992233/186859973-ec287d90-f12e-4685-87cc-7314e6ddb715.png)
Commenting this line $this->setFilterLayoutSlideDown(); hides the filter box forever. Popover style doesn't work at all.

2) I've got an array of options like
`Array
(
    [0] => Pending
    [10] => Ready for translation
    [20] => Translation in progress
)`

I have read about numerical keys and cast them to string, but no effect - I still see 0, 1 and 2 in dropdown options.

![image](https://user-images.githubusercontent.com/9992233/186861584-42b52cb5-270a-442b-99e8-f3d01ce3d3fa.png)

**Comment by rafap4j** [comment]
Hi @drSun , did you manage to solve this?

**Comment by lrljoe** [comment]
This is an old old issue, there have been many releases since then.  If you are having an issue then please raise a new issue rather than replying to old closed ones
