### ISSUE TITLE
Filters url and localisation

### ISSUE THREAD

**Issue by dgillier** [rappasoft/laravel-livewire-tables#893]
Hello,

I'm using this package in a multilingual website.

Problem is there is no way to have a key and a label when you create a filter: `SelectFilter::make('Active')`.
So to do translation I doing `SelectFilter::make(__('filter-name.active')`.

So this mean if a filter is selected, the page url is becoming:
https://domain-name.com/members/users?table[filters][members]=1

But if the user is switching to another language on the page with a menu i.e, the app is crashing because the url is staying the same but the filter name has changed due to `__('filter-name.active'`

There is a   `->setFilterPillTitle(__('cruds.user.fields.experience'))` method, used to changed the filter name in the pill, why not using it also for displaying the filter label ?

**Comment by Oleksandr-Moik** [comment]
Hello. You can pass a second argument to the make function to set the key when the first argument is the label name

From official docs: 
https://rappasoft.com/docs/laravel-livewire-tables/v2/filters/creating-filters#content-filter-keys

and explanations in the code: 
https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Views/Filter.php#L26

**Comment by Oleksandr-Moik** [comment]
and in your case it will look like this:
`SelectFilter::make(__('filter-name.active'), 'active')`

**Comment by dgillier** [comment]
@Oleksandr-Moik Thanks a lot, did not see that in the doc ;)
