### ISSUE TITLE
table-striped on bootstrap doesn't work

### ISSUE THREAD

**Issue by GermanZun** [rappasoft/laravel-livewire-tables#895]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/894

<div type='discussions-op-text'>

<sup>Originally posted by **GermanZun** August 29, 2022</sup>
Hi. table-striped doesn't work for me on bootstrap. Even on the demo sample doesn't work and i can see that table-striped class is aplied to the table. How can i enable it? Thanks!

https://tables.laravel-boilerplate.com/bootstrap-5

![Screenshot from 2022-08-29 12-13-29](https://user-images.githubusercontent.com/12190841/187246884-4a3c2935-c287-4685-a873-10c9352c97b1.png)

</div>

**Comment by rappasoft** [comment]
Not sure how to fix this one as it deals with the hidden rows.

**Comment by lrljoe** [comment]
So this is to do with the hidden rows for collapseOn.

I'm planning to revisit a PR from someone else in relation to the collapseontablet etc and will look at this at the same time.

**Comment by lrljoe** [comment]
Initial tests show my approach works, but it's not super-clean:

![Bootstrap-Striped](https://user-images.githubusercontent.com/104938042/224259159-42468bea-1ae8-4316-b627-5fe007584cc6.png)
![Bootstrap-Striped-Filtered](https://user-images.githubusercontent.com/104938042/224259165-32d5fdfc-fc0b-40c6-acb9-3643dfbd53f8.png)

**Comment by lrljoe** [comment]
This will be addressed in a future version (soon), couple of items left on my to-do before I can do some proper testing on my fix.

**Comment by lrljoe** [comment]
Will be in 2.15 most likely, once I've finished testing the collapsed columns element then the fix slots in nicely
