### ISSUE TITLE
Custom model path in command

### ISSUE THREAD

**Issue by keizah7** [rappasoft/laravel-livewire-tables#896]
Where is no way to pass custom model namespace.

I'm using `spatie/laravel-event-sourcing` and my models is in `\App\Projections` folder, so when I trying create table I getting an error:

```
php artisan make:datatable Tables/BillTable \App\Projections\Bill
```
![image](https://user-images.githubusercontent.com/49227202/187625122-b3ba5a63-8662-4228-8603-dd6ccfc19e34.png)

I must use fake model to generate component, and after that modify it to needs

**Comment by lrljoe** [comment]
You can always make your own version of this MakeCommand.php and customise it to accept non-standard paths.

I'm not sure why you'd want to deviate from the standard to be honest, unless I'm missing something?

**Comment by keizah7** [comment]
> You can always make your own version of this MakeCommand.php and customise it to accept non-standard paths.
> 
> I'm not sure why you'd want to deviate from the standard to be honest, unless I'm missing something?

Like I mentioned I'm using `spatie/laravel-event-sourcing` and that package projectors is stored in not standar directories.

**Comment by lrljoe** [comment]
Go with a custom version of the MakeCommand.php, replacing the getModelImport function with the below, which should pick up your models if they're in the root of App\Projections.

Let me know if it works for you, and if so I'll issue a pull request, if not, drop me a note with a repository with a basic example, and I'll take a closer look.

    public function getModelImport(): string
    {
        if (File::exists(app_path('Models/' . $this->model . '.php'))) {
            return 'App\Models\\' . $this->model;
        }

        if (File::exists(app_path('Projections/' . $this->model . '.php'))) {
            return 'App\Projections\\' . $this->model;
        }

        if (File::exists(app_path($this->model . '.php'))) {
            return 'App\\' . $this->model;
        }

        $this->error('Could not find path to model.');

        return 'App\Models\\' . $this->model;
    }

**Comment by keizah7** [comment]
You saw something wrong, some models become Projectors and etc.

Thank you for example, would you consider add this to package?

**Comment by lrljoe** [comment]
If it works for you, then I'll certainly add a pull request for Anthony - @rappasoft , or he may just add it himself as it's only a one-line change.

**Comment by rappasoft** [comment]
Feel free to make a PR though I don't think it's entirely necessary as you can just change the namespace after it's generated.
