### ISSUE TITLE
Using $this when not in object context

### ISSUE THREAD

**Issue by keizah7** [rappasoft/laravel-livewire-tables#897]
For some reason if datatable is above simple table with links it throws this exception

https://flareapp.io/share/17D2EGvm

Commenting out
```
$bills->links()
```
or moving datatable below this code, solves and issue.

Changing pageName doesn't help
```
->paginate(12, ['*'], 'pg');
```

**Comment by lrljoe** [comment]
Not sure why you're trying to use $this in a blade, unless I've missed something!

If you've set the variable or method to public, then $this is not required and you can reference as you've done elsewhere in your code.

**Comment by keizah7** [comment]
I don't use `$this` in blade file. I just got error with that message, I'm using `$bills`

**Comment by lrljoe** [comment]
Apologies, I must have been half asleep.

Just to check, are you given the simple table a name for pagination purposes otherwise it'll be getting confused!
e.g.
        return view('livewire.show-posts', [
            'posts' => $post->comments()->paginate(10, ['*'], 'commentsPage'),
        ]);

**Comment by keizah7** [comment]
I tried this one, it didin't help

**Comment by lrljoe** [comment]
Can you paste your entire resources/views/bill/index.blade.php, or drop me a link to it, and I'll see if I can reproduce from my end.

I'm assuming you're not seeing any "multiple root elements detected" errors in the console, as this would potentially cause the issue if the DOM is broken.
