### ISSUE TITLE
sortable(callable $callable = null) example.

### ISSUE THREAD

**Issue by pkeogan** [rappasoft/laravel-livewire-tables#90]
Are there any examples of the `sortable(callable $callable = null)` function? Not sure how to implement into code and unable to find examples. Looking to implement sortable on columns that use relationships. Thanks for any help!

**Comment by pkeogan** [comment]
figured it out. Here is the code I am using if anyone is looking for an answer.
```
...
            Column::make(__('Author'))
                ->searchable(function($builder, $term) {
                    return $builder->orWhereHas('author', function($query) use($term) {
                          return $query->where('first_name', 'like', '%'.$term.'%')
                                       ->orWhere('last_name', 'like', '%'.$term.'%');
                    });
                })
...
```

**Comment by MartinP7r** [comment]
@pkeogan the code you posted is for `searchable()`, not `sortable()`.  
Do you have an actual example for `sortable()`?

**Comment by maximiliandoerner** [comment]
> @pkeogan the code you posted is for `searchable()`, not `sortable()`.
> Do you have an actual example for `sortable()`?

probably pretty similar, if it's still relevant to you, may have a look at the function which actually is responsible for gathering the data you want to display! :) The relevant function is in ´TableComponent´ in the ´models()´ function
