### ISSUE TITLE
using mongodb show empty rows

### ISSUE THREAD

**Issue by MazenRex** [rappasoft/laravel-livewire-tables#900]
while using MongoDB I get empty rows
### Transaction model
```
namespace App\Models;
use Jenssegers\Mongodb\Eloquent\Model as MongodbModel;
class Transaction extends MongodbModel
{
    protected $connection = 'mongodb';
    protected $collection = 'transactions';
    protected $guarded = [];
}
```
### Table
```
protected $model = Transaction::class;
    public function configure(): void
    {
        $this->setDefaultSort('date', 'desc');
        $this->setPerPageAccepted([10, 25, 50, 100]);
        $this->setPrimaryKey('id')->setAdditionalSelects(['transactions._id as id'])->setHideBulkActionsWhenEmptyEnabled();
    }

    public function columns(): array
    {

            return [
                Column::make("terminal Id", "terminalId")->excludeFromColumnSelect()
                    ->sortable()->searchable(),
                Column::make("date", "date")
                    ->sortable()->searchable()->collapseOnTablet(),
            ];

    }
```
![image](https://user-images.githubusercontent.com/68430424/188470977-5f2a510a-e270-4b2b-8931-ad2782bc8e00.png)

**Comment by Sasuka** [comment]
I have a issue. Who fixed it yet?

**Comment by MazenRex** [comment]
> I have a similar problem. Who fixed it yet?

No one i think

**Comment by Sasuka** [comment]
> > I have a similar problem. Who fixed it yet?
> 
> No one i think

So, Do you have any ideas to solve this problem?

**Comment by Sasuka** [comment]
- I have 2 options but I don't know which is the best!

**Options 1**: At component I added this line:
`
$this->additionalSelects = ['name', 'phone', 'is_proxy', 'max_account', 'email'];`
**Options 2**: I updated in function selectFields() at line 120
`
    // $this->setBuilder($this->getBuilder()->addSelect($column->getColumn() . ' as ' .$column->getColumnSelectName()));
    $this->setBuilder($this->getBuilder()->addSelect($column->getColumnSelectName()));
`

**Comment by MazenRex** [comment]
> * I have 2 options but I don't know which is the best!
> 
> **Options 1**: At component I added this line: ` $this->additionalSelects = [''name','email'];` **Options 2**: I updated in function selectFields() at line 120 `// $this->setBuilder($this->getBuilder()->addSelect($column->getColumn() . ' as ' .$column->getColumnSelectName())); $this->setBuilder($this->getBuilder()->addSelect($column->getColumnSelectName()));`

It's work know ?

**Comment by MazenRex** [comment]
thanks @Sasuka  i add this `$this->additionalSelects = ['name',...]; `  at my component for all table column and its work fine .

**Comment by berksmbl** [comment]
I have the same problem and the solution partially worked. But I can't use functions like search.

**Comment by MazenRex** [comment]
> I have the same problem and the solution partially worked. But I can't use functions like search.

you can edit WithSearch in line 33
from `$query->{$index === 0 ? 'where' : 'orWhere'}($column->getColumn(), 'like', '%'.$this->getSearch().'%');`
to `$query->{$index === 0 ? 'where' : 'orWhere'}($column->getColumnSelectName(), 'like', '%'.$this->getSearch().'%');`
