### ISSUE TITLE
Call to undefined method Rappasoft\LaravelLivewireTables\Views\Column::getHash()

### ISSUE THREAD

**Issue by cloudwales** [rappasoft/laravel-livewire-tables#902]
Hi. 
I updated composer and Im not getting this error `Call to undefined method Rappasoft\LaravelLivewireTables\Views\Column::getHash()`

Everything is up-to date and I cant see what is causing it. 

Any ideas on what could be causing this. 

composer.json
```
"require": {
        "php": "^8.1",
        "asantibanez/livewire-charts": "^2.4",
        "guzzlehttp/guzzle": "^7.2",
        "jantinnerezo/livewire-alert": "^2.2",
        "laravel-frontend-presets/tall": "^4.2",
        "laravel/framework": "^9.2",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "livewire/livewire": "^2.10",
        "maatwebsite/excel": "^3.1",
        "phpoffice/phpspreadsheet": "^1.2",
        "rappasoft/laravel-livewire-tables": "^v2.8",
        "sentry/sentry-laravel": "^2.13",
        "spatie/laravel-activitylog": "^4.5",
        "spatie/laravel-permission": "^5.5"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^6.1",
        "phpunit/phpunit": "^9.5.10",
        "spatie/laravel-ignition": "^1.0"
    },
```

**Comment by lrljoe** [comment]
getHash was removed from the ColumnHelpers file in a recent commit.  What were you using it for out of interest?

**Comment by BrenoLopes** [comment]
I'm also experiencing this problem even on version 2.7. The only thing I've published is the configuration file so all the views comes from the vendor folder. But I still get this error.

**Comment by BrenoLopes** [comment]
For anyone looking to solve this problem, look for a folder called livewire-tables inside the views/vendor. I deleted it here and the problem stopped happening.

**Comment by afariasfermin** [comment]
> For anyone looking to solve this problem, look for a folder called livewire-tables inside the views/vendor. I deleted it here and the problem stopped happening.

I removed the vendor folder & then run composer install, i does not publish the assets from the packages as it recommended in the doc, the issue persist i get the same error after a fresh install.

**Comment by jarwonozt** [comment]
> For anyone looking to solve this problem, look for a folder called livewire-tables inside the views/vendor. I deleted it here and the problem stopped happening.

ah.. that's right this alternative way works perfectly. i also do the same. this happens when updating or upgrading composer.

**Comment by raviraj-31** [comment]
> For anyone looking to solve this problem, look for a folder called livewire-tables inside the views/vendor. I deleted it here and the problem stopped happening.

Thank you for solution. Same issue I fixed with your solution.
