### ISSUE TITLE
Passing Properties

### ISSUE THREAD

**Issue by vavicheth** [rappasoft/laravel-livewire-tables#91]
I have a problem with Passing Properties. Do you have an example for passing properties or parameters?

**Comment by detygon** [comment]
You can use the `mount` [lifecycle hook](https://laravel-livewire.com/docs/2.x/lifecycle-hooks). It's a feature of livewire.

**Comment by sarabando** [comment]
change livewire in blade view 
```xml
 <livewire:users-table role="{{ request('role') }}" />
```
URL : http://laravel-project/admin/users?role=standart_user

**Comment by vavicheth** [comment]
Thank you so much for your guideline. But when I passed like this, It's nothing to show.

**Comment by sarabando** [comment]
> Thank you so much for your guideline. But when I passed like this, It's nothing to show.

check this approach


```
    public function query(): Builder
    {
        $localRole= request('role');
        if (! empty($localRole)) {
            $this->role= $localRole;
        }
        $query = User::withTrashed();

        if (!empty($this->role)) {
            $query = $query->where('role', '=', $this->role);
        }

        return $query;
    }

```

**Comment by calvez** [comment]
``php
<livewire:server-users-table server="{{ $server->id }}" />
``

**Comment by vavicheth** [comment]
Thank you so much!

**Comment by Afinetri** [comment]
but why this does not work if for sorting?

**Comment by anuzpandey** [comment]
> `<livewire:server-users-table server="{{ $server->id }}" />`
> 
> and in the table:
> 
> ```
> 
> /**
>  * Class ServerUsersTable.
>  */
> class ServerUsersTable extends TableComponent
> {
> 
>     protected $server = 'server';
> 
>     public function mount($server)
>     {
>         $this->server = $server;
>     }
> 
>     /**
>      * @var string
>      */
>     public $sortField = 'user_id';
> 
>     /**
>      * @return Builder
>      */
>     public function query(): Builder
>     {
>         return ServerUser::with('user')->where('server_id', $this->server);
>     }
> ```

Searching and sorting doesn't work after this.

**Comment by vincent-ikonk** [comment]
did you find a solution? I have the same problem.

**Comment by ianwinstanley** [comment]
Hi

I have the same problem when sorting or filtering.

```
    public function mount($permission, $formSchema, $model)
    {
        $this->permission = $permission;
        $this->formSchema = $formSchema;
        $this->model = $model;
    }
```

I am passing in a builder model as $model and an array as $formSchema. The table displays perfectly on initial render but then I sort or filter I get "You must either specify a model or implement the builder method" or "$formSchema is null".

**Comment by lrljoe** [comment]
Protected properties do not persist past a single lifecycle.  They must be set to public.

**Comment by lrljoe** [comment]
Keep in mind that public properties can always be modified from the frontend.

There are packages such as LeanAccess that help combat this, and Livewire 3 supports it natively (v3 of this package currently being finished off to support livewire 3)
