### ISSUE TITLE
Checkbox behavior.

### ISSUE THREAD

**Issue by vavicheth** [rappasoft/laravel-livewire-tables#92]
Can you add checkbox functionalities?

**Comment by iosiflivadaru** [comment]
@vavicheth You could just return a view that contains the checkboxes! Will that work for you?

**Comment by ambitionphp** [comment]
How about a main checkbox in the header for select/deselect all functionality?

**Comment by iosiflivadaru** [comment]
@ambitionphp I don't think that is possible yet sadly or maybe I might be missing something... but I noticed that right now the <th> requires a string!

**Comment by rappasoft** [comment]
The checkbox functionality was removed in the last release as I couldn't find a good way to do it with large amounts of data, I will try again in the future. You can create a PR and i'll happily look at it as well. As soon as I have time i'll revisit it.

**Comment by AEK-BKF** [comment]
Hello @rappasoft ,
Any updates here ? Thanks

**Comment by rappasoft** [comment]
Checkboxes are back in 1.0 for bulk actions.
