### ISSUE TITLE
Multi-column search engine

### ISSUE THREAD

**Issue by daniieljc** [rappasoft/laravel-livewire-tables#929]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/927

<div type='discussions-op-text'>

<sup>Originally posted by **daniieljc** September 26, 2022</sup>
Buenas, tengo dos columnas, nombre y apellido, el problema viene cuando quiero buscar a una persona por los dos campos a la vez, sería esto posible?

[![Captura-de-Pantalla-2022-09-26-a-las-8-09-28.png](https://i.postimg.cc/CLKgDx22/Captura-de-Pantalla-2022-09-26-a-las-8-09-28.png)](https://postimg.cc/YjTZBMMN)</div>

**Comment by Oleksandr-Moik** [comment]
Hello. Yes, it is possible, but not in this way. There are text filters for your problem. Try them.

https://rappasoft.com/docs/laravel-livewire-tables/v2/filters/creating-filters#content-text-filters
