### ISSUE TITLE
Bulk Actions - Select one box, all are selected

### ISSUE THREAD

**Issue by ksorbo** [rappasoft/laravel-livewire-tables#932]
NB: upgrading from version 1.x

I have set up bulk actions. Check boxes appear with each row. Bulk actions dropdown appears correctly with my actions present

HOWEVER, when I click one box, **all checkboxes are automatically selected.** 

When I run
  `      dd($this->getSelected());`

in one of the bulk actions, it shows
`^ array:1 [▼
  0 => ""
]`

In the header of the table, it shows:
You have selected 1 rows, do you want to select all 737? Select All Deselect All

I have selected the Tailwind option.

**Comment by SiebeVE** [comment]
I had the same issue. I had to add the primary key column to my columns. I set it to be hidden with `hideIf(true)`

**Comment by DrewAPicture** [comment]
Ran into this problem today. I think it might be related to an undocumented requirement of having an `id` key on your data source.

I saw this same behavior until I tried to select all and then it threw an exception for the undefined `stdClass::$id` property.

**Comment by lrljoe** [comment]
You have to define a primary key, it doesn't have to be "id"

**Comment by DrewAPicture** [comment]
> You have to define a primary key, it doesn't have to be "id". Or at least it shouldn't do in v3!

Yep, I saw that just a little bit ago, thanks for the followup 🙏 🤦 

I've updated my comment.

**Comment by lrljoe** [comment]
> > You have to define a primary key, it doesn't have to be "id". Or at least it shouldn't do in v3!
> 
> Yep, I saw that just a little bit ago, thanks for the followup 🙏 🤦 
> 
> I've updated my comment.

No problem, I'm usually more responsive on the Discord btw if you run into anything else
