### ISSUE TITLE
Column sorting not work with label

### ISSUE THREAD

**Issue by keizah7** [rappasoft/laravel-livewire-tables#946]
Sorting not working with custom view

Works
```
Column::make('title', 'payment_paid_sum'),
```

Not works
```
Column::make(__('Title'))
    ->sortable(fn (Builder $query, string $direction) => $query->orderBy('payment_paid_sum'))
    ->label(fn ($row, Column $column) => view('partials.tables.payment-debt-report._payment_paid')->with(['report' => $row])),
```

**Comment by Oleksandr-Moik** [comment]
Hi. Sorting by columns with  **label** type is not possible ([see doc](https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-labels)). This column type is for additional information only with no interaction with the database queries or database columns.

If you want to sort the column and use a view to display the value, use the **fromat** method instead of the **label**.

Example for your case:
```diff
Column::make(__('Title'))
    ->sortable(fn (Builder $query, string $direction) => $query->orderBy('payment_paid_sum'))
-     ->label(fn ($row, Column $column) => view('partials.tables.payment-debt-report._payment_paid')->with(['report' => $row]))
+     ->format(fn ($row, Column $column) => view('partials.tables.payment-debt-report._payment_paid')->with(['report' => $row]))

```



This is also described in this section - https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-using-a-view

**Comment by keizah7** [comment]
> Hi. Sorting by columns with **label** type is not possible ([see doc](https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-labels)). This column type is for additional information only with no interaction with the database queries or database columns.
> 
> If you want to sort the column and use a view to display the value, use the **fromat** method instead of the **label**.
> 
> Example for your case:
> 
> ```diff
> Column::make(__('Title'))
>     ->sortable(fn (Builder $query, string $direction) => $query->orderBy('payment_paid_sum'))
> -     ->label(fn ($row, Column $column) => view('partials.tables.payment-debt-report._payment_paid')->with(['report' => $row]))
> +     ->format(fn ($row, Column $column) => view('partials.tables.payment-debt-report._payment_paid')->with(['report' => $row]))
> ```
> 
> This is also described in this section - https://rappasoft.com/docs/laravel-livewire-tables/v2/columns/available-methods#content-using-a-view

Your answer throws an error, after some corrections I made it work. Thank you!

```php
Column::make(__('Debt'), 'payment_debt_sum')
    ->sortable()
    ->excludeFromColumnSelect()
    ->format(fn ($value, $row, Column $column) => view('partials.tables.payment-debt-report._payment_debt')->with(['report' => $row])),
```

**Comment by Oleksandr-Moik** [comment]
> Your answer throws an error...

Yeah😅, I forgot change arguments for format closure, thanks.
