### ISSUE TITLE
Selecting withSum within column Make?

### ISSUE THREAD

**Issue by tonypartridge** [rappasoft/laravel-livewire-tables#955]
I have built a withSum() relation into the model which references it's self to calculate the total amount within a set of rows. So the rows have a total value based on the user_id. 

This works really well, however, when trying to display this in a column it fails. Because when you reference the naming convention:

total_sum 

which is as per the query builder:

```php
        $query = AmountRecords::query()
                                ->withSum('totalAmount AS user_total', 'amount')
                                ->where('user_id', '=', auth()->user()->id);

```
It cannot find amount_records.user_total because it's been created by the withSum. 

If I could specific to select user_total instead of amount_records.user_total all would be well...

**Comment by lrljoe** [comment]
Can you post your full component so that I can take a look?
