### ISSUE TITLE
Custom Search Funcitionality not working

### ISSUE THREAD

**Issue by maximiliandoerner** [rappasoft/laravel-livewire-tables#96]
I use this table to display the users of my application, they are differentiated by the `user_type` column. As it stands searchable() doesnt work for this since in DB it's saved as 0, 1 and 2. Let's say we want to query all `Executives`, we would have to search for `2`, which isn't optimal at all. So how do I go about that?

    public function query(): Builder
    {
        return User::with(['roles', 'trainee'])->withCount('permissions');
    }

    public function columns(): array
    {
        return [
            Column::make(_i('ID'))
                ->searchable()
                ->sortable(),
            Column::make(_i('Name'))
                ->searchable()
                ->sortable(),
            Column::make(_i('E-mail'), 'email')
                ->searchable()
                ->sortable()
                ->format(function (User $model) {
                    return $this->mailto($model->email, null, ['target' => '_blank']);
                }),
            Column::make(_i('User Type'), 'user_type')
                ->searchable()
                ->sortable()
                ->format(function (User $model) {
                    if ($model->user_type == 0) {
                        return _i('Admin');
                    } elseif ($model->user_type == 1) {
                        return _i('Trainee');
                    } elseif ($model->user_type == 2) {
                        return _i('Executive');
                    }
                }),
           
        ];
    }

UPDATE:
You have to overwrite the `models()` function of `TableComponent`. I will post some examples for others to use.
To test this yourself right now add the following to your `Table`, it will "break" the search but you can go from there.
```
public function models():Builder
    {
        return $this->query();
    }
```

**Comment by kungro** [comment]
I have successfully used the searchable like this:

->searchable(function(Builder $builder, String $term) {
	return $builder->orWhere('title', 'like', '%'.$term.'%');
}),

Please do not change the function parameters: "Builder $builder, String $term".

See if it works with you. I am using Laravel 8.

**Comment by maximiliandoerner** [comment]
> I have successfully used the searchable like this:
> 
> ->searchable(function(Builder $builder, String $term) {
> return $builder->orWhere('title', 'like', '%'.$term.'%');
> }),
> 
> Please do not change the function parameters: "Builder $builder, String $term".
> 
> See if it works with you. I am using Laravel 8.

@kungro sadly this doesn't work for me...
I want to search for `admin` while the actual query needs to be `where('user_type', '=', 0)`. I found a way how to do it. Will post it in a seperate comment.

**Comment by maximiliandoerner** [comment]
Like I mentioned in the update of my question i managed to get it working. 
I added this code before the regular code of `models()`:
```
if (trim($this->search) != '') {
            if (mb_stripos('Admin', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 0;
            }
            if (mb_stripos('Trainee', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 1;
            }
            if (mb_stripos('Executive', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 2;
            }
        }
```

After that I included the code of the base function so the whole function looks like this:
```
public function models(): Builder
    {
        if (trim($this->search) != '') {
            if (mb_stripos('Admin', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 0;
            }
            if (mb_stripos('Trainee', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 1;
            }
            if (mb_stripos('Executive', $this->search) !== false) {
                $originalSearch = $this->search;
                $this->search = 2;
            }
        }
        $builder = $this->query();

        if ($this->searchEnabled && trim($this->search) !== '') {
            $builder->where(function (Builder $builder) {
                foreach ($this->columns() as $column) {
                    if ($column->isSearchable()) {
                        if (is_callable($column->getSearchCallback())) {
                            $builder = app()->call($column->getSearchCallback(), ['builder' => $builder, 'term' => trim($this->search)]);
                        } elseif (Str::contains($column->getAttribute(), '.')) {
                            $relationship = $this->relationship($column->getAttribute());

                            $builder->orWhereHas($relationship->name, function (Builder $builder) use ($relationship) {
                                $builder->where($relationship->attribute, 'like', '%' . trim($this->search) . '%');
                            });
                        } else {
                            $builder->orWhere($builder->getModel()->getTable() . '.' . $column->getAttribute(), 'like', '%' . trim($this->search) . '%');
                        }
                    }
                }
            });
        }

        if (($column = $this->getColumnByAttribute($this->sortField)) !== false && is_callable($column->getSortCallback())) {
            return app()->call($column->getSortCallback(), ['builder' => $builder, 'direction' => $this->sortDirection]);
        }
        if (!empty($originalSearch)) {
            $this->search = $originalSearch;
        }
        return $builder->orderBy($this->getSortField($builder), $this->sortDirection);
    }
```

I'm sure the is a more elegant and less repetitive solution, but as a quick and dirty fix this will suffice at least. Might make a PR with a proposed change if I got time for that.
