### ISSUE TITLE
Unable to sort or search a column that is not associated with a database column

### ISSUE THREAD

**Issue by FormindMBA** [rappasoft/laravel-livewire-tables#961]
Hello, I created a table with a column that is not associated with a database column using the 'label()' method. But, I'm not able to sort nor search this column like the others, why?

```php
public function columns(): array
{
        return [
            Column::make("Title", "title")
                ->sortable()
                ->searchable(),
            Column::make("Subtitle", "subtitle")
                ->sortable()
                ->deselected(),
            Column::make("Release date", "release_date")
                ->sortable(),
            Column::make('Product(s)')
                ->label(fn($row) => $this->getProductName($row))
                ->sortable()
                ->searchable(),
        ];
}
```

**Comment by dgillier** [comment]
Labels content are not in the database so no sorting :)

**Comment by FormindMBA** [comment]
Thank you for the answer. I understand that if I'm using labels, I'll not be able to use sorting in any way?

**Comment by DaniWinter** [comment]
I'm having the problem, I even defined a custom sorting rule, why does this not work?
```
public function columns(): array
{
        return [
            Column::make("Bedrijfsnaam")
                ->label(
                    fn($row, Column $column) => $row->company ?? '-'
                )
                ->sortable(
                    fn(Builder $query, string $direction) => $query->orderBy('company', $direction)
                )
                ->searchable(),
        }
}
```

The 'company' field is also included in `$this->setAdditionalSelects();`

**Comment by ArnaudBan** [comment]
I am facing the same probleme : I have a Column with label but want to be able to make it sortable by passing a callback to thee `sortable`method.

**Comment by shlucky90** [comment]
> I'm having the problem, I even defined a custom sorting rule, why does this not work?
> 
> ```
> public function columns(): array
> {
>         return [
>             Column::make("Bedrijfsnaam")
>             ->label(
>                 fn($row, Column $column) => $row->company ?? '-'
>             )
>             ->sortable(
>                 fn(Builder $query, string $direction) => $query->orderBy('company', $direction)
>             )
>             ->searchable(),
>         }
> }
> ```
> 
> The 'company' field is also included in `$this->setAdditionalSelects();`

Instead of `label`, you can use `format` method.
