### ISSUE TITLE
I didn't get the proper input fields and dropdown

### ISSUE THREAD

**Issue by AbhinavNmdo** [rappasoft/laravel-livewire-tables#966]
### Discussed in https://github.com/rappasoft/laravel-livewire-tables/discussions/965

<div type='discussions-op-text'>

<sup>Originally posted by **AbhinavNmdo** November 17, 2022</sup>
I don't know why this happens for me.

![image](https://user-images.githubusercontent.com/86583211/202353602-56283479-2578-4f7b-a7c3-f29458b4b547.png)

My tailwind file content.
`'./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',`
  `  './vendor/laravel/jetstream/**/*.blade.php',`
  `  './storage/framework/views/*.php',`
 `   './resources/views/**/*.blade.php',`
 `   './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',`
  `  './app/Http/Livewire/**/*.php',`

Please help and thanks in advance.
</div>

**Comment by XaiMeS** [comment]
I have the same problem. In the old project with laravel mix is ok, while in the new one with Vite this problem appears.
![image](https://user-images.githubusercontent.com/36962784/202457280-83965e03-3c75-4fba-a215-b628b220e925.png)
