### ISSUE TITLE
Modals for actions (create, edit, delete)

### ISSUE THREAD

**Issue by marioene** [rappasoft/laravel-livewire-tables#97]
Hi! First, great package!

I want to implement Bootstrap 4 modal on different actions (edit or delete) in my TableComponent, but I am stuck right now.

1. How can I call an edit form in a modal with values from every row? Can I use wire:model in my modal form?

2. Where can I validate and save the values resulted from the update action from the form?

3. It is possible to show me a small example?

**Comment by rappasoft** [comment]
You can make each button its own livewire component and pass the current ID of the model from the row? Or pass the model itself to prepopulate whatever is in your modal.

**Comment by thegarlynch** [comment]
So, a livewire component should be used for one and one action only ? how do you return livewire component in this ?
