### ISSUE TITLE
Tailwind not inlcuding needed classes added via "setAttributes"

### ISSUE THREAD

**Issue by fuzzyhope1502** [rappasoft/laravel-livewire-tables#982]
So it seems from my usage that attempting to add custom Tailwind classes via any `setAttribute` function inside a Table Class doesn't work since they aren't included in the final css. The classes are added to the DOM node fine, but Tailwind just doesn't generate them unless you explicitly whitelist them in the config. 

E.g in this case, `bg-red-500` is added to the DOM, but is not defined by Tailwind.
```php
$this->setThAttributes(function (Column $column) {
    return [
        'class' => 'bg-red-500',
        'default' => false,
    ];
});
```

I've configured exactly as described in docs and also added the additional content path to config shown below. Not sure if I'm missing something, but I don't really see anything about it in docs or from searching issues. I did see a previous ticket that said to include the entire cdn of Tailwind, but that seems foolish and like it defeats the point of Tailwind entirely.

tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',

        // Pagination Views
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',

        // Table Views
        './vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php',
    ],

    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/typography')],
};

```

Is there something obvious I'm missing here? I tried adding other paths to content but no luck.

**Comment by lrljoe** [comment]
Are you running Mix or Vite, or another option?

Are you running a dev instance, or building files?

**Comment by SilverBull** [comment]
> Are you running Mix or Vite, or another option?
Are there any known problems with Vite? Because I'm having messy styles that I didn't have with the old Mix setup on another project.

**Comment by lrljoe** [comment]
> > Are you running Mix or Vite, or another option?
> 
> Are there any known problems with Vite? Because I'm having messy styles that I didn't have with the old Mix setup on another project.

Not to my knowledge.  It did take a bit of corrective action for one of my projects to get Vite to play nicely though!

**Comment by SilverBull** [comment]
> Not to my knowledge. It did take a bit of corrective action for one of my projects to get Vite to play nicely though!

Would you mind giving me an example? I followed the documentation and entered the path in the tailwind config but it still doesn't render all the components correctly and I don't understand if it is the fault of the installed template or something else.

**Comment by lrljoe** [comment]
> > Not to my knowledge. It did take a bit of corrective action for one of my projects to get Vite to play nicely though!
> 
> Would you mind giving me an example? I followed the documentation and entered the path in the tailwind config but it still doesn't render all the components correctly and I don't understand if it is the fault of the installed template or something else.

I had to manually add in some colours (colors) to get certain bits to work nicely.  For some programmatically created classes I ended up just having a blade with some of the output examples so that when I ran dev/build it'd pick them up.

If you post your tailwind config and give me an example of what isn't working then I may be able to give you a pointer.

**Comment by SilverBull** [comment]
I don't know at this point if the issue is the same as op. Btw for me is just some minor style issue on search field and columns/pages select

![immagine](https://user-images.githubusercontent.com/12399837/211881982-b2454719-a236-4643-a1b6-22179a4468b4.png)

as for my config is the one of the template
```const colors = require("tailwindcss/colors");
const defaultTheme = require("tailwindcss/defaultTheme");

const navyColor = {
  50: "#E7E9EF",
  100: "#C2C9D6",
  200: "#A3ADC2",
  300: "#697A9B",
  400: "#5C6B8A",
  450: "#465675",
  500: "#384766",
  600: "#313E59",
  700: "#26334D",
  750: "#222E45",
  800: "#202B40",
  900: "#192132",
};

const customColors = {
  navy: navyColor,
  "slate-150": "#E9EEF5",
  primary: colors.indigo["600"],
  "primary-focus": colors.indigo["700"],
  "secondary-light": "#ff57d8",
  secondary: "#F000B9",
  "secondary-focus": "#BD0090",
  "accent-light": colors.indigo["400"],
  accent: "#5f5af6",
  "accent-focus": "#4d47f5",
  info: colors.sky["500"],
  "info-focus": colors.sky["600"],
  success: colors.emerald["500"],
  "success-focus": colors.emerald["600"],
  warning: "#ff9800",
  "warning-focus": "#e68200",
  error: "#ff5724",
  "error-focus": "#f03000",
};

module.exports = {
  content: [
    "./src/**/*.{php,html,js,jsx,ts,tsx,vue}",
    "./resources/**/*.{php,html,js,jsx,ts,tsx,vue}",
    "./storage/framework/views/*.php",
    "./vendor/rappasoft/laravel-livewire-tables/resources/views/**/*.blade.php",
  ],
  mode: "jit",
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["Poppins", ...defaultTheme.fontFamily.sans],
        inter: ["Inter", ...defaultTheme.fontFamily.sans],
      },
      fontSize: {
        tiny: ["0.625rem", "0.8125rem"],
        "tiny+": ["0.6875rem", "0.875rem"],
        "xs+": ["0.8125rem", "1.125rem"],
        "sm+": ["0.9375rem", "1.375rem"],
      },
      colors: { ...customColors },
      opacity: {
        15: ".15",
      },
      spacing: {
        4.5: "1.125rem",
        5.5: "1.375rem",
        18: "4.5rem",
      },
      boxShadow: {
        soft: "0 3px 10px 0 rgb(48 46 56 / 6%)",
        "soft-dark": "0 3px 10px 0 rgb(25 33 50 / 30%)",
      },
      zIndex: {
        1: "1",
        2: "2",
        3: "3",
        4: "4",
        5: "5",
      },
      keyframes: {
        "fade-out": {
          "0%": {
            opacity: 1,
            visibility: "visible",
          },
          "100%": {
            opacity: 0,
            visibility: "hidden",
          },
        },
      },
    },
  },
  corePlugins: {
    textOpacity: false,
    backgroundOpacity: false,
    borderOpacity: false,
    divideOpacity: false,
    placeholderOpacity: false,
    ringOpacity: false,
  },
  plugins: [
    require("@tailwindcss/line-clamp")
  ],
};
```
That's the reason I asked if there was known problems, I'm trying to figure out if is the template fault or some error in some config that I made

**Comment by lrljoe** [comment]
If you disable JIT, does it improve matters?

Are you running Vite in dev or build mode, I've found that sometimes dev mode can be a behave a bit oddly (frustratingly).  Worth trying to run an "npm run build" and see if that improves matters.

The only difference for my core build is that I'm including "@tailwindcss/forms" as a plugin too.

**Comment by SilverBull** [comment]
> The only difference for my core build is that I'm including "@tailwindcss/forms" as a plugin too.

That was it for me, thank you mate :D

**Comment by lrljoe** [comment]
For the OP, bit of a hack, but create an otherwise empty blade with an element with all of the classes you want to use in the table, and tailwind will pick it up.

**Comment by rappasoft** [comment]
You need to add any classes to Tailwinds whitelist that do not show up in blade files in order for the JIT to find them.
